### ISSUE TITLE
Upozornit na možnost stažení mobilní appky

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#102]
Při načtení v browseru na Androidu a iOSu upozornit na možnost stáhnout si nativní appku.

**Comment by SPXcz** [comment]
![Screenshot from 2021-08-12 10-39-20](https://user-images.githubusercontent.com/55412542/129166394-96ec836b-a8ad-4195-91c4-bf6cc6358b28.png)
@zabak, něco takovýho by se ti líbilo? Samozřejmě obsah bych asi změnil.

**Comment by zabak** [comment]
Jo, neco takového. Zapínalo by se to v konfiguraci, vyskočilo by to na uživatele jen jednou a asi by to mělo nějakou základní inteligenci (pokud to otevřu na androidu, nebude mi to nabízet ios verzi a naopak; pokud to otevřu jinde, tak mi nabídne i QR kódy. Tlačítka by měla být ta oficiální s logem těch dvou obchodů. A samozřejmě musíme připravit textaci v češtině a angličtině.

**Comment by honza-rychtar** [comment]
Vzhledem k tomu, že mobilní aplikace jsou teď pouze obálky webové aplikace, tak bych tohle nedoporučoval.

**Comment by honza-rychtar** [comment]
@zabak můžeme zavřít?

> Vzhledem k tomu, že mobilní aplikace jsou teď pouze obálky webové aplikace, tak bych tohle nedoporučoval.
