### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#103]
V klientovi by mělo být možné zaslat zpětnou vazbu.

**Comment by zabak** [comment]
Upřesňuji: mělo by to umožňovat hlášení chyb v digitalizovaných dokumentech. Nejde o zpětnou vazbu k aplikaci jako takové, to si může každý dát do stránky Informace sám.

**Comment by pavelkocourek** [comment]
( Probírali jsme to s Petrem a ) Mělo by to směřovat do kontrolních mechanismů, které mohou být do budoucna součástí Administračního rozhraní Krameria

**Comment by zabak** [comment]
Jo, ale cílem je, aby na chyby mohli upozornit sami uživatelé, když na ně narazí.

**Comment by JanMeritus** [comment]
nestacilo by teda zatim nejaky button evokujuci predvyplnene mailto (s uid, prip. historii session)?

**Comment by honza-rychtar** [comment]
Na dubnové schůzce se dohodlo, že nebudeme realizovat.
Stačí kontakt na informační stránce a případně doplňující informace u neveřejného dokumentu, kde by měl být též kontakt.
