### ISSUE TITLE
Hláška o nepřístupnosti dokumentu - více informací

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#105]
V hlášce by mělo být víc informací podle toho, co má každá knihovna v Krameriu. My tam máme např., že k dokumentu se člověk dostane na studovnách MZK atp. 

Viz https://github.com/honza-rychtar/kramerius-web-client/issues/257

**Comment by zabak** [comment]
Domníváme se, že je to shodné se #176 - a je podstatné aby to bylo přes API. Toto prosím uzavřít ve prospěch #176.

**Comment by honza-rychtar** [comment]
Hláška se teď bere z nastavení Krameria (**rightMsg**).
Např. 
MZK: http://kramerius.rychtar.cloud/mzk/uuid/uuid:e8949dd4-8d2e-4369-8d7d-2fb85e101f4e
NKP: http://kramerius.rychtar.cloud/nkp/uuid/uuid:e8949dd4-8d2e-4369-8d7d-2fb85e101f4e

V konfiguraci je možné nastavit použití výchozí hlášky klienta (pokud nemá knihovovna nastavenou vlastní v Krameriovi). 
Např. NM: http://nm.kramerius.rychtar.cloud/uuid/uuid:8aab6de4-6ae9-482d-a5ab-24d68b954914
