### ISSUE TITLE
JPEG - neveřejný dokument

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#107]
Při kliku na JPEG stránky u neveřejného dokumentu vyskočí hláška
"action READ is not allowed, object is uuid:1b9dbdc0-90d0-11e8-86d2-005056822549, datastream is IMG_FULL"
status: 403

Chtělo by to uživatelštější hlášku jako u generování PDF - např. U autorsky chráněných dokumentů nelze zobrazit JPEG stránky.

**Comment by honza-rychtar** [comment]
Pokud je stránka neveřejná, tak se zobrazi dialog s varováním "Stránka není veřejně dostupná."
