### ISSUE TITLE
Příprava k tisku - neveřejný dokument

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#108]
Stejně jako u JPEG stránky se zobrazí status 403 s popisem "Access to the specified resource has been forbidden.". A je to až po tom, co si navolím strany k tisku. Ideální by bylo u neveřejných dokumentů rovnou při kliku na Přípravu tisku zobrazit hlášku ve stylu "Autorsky chráněné dokumenty nelze tisknout."

**Comment by honza-rychtar** [comment]
Ale autorsky chráněné dokumenty přece **lze** tisknout v budově knihovny.
Tady by se měl upravit ten ednpoint Krameria (https://kramerius.mzk.cz/search/localPrintPDF), který přípravu k tisku řeší. 
Klient by mohl ještě před výběrem stran u přípravy k tisku varovat u neveřejného dokumentu, že je to možné jen v budově knihovny. 
Klient by tady ale něměl řídit přístup, protože v určitých případech je možné tisknout neveřejné dokumenty (Kramerius to umožní) a klient nemá jak dopředu zjistit, že jsou všechny stránky dokumentu takto uvolněny.

**Comment by zabak** [comment]
Klient by ale měl mít možnost nějak poznat že je v budově knihovny a podle toho buď upozorňovat nebo neupozorňovat. A u knih, kde jsou některé stránky chráněné a jiné ne by měl být schopen nabídnout tisk jen volných stránek. Což by znamenalo upravit tiskový dialog a místo dvou políček na rozsah tam dát jedno pole a umožnit syntaxi s čáskama a pomlčkama, jak je zvykem v operačních systémech - tj. např. 1,5,8-13,15

**Comment by zabak** [comment]
@honza-rychtar tohle by mělo být vyřešeno nastavením zobrazení tlačítka pro tisk jako "available" a tohle issue zavřít, je to tak?

**Comment by honza-rychtar** [comment]
Vyřeší #516 - v dialogu pro přípravu k tisku nebo generování PDF bude možné vybrat jen strany, které jsou dostupné.
Dostupnost se bude generovat pro každou stranu z jádra, takže ani nebude možné přejít k tisku/generování s vybranými stranami, které jsou pro uživatele nedostupné.
