### ISSUE TITLE
Zobrazení úryvku při vyhledávání ve fulltextu

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#109]
Pokud je výsledkem vyhledávání periodikum, tak byť má jen jeden ročník, zobrazí se po rozkliknutí nejprve úryvek. U knih se rovnou otevře prohlížečka s vyznačeným slovem na stránkách. U chráněných knih nevíme, co tam je a jestli je to relevantní. I u těch veřejných knih je pracnější proklikat x stránek, každou zoomovat apod., než si zobrazit přehled a mít větší představu o tom, co tam je. Návrh je, aby se ty úryvky zobrazovaly vždy i v případě monografických dokumentů.

Viz https://github.com/honza-rychtar/kramerius-web-client/issues/310

**Comment by zabak** [comment]
Ještě doplním: na stránku s úryvky bychom rádi linkovali i z portálu knihovny.cz. Když mám knihu, kterou jsem našel podle výskytu výrazu ve fulltextu, tak bych uživatele chtěl poslat na stránku, kde najde příslušné výskyty.

**Comment by zabak** [comment]
... a proto by bylo fajn, kdyby URL stránky s výsledky hledání ve fulltextu dokumentu nezáviselo na druhu dokumentu (tj aby výsledky hledání v periodiku neobsahovaly v URL /periodical/ )

**Comment by honza-rychtar** [comment]
@zabak Různé reprezentace mají různou cestu v URL. V případě samotných dokumentů to jsou 3 (view, periodical, music).
Pro odkazování pak funguje jednotná struktura URL
Konkrétně pro DK
www.digitalniknihovna.cz/KOD_KRAMERIA/uuid/UUID_OBJEKTU
kde UUID_OBJEKTU může být periodikum, číslo, stránka, monografie, ... cokoli. Pak dojde k přesměrování na správné URL.
U tohoto se teď ale nepřenáší paramtery. To upravím, aby se dalo jednotně odkazovat
www.digitalniknihovna.cz/KOD_KRAMERIA/uuid/UUID_OBJEKTU?fulltext=FULLTEXT
Kde FULLTEXT by se potom přenesl do URL s periodikem nebo prohlížečkou.

**Comment by honza-rychtar** [comment]
Hotovo.
http://www.digitalniknihovna.cz/mzk/view/uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23?page=uuid:416ef62f-1d89-4d57-80e7-f92a9df7328f&fulltext=%22%C5%A1ach%20mat%22
