### ISSUE TITLE
Informace o dokumentu

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#11]
Bude možné nějakým způsobem přidat či odebrat (pokud možno nějak jednoduše) metadata, která se zobrazují v pravém sloupci? Například v některých případech bychom potřebovali, kdyby byl u čísla periodika zobrazen název (partName) a taky autor, pokud nějaký je.

**Comment by honza-rychtar** [comment]
Proc neco zobrazovat jen v Brne, neco jen v Ostrave a neco jen v Praze - uzivatele maji jiste vsude stejne potreby.

Poslete mi prosim odkaz na nejake cislo periodika, ktere ma v MODS partName a autora.
A zobrazime to vsude, kde jsou tyto udaje vyplnene.

**Comment by krizovj** [comment]
Například tady je speciální číslo Filosofického časopisu, které má v MODS partName, ale autora nemá. Žádné číslo, kde by byl autor zatím v Krameriovi nemáme, ale vím, že takové dokumenty budou. Bylo by možné zobrazovat tedy i autora, pokud bude?
https://kramerius.lib.cas.cz/client/handle/uuid:9e775346-25da-462c-894c-0aec0ebadd34 

Záznam čísla, kde je i autor bude vypadat takto:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods:mods version="3.5" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
    <mods:genre type="normal">issue</mods:genre>
    <mods:identifier type="uuid">c63fe143-06a2-4914-b9ca-8ac130b8d9ca</mods:identifier>
    <mods:identifier type="ccnb">cnb001699431</mods:identifier>
    <mods:identifier type="issn">1803-5795</mods:identifier>
    <mods:language>
        <mods:languageTerm authority="iso639-2b" type="code">ger</mods:languageTerm>
    </mods:language>
    <mods:location>
        <mods:physicalLocation authority="siglaADR">ABA007</mods:physicalLocation>
        <mods:shelfLocator>I ČSAV 2</mods:shelfLocator>
    </mods:location>
    <mods:location>
        <mods:physicalLocation authority="siglaADR">ABA007</mods:physicalLocation>
        <mods:shelfLocator>I ČSAV 2</mods:shelfLocator>
    </mods:location>
    <mods:name usage="primary" type="personal" authorityURI="http://aut.nkp.cz" valueURI="http://aut.nkp.cz/mzk2005299195">
        <mods:namePart type="date">1773-1861</mods:namePart>
        <mods:namePart type="family">Kolowrat-Liebsteinský</mods:namePart>
        <mods:namePart type="given">František Antonín</mods:namePart>
        <mods:role>
            <mods:roleTerm type="code" authority="marcrelator">edt</mods:roleTerm>
        </mods:role>
    </mods:name>
    <mods:originInfo>
        <mods:dateIssued>1825</mods:dateIssued>
    </mods:originInfo>
    <mods:part type="issue"/>
    <mods:titleInfo>
        <mods:title>Abhandlungen der Königlichen böhmischen Gesellschaft der Wissenschaften</mods:title>
        <mods:partNumber>1</mods:partNumber>
        <mods:partName>Vorträge, gehalten in der offentlichen Sitzung der k. böhm. Gesellschaft dr Wissenschaften in ihrem Versammlungssaale im Karolin bei Gelegenheit der feyerlichen Einführung Seiner Excellenz des Herrn Oberstburggrafen</mods:partName>
    </mods:titleInfo>
</mods:mods>

**Comment by pavelkocourek** [comment]
pripravime navrh na schuzku

**Comment by honza-rychtar** [comment]
Mohli bychom pridat plna metadata jako v pripade clanku (#14). Takze krome data vydani, cisla a navigace na predchozi/dalsi cislo by se zobrazily taky vsechny ostatni informace z MODS cisla, ktere se zobrazuji pro hlavni dokument.

**Comment by honza-rychtar** [comment]
Pridal jsem vypis metadat pro cislo, rocnik a monographunit stejnym zpusobem jako u clanku.

**monograph unit**
- Zobrazi se kompletni zaznam pod uvozenim *cast* (tohle prejmenujem asi na cast knihy, dil knihy, ...)
- Navigace na na predchozi/nasledujici cast je za metadaty pro cast
Napr. http://knav.kramerius.rychtar.cloud/view/uuid:49e4bccf-f77e-48f9-98cc-0e772a9f2d40?page=uuid:8ab8a4d8-908a-4137-ab44-1eaeb82c3a9a

**Cislo periodika**
- Zobrazi se lehce omezeny zaznam pod informacemi o cisle (datum, cislo, predchozi/nasledujici).
- Nazev se neduplikuje, zobrazi se pouze partName, pokud je vyplneno (http://knav.kramerius.rychtar.cloud/view/uuid:f058aa95-f119-48a3-a86d-db07e63011a2?article=uuid:9e775346-25da-462c-894c-0aec0ebadd34)
- Pridal jsem (vsude, nejen k cislu) fyzicky popis, kde u cisla v poznamce byvaji informace o kvalite predlohy, vecernim/rannim vydani apod, napr. http://mzk.kramerius.rychtar.cloud/view/uuid:b77880a0-435d-11dd-b505-00145e5790ea?page=uuid:52c3cab2-435f-11dd-b505-00145e5790ea
- Casto je tam zduplikovany jazyk a misto umisteni z celeho periodika

**Rocnik periodika**
- Stejne jako u cisel
- Je tam malokdy neco vyplneno.
- Zobrazi se v prohlizecce i v seznamu cisel - http://mzk.kramerius.rychtar.cloud/periodical/uuid:9cf6cb80-4929-11de-8d31-000d606f5dc6
