### ISSUE TITLE
Chybí ikona pro stažení zvukové nahrávky

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#110]
Buď v tom přehrávači není nebo ji prostě nevidím.

**Comment by filipsir** [comment]
Pockej pockej. My ale nemuzeme davat nahravky ke stazeni. To jde proti AZ. I kdyz jsou volne... pokud se nepletu tak zvuk to ma jinak.

**Comment by filipsir** [comment]
ja si nejsem jisty... mas docilit streamovani a ne stahovani. i kdyz je volna...

**Comment by LenkaKravecova** [comment]
Filipe, reaguju až teď.. Je to v autorském zákoně? Já vím, že to omezení se týká hudebnin (not), proto se už dřív řešilo znemožnění generování PDF a tisku i v případě volných hudebnin. Ohledně zvukáčů jsem o tom neslyšela. Do teď to bylo v Krameriu normálně ke stažení, nikdo si nestěžoval. Ale to neznamená, že to tak není ;)

**Comment by LenkaKravecova** [comment]
S temi hudebninami jsem to uplne pomotala.. To omezeni se tyka jen autorsky chranenych hudebnin, ze v pripade zpristupneni na miste samem se nesmi tisknout. Zkratka uzivatel si nesmi vytvorit kopii ani pro vlastni potrebu. 

Kdyz je neco volne, tak tam omezeni uz neni, muze se to vystavit i stahovat.

**Comment by honza-rychtar** [comment]
Nahrávku je teď možné sáhnout přes ikonku u skladby vpravo.
http://mzk.kramerius.rychtar.cloud/uuid/uuid:9f2fec5f-076b-424f-9b8d-d3a0aed4f0b1

Pokud je nahrávka neveřejná, tak se po pokusu o stažení zobrazí dialog s varováním že nahrávka není veřejně dostupná.
