### ISSUE TITLE
Funkce Vybrat text

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#112]
Ještě bychom rádi, kdyby byla přidána i funkce Vybrat text. Po vybrání určitého místa na stránce se zobrazí textový přepis toho místa. 

K tomu byly ještě i návrhy (které se zatím neuskutečnily), že při výběru textu se může v dialogu se zobrazeným textem zobrazit i citace dle normy. Viz https://github.com/honza-rychtar/kramerius-web-client/issues/253 

![vybrat text 1](https://user-images.githubusercontent.com/11834597/43410863-aba64008-9428-11e8-9d37-81c0b294cc90.jpg)
![vybrat text 2](https://user-images.githubusercontent.com/11834597/43410864-abc1fb36-9428-11e8-906d-4e5c42ee8758.jpg)

**Comment by honza-rychtar** [comment]
Hotovo.
Výběr textu se aktivuje tlačítkem v ovládacích prvcích:
<img width="697" alt="screenshot 2019-02-05 17 58 11" src="https://user-images.githubusercontent.com/1178142/52290185-d0a39180-296f-11e9-8b89-30133a99a9b8.png">

Potom se vybere oblast na obrázku a text se vypíše i s citací takto.
<img width="1680" alt="screenshot 2019-02-05 17 58 49" src="https://user-images.githubusercontent.com/1178142/52290243-f2047d80-296f-11e9-8cba-6495d3093a94.png">
