### ISSUE TITLE
Info o DK a o knihovně

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#113]
Ještě bychom uvítali, kdyby byla v DK nějaká stránka s informacemi o dané knihovně a o DK. Mohlo by se to brát z Krameria z textu Intro.

**Comment by honza-rychtar** [comment]
Přidal jsem stránku s informacemi o digitální knihovně.
V konfiguraci klienta se nastaví cesta k html souborům s informacemi v češtině a angličtine.
Více o nastavení zde:
https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta

Příklad pro KNAV
http://knav.kramerius.rychtar.cloud/about

Příklad pro NKP
http://nkp.kramerius.rychtar.cloud/about

Pro testovacího klienta se všema Krameriema od teď budu stránku s informacemi používat pro seznam nových věcí v klientovi pro každou verzi.
http://kramerius.rychtar.cloud/mzk/about

**Comment by honza-rychtar** [comment]
Ještě teda poznámka proč to neberu z intro textu.
Intro text popisuje (měl by popisovat obsah digitální knihovny nezávisle na klientovi a v praxi naopak popisuje K4 klienta, což je tady taky nepoužitelné).
Tady by ale měla být možnost popsat i klienta. V přápadě více Krameriů v klientovi pak intro text taky nedává smysl.
Součástí instalace klienta je i konfigurace, která se musí ručně projít a v tomto kroku se můžou i doplnit soubory s informacemi jako součást klienta.

**Comment by annie-cz** [comment]
Ahoj, v MZK jsme popisky už změnili, nicméně máme dotaz. Lze nějak udělat, abychom měli u seznamů textů funkční a nějak slušně vypadající odrážky? Formátování se tváří, že když vložíme text s odrážkami, tak nám je to ustřihne. Podařilo se to nějak pořešit u české verze, ale není to moc pěkné, tj. u anglické verze ponecháváme jako příklad.

**Comment by honza-rychtar** [comment]
@annie-cz Můžu změnit zobrazení odrážek. Otázka je, jestli zobrazení odrážek bude lepší (hezčí to nebude) a akorát to potom svádí právě k těm strohým výčtům, místo nějakého pěkného popisu.

Každopádně upozorňuju, že pokud chce MZK mít v klientovi víc než jen svého Krameria, tak nemůže (neměla by) použít stránku s informaceni k popisu obsahu jednoho konkrétního Krameria, když jich je v klientovi 30.

**Comment by annie-cz** [comment]
@honza-rychtar Zkus to prosím, když to nebude vypadat dobře, tak to tomu nějak přizpůsobím.

Co se týče toho popisu, tak v naší nápovědě bude toto vysvětleno a připíšu o tom nějaké základní informace i do toho základního informačního textu.
