### ISSUE TITLE
Uživatelské účty 

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#114]
Pokud by se uživatelé přihlašovali, mohli by si mimo jiné ukládat knihy do oblíbených, vytvářet poznámky aj.

**Comment by honza-rychtar** [comment]
Uzivatelske ucty by mohly/mely byt nad Krameriem. Tohle je na delsi debatu mimo isuues, ale pokud by nebyly uzcty zavisle na konktetni instalaci konkretniho klienta a konkretni knihovne, pak by se vlastne v pripade komentaru, poznamek, oblibenych, zalozek, .... jednalo jen o vazby KOD_KRAMERIA, UUID_OBJEKTU, USER_ID a pak konkretni objekt (poznamka, komentar, ...).

**Comment by zabak** [comment]
Uživatelské účty máme, pokud  budou požadavky na funkce na ně navázané, tak zakládejme nová issue.
