### ISSUE TITLE
Přístup do dalších Krameriů

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#115]
Za MZK máme zájem o to, aby bylo možné z klienta podobně jako na digitalniknihovna.cz mít přístup i do dalších Krameriů s využítím registru Krameriů, aby bylo možné tohoto klienta nasadit na digitalniknihovna.cz bez ztráty funkčnosti.

**Comment by zabak** [comment]
Bude to nějak napojené na registr Krameriů jako doposud? Nebo bude registr generovat konfigurační soubor, který si bude správce moci stáhnout?

**Comment by honza-rychtar** [comment]
V konfiguraci klienta je možné uvést více Krameriů a klient pak bude fungovat v režimu více Krameriů.
Kramerius se vybírá na hlavní stránce přes logo a název instituce s šipečkou.
V klientovi http://kramerius.rychtar.cloud je teď nastaveno 29 Krameriů.

V url se navíc použije na začátku cesty kód knihovny stejně jako v Digitální knihovně. Kódy jsou stejné jako v Registru Krameriů a v Digitální knihovně.

Persistentní linky mají tvar KLIENT/KOD_KRAMERIA/uuid/UUID_OBJEKTU

Až otevřete několik různých dokumentů z více Krameriů, tak na hlavní stránce v Navštívených budou dokumenty napříč Krameriema s vyznačeným logem knihovny.

Pokud je v konfiguraci klienta pouze jeden Kramerius, tak se klient chová jako předtím - Kramerius se nedá vybrat, kód není součástí url. 
Např. 
MZK: http://mzk.kramerius.rychtar.cloud/
KNAV: http://knav.kramerius.rychtar.cloud/

@zabak Můžeme udělat ten generátor seznamu do konfiguračního souboru. Ale až se to ustálí.
