### ISSUE TITLE
Chybné řazení ročníků u některých periodik - K6 vs. Kramerius

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#116]
U některých periodik se ročníky v klientovi řadí špatně (oproti Krameriovi, kde je to seřazeno správně).

Např.:
Epocha - uuid:73910710-4146-11e7-b3c8-005056825209
Rozkvět - uuid:4dc31870-107c-11e7-ac02-5ef3fc9ae867
Reklama - uuid:b62ebd90-a2f2-11e5-b770-5ef3fc9ae867
Časopis Moravského musea zemského - uuid:a04f0730-fb62-11e7-b1a1-005056827e52 a další.

Stejná chyba je i v Digitální knihovně.

**Comment by honza-rychtar** [comment]
Řadí se podle pole **datum**, které je v některých případech špatně nebo chybí. U seznamu ročníků jsem to změnil, aby se řadily podle pole **datum_str** - (textového pole s rokem nebo rozpětím let) - takže to teď funguje dobře. U čísel periodika se pořád používá pro řazení pole **datum**, protože datum ve formátu _dd.mm.yyyy_ nelze seřadit lexikograficky.

**Comment by honza-rychtar** [comment]
Tohle už je vlastně opraveno - pokud jde o ročníky uvedených periodik.
Řazení ročníků a čísel se dál řeší v #124
