### ISSUE TITLE
Razeni dle abecedy

### ISSUE THREAD

**Issue by filipsir** [ceskaexpedice/kramerius-web-client#117]
Nevim zda to jiz nekde neni...ale je to dosti problem vysvetlovat v muzeu ze to nejde vyresit. Pohne se toto? Je to naprosto marginalni problem a stale je dle me nevyresen. Dekuji za zpravu

**Comment by filipsir** [comment]
to sice mas, ale nefunguje razeni dle abecedy. koukni na to

**Comment by filipsir** [comment]
Tak co Petre.  Uz jsi zjistil ze to nefunguje ? ;)

**Comment by zabak** [comment]
Máš pravdu, je to bug.

**Comment by filipsir** [comment]
Jak to vypada? Porad me prudi kolegove a uzivatele ze to nejde. Vazne je to k nicemu kdyz to nefunguje

**Comment by honza-rychtar** [comment]
Neni to problem klienta ale solru. Nevim proc, ale u vas nefunguje razeni podle root_title. Nefunguje to ani u uzei, kteri maji taky 5.4.1 (Na druhou stranu u MKP s 5.4.1 to funguje).
Novy klient ziskava vysledky z metadata a z fulltextu jednim dotazem, proto pouziva root_title. 
Digitalni knihovna se pta na metadata zvlast a radi pres title_sort, coz u vas funguje.

Zjistim proc to nefunguje a dam vedet.

**Comment by honza-rychtar** [comment]
Neni to problem klienta ale solru. Nevim proc, ale u vas nefunguje razeni podle root_title. Nefunguje to ani u uzei, kteri maji taky 5.4.1 (Na druhou stranu u MKP s 5.4.1 to funguje).
Novy klient ziskava vysledky z metadata a z fulltextu jednim dotazem, proto pouziva root_title.
Digitalni knihovna se pta na metadata zvlast a radi pres title_sort, coz u vas funguje.

Zjistim proc to nefunguje a dam vedet.

**Comment by filipsir** [comment]
Diky moc Honzo. Klidne to muzes pak predat na Martina Rumanka aby to zapracoval

**Comment by pavel-stastny** [comment]
Zdravim vespolek, 

pro trideni by se melo pouzivat pole title_sort. I u tech instanci, ktere to maji setrideny dobre by mel byt problem se spravnym zarazenim pismene 'ch'.   Root_title by se melo vyuzivat pouze na vyhledavni.

**Comment by honza-rychtar** [comment]
@pavel-stastny Pokud hledám ve fulltextu a výsledky chci seskupit do top level dokumentů, tak musím použít root_title. V title_sort je název stránky a ne toho top-level dokumentu.

Když budeme dělat ty změny v solru, tak můžeme přidat root_title_sort

Teď to uprvím tak, že pokud není zadaný hledaný řetězec, tak to seřadím podle title_sort (neřeší se fulltext, takže root_title není potřeba).
Pokud řetězec je zadaný, tak řazení podle abecedy nebude u někoho fungovat, ale u zobrazení fulltextových výsledků ani nedává řazeni podle abecedy moc smysl - jde o relevanci.

**Comment by pavel-stastny** [comment]
@honza-rychtar  Alberto to tusim v klientovi nejdriv radil podle pole level a pak podle sort_title. 

Ad pridani root_title_sort. Jasne , pridam ho tam.

**Comment by filipsir** [comment]
Jak toto dopadlo? Uzje to funkcni?

**Comment by honza-rychtar** [comment]
@filipsir Bez fulltextu se to teď řadí správně - http://nm.kramerius.rychtar.cloud/search?accessibility=public&ordering=alphabetical
Pro řazení výsledku ve fulltextu budeme přidávat pole root_title_sort

**Comment by honza-rychtar** [comment]
Abecední řazení fulltextových výsledků funguje až od K7.

**Comment by zabak** [comment]
ověřeno, zavírám
