### ISSUE TITLE
Sbírky - přidat obrázek a popis

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#118]
Nenašla jsem to tu, takže zadávám. Prosím přizpůsobit sbírky tak, aby u sbírky šel vidět reprezentativní obrázek i popis (český, anglický) jako tady: http://www.digitalniknihovna.cz/mzk/collections/

Ta možnost nahrát obrázek a vyplnit texty v Krameriu je, takže pokud to sbírky obsahují, mělo by se to i zobrazovat. Bylo by taky dobré, aby si to knihovny doplnily..

**Comment by honza-rychtar** [comment]
Hotovo.
http://mzk.kramerius.rychtar.cloud/collections
Použití tohoto zobrazení je součástí konfigurace. Pokud neni zapnuto, tak sbírky vedou do procházení jako dosud.
Obrázky a popisky má v Krameriovi (pokud vím) zatím jen MZK.
