### ISSUE TITLE
Generování PDF - čísla stran

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#12]
Čísla stran při generování PDF nesouhlasí s čísly stránek v dokumentu.

**Comment by honza-rychtar** [comment]
U generovani PDF se uvadi index stranky (poradi v dokumentu). Tohle se taky pouziva u aktualni stranky v navigaci nad nahledy. 
Nazvy stranek muzou obsahovat libovolny retezec a nejde je obecne pouzit pro odkazovani na konkretni stranku.
Pak by to dopadlo:
[IXXXa] z 238 stranek (v navigaci)
od stranky 8a po stranku [9] (u generovani pdf) - tohle muze znamenat treba 10 stran, protoze mezi nimi je 8b, 8c, 8d, ...

A hlavne by uzivatel musel znat presne nazvy stranek, aby mohl prejit na konretni stranu v navigaci nebo zadat rozsah stran u generovani PDF.

**Comment by krizovj** [comment]
Chápu, nemohly by tedy náhledy stránek být taky označeny indexem? Pokud by neměl nikdo nic proti? Vím, že to neodpovídá číslování v dokumentu, ale takhle když jsou náhledy stránek označeny číslem stránky a při generování je použitý index stránky, tak je to dost matoucí.

**Comment by pavelkocourek** [comment]
Thumbnaily obsahují "číslo strany" - systém pracuje s indexem (stránkování, tisky) - bude probráno na schůzce

**Comment by LenkaDamborska** [comment]
Jen k tomu dodám, že u nás v MZK s tím mají uživatelé problém na digitalniknihovna.cz. Už mi přišlo několik připomínek, že generované strany nesouvisí se zadanými stranami a je to matoucí. Všem jsem musela vysvětlovat, že je to podle indexu. Není to moc srozumitelné.

**Comment by jandera** [comment]
Týká se i přípravy k tisku, uživatelé jsou opravdu zmatení i v KNAV. Třeba by se mohly reálné strany dokumentu zobrazovat jako první a strany indexu v závorce (a nebo raději vůbec).

**Comment by zabak** [comment]
Co kdyby se to vybíralo podobně jako fotky na Google Photos? Tj. v rožku každého thumbnailu by bylo zatržítko a vybíralo by se vyklikáváním, případně v kombinaci s ctrl/shift jak jsou lidi zvyklí.

**Comment by jandera** [comment]
To už souvisí s výběrem stran:
https://github.com/ceskaexpedice/kramerius-web-client/issues/50#issue-300138445
ale určitě to také do budoucna chceme.
Ať už přímo v levé liště s thumbnaily, nebo v dialogu k tisku jak je navrhováno #50

**Comment by zabak** [comment]
Ano, jiné rozumné řešení moc nevidím.

**Comment by honza-rychtar** [comment]
Po kliknutí na přípravu k tisku nebo generování PDF se nebude zobrazovat současný dialog, ale mřížka s náhledy přes celou obrazovku, kde si uživatel nakliká stránky, které chce. 
Pro rychlý výběr nepřerušované sekvence od do se použíje výběr prvního náhledu a výběr posledního se zmáčknutým shiftem - což bude uvedeno v poznámce pod náhledy.
Náhled  bude možné přes ikonu lupy zvětšit.
Bude se vypisovat počet vybraných stran a varování pokud se překročí maximální počet stran.
Budou tam tlačítka označit vše a odznačit vše.
Tímto se vyřeší zmatek s indexy a názvy stran, možnost nesouvislého výběru, kontroly atd.

Ok?

**Comment by zabak** [comment]
Bude fungovat i ctrl pro výběr jen některých stránek napřeskáčku?

**Comment by honza-rychtar** [comment]
@zabak Výběr zůstává aktivní i po výběru dalších stran. Pro zrušení výběru musím stránku odznačit.
Takže ctrl není potřeba, ten se používá v případě, kdy nové označení ruší předchozí výběr. Takže se to bude vlatně chovat jako s automaticky zmáčknutým ctrl - jako v těch zmíněných Google Photos.

**Comment by zabak** [comment]
@honza-rychtar OK

**Comment by jandera** [comment]
To vypadá rozumně, už se těšíme, spolu s našimi uživateli, až to bude.

**Comment by honza-rychtar** [comment]
Řešeno novým dialogem pro výběr stran.
