### ISSUE TITLE
Vyhledávání podle žánrů apod.

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#120]
Bylo by prosím možné do budoucího klienta zapracovat vyhledávání podle žánrů (či případně dalších kategorií, jako např. geografické polohy, místa uložení apod.)? 

Je velký rozdíl, když chci vyhledat např. staré fotografie z určitého regionu/města a mám možnost vyhledávat v tuto chvíli víceméně jen fulltextově a nebo dle klíčových slov.. v obou případech jsou výsledky prakticky totožné, ale jednotlivé fotografie mi to bohužel nenajde, pokud neznám jejich přesný název - jako např. zde: http://mzk.kramerius.rychtar.cloud/uuid/uuid:efd4258c-e764-4f86-97af-8c38e87cbb26. Podobné je to i u geografické polohy a místa uložení (např. mne jako uživatele zajímají pouze věci uložené v Rajhrajdském opatství, viz http://mzk.kramerius.rychtar.cloud/uuid/uuid:8b8c1bf9-caba-4ce5-b668-007181b315df).

Věřím, že lepší propracovanost vyhledávání/filtrace by byla pro uživatele atraktivní, neboť takto trošku přichází o potenciální zajímavé dokumenty.

Částečně navazuje na: https://github.com/honza-rychtar/kramerius-web-client/issues/239

**Comment by honza-rychtar** [comment]
Geografická poloha už je v nové verzi schéma solru, kterou ale ještě v MZK nemáte nasazenou.
Žánr v solru není. Ten si přidejme jako další požadavek na rozšíření solru.

**Comment by zabak** [comment]
Geografické názvy už máme zaindexované a v novém klientu fungují - viz. https://github.com/moravianlibrary/kramerius/issues/229 takže zbývá žánr.

**Comment by honza-rychtar** [comment]
Geografické názvy už jsou docela dlouhé.
S novým indexem přibyly ještě fasety Žánr a Nakladatel
<img width="296" alt="Snímek obrazovky 2020-09-17 v 16 53 53" src="https://user-images.githubusercontent.com/1178142/93488383-926da280-f906-11ea-89e8-d5f3aadf9370.png">

**Comment by honza-rychtar** [comment]
Hotovo v K7
http://dk.kramerius.org/mzkk7/search

**Comment by zabak** [comment]
funguje, zavírám
