### ISSUE TITLE
Neposouvá se číslování zobrazených výsledků

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#121]
V klientu se při procházení, vyhledávání apod. mají vlevo nahoře za popiskou *"Výsledky:"* zobrazovat číslice, které vyjadřují, kolikátý až kolikátý výsledek je aktuálně zobrazen.
Při procházení množiny dokumentů větší než 60 ale od druhé šedesátky dochází k chybě: první číslice nevyjadřuje, kolikátý dokument je zobrazen jako první, ale jen kolik dokumentů je aktuálně zobrazeno.

![](https://user-images.githubusercontent.com/44299577/47432556-b538c000-d79e-11e8-9dc0-50c90a43f8a5.jpg)
![](https://user-images.githubusercontent.com/44299577/47432570-bf5abe80-d79e-11e8-9625-b4b5fa892fc8.jpg)
![](https://user-images.githubusercontent.com/44299577/47432578-c41f7280-d79e-11e8-80af-6f9fba59fdc4.jpg)

**Comment by honza-rychtar** [comment]
Opraveno
