### ISSUE TITLE
Konec vydávání u stále vycházejících periodik

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#122]
U periodik, jejichž vydávání ještě neskončilo, se jako rok jejich ukončení zřejmě automaticky vyplní údaj *"9999"*.
Lépe by samozřejmě bylo nechat to prázdné nebo aspoň vyplněné nějakým *"dodnes"* nebo tak.

![](https://user-images.githubusercontent.com/44299577/47434226-6d1b9c80-d7a2-11e8-91c4-09aca203a137.jpg)

**Comment by honza-rychtar** [comment]
Datum se bere z MODS, kde je to takto uloženo.
Změnil jsem to tak, že pokud je datum ve formátu yyyy-9999, tak se zobrazí jen yyyy-
