### ISSUE TITLE
Chybné řazení čísel v ročnících u některých periodik

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#124]
Možná souvisí s #116, nicméně se projevuje o úroveň níže, takže zakládám zvlášť:

V rámci ročníku se čísla periodik někdy seřazují chybně - např. [uuid:4b80bf10-51fb-11e8-946a-005056825209](http://mzk.kramerius.rychtar.cloud/uuid/uuid:4b80bf10-51fb-11e8-946a-005056825209).
Stejný problém je v Digitální knihovně - např. [uuid:bbdeadc0-a6e3-11e8-a2d0-005056827e52](http://www.digitalniknihovna.cz/mzk/uuid/uuid:bbdeadc0-a6e3-11e8-a2d0-005056827e52).

Jde zřejmě o případy, kdy mají data vydání různý formát (některá *dd.mm.rrrr*, jiná jen *mm.rrrr* a/nebo jen *rrrr*).

**Comment by krizovj** [comment]
Máme stejný problém 
![image](https://user-images.githubusercontent.com/21309201/51231351-80827200-1963-11e9-8773-d2a2ac1fc11c.png)

**Comment by krizovj** [comment]
Problém zůstává, i když čísla seřadím v editoru částí.  Stejné je to s přílohou k ročníku, zařadí se na začátek, před číslo 1, ale logicky by měla být na konci.

**Comment by JanMeritus** [comment]
Je tu nejaky postup ? (aj kvoli #250  - duplicita?)

**Comment by luckajirku** [comment]
Řeší se tenhle problém?

**Comment by honza-rychtar** [comment]
Opraveno. S novým indexem se spraví řazení přímo. U starého se řazení po načtení upraví na straně klienta.
Takže by to mělo fungovat ve všech Krameriich.
http://www.digitalniknihovna.cz/knav/periodical/uuid:2848e915-2a0a-4588-87df-a9765b6432a1
Špatné zařazení čísla 9 se spravilo.
Čísla 15 a 16 jsou stále přehozena, protože číslo 16 má rok vydání starší než číslo 15.
