### ISSUE TITLE
Nejednotné popisky ikon typů dokumentů

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#125]
Popisky, které vyskakují po najetí kurzorem na ikony typů dokumentů na horní liště, jsou některé v množném čísle (*"Noviny a časopisy"*, *"Zvukové nahrávky"*, *"Hudebniny"*), jiné v jednotném (*"Kniha"*, *"Mapa"*, *"Grafika"*, *"Rukopis"*, *"Článek"*).
Prospělo by sjednocení na množné číslo - tj. tak, jak jsou *Typy dokumentů* konzistentně označeny v seznamu v záložce *Procházet*.

**Comment by honza-rychtar** [comment]
Opraveno
