### ISSUE TITLE
Nezobrazující se jméno autora

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#126]
V metadatech v pravém sloupci se nezobrazuje jméno autora, pokud je jeho zápis v MODS rozdělen do elementů `<mods:namePart type="family">`  a `<mods:namePart type="given">` a jeden z obou elementů neobsahuje žádnou hodnotu (pravidelně u autorů, kteří mají jen jednoslovné jméno).
Např. http://nkp.kramerius.rychtar.cloud/view/uuid:66d5fc80-c58e-11dc-8300-000d606f5dc6 - chybí *Aristotelés* v položce *Autor* i v rozklikávacím okně *Informace o autorech*.

Přitom zobrazování funguje, pokud je hodnota vyplněna v obou elementech (ve stejném příkladu *Vrťátko, Jaroslav*) nebo pokud je použit pro všechny části jména jediný element `<mods:namePart>` bez atributů (např. http://nkp.kramerius.rychtar.cloud/view/uuid:ddcf5e60-fae0-11e3-9789-005056827e52 - opět *Aristotelés*).

**Comment by honza-rychtar** [comment]
Opraveno
