### ISSUE TITLE
Zobrazení autorských rolí

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#127]
Zobrazení autorských rolí v okně na rozkliknutí (zavedeno na základě #85) má potíže, pokud za elementem `<mods:roleTerm type="code">` následuje ještě druhý, `<mods:roleTerm type="text">` (což je element nestandardní, ale u starších dat v NK bohužel častý).
Za správný údaj (získaný z prvního elementu) se v takovém případě doplní ještě *"relator."* a hodnota druhého elementu - oboje nežádoucí text.
Například u http://nkp.kramerius.rychtar.cloud/view/uuid:91525a00-e0a2-11dd-b9ea-000d606f5dc6.

**Comment by honza-rychtar** [comment]
Opraveno
