### ISSUE TITLE
Filtr "Pouze veřejné"

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#128]
V na úvodní/hlavní stránce je (nejspíše defaultně) nastavený filtr "pouze veřejné".

![obrazek](https://user-images.githubusercontent.com/31240271/47640467-fbf23580-db63-11e8-8e34-55b73a1671c4.png)

V zásadě je to správně. Ale na PC v knihovně (na místě samém) bychom uvítali, kdyby šlo zaškrtnutí tohoto filtru na úvodní straně zrušit. Uživatel, který přijde do budovy knihovny za účelem přečíst si neveřejný dokument (a nejnovější client mu ho na hl. str. dokonce i našeptává), by si nemusel všimnout, že má aktivní právě tento filtr a bude zobrazené výsledky považovat za chybné. 
Může si knihovna nějak jednodušše **nastavit/zrušit zaškrtnutí filtru "pouze veřejné" na úvodní stránce**? Děkuji

**Comment by jandera** [comment]
Ještě doplním, že je žádoucí filtr "pouze veřejné" vypnout pouze na stanicích "na místě samém", tedy ve studovně knihovny. A určitě nechceme provozovat dva běžící klienty, jeden pro studovnu a druhý pro ostatní. Ideálně by tedy nastavení mělo být pro konkrétní stanice, třeba na základě IP nebo MAC adres, nebo jiného ID.

**Comment by honza-rychtar** [comment]
On se ten filtr nastavuje podle toho, jak byl použit při posledním hledání - prohlížeč si volbu zapamatuje. 
Takže by měl být odškrtnutý, dokud ho nějaký uživatel nezaškrtne. 
Není to lepší takto? Pokud bychom měli nastavovat výchozí hodnotu podle IP adresy, tak stejně nepoznáme, že se vystřídali dva uživatelé u stejné stanice, aby se rozhodlo, jestli se má používat uživatelova preference z předchozího hledání, nebo jestli mu vnutit výchozí hodnotu.

**Comment by jandera** [comment]
Toto bohužel neplatí. Plný přístup k obsahu digitální knihovny (DK) "na místě samém" musí být v knihovnách provozován na zabezpečených kioscích, kde je zpravidla nasazen browser v anonymním režimu a tedy po jeho restartu je tam opět defaultně nastavený filtr "pouze veřejné". Jde nám o nastavení právě na těchto stanicích, kde má jakýkoli uživatel možnost prohlížet a tisknout veškerý obsah DK a kde je filtr "pouze veřejné" irelevantní a je žádoucí jej na těchto stanicích defaultně vypnout.

**Comment by honza-rychtar** [comment]
Výchozí hodnota filtru **pouze veřejné** je teď součásti konfigurace klienta. 
Pokud byste to opravdu chteli ještě rozlišovat podle IP adresy, aby se klient choval na různých místech jinak. Tak to musíme propojit s jádrem Krameria a musíme počkat na update Krameria a bude to pak závislé na verzi Krameria.

Stačí nastavení na úrovni klenta?

**Comment by jandera** [comment]
Myslím, že bude stačit na úrovni klienta, našeho si nastavíme s odškrtnutou hodnotou.
