### ISSUE TITLE
Trvalý odkaz - časopisy

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#13]
U časopisů nejde získat odkaz na celý časopis nebo na ročník, ale jen na konkrétní stranu. Bylo by možné přidat možnost vygenerování trvalého odkazu taky na celý titul časopisu a ročník?

**Comment by honza-rychtar** [comment]
Odkaz na sdileni jsem provizorne umistil jen v prohlizecce vlevo.
Logicky patri vravo do panelu s metadaty. Sdilet tak pujde vse, kde se zobrazuji metadata, takze i cely casopis, rocnik a pozdeji i zvukove nahravky v budoucim hudebnim prehravaci.

**Comment by honza-rychtar** [comment]
Akce pro sdileni je ted v panelu s metadaty. Odkaz pro sdileni je mozne ziskat vsude, kde se zobrazuji metadata.
