### ISSUE TITLE
Dvoustránkové zobrazení chráněné a nechráněné stránky nezobrazí volnou stránku

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#134]
Např. http://kramerius.rychtar.cloud/view/uuid:8eaa6c40-db45-11e8-a5a4-005056827e52?page=uuid:dd5e9640-f24c-11e8-9984-005056825209 - pokud mám v rámci dvoustránky jednu volnou a jednu chráněnou stránku, tak se mi zobrazí jen hláška, že stránka nelze zobrazit. V jednostránkovém zobrazení je samozřejmě vše OK.

**Comment by honza-rychtar** [comment]
Pokud ve dvoustránkovém režimu otevřu neveřejnou stránku (levou/pravou/obě), tak se prohlížečka přepne do jednostránkového režimu (jen pro tento dokument) a otevře se strana, která byla vybrána (levá/pravá).
