### ISSUE TITLE
Označení ročníků u náhledů

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#139]
V novém klientovi se pod thumbnaily ročníků nezobrazuje **označení ročníků**. 

Nejspíš se jedná o chybu u nově přidaných ročníků. Např. u časopisu Knihy a dějiny je u dříve přidaných ročníků správně zobrazeno "Ročník 21" (22, 23), u nedávno přidaných chybí označení "Ročník 24" (resp. "Ročník 25") a místo toho je tam pouze pomlčka.
![obrazek](https://user-images.githubusercontent.com/31240271/49632463-12f33580-f9f6-11e8-865f-ce4cf9968215.png)
(v jiných instalacích to máme správně: https://kramerius.lib.cas.cz/client/handle/uuid:fc144bf1-8d61-4f4b-80f9-e4a772db32dc a https://kramerius.lib.cas.cz/search/handle/uuid:fc144bf1-8d61-4f4b-80f9-e4a772db32dc)

Chyba je u přístupných i nepřístupných dokumentů, např. i u nepřístupného čas. Folia historica Bohemica (https://kramerius.lib.cas.cz/client/handle/uuid:6f732cf5-4a04-11e1-aea0-005056a60003 a https://kramerius.lib.cas.cz/search/handle/uuid:6f732cf5-4a04-11e1-aea0-005056a60003):
![obrazek](https://user-images.githubusercontent.com/31240271/49632624-acbae280-f9f6-11e8-8b6a-ec8b6576b1ea.png)
Nebo částečně (ne)přístupného Právníka (https://kramerius.lib.cas.cz/client/handle/uuid:719be951-4eb0-11e1-9043-005056a60003 a https://kramerius.lib.cas.cz/search/handle/uuid:719be951-4eb0-11e1-9043-005056a60003):
![obrazek](https://user-images.githubusercontent.com/31240271/49632792-44b8cc00-f9f7-11e8-8633-a31dc22c333c.png)

V metadatech všech zmíněných ročníků je stejně numericky vyplněn **partNumber**.

**Comment by honza-rychtar** [comment]
Opraveno
