### ISSUE TITLE
Informace o dokumentu - článek (PDF)

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#14]
V testovací verzi jsem nenašla žádný článek v PDF. Co by se zobrazovalo za údaje v případě, že tam bude článek? V Digitální knihovně jsem našla jeden příklad (http://www.digitalniknihovna.cz/knav/view/uuid:9ba071bc-0327-4ca9-90cd-b1875b0c2ea6). I když jde o článek, tak jsou u něj údaje ze záznamu titulu periodika (alespoň to tak podle těch údajů vypadá).

U článků bychom potřebovali hlavně tyto údaje:
Název článku
Autor
Jazyk
Klíčová slova
Abstrakt
Rozsah stran
A pokud půjde o recenzi, tak by tam měly být ještě uvedeny údaje o dokumentu, který je recenzován. Že jde o recenzi se pozná z elementu genre:
<mods:genre>article</mods:genre>
<mods:genre **type="review"** authority="czenas">recenze</mods:genre>
<mods:genre authority="eczenas">reviews</mods:genre>

A údaje o recenzovaném dokumentu jsou v elementu relatedItem:
 <mods:relatedItem displayLabel="Recenze na:">
        <mods:name>
            **<mods:namePart>Šimeček, Zdeněk</mods:namePart>**
        </mods:name>
        <mods:originInfo>
            <**mods:publisher>Brno : Statutární město Brno, Archiv města Brna, 2011</mods:publisher>**
        </mods:originInfo>
        <mods:part>
            <mods:extent>
                <mods:start>161</mods:start>
                <mods:end>163</mods:end>
            </mods:extent>
        </mods:part>
        <mods:titleInfo>
            **<mods:title>Knižní obchod v Brně od sklonku 15. do konce 18. století</mods:title>**
        </mods:titleInfo>
    </mods:relatedItem>

**Comment by krizovj** [comment]
Jen mě ještě napadlo, že ten abstrakt nemusí být rovnou celý, ale může být rozklikávací, podobně jako když je moc dlouhý název, tak se dá zobrazit nebo schovat.

**Comment by honza-rychtar** [comment]
Podpora clanku zatim neni, bude reseno v ramci #40 
Tyto clanky, ktere maji na sebe navazany rozsekane pdf dokumenty a jsou pod cisly, ktere obsahuji pouze tyto clanky a ne stranky nejsou podporovany ani v Digitalni knihovne ani v Krameriovi pro Androd a ani v Krameriovi pro iOS

**Comment by honza-rychtar** [comment]
Pridal jsem zobrazeni metadat clanku - zobrazuji se plna metadata a jsou vlozena do panelu vpravo mezi info o vytisku a nakladatelske udaje.
Priklad pro PDF clanky:
http://knav.kramerius.rychtar.cloud/view/uuid:28660055-addd-438c-82a6-3704cb8e499e?article=uuid:52e02a2a-26e3-4645-b488-240182103ecf
Priklad pro clanky se strankama
http://mzk.kramerius.rychtar.cloud/view/uuid:b827fa0d-435d-11dd-b505-00145e5790ea?article=uuid:19ec0964-7213-452c-b26c-8cdb1d694e38

Recenze jsem zatim nepridaval. @krizovj Poslete mi prosim odkaz na konkretni clanek s recenzi v Krameriovi.

**Comment by krizovj** [comment]
Příklad recenze třeba tady:
https://kramerius.lib.cas.cz/client/handle/uuid:352f9b3f-44b5-4285-8dc7-7690ff24ca2a

**Comment by honza-rychtar** [comment]
@krizovj  Nahore pisete, ze recenze se pozna podle
<mods:genre **type="review"** authority="czenas">recenze</mods:genre>
Ale uvedeny dokument (https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:352f9b3f-44b5-4285-8dc7-7690ff24ca2a/streams/BIBLIO_MODS) nema atribut **type="review"**
Jen 
<mods:genre authority="czenas">recenze</mods:genre>

**Comment by krizovj** [comment]
No jo, to tam máme špatně. Tak v tom případě by se to asi nezobrazilo ne? I podle standardu je to tak jak jsem to psala výše. My si to někdy opravíme. Nové příklady, kde je to tak, jak bylo popsáno výše:
https://kramerius.lib.cas.cz/search/handle/uuid:407c4b6f-4782-450e-957f-d1b90e4f0b6b
https://kramerius.lib.cas.cz/search/handle/uuid:dff611b3-0826-4c54-bd8b-3045e9caf837
https://kramerius.lib.cas.cz/search/handle/uuid:4952b458-cd38-4050-826e-a34be7c01a86

**Comment by krizovj** [comment]
Ještě bych měla k těm metadatům článků jednu věc. Když jde o anglický článek, který začíná členem, tak ten člen je někdy zapsaný zvlášť v elementu "nonsort". 

<mods:titleInfo lang="eng">
            <mods:title>evaluation of time variability of tidal parameters h and l using SLR technique</mods:title>
            <mods:nonSort>The</mods:nonSort>
</mods:titleInfo>


V navigaci vlevo se ten člen normálně zobrazí, ale v metadatech vpravo ne.
![clen](https://user-images.githubusercontent.com/21309201/40915402-2ec4a0c8-67fc-11e8-9741-cbc54ba6e7d7.jpg)

**Comment by honza-rychtar** [comment]
Cleny v nazvech clanku pres nonSort jsem opravil - http://knav.kramerius.rychtar.cloud/view/uuid:6b9a10de-1f77-4a02-8260-37d4527b89bb?article=uuid:ad53e722-a06e-48b2-8adc-b57258c3725e

Recenze v clancich se ted zobrazi takto - http://knav.kramerius.rychtar.cloud/view/uuid:e8273fdf-be68-4e0b-8b54-be7b0f55a4b0?article=uuid:407c4b6f-4782-450e-957f-d1b90e4f0b6b
