### ISSUE TITLE
Při stahování dokumentu je tlačítko pojmenované „GENEROVAT“.

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#144]
Tento název neodpovídá akci, kterou provádí. Vhodnější by bylo například použít „Stáhnout dokument“.

**Comment by honza-rychtar** [comment]
Ale odpovídá. 
Generování PDF je proces, který může trvat dlouho. Naopak použití **Stáhnout dokument** by bylo zavádějící, protože před samotným **stažením** docházi právě k tomu **generování**.

**Comment by zabak** [comment]
No, jenže podívej se třeba na Google dokumenty. Tam máš stáhnout jako - a vybíráš si formát. Ten se nepochybně generuje. Ale to uživatele nezajímá, on ho nechce generovat, ale stáhnout. Časem přibude třeba stažení epub, nakonec i stažení jpg je vlastně generování pokud originál je v jp2...

**Comment by honza-rychtar** [comment]
@zabak To je fakt.
Ale nejde ani tak o akci, která se provádi, ale o čás, který ta akce zabere.
Pokud se něco jsmenuje **Stáhnout** a po kliknutí na to vidím točící se kolečko a čekám víc než 30 sekund, tak to vypnu, protože se nic nestahuje. Pokud se to jmenuje **Generovat**, tak počkám.

Ale ok, přejmenujem to na **Stáhnout**. A když se na to klikne a začne es točit kolečko, tak zvýrazním ten popisek _Vytváření PDF dokumentu může trvat několik minut v závislosti na počtu vybraných stránek._

**Comment by honza-rychtar** [comment]
Přejmnenováno na Stáhnout PDF.
