### ISSUE TITLE
Scrollování při rozlišení 1920x1080 není plynulé.

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#149]

**Comment by zabak** [comment]
Scrollování čeho měls na mysli? Zkoušel jsem teď na 4K monitoru a nevidím problém.

**Comment by honza-rychtar** [comment]
To psali v té UX analýze. Taky se mi to nepdařílo navodit. Zavírám. Pokud s tím někdo bude mít problém, tak to můžem otevřít a řešit to až to bude relevantní.
