### ISSUE TITLE
Otevřít v novém okně - dotaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#15]
Mám možná hloupý dotaz. Bylo by možné aby se dalo otevřít víc dokumentů každý v novém okně (kolečkem myši nebo přes pravé tlačítko)? Takhle je nutné se pořád vracet na výsledky a myslím, že hodně lidí si při vyhledávání otevře více oken a pak je prochází a případně rovnou zavírá, je to pohodlnější než se pořád vracet.
V Digitální knihovně tohle funguje.

**Comment by honza-rychtar** [comment]
Predelam karty, aby fungovaly jako odkazy.

**Comment by honza-rychtar** [comment]
Karty na hlavni obrazovce, ve vysledcich hledani a v periodiku funguji jako odkazy a je mozne je otevirat v novem okne/tabu.
