### ISSUE TITLE
Filtry na stránce výpisu dokumentů není možné řadit abecedně. 

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#151]
Může to být zdržující, pokud budu například hledat konkrétního autora.

**Comment by honza-rychtar** [comment]
Takhle fasety fungují. Pokud budu chtít hledat autora, tak ho buď zadám do vyhledávacího pole nebo jdu do procházení.
Seřazením faset si moc nepomůžu, když pak uvidím 50 autorů začínajících na **A**.

Pokud by to tam někdo chtěl, tak se ozvěte, jinak to zavřu jako nepodstatné.

**Comment by zabak** [comment]
Jsou fasety, u kterých má smysl neřadit je podle velikosti, ale to jsou ty co mají relativně málo výskytů, které jsou zobrazeny všechny. Třeba u věcné kategorie časového období, pokud by bylo smysluplně zobrazeno. Ale není to něco co by měl měnit uživatel.

**Comment by honza-rychtar** [comment]
Ok. Zavírám.
