### ISSUE TITLE
Filtr na roky nefunguje správně.

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#153]
Vypisují se záznamy, které neodpovídají rokům. Například zadám do roku 1800, ale vyjedou i dokumenty z roku 1967.

**Comment by honza-rychtar** [comment]
Uváděný příklad jsem nenašel, ale např u hledáná do 1800 http://kramerius.rychtar.cloud/mzk/search?ordering=newest&from=0&to=1800
To najde i 
<img width="347" alt="screenshot 2018-12-09 12 25 53" src="https://user-images.githubusercontent.com/1178142/49696665-9c009d00-fbad-11e8-9807-91fec77bb1c1.png">

V MODS je
```
<mods:dateIssued>1861-[18--]</mods:dateIssued>
<mods:dateIssued encoding="marc" point="start">1861</mods:dateIssued>
<mods:dateIssued encoding="marc" point="end">18</mods:dateIssued>
```
Což se zaidexuje jako: 
datum_begin: **1861**
datum_end: **18**

A jelikož `datum_end = 18 ≤ 1800`, tak to klient správně zobrazil.
Chyba je v indexaci toho data (a zápisu end hodnoty v MODS). Tady to potřebujeme změnit, aby katalogizační zápis, který používá jistá pravidla, byl správně převeden na takové číselné hodnoty, nad nimiž bude fungovat filtrování podle data.
Např. 18-- u počátečního data by se měo vyhodnotit jako 1800 a i koncového jako 1899.

Každopádně tohle není problém klienta, zavírám.

**Comment by zabak** [comment]
Prosím když už to tady zanalyzuješ tak to zavírej až po vytvoření issue v Krameriu.

**Comment by honza-rychtar** [comment]
@zabak Tohle máme jako samostatnou kapitolu pro rozšíření solru/indexace - parsování a indexace data.

**Comment by zabak** [comment]
OK, jestli jsi to linkoval z toho dokumentu tak to tady zavři.
