### ISSUE TITLE
Zpět na výsledky vyhledávání

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#16]
Když při prohlížení dokumentu kliknu na zpět, vrátí mě na seznam výsledků vyhledávání, ale vždy na začátek stránky. Nešlo by, aby mě to hodilo na stejné místo?

**Comment by pavelkocourek** [comment]
Projdeme na schůzce význam ... řešeno stránkováním.

**Comment by honza-rychtar** [comment]
@krizovj Opravdu je tohle potreba? U strankovani je najedou zobrazeno maximanle 60 vysledku - maximalne me to odscrolluje o jednu obrazovku. 
U Digitalni knihovny by to smysl davalo - tam je nekonecny seznam, kdy muzu scrollovat treba 10 minut a taky me to pri navraceni hodi na zacatek. Ale i tam upozornuju, ze je lepsi si dokumenty otevirat v novem tabu, pokud jich chci otevrit vic a nevracet se tam a zapet.
