### ISSUE TITLE
Parametr query ve funkci assignPdfPath() nefunguje (?)

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#161]
Zdá se mi, že to nějak nefunguje, srovnej příklad:

http://kramerius.rychtar.cloud/assets/pdf/viewer.html?file=http://kramerius.medvik.cz/search/api/v5.0/item/uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990/streams/IMG_FULL&query=didaktika

http://kramerius.rychtar.cloud/assets/pdf/viewer.html?file=http://kramerius.medvik.cz/search/api/v5.0/item/uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990/streams/IMG_FULL#query=didaktika

http://kramerius.rychtar.cloud/assets/pdf/viewer.html?file=http://kramerius.medvik.cz/search/api/v5.0/item/uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990/streams/IMG_FULL&search=didaktika

http://kramerius.rychtar.cloud/assets/pdf/viewer.html?file=http://kramerius.medvik.cz/search/api/v5.0/item/uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990/streams/IMG_FULL#search=didaktika

Upgradoval jsem na pdfjs-dist 2.0.943 + ng2-pdf-viewer 5.2.3 a pak to funguje s parametrem: #search

https://dev.medvik.cz/wck/assets/pdf/web/viewer.html?file=uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990#search=didaktika

**Comment by honza-rychtar** [comment]
Měl jsem tam chyb, opravil jsem to.
Funguje ta první verze http://kramerius.rychtar.cloud/assets/pdf/viewer.html?file=http://kramerius.medvik.cz/search/api/v5.0/item/uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990/streams/IMG_FULL&query=didaktika (budeš asi muzat cache).

Tobě ten #search jen zvýrazní první výsledek - není to provázané s hledáním.
Potřeboval jsem tu pdf prohlížečku trochu hacknout, aby se rovnou otevřelo vyhledávací onko, tam se vložil ten hledaný řetezec a přešlo se na první nález. Pak je hned možné přecházet na další výsledky.
