### ISSUE TITLE
Kapitoly v monografiích - dotaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#162]
Mám dotaz ohledně monografií, členěných do kapitol. Umí je klient zobrazit? My žádné vlastně nemáme, tedy máme, ale máme je zpracované trochu jinak (ve starých tiscích), takže z toho nepoznám, jestli to ten klient nezobrazí ptž to neumí nebo proto že je to jinak zpracováno.

**Comment by zabak** [comment]
V metadatech by bylo dobré zobrazovat i číslo stránky, na které článek začíná. U dvoustránkového zobrazení u novin se mnohdy článek špatně hledá. Taky by stálo za pokus vyhledat na stránce název článku (nebo aspoň slova z názvu). - nebo to tam dát jako volbu na místo, kde normálně je "vyhledat v textu".

**Comment by krizovj** [comment]
Vypadá to dobře, díky. Měla jsem na mysli právě tenhle případ, kapitoly z jednotlivých stran jako je to v případě MZK. 

Šlo by jen udělat, aby, když budu na konkrétní stránce (na záložce "stránky"), tak když se přepnu do kapitol, aby to označilo kapitolu, kde jsem? 
Teď když se přepnu do záložky "kapitoly", tak zůstanu na stejné stránce jako jsem byla, ale nevím, ve které jsem kapitole. 

Mohl by se k tomu prosím vyjádřit ještě někdo další? Nevím, jestli to vadí jen mně, nebo ještě někomu. Díky

**Comment by krizovj** [comment]
A ještě mám dotaz k vyhledávání článků a kapitol, které nejsou v PDF, ale jak je uvedeno výše. Tam bude to vyhledávání fungovat stejně jako u PDF? Tedy, že to nejdřív najde články/kapitoly podle metadat a potom podle výskytů ve fulltextu?

**Comment by LenkaKravecova** [comment]
S tímto souhlasím: "Šlo by jen udělat, aby, když budu na konkrétní stránce (na záložce "stránky"), tak když se přepnu do kapitol, aby to označilo kapitolu, kde jsem?" 
Jinak si myslím, že je to fajn :)

**Comment by honza-rychtar** [comment]
Z tohoto chybí pouze #535, tady navrhuju zavřít.
