### ISSUE TITLE
Tlačítka na hlavní stránce se v mobilní verzi překrývají

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius-web-client#163]
Dobrý den, 
zjistili jsme že na některých zařízeních dochází v případě užších displayů k překrývání, nebo vyčnívání tlačítek. Testováno na rozlišení 1080:1920, telefony Honor 7 a Samsung Galaxy S9. 

Více ve screenshotech

**Comment by jdobiasovsky** [comment]
Zapoměl jsem screenshoty, ještě doplním že možná by stačilo jenom nějakým způsobem škálovat, případně nahradit ikonkami. 
![screenshot from 2018-12-19 12-32-16](https://user-images.githubusercontent.com/17568929/50218104-1047f700-038b-11e9-9cde-5b4cdec0d287.png)
![image001](https://user-images.githubusercontent.com/17568929/50218105-10e08d80-038b-11e9-88c6-a6ca7a67de7a.jpg)

**Comment by honza-rychtar** [comment]
Tohle už bylo vyřešeno (#155). 
Zkuste novou verzi na http://kramerius.rychtar.cloud
