### ISSUE TITLE
Klient pro ČDK - dát pryč filtr "Místo uložení"

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#167]
Filtr "Místo uložení" je matoucí, z klienta pro ČDK by se měl dát úplně pryč a na jeho místo (tedy výš než je to teď) by se měl přesunout filtr "Sbírky", který by se měl zároveň přejmenovat na "Knihovny". Jen v klientovi pro ČDK.

**Comment by honza-rychtar** [comment]
> Filtr "Místo uložení" je matoucí, z klienta pro ČDK by se měl dát úplně pryč

Filtry pro procházení a hledání se nastavují v konfiguraci u každého Krameria.

`filters: ['accessibility', 'doctypes', 'authors', 'keywords', 'geonames', 'collections', 'locations', 'languages']`

Tady je možné zvolit libovolnou podmnožinu.
Takže konkrétně tady ze seznamu odstranit _'locations'_
http://kramerius.rychtar.cloud/cdk/search?q=

> by se měl přesunout filtr "Sbírky", který by se měl zároveň přejmenovat na "Knihovny". Jen v klientovi pro ČDK.

Přejmenování _sbírek_ na _knihovny_ je už dost specifiké pro konkrétní použití Krameria, takže i u klienta bych tady šel cestou změny až v konkrétní instalaci klienta.
Není to jen u hledání, ale taky u procházení a odkaz v hlavičce na sbírky.
Všechny texty jsou v lokalizačních souborech:
CS: /assets/i18n/cs.json (http://kramerius.rychtar.cloud/assets/i18n/cs.json)
EN: /assets/i18n/en.json (http://kramerius.rychtar.cloud/assets/i18n/en.json)
Tam se dají dohledat všechny zmínky o _sbírkach_ a změnit to na _knihovny_.
