### ISSUE TITLE
Problém při stisku Ctrl+r (F5)

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#168]
Zdravím,

narazil jsem při testování nového klienta na následující problém. Pokud se zanořím z výchozí/domácí stránky na nějakou nižší úroveň tlačítkem [ -> VSTUPTE ] a následně provedu reload kombinací kláves viz. subject, tak při stisknutí tlačítka/šipky (nikoliv šipka samotného prohlížeče, ale ta co je součástí html stránky) v levém horním horu (zpět na předchozí stránku) dostanu následující chybovou hlášku:

![404-01](https://user-images.githubusercontent.com/8750622/51611812-7262c180-1f20-11e9-8a41-423548331565.png)

a zároveň už nejsem schopen se z tohoto chybového stavu dostat jinak, než skokem na výchozí/domácí stránku.

Řešili jsme to tady i s @pavel-stastny, měli jsme podezření na chybné nastavení přepisování přímo ve webserveru, ale nakonec to spíše vypadá na nějaký bug.

Modul mod_rewrite je aktivní a obsah .htaccess v root-u klienta je nastaven dle návodu.

MD

**Comment by honza-rychtar** [comment]
Je to chyba na straně klienta. Projevuje se jen v *jednokrameriové* instalaci. Proto se to v té testovací instalaci s více Krameriema neprojevilo.
Hned to opravím.

**Comment by honza-rychtar** [comment]
Opraveno.

**Comment by mduda100871** [comment]
Zdravím,
zdá se, že reload už chodí jak má...
MD
