### ISSUE TITLE
Neveřejné PDF

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#170]
V případě, že není PDF veřejně přístupné, tak se objeví hláška: "PDF dokument není veřejně dostupný" v češtině a to bez ohledu na jazyk, na který mám nastaveno.

**Comment by honza-rychtar** [comment]
Opraveno

**Comment by krizovj** [comment]
Hláška se změní do jiného jazyka až potom, co ji obnovím, ale ne hned, jak to přepnu. Šlo by s tím něco dělat?
