### ISSUE TITLE
změnit text placeholderu v poli hledaní

### ISSUE THREAD

**Issue by indrakm** [ceskaexpedice/kramerius-web-client#171]
změnit text placeholderu v poli hledaní když sem na obrazovce hledání. Při filtru rozlišit jiný text, že nehledám ve všem.

**Comment by honza-rychtar** [comment]
Všude kromě vyhledávací obrazovky má text placeholderu 2 stavy podle naposledy zvoleného přepínače **Pouze veřejné**.
1. _Hledat v celé digitální knihovně_
2. _Hledat ve veřejných dokumentech digitální knihovny_


Ve vyhledávací obrazovce má text placeholderu 3 stavy
1. _Hledat v celé digitální knihovně_ není-li vybrán žádný filtr
2. _Hledat ve veřejných dokumentech digitální knihovny_ je-li vybrán jen filtr **Pouze veřejné**
3. _Hledat s filtry F1, F2, ..., Fn_ v všech ostatních případech pro _n_ vybraných filtrů

Ad 3) Např. **Hledat s filtry Pouze veřejné, Kniha, Komenský, Jan Amos, 1650 - 1700, čeština**
http://dk.kramerius.org/mzk/search?accessibility=public&sort=newest&authors=Komensk%C3%BD,%20Jan%20Amos&languages=cze&doctypes=monograph&from=1650&to=1700

Mezi filtry se nepočítá hledaný řetězec, který se neuplatňuje při dalším hledání, protože je novým řetězcem nahrazen.
