### ISSUE TITLE
Procházení dle autora

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#174]
Pokud procházím knihovnu dle autorů, seřadím dle abecedy - zobrazí se mi pouze 100 výsledků a nemohu dále listovat...

![snimek z 2019-02-05 11-33-08](https://user-images.githubusercontent.com/33415849/52267801-412fbb80-293a-11e9-85a1-2152a0eaeb43.png)

**Comment by jahhoo** [comment]
Nebylo by špatné tam přidat lištičku s abecedou jako ve starém klientovi.
![snimek z 2019-02-05 13-30-10](https://user-images.githubusercontent.com/33415849/52273523-675d5780-294a-11e9-97e1-162766bc42cb.png)

**Comment by zabak** [comment]
Na nejnovější verzi mi to zobrazí 100 a pak můžu dole skákat po stovkách. Lišta se stránkováním by ale mohla být vylepšena. Teď na MZK člověk vidí při listování něco jako 

`< 1 113 114 115 116 117 118 119 120 121 122 123 1005>`
bylo by lepší něco jako
`< 1 ... 113 114 115 116 117 118 119 120 121 122 123 ... 1005>`

Abeceda je sice fajn, ale pokud mám v Krameriu přes 100.000 autorit, tak selhává - na jedno písmeno by vyšlo cca 4000 položek, což je k ničemu.
Osobně vidím jako užitečnější to vyhledávací okénko nahoře nad seznamem, ideálně reagující aktivně po vepsání každého znaku podobně jako našeptávač, jen by se skákalo v seznamu.

**Comment by D-Benes** [comment]
Pro přehled připomenu, že první ze zde zmíněných problémů už zazněl v #123.
