### ISSUE TITLE
vylepšení heuristiky zobrazování dvoustran u rukopisů

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#175]
U rukopisů kde jsou stránky číslované podle pravidel pro zpracování rukopisů, např. 
[zde](http://kramerius.rychtar.cloud/mzk/view/uuid:5e0d749d-c560-4b8c-aae7-665cb952b655?page=uuid:d74c36f9-90d8-409d-b0e7-b04d0d2ac5b9)
platí tyto konvence pro zobrazování dvoustran: 

FC = přední desky = zobrazit samostatně
FS = přední přídeští = zobrazit vlevo, spolu s 1r
SP = hřbet = zobrazovat samostatně, klidně až na konci, nebo společně se zadní obálkou
NNNr = NNN recto = zobrazit vždy vpravo
NNNv = NNN verso => zobrazit vždy vlevo
BS = zadní přídeští
BC = zadní desky

tj. dvojice budou např. FS+1r,1v+2r,...,28v+BS,BC
podrobněji popsáno na straně 13 zde: [zde](http://www.manuscriptorium.com/sites/default/files/docs/manuscriptorium_visk6_definice.pdf
)

Předpokládám, že heuristiku rozhodilo jednak FC (je první ale zobrazeno jako dvoustrana místo samostatně) a potom hřbet, který je vložený jako 3. snímek (což u rukopisů s TEI metadaty bývá) a který by stačilo ignorovat a hodit na konec.

**Comment by honza-rychtar** [comment]
@zabak Proč nejsou ty typy stran v datech? Všechny strany mají typ NormalPage.

**Comment by zabak** [comment]
@honza-rychtar možná i proto, že jsme tu konverzi dělali hodně dávno.

**Comment by zabak** [comment]
@honza-rychtar Opravíme to v datech - vycházel jsem hlavně z toho, že podobnou úpravu jsi dělal v digitální knihovně

**Comment by honza-rychtar** [comment]
@zabak U většiny rukopisů jsou typy stran uváděny správně. Např. http://kramerius.rychtar.cloud/mzk/view/uuid:83aa6b97-92d1-4d38-b78a-a30839717c6a?page=uuid:fda671a4-70ef-430e-a3ad-bc2877d5e5c6
Přehodím alespoň ty hřbety na konec seznamu (#187)

**Comment by zabak** [comment]
OK, toto issue zavírám.
