### ISSUE TITLE
Neveřejný dokument - hláška

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#176]
Jde hláška pro zobrazení neveřejného dokumentu změnit, nebo je pro všechny knihovny stejná? Teď to vypadá, že tam mají všichni hlášku z ČDK. 

Aspoň tady v těch testovacích verzích je všude stejná.
http://kramerius.rychtar.cloud/mzk
http://nkp.kramerius.rychtar.cloud/about
http://knav.kramerius.rychtar.cloud/about

A v těch testovacích není hláška pro anglickou verzi.

**Comment by krizovj** [comment]
A pokud jde o PDF, šlo by to udělat stejně? Aby se to dalo upravit pro konkrétní knihovnu a byl tam stejný text jak pro PDF tak pro sken?

**Comment by zabak** [comment]
Pokud je ta hláška individualizovaná, měla by lézt z Krameria přes API, aby byla použitelná i v mobilních aplikacích.

**Comment by JanMeritus** [comment]
Osobne si myslim ze hlaska by sa mala rozsirit o rozne druhy neverejnych dokumentov, napr. podla priznaku DNNT true #210 .

**Comment by honza-rychtar** [comment]
Pro PDF dokumenty jsem založil separátní issue #227 
Jinak vyřešeno v rámci #105
