### ISSUE TITLE
Příloha monografie

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#177]
Dobrý den, 
mám dotaz ohledně přílohy monografie. Zdá se mi, že je klient neumí zobrazit. Nebo to tak alespoň vypadá. 

Asi je problém s tím, že když má monografie přílohu, tak ten záznam té přílohy je na stejné úrovni jako jednotlivé stránky té monografie. 

Tady je příklad z ČDK:
http://cdk.lib.cas.cz/client/handle/uuid:ab822bb6-5510-11e4-b8cd-00155d010f03
Příloha je vidět na konci po jednotlivých stránkách. Lze ji otevřít a zobrazí se další úroveň. 

Stejnou monografii jsem hledala tady: http://kramerius.rychtar.cloud/cdk 
A zobrazily se jen stránky té monografie, příloha tam není, ani její metadatový záznam. 
http://kramerius.rychtar.cloud/cdk/uuid/uuid:ab822bb6-5510-11e4-b8cd-00155d010f03

A u toho jsem přišla na jednu věc, i když to není chyba, ale je to zvláštní.
Vyhledala jsem "140 let divadla v Jaroměři" takhle číslovkou. 
Ve výsledcích vyhledávání bylo tohle (slovní vyjádření číslovky):
![image](https://user-images.githubusercontent.com/21309201/52620664-73469d80-2ea5-11e9-9be1-682eb46ad579.png)

A po otevření záznamu zase číslovka:
![image](https://user-images.githubusercontent.com/21309201/52620694-8d807b80-2ea5-11e9-8c3c-8b9eb147270e.png)

**Comment by honza-rychtar** [comment]
> Stejnou monografii jsem hledala tady: http://kramerius.rychtar.cloud/cdk
A zobrazily se jen stránky té monografie, příloha tam není, ani její metadatový záznam.
http://kramerius.rychtar.cloud/cdk/uuid/uuid:ab822bb6-5510-11e4-b8cd-00155d010f03

Udělám to stejně jako v Digitální knihovně -
http://www.digitalniknihovna.cz/cdk/view/uuid:12dc7c67-672e-4fda-aa6b-4623b71fb9c4?page=uuid:ab822bb6-5510-11e4-b8cd-00155d010f03
Stránky přílohy se zobrazí za stránky monografie.
Ok?

> A u toho jsem přišla na jednu věc, i když to není chyba, ale je to zvláštní.
Vyhledala jsem "140 let divadla v Jaroměři" takhle číslovkou.
Ve výsledcích vyhledávání bylo tohle (slovní vyjádření číslovky):

Název se slovním vyjádřením je vedený jako alternativní. V Solr se pak (nevím proč) zapsal *root_title*.
Celkově je to tím, že *root_title* a _dc.title_ obsahují různé hodnoty, což by se u top level dokumentu nemělo vůbec stát.

**Comment by krizovj** [comment]
Za mě asi v pohodě, ale bylo ještě možné, když budu na stránce, která patří do té přílohy, aby se vpravo zobrazila metadata k té příloze? Je to celý záznam a tady
http://www.digitalniknihovna.cz/cdk/view/uuid:12dc7c67-672e-4fda-aa6b-4623b71fb9c4?page=uuid:ab822bb6-5510-11e4-b8cd-00155d010f03

není moc poznat, že je to příloha. Je to uvedeno jen u popisu stránky. 

Ještě by se měl asi vyjádřit někdo, kdo těch příloh má více. My jich tolik nemáme. 


Díky za vysvětlení těch číslovek.

**Comment by honza-rychtar** [comment]
Stránky přílohy se už zobrazují. Metadata ještě ne - k tomu jsem založil separátní issue (#189) a toto zavírám.

**Comment by tumovam** [comment]
Dobrý den,
v KNAV jsme opět narazili na problém s přílohami monografie. Pokud má monografie 2 (a asi více, ale to jsme nezkoušeli) přílohy, v bílém klientovi se zobrazí jen první. 

Např. 2. svazek (https://kramerius.lib.cas.cz/view/uuid:958cf0f8-2bf3-4c54-b7f8-17ba6059bd3b) monografie "Die Naturgesetze und ihr Zusammenhang mit den Prinzipien..." (https://kramerius.lib.cas.cz/uuid/uuid:58bd01a7-e617-4311-b9ef-904b4291d5f3) má dvě přílohy, ale v UNNK se zobrazuje pouze 1. příloha ("Theile Wärme und Elastizität" - s. [1a]-[231]):
https://kramerius.lib.cas.cz/uuid/uuid:c918a82d-dc9e-492d-b505-14062771d600 a úplně chybí skeny (+ tedy i metadata) 2. přílohy... 

V jádru jsou obě přílohy. Jak 1. "Theile Wärme und Elastizität" - s. [1a]-[231]: https://kramerius.lib.cas.cz/search/handle/uuid:68325fd0-51fe-47d4-b3a8-54a7ea062800, tak i 2. "Das Wesen der Elektrizität, des Galvanismus und Magnetismus" - s. [1a]-III: https://kramerius.lib.cas.cz/search/handle/uuid:e414390a-fef7-4d29-9e49-7a607d08a2c0

![obrazek](https://user-images.githubusercontent.com/31240271/64510962-88709700-d2e3-11e9-82d6-01c59a382735.png)


Šlo by povolit zobrazení i více příloh monografie? Nejspíš to budou ojedinělé případy, ale stát se to může. Díky moc

**Comment by krizovj** [comment]
https://github.com/ceskaexpedice/kramerius-web-client/issues/262

**Comment by honza-rychtar** [comment]
Opraveno.
