### ISSUE TITLE
Spojování stran

### ISSUE THREAD

**Issue by PavlinaKocisova** [ceskaexpedice/kramerius-web-client#178]
Dobrý den,  chtěli  bychom se zeptat, na jakém základě se v Krameriovi spojují strany? Odkud Kramerius čerpá data pro spojení, případně pro to, která strana je levá, a která pravá, aby je následně spojil?
Děkuji.

**Comment by vjirousek** [comment]
Dotaz primárně směřuje k tomu, jak přesně by měl vypadat zápis nově přidaných informací ke stránce (dle loňských DMF) ve FOXML. UUID je vcelku jasné, ale jelikož v rámci NDK linky posíláme do Krameria balíčky již ve FOXML, potřebovali bychom zejména vyjasnit správný zápis informace o reprezentativní straně a informaci zda jde o right/left/singlepage stranu, tedy v NDK balíčku tyto elementy v dmdsec pro PAGE:

![obrazek](https://user-images.githubusercontent.com/22765973/53176140-bd3e2a80-35ed-11e9-8a87-4712805c5ced.png)


Děkuji.

**Comment by pavelkocourek** [comment]
@honza-rychtar Honzo, používáme již metadata na určení Leve/Prave, která definovala NK?

**Comment by honza-rychtar** [comment]
Dvoustránkového zobrazení je teď řešeno heurestikou na straně klienta, která určuje (*hádá*) pořadí stran na základně
* typu dokumentu
* typu strany (desky samostatně, titulní strana vpravo, ...)
* pořadí strany
* okolí strany

Až bude informace o pozici strany přímo v datech tak heurestiku nahradíme touto přesnou informaci.

Pokud jde o reprezentativní stranu, tak tu klient neřeší vůbec.
Vím, že se loni (podle mě nesprávně) rohodlo, že informace o reprezentativní straně bude na úrovni strany. Ale letos se zase zvažovala (podle mě správná) varianta, že se informace o reprezentativní straně bude uvádět shora, tj. 
**Periodikum P má reprezentativní stranu S**
místo toho, aby to bylo 
**Strana S je reprezentativní stranou**
Z čehož pak ale nejde určit čeho to vlastně je reprezentativní stranou - periodika? čísla? ročníku?

**Comment by krizovj** [comment]
"Až bude informace o pozici strany přímo v datech tak heurestiku nahradíme touto přesnou informaci."

Takže pokud to bude v datech, tak si ten údaj vezme z dat a pokud to tam nebude, tak budou pořád platit ta výše uvedená pravidla?

**Comment by honza-rychtar** [comment]
@krizovj 

> Takže pokud to bude v datech, tak si ten údaj vezme z dat a pokud to tam nebude, tak budou pořád platit ta výše uvedená pravidla?

Ano

**Comment by godnat** [comment]
Dobrý den,

nové standardy NDK už umožňují informace o levé/pravé straně do metadat zapsat, v datech to pak vypadá takto: 
[mets_740393a0-3110-11e9-b40e-0050568209d3.zip](https://github.com/ceskaexpedice/kramerius-web-client/files/2893665/mets_740393a0-3110-11e9-b40e-0050568209d3.zip)

Zajímá nás, jak z těchto dat pak vypadá FOXML, kam se ve FOXML ten údaj levá/pravá propíše.

**Comment by honza-rychtar** [comment]
Je to součástí MODS stránky. Do FOXML by se měl přenést celý MODS záznam včetně pozice strany.
Všiml jsem si tam jedné chyby:
`<mods:detail type="page number"> 
`
místo
`<mods:detail type="pageNumber"> 
`

Od změny standardu k použití v klientovi je ještě dlouhá cesta.
1) Import METS - Uložení MODS data streamu stránky
2) Změna SOLR schema a indexace - pozice stránky musí být v indexu
3) Změna API Krameria - výpis stran dokumnetu /item/UUID/children musí obsahovat pozici stránky (která je nově v indexu)
4) Změna klienta - pokud objekt stránky obsahuje pozici, tak použiju tuto pozici místo heurestikou spočítanou pozici. Pokud stránka neobsahuje pozici, tak se řídím heurestikou.

**Comment by godnat** [comment]
Díky, nám se FOXML pro strany z těchto dat už tvoří, tak nám jde o to, aby se tvořil správně až to jednou Kramerius bude umět z těch dat brát. Takže to tedy zatím uděláme tak, že tam tu pozici strany přeneseme tak jak je v balíku NDK v MODS metadatech. 

Co se týče té chyby v <mods:detail type="page number">, tak standard NDK aktuálně předepisuje hodnotu atributu takto s mezerou. Je to v Krameriovi problém?

**Comment by honza-rychtar** [comment]
> Co se týče té chyby v <mods:detail type="page number">, tak standard NDK aktuálně předepisuje hodnotu atributu takto s mezerou. Je to v Krameriovi problém?

Není to jen překlep ve standardu?
Nedokážu si racionálně vysvětlit, proč by zrovna tato a jediná hodnota atributu **type** byla psána s mezerou.
**pageIndex**, **titlePage**, **normalPage** zůstává
a u **pageNumber** se najednou udělá změna na **page number**.

**Comment by JanMeritus** [comment]
@PavlinaKocisova je to chyba, alebo nejaky specificka interpretace mimo LOC? ak sa vychadza z filozofie top lvl elementu part (a jeho napr partNumber -> https://www.loc.gov/standards/mods/userguide/part.html), tak by to malo byt ako @honza-rychtar pise .. ?

**Comment by vjirousek** [comment]
@JanMeritus Nic specifického v intepretaci nevidím, přímo v odkazované dokumentaci k _Top-level Element: part_ je uveden tento příklad:

![obrazek](https://user-images.githubusercontent.com/22765973/53621562-35f94400-3bf7-11e9-818b-34f1e79f9d02.png)

**Comment by vjirousek** [comment]
@honza-rychtar Honzo, platí prosím stále že klient nepracuje s informací levá-pravá strana ani s údajem o reprezentativní straně? Díky.

**Comment by honza-rychtar** [comment]
@vjirousek Ano, klient informaci o levé, pravé, repre straně nijak nezohledňuje.
Jsou už nějaké ukázky, kde je to produkčně v datech?

**Comment by honza-rychtar** [comment]
Implementaci zobrazení dvoustran podle dat z MODS řešme dál tady #487
