### ISSUE TITLE
Tlačítko "zpět" v prohlížeči vs. v aplikaci

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#179]
Zvláštní chování tlačítek "zpět", možná se jedná o chybu.

Když vstoupím do titulu/čísla (např. z některé vyšší úrovně), ocitnu se na některé stránce daného dokumentu. V rámci tohoto dokumentu se pak dalším klikáním přesunuju na další jeho stránky. A teď:
1) Když nyní použiju tlačítko "Zpět na předchozí stránku", které je v aplikaci (šipka vlevo nahoře), vyhodí mě to o úroveň výše.
2) Když namísto toho ve stejnou chvíli použiju tlačítko "zpět" v prohlížeči (zde Firefox), hodí mě to jen na předchozí zobrazenou stránku v rámci téhož dokumentu.
3) Když ale nejdřív použiju "prohlížečovou zpátečku" (aniž bych přitom vyskočil ven z dokumentu) a POTOM kliknu na "zpátečku v aplikaci", nevyhodí mě to (oproti očekávání) o úroveň výš, nýbrž se začnu posouvat zase dopředu (!) po krocích, které jsem předtím "prohlížečovou zpátečkou" vracel (tj. znovu se přesunuji jen mezi stránkami téhož dokumentu).

Je prosím chování, popsané v bodu 3, v pořádku?

**Comment by honza-rychtar** [comment]
Tohle je chyba. Opravím.

**Comment by honza-rychtar** [comment]
Opraveno.
