### ISSUE TITLE
Problém se zobrazením příloh + proklik z vyhledávání

### ISSUE THREAD

**Issue by vjirousek** [ceskaexpedice/kramerius-web-client#184]
Z výsledků vyhledávání nelze prokliknout na stránky zařazené pod přílohou. Například při vyhledávání termínu "mohrau" v titulu Brünner Zeitung: 

http://digitalniknihovnanew.mzk.cz/mzk/periodical/uuid:eb3adc60-dd58-11e2-9923-005056827e52?fulltext=mohrau

![obrazek](https://user-images.githubusercontent.com/22765973/53501174-05f15a00-3aac-11e9-848b-7ba34937b025.png)

U vyznačených výsledků se nenačte obrázek. Jde o stránky nacházející se pod přílohou (zařazenou přímo pod ročníkem). 

Při procházení periodika se příloha zobrazí, nenačítají se ale metadata k příloze:

![obrazek](https://user-images.githubusercontent.com/22765973/53501404-608ab600-3aac-11e9-87c3-19b44624f35a.png)

**Comment by honza-rychtar** [comment]
Opraveno

**Comment by jahhoo** [comment]
@honza-rychtar problém byl sice opraven, ale stále se generuje špatné URL pro sdílení a v citaci - přidává se parametr &full - dokument pak nejde z odkazu otevřít.
