### ISSUE TITLE
Autoři s více křestními jmény

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#185]
U autorů s více křestními jmény (= v MODS je dvakrát _<mods:namePart type="given">_) se po otevření titulu v levém sloupci v položce _Autor_ zobrazí jen druhé z obou jmen.
Patrně následkem toho pak tato položka také nefunguje jako klikatelný odkaz (protože odkazuje na neexistující kombinaci jméno+příjmení).

Např. Josef Václav Frič (http://kramerius5.nkp.cz/search?ordering=relevance&authors=Fri%C4%8D,%20Josef%20V%C3%A1clav):
![1](https://user-images.githubusercontent.com/44299577/53580178-571c4f00-3b7b-11e9-86e4-729f276bee8d.jpg)

![2](https://user-images.githubusercontent.com/44299577/53580197-60a5b700-3b7b-11e9-8ae2-ec4300f6ceb7.jpg)

**Comment by luckajirku** [comment]
Můžu se zeptat, proč ta křestní jména vlastně rozdělujete do dvou a nenecháte to v jednom výskytu? Je pravda, že standard přímo tuhle situaci neřeší, je tam popsáno jen rozdělení na family/given, ale logicky to moc nedává smysl dělit.

**Comment by pavluska** [comment]
MODS sice explicitně nezakazuje dva elementy namePart s atributem given, ale v příkladech a doporučeních jsou dvě jména vždy v jednom elementu. A to ze zřejmého důvodu. Křestní jména jsou v daném pořadí. Třeba Josef Václav Sládek nebo Jan Amos Komenský. Václav Josef nebo Amos Jan jsou úplně jiné osoby. A jelikož pořadí prvků v MODS není pevně dané, musí tak být určeno pořadí jmen v jednom elementu.

**Comment by pavelkocourek** [comment]
Při-ohnout funkcionalitu aplikace Krameria není správná cesta ...  i když to účelově lze udělat.
Nicméně ... existuje možnost, že by se data v Národní knihovně "opravila"?

**Comment by D-Benes** [comment]
Děkuji za odpovědi - a ano, víme, že to není ideální stav metadat; nicméně se ukázalo, že se to naštěstí vyskytuje jen u menší části našich digitalizátů (a další taková data že už vznikat nebudou).
Takže momentálně zjišťujeme, jak často se tato "chyba" vyskytuje, a podle toho uvidíme, jestli bude rozumnější data jen rovnou opravit anebo jestli budeme nejdřív nuceni vývojový tým o nějaké to "při-ohnutí" Krameria poprosit.

**Comment by pavluska** [comment]
Když si to přiohnete, tak už si to nikdy neopravíte :) Věřte mi :)

**Comment by Drahotussky** [comment]
Dobrý den,
rád bych se zeptal kohokoliv na jednu věc k tomuto problému jmen. 
Jak postupujete v případech, kdy v katalogizačním záznamu je křestní jméno i příjmení autora zapsáno v jednom poli? V metadatovém editoru pak jméno převedené z katalogizačního záznamu rozdělujete do dvou elementu namePart s příznaky given a family nebo celé jméno prostě převedete z katalogizačního záznamu do jednoho elementu namePart a necháte tak?
Děkuji
A. Drahotušský

**Comment by pavluska** [comment]
Nevím jak teď, ale dřív se to neřešilo a nechávalo v jednom poli, když se konvertovalo z MARCu. Není to chyba, je to jedna z možností, pravděpodobně ta nejčastější.

**Comment by krizovj** [comment]
My to tedy rozdělujeme. Rozděluje to ProArc při konverzi z MARC.
Ve standardu je u atributu "type" povinnost M a je tam uvedeno, že pokud lze rozdělit, tak se to musí rozdělit. Pokud ne (např. Homér nebo jména, u kterých nelze určit, co je jméno a co příjmení), tak to může být v elementu namePart.
