### ISSUE TITLE
Hledání v OCR při určitých kombinacích filtrů

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#186]
Když vyfiltruju zároveň (1) typ dokumentu _Mapa_ a (2) konkrétního autora, tak následně nefunguje hledání textových řetězců v OCR. Přitom bez vyfiltrování autora je tentýž řetězec v tomtéž titulu bez potíží vyhledán.
Např. slovo _"ukrajinská"_ se v titulu http://kramerius5.nkp.cz/view/uuid:de2ecae0-82dd-11e5-a715-005056827e52 vyskytuje ([zde](http://kramerius5.nkp.cz/view/uuid:de2ecae0-82dd-11e5-a715-005056827e52?page=uuid:1b30a680-b3d4-11e5-b404-005056825209&fulltext=ukrajinsk%C3%A1)) a v prvním popsaném případě se jeho výskyty zde [vyhledají](http://kramerius5.nkp.cz/search?q=ukrajinsk%C3%A1&ordering=relevance&doctypes=map), kdežto ve druhém [nikoliv](http://kramerius5.nkp.cz/search?q=ukrajinsk%C3%A1&ordering=relevance&authors=Aunick%C3%A1,%20Eva&doctypes=map).

Je možné, že podobné problémy se vyskytují i při jiných kombinacích filtrů (jen jsem na ně nenarazil).

**Comment by zabak** [comment]
Tohle je způsobeno tím, že stránky (model page) v solru neobsahují kompletní metadata, podle kterých se dá filtrovat a naopak ostatní modely neobsahují OCR. takže když se potká filtr na autora, který vyloučí všechny stránky, tak pak už není kde najít ten text a naopak. Toto je jedna z věcí, která by měla být řešena v rámci plánovaných změn v Solru. Obecně se dá řešit buď doplněním "fasetotvorných" metadat do každé stránky, nebo doplněním fulltextu do všech modelů s výjimkou periodik, kde by se asi muselo končit na úrovni ročníku kvůli velikosti toho fulltextu. Předpokládám, že se půjde cestou doplnění metadat do stránek.

**Comment by D-Benes** [comment]
Děkuju za odpověď a kvituju uzavření issue, pro jistotu se ale ještě zeptám:
Takže tomu můžeme rozumět tak, že na odstranění problému budou stačit úpravy Solru (které se plánují v brzké době)?
