### ISSUE TITLE
Posun hřbetu knihy konec dokumentu

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#187]
Bylo by prosím možné, aby se hřbety knih knih zobrazovaly stejně jako v Digitální knihovně dole? Když jsou nahoře, rozhazuje to dvoustránkové zobrazení. Souvisí s https://github.com/honza-rychtar/kramerius-web-client/issues/164

**Comment by honza-rychtar** [comment]
Hotovo
