### ISSUE TITLE
Poznámky - dotaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#19]
Měla bych dotaz ohledně poznámky v informacích o dokumentu. V tomto poli se zobrazují všechny poznámky, které jsou v záznamu nebo jen některé? A bylo by možné pokud budu u úrovně ročníku nebo čísla, aby se tam zobrazily poznámky k té konkrétní úrovni (a ne pouze k celému periodiku?).

**Comment by honza-rychtar** [comment]
Zobrazuji se vsechny poznamky ktere jseu v MODS hlavniho dokumentu primo pod <mods> elementem. 

Poznamky pro rocnik nebo cislo bychom mohli udelat jako u clanku (#14) a jak je navrhovano pro cisla v #11, tj. nacetla by se plna metadata pro rocnik a cislo vcetne poznamek.

**Comment by krizovj** [comment]
To by šlo

**Comment by honza-rychtar** [comment]
Hotovo, viz #11
