### ISSUE TITLE
Vyhledávání v dokumentu - zobrazení

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#190]
Když vyhledávám v dokumentu, nebo když otevřu dokument, kde jsou zobrazené výsledky vyhledávání, tedy jen ty stránky, kde se hledaný termín nachází, tak když je ten termín moc dlouhý nebo je to více slov, tak není vidět křížek u vyhledávacího pole. 
Šlo by to prosím opravit? Takhle to vypadá hrozně.
![image](https://user-images.githubusercontent.com/21309201/54432622-02a3d280-472a-11e9-9670-eaeb9ad57d94.png)

**Comment by krizovj** [comment]
Prosím o doplnění oranžového štítku, ať vím, jestli je to enhancement a jestli to mám dát do hlasovací tabulky. Přijde mi to teda spíš jako chyba...

**Comment by honza-rychtar** [comment]
Opraveno.
