### ISSUE TITLE
Příloha periodika - "Přejít na periodikum"

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#191]
Když jsem v čísle periodika, tak pod názvem periodika je proklik na celé periodikum "Přejít na periodikum". 
U přílohy periodika to chybí.

**Comment by krizovj** [comment]
Prosím o doplnění oranžového štítku, ať vím, jestli je to enhancement a jestli to mám dát do hlasovací tabulky. Přijde mi to teda spíš jako chyba...

**Comment by honza-rychtar** [comment]
Prosím o příklad.
Příloha je buď pod ročníkem nebo pod číslem a u obou případů se proklik _Přejít na periodikum_ zobrazuje.

**Comment by krizovj** [comment]
třeba tady: https://kramerius.lib.cas.cz/uuid/uuid:92bb81df-4c98-40e7-aa2b-75279c2164e9 
Když otevřete tu přílohu, která je na prvním místě před prvním číslem, tak mi proklik na celé periodikum zmizí. Ale když otevřu číslo jedna, tak tam je. 

Dělají to i klasicky naskenované dokumenty, nejen PDF: 
https://kramerius.lib.cas.cz/uuid/uuid:484c8b9e-5228-400d-ad1f-3aa0fe47f771

**Comment by honza-rychtar** [comment]
Bylo opraveno ve verzi 1.2.5
http://kramerius.rychtar.cloud/knav/uuid/uuid:92bb81df-4c98-40e7-aa2b-75279c2164e9
http://kramerius.rychtar.cloud/knav/periodical/uuid:484c8b9e-5228-400d-ad1f-3aa0fe47f771
