### ISSUE TITLE
označení více stránek pro stažení JPEG stránky

### ISSUE THREAD

**Issue by KarolinaKostalova** [ceskaexpedice/kramerius-web-client#196]
Nenašla jsem způsob, jak označit v rámci dokumentu více stránek z dokumentu, u kterých si potřebuju stáhnut JPEG. Kliknutím na ikonku pro stažení JPEG se rovnou vygeneruje obrázek té dané stránky, na které aktuálně jsem, respektive naší úpravou teď můžu stáhnout obrázky ze zobrazené dvojstrany.

Pokud chceme tisknout např. celé výtisky novin oboustranně, u starší digitalizace musíme často nejdřív stránky oříznout a případně narovnat. Teď postupujeme tak, že si jednotlivé stránky označíme, obrázky stáhneme, otočíme, ořízneme, převedeme do pdf a spojíme pro tisk.
Kdybychom si mohli označit celé vydání nebo více stránek, tak by nám to trochu ušetřilo práci, než že budeme postupně vydáním listovat a soubory si stahovat.

**Comment by pavelkocourek** [comment]
Souvisí s #50 - Výběr stran dokumentu pro tisk/generování PDF.

**Comment by KarolinaKostalova** [comment]
Ano, princip by měl být stejný jako při výběru stránek pro generování pdf nebo pro tisk.

**Comment by honza-rychtar** [comment]
Bude řešeno v rámci #50
