### ISSUE TITLE
U jména autora zobrazovat i doplňky ke jménu

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#197]
Viz např. uuid:6bb7a768-4afc-48bb-aa81-81abc2d69ce4 - statuta synodalia - zobrazuje se jen Arnošt, chybí zobrazit "z Pardubic" - což se zobrazuje na dlaždicích, ale ne v metadatech a dokonce ani v rozšířeném zobrazení metadat.

<namePart type="termsOfAddress">z Pardubic, pražský arcibiskup</namePart>

**Comment by honza-rychtar** [comment]
Přidáno.
