### ISSUE TITLE
Role u autora - kód "dis"

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#199]
Bylo by možné, aby se u kódu role "dis", zobrazil název role: "defendent" místo současného "Autor diplomové práce nebo disertace"? 

Hodilo by se to, kvůli starým tiskům. Pro badatele a KVO je nesmírně důležitý. Defendent je student, který dal vytisknout něčí práci, kterou následně obhajoval.

Podle kódů rolí je to správně, viz. https://www.nkp.cz/o-knihovne/odborne-cinnosti/zpracovani-fondu/informativni-materialy/kody-roli

Ale také podle NK je správně i ten defendent, pokud jde o staré tisky (strana 12): http://text.nkp.cz/o-knihovne/odborne-cinnosti/oddeleni-rukopisu-a-starych-tisku/strucna-rukovet-pro-katalogizaci-starych-tisku-podle-rda

**Comment by honza-rychtar** [comment]
Možné by to bylo, ale bude to celkově ku prospěchu?
Pro malou část uživatelů se to _zpřesní_, ale pro větší část uživatelů se použije neznámý výraz, který nejde ani vygoolit. Já jsem v tom teda hned viděl obžalovaného u soudu.

Podle https://www.loc.gov/marc/relators/relaterm.html je **Dissertant [dis]**
_A person who presents a thesis for a university or higher-level educational degree_
Taky je tady důraz na prezentaci/obhajobu a ne na to, že je autorem.

Tak co kompromis **Obhájce diplomové práce nebo disertace**?

**Comment by nezbedova** [comment]
Dívala jsem se do Manuscriptoria a tam mají ještě lepší kompromis:
**Autor diplomové práce nebo disertace, defendent**
Šlo by to tak? 

A obžalovaný u soudu je defendant [dfd] nikoli defendent. Což by se opravdu mohlo zaměňovat.

**Comment by honza-rychtar** [comment]
Změněno na **Autor diplomové práce nebo disertace, defendent**.
