### ISSUE TITLE
Nefunguje tlačítko "zpět na předchozí stránku"

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#2]
Nefunguje tlačítko "zpět na předchozí stránku"

**Comment by honza-rychtar** [comment]
Bude zprovozneno zacatkem pristiho tydne.

**Comment by honza-rychtar** [comment]
Tlacitko zpet ted funguje jako prochazeni zpet v historii s nekolika vyjimkami:
1) Prochazeni stranek v prohlizecce se nezapocitava
2) U hledani se zapamatuje vzdy jen posledni volba filtru
3) U prochazeni se zapamatuje vzdy jen posledni volba filtru

Chovani tlacitka zpet bude jeste upraveno, viz #10.
