### ISSUE TITLE
Hudebniny - zákaz tisku - hláška

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#20]
Pokud je dokument nepřístupný a je hudebninou, měl by u něj být zakázán tisk, a to i na místě samém. Ve všech klientech Krameria by se po kliknutí na ikonu pro tisk mělo objevit okno s následující hláškou:

"Autorsky chráněné hudebniny bohužel nelze žádným způsobem kopírovat z
důvodu výjimky v Autorském zákoně." 

V současné době je to zakázané, ale hází to chyby.

**Comment by honza-rychtar** [comment]
Hotovo. V pripade neverejne hudebniny se pri kliku na akci **Příprava k tisku** nebo **Vygenerovat PDF** zobrazi dialog s uvedenou hlaskou
