### ISSUE TITLE
Hlavní autor a další tvůrci

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#200]
Bylo by možné rozdělit pole Autor v metadatech v pravém sloupci do dvou polí? Jedním by byl "Hlavní autor" a druhým "Další tvůrci". 

Rozdělilo by se to podle atributu usage="primary" v elementu name. Pokud by tam atribut byl, tak by byl autor v poli "Hlavní autor", pokud by atribut chyběl, tak by bylo jméno v poli "Další tvůrci".
Autorů s atributem  usage="primary" může být více než jeden.

![PA_metadata_xml-1](https://user-images.githubusercontent.com/21309201/54899212-6323d400-4ecf-11e9-8293-f7d443e96c7b.jpg)

**Comment by zabak** [comment]
Pokud by se dělal zásah do zobrazovaných metadat, bylo by dobré sebrat všechny tyto požadavky a uplatnit je najednou. Kontroloval někdo detailněji jaké údaje zobrazujeme třeba o hudebninách nebo jakýchkoli jiných druzích dokumentů? Pokud se to bude dělat postupně po kouskách, bude to stát spoustu času.

**Comment by zabak** [comment]
S tím souvisí otázka kolik autorů zobrazovat. U http://www.digitalniknihovna.cz/mzk/view/uuid:5be687c0-d2bf-11e6-8f91-005056827e51?page=uuid:e6a79b70-de76-11e6-9964-005056825209 jsou tři autoři, ale Voskovec se nezobrazí, musí se rozkliknout, přestože je uvedený jako autor. Samozřejmě existují i věci s více autory, ale 3 autory by se zobrazovat ještě měli bez nutnosti rozklikávání.

**Comment by honza-rychtar** [comment]
Rozděleno na _Autor_ a _Další tvůrci_. Počet autorů v obou skupinách zobrazených bez nutnosti rozbalení zvýšen na 3.

<img width="302" alt="Screenshot 2019-12-15 23 35 18" src="https://user-images.githubusercontent.com/1178142/70870445-bb39c380-1f93-11ea-824e-247686fc70ad.png">
