### ISSUE TITLE
Možnost nastavit dvě loga

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius-web-client#201]
Momentální řešení umožňuje nastavit instituci logo pomocí proměnné `logo`. Navrhovaná úprava by umožňovala definovat `logoBig`, které by obsahovalo odkaz na variantu loga, která by se zobrazovala na domovské stránce.

Jde hlavně o situaci při použití `bigHomeLogo`, kdy bychom pro chráněný režim rádi použili graficky "složitější" variantu, která ovšem při zobrazení mimo domovskou stránku nevypadá dobře.

**Comment by honza-rychtar** [comment]
To dává smysl, udělám.

**Comment by honza-rychtar** [comment]
Hotovo.
V konfiguraci je teď kromě **logo**, taky **logoHome**. 
**logoHome** se použije pro logo na hlavní stránce (při obou variantách - malé i velké).
Pokud se **logoHome** nevyplní, tak se použije **logo**

Příklad.
http://mzk.kramerius.rychtar.cloud/
Různá loga na hlavní stránce a jinde v navbaru.
