### ISSUE TITLE
citace kartografického dokumentu

### ISSUE THREAD

**Issue by KarolinaKostalova** [ceskaexpedice/kramerius-web-client#202]
Aktuálně z citace mapy moc nejde poznat že jde o mapu. V NKC se do citací doplňuje \[kartografický dokument\], ale podle normy to není povinné.

**citace z K6:** Plavební mapa Labe: ř. km 726,60-837,40: Hřensko - Mělník. V Brně: Státní plavební správa, 2011. ISBN 978-80-260-1694-6. Dostupné také z: http://kramerius5.nkp.cz/uuid/uuid:df8fb4f0-7b99-11e8-9690-005056827e51

**citace z NKC:** Plavební mapa Labe. Hřensko - Mělník: ř. km 726,60-837,40 \[kartografický dokument\]. 1:5 000. \[Praha\]: Státní plavební správa, 2011. 1 atlas (\[116\] s.). ISBN 978-80-260-1694-6.

**Povinné** by podle normy mělo být v citaci kartografického díla **měřítko** (např. 1:50 000, pokud je to nutné, lze zapsat "měřítko neuvedeno", "Měřítko nelze určit". Nepovinný je rozměr, ten by se měl uvádět jako výška x šířka v milimetrech, pokud je to nutné, uvádějí se další rozměry, např. velikost listu (např. 250 mm x 350 mm, list 600 mm x 800 mm).

U některých map měřítko v metadatech je, např. http://kramerius5.nkp.cz/uuid/uuid:df8fb4f0-7b99-11e8-9690-005056827e51: `<mods:scale> Měřítko 1:5 000 </mods:scale>` nebo http://kramerius5.nkp.cz/uuid/uuid:10271b50-d54b-11e5-964f-005056825209 `<mods:scale> Měřítka různá </mods:scale>`

**Bylo by možné do citace přidat údaj o měřítku, pokud se v metadatech objevuje, a pokud ne, tak třeba "měřítko neuvedeno"?**

Pokud by to šlo, byly bychom rády, pokud by se do citace dala přidat i nepovinná informace o rozměru. Ta je v metadatech součástí fyzického popisu: `<mods:extent>1 mapa : barevná ; 37 x 51 cm, na listu 50 x 75 cm</mods:extent>`

**Comment by zabak** [comment]
Mimochodem, neměla by citace generovaná z anglické verze stránek mít ty české fráze v angličtině?

**Comment by KarolinaKostalova** [comment]
Určitě :)

**Comment by honza-rychtar** [comment]
Hotovo.
Je třeba počítat s tím, že v metadatech může být u měřítka i rozsahu libovolný text. A nevím, jestli by měl být celý ten text v rozsahu součástí citace.

http://www.digitalniknihovna.cz/mzk/uuid/uuid:fecf57c0-47c9-11e8-9a44-005056827e52
<img width="696" alt="Snímek obrazovky 2020-11-12 v 16 01 25" src="https://user-images.githubusercontent.com/1178142/98956462-5a4aa080-2500-11eb-9a93-fe25980084d3.png">

http://www.digitalniknihovna.cz/mzk/uuid/uuid:c62b1ca8-cfec-4634-a42d-b4e41b532d25
<img width="699" alt="Snímek obrazovky 2020-11-12 v 16 00 46" src="https://user-images.githubusercontent.com/1178142/98956400-456e0d00-2500-11eb-8356-7636960817c7.png">

http://www.digitalniknihovna.cz/mzk/uuid/uuid:0669c8a0-1be8-11ea-b1af-005056827e51
<img width="701" alt="Snímek obrazovky 2020-11-12 v 16 02 26" src="https://user-images.githubusercontent.com/1178142/98956587-81a16d80-2500-11eb-92f6-846743cef6ec.png">

**Comment by jachym-s** [comment]
Dobrý den,

rád bych toto issue po čase otevřel, s dvěma návrhy:

1. Nyní se v citacích neobjevuje slovo "Měřítko", i když je v metadatech. To je problematické u map, které měřítko nemají a v metadatech je napsáno např. "Měřítko neuvedeno". V citaci se pak objeví jen slovo "neuvedeno" a není tak zřejmé, co není uvedeno. Bylo by možné toto opravit, doplnit slovo "Měřítko" do citací? (Ono by snad nevadilo, kdyby slovo "Měřítko" bylo uvedené i tam, kde je číselný údaj...)

<img width="508" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/135708946/dacc31af-a8ac-4d09-921e-a033e978c4bd">

2. Rukopisné mapy, které nemají v metadatech "dateIssued", ale mají "dateCreated" (viz např. ta samá mapa https://kramerius.cuni.cz/uk/uuid/uuid:3ecf5ec6-4d4b-11ec-84a6-fa163e4ea95f) - bylo by možné toto datum dostat do citace? Případně i do pravého panelu k ostatním bibliografickým údajům?

S díky za zvážení návrhů
Jáchym Šenkyřík

**Comment by honza-rychtar** [comment]
@jachym-s přepsal jsem to tady #678 
Tohle issue zůstalo zavřené, to už bychom nedohledali - narazil jsem na to náhodou přes mail.

Nové věci prosím přes nové issue, i když nějak souvisí s něčím v minulosti.

**Comment by jachym-s** [comment]
Rozumím, děkuju!
