### ISSUE TITLE
Seznam našeptávače přebírá to co je pod kurzorem bez kliknutí 

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#205]
Pokud začnu zadávat vyhledávací dotaz, tak se objeví nabídka našeptávače. 

- Pokud najedu kurzorem nad nějakou položku z tohoto seznamu, tak se její text rovnou převezme do vyhledávacího pole. Když ale bez kliknutí vyjedu mimo to menu, tak ve vyhledávacím poli už zůstane ten text zadaný a nezmizí. 
- Pokud kliknu do prázdného vyhledávacího pole, kurzor muši odsunu dolů aby nezacláněl a začnu psát vyhledávací dotaz, tak po prvním písmeni se mi vybalí nabídka našeptávače, jedna z jejích položek se objeví pod kurzoram myši a rovnou se přenese do vyhledávacího pole přesto, že já jsem nic z našeptávače nechtěl. A pak celý ten vložený text musím smazat.

Návrh řešení: podobně jako v digitální knihovně přebírat položky z našeptávače až po kliknutí.

**Comment by honza-rychtar** [comment]
Změním, tohle chování je hodně otravné.

**Comment by honza-rychtar** [comment]
Hotovo.
