### ISSUE TITLE
Metadata k článku - rozdělení abstraktu

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#209]
Když má článek abstrakt v češtině a angličtině, v metadatech se vloží do jednoho pole. Nešlo by to nějak opticky odlišit, že jako začíná něco dalšího? Takhle je např. text v češtině a rovnou na to navazuje anglický abstrakt.
Příklad: 
https://kramerius.lib.cas.cz/uuid/uuid:b4ca0d94-c8d6-42e9-bc87-b3fb488da8fc

S tím souvisí další věc a to je délka abstraktu. Šlo by zobrazit z každého toho abstraktu třeba pět řádek a pak by tam byly rozklikávací tři tečky jako je to třeba u autora?

**Comment by honza-rychtar** [comment]
Hotovo.
<img width="373" alt="Snímek obrazovky 2020-11-12 v 15 21 16" src="https://user-images.githubusercontent.com/1178142/98964294-eeb90100-2508-11eb-943d-7f9decf5f660.png">

**Comment by zabak** [comment]
@honza-rychtar Ještě není dořešená ta délka abstraktu: "S tím souvisí další věc a to je délka abstraktu. Šlo by zobrazit z každého toho abstraktu třeba pět řádek a pak by tam byly rozklikávací tři tečky jako je to třeba u autora?" Zrovna v tom příkladu je ten abstrakt fakt dlouhý.

**Comment by honza-rychtar** [comment]
Delší abstrakt je teď rozbalovací.
<img width="291" alt="Snímek obrazovky 2020-11-30 v 17 29 18" src="https://user-images.githubusercontent.com/1178142/100636112-a33c8a80-3331-11eb-873b-ad6a4fc056b2.png">
