### ISSUE TITLE
Priznak DNNT: Filter, lock a informacie

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius-web-client#210]
Pri vyhladavani by client mal zohladnovat diela s priznakom DNNT. Zatial nema na to nijaky : 

- volitelny filter (napr v dostupnosti)

- odlisne zobrazenie zamku (vid Stalin - horor 20. století)

- moznost informativneho textu, ak to pravidla pre Read pre daneho uzivatela nedovoluju citat

<img width="1439" alt="Screenshot 2019-04-01 at 16 19 01" src="https://user-images.githubusercontent.com/25201690/55335049-b206d600-549a-11e9-8ed3-d0585a9fa636.png">

- citatelnost funguje, ale znova bolo by v datach k dielu dobre pridavat priznak DNNT

<img width="1403" alt="Screenshot 2019-04-01 at 16 19 24" src="https://user-images.githubusercontent.com/25201690/55335572-9a7c1d00-549b-11e9-9abd-f3d79c7455f7.png">

- u periodik chyba podobne odlisenie v jednotlivych rokoch, co sa tyka mriezkoveho a rocneho zobrazenia

<img width="1406" alt="Screenshot 2019-04-01 at 16 25 41" src="https://user-images.githubusercontent.com/25201690/55335516-80423f00-549b-11e9-8704-525bdaa79607.png">

**Comment by pavelkocourek** [comment]
přidávám z mailové komunikace s H:
Zobrazení hlášky u DNNT by mělo fungovat.  Ta ukázka vypadá, že to vůbec neřeší DNNT, ale že je uživatel v budově knihovny a k dokumentu ma tedy přístup na základě povolené IP adresy.
Pokud by byla na základě DNNT - měl by tam hlášku, resp. hlášku v případě, že není přihlášený jako dnnt user. Nebo lištu se svým jménem a infem o DNNT, pokud je přihlášeny jako dnnt user.
(navbaru na příkladu nemá přihlášení/odhlášení -  dnnt mód není aktivní)

**Comment by JanMeritus** [comment]
@pavelkocourek nase riesenie virtualov nepredpoklada pre prvy stupen spristupnenia na mieste samotnom ziadneho usera. DNNT channel je len podla IP.

**Comment by pavel-stastny** [comment]
Jenom poddotek. A nemas v pravech nastaveny standardni IP filter, ktery ti to povoli a vlastne predbehne to DNNT?  Alespon tak to na me pusobi.    (Muzes overit tak, ze se v API podivas na priznak `"providedByDnnt":true`)

**Comment by pavelkocourek** [comment]
To tak bude ... má vědět koncový uživatel, u přístupného dokumentu, že se jedná "dnnt"?

**Comment by honza-rychtar** [comment]
> @pavelkocourek nase riesenie virtualov nepredpoklada pre prvy stupen spristupnenia na mieste samotnom ziadneho usera. DNNT channel je len podla IP.

Nedomluvili jsme se náhodou na poslední schůzce k DNNT, že v DNNT režimu bude **vždy** muset být přihlášen uživatel s oprávněním k DNNT?. Filtr na IP adresu může být jen dodatečné kritériem.

V případě terminálů v NK se pak stačí přihlásit pod knihovním účtem určenému k DNNT. Knihovník provede přihlášení na všech terminálech. Pokud by někdo nechtěl přihlašování dělat, tak dá k terminálu lísteček s přihlašovacími údaji, ať se přihlásí uživatelé sami.

Přistupovat k chráněnému obsahu bez přihlašování nedává moc smysl a IP adresa není uživatelský účet. 

Na terminálech v NK to nemá smysl testovat, tam máte přístupné vše a toto kritérium zpřístupnění (správně) přebije DNNT kritérium, které se vůbec neuplatňuje a ani se tedy nezobrazují žádné vizuální indikace, že se jedná o DNNT.

**Comment by JanMeritus** [comment]
V rieseni prveho kroku, je pristup rieseny z autorizovanej proxy ku ktorej sa dostanu len specificke obrazy. Podla mna nema zmysel davat

> "pokud by někdo nechtěl přihlašování dělat, tak dá k terminálu lísteček s přihlašovacími údaji, ať se přihlásí uživatelé sami."

Pre terminaly a rozne koncove body nemame jedno pravidlo, kazdy ma ine prava. Na terminaloch s obmedzenymi pravami a spravnym nastavenim sa to samozrejme testovat da a funguje to podla ocakavani (povolene DNNT ale iny neverejny obsah zakazany).

K topicu: Myslim ze ako pre prihlaseneho, tak i neprihlaseneho uzivatale, je informacia, ze sa jedna o dielo DNNT dolezita.

**Comment by pavelkocourek** [comment]
Rozhodněte prosím, jak má vypadat vizuální stránka v klientovi. (Zámeček s písmeny DNNT). A zdali má ve fasetě Dostupnost být hodnota DNNT.

**Comment by pavelkocourek** [comment]
KNAV 16.6.
_**Dostupnost**
pouze veřejné	25435
dnnt                        NNNN
pouze neveřejné	172954
Vše	                        198389
(existuje kombinace Pouze veřejné a dnnt)
+ customizovaná hláška k DNNT

**Comment by JanMeritus** [comment]
Chovanie klienta je nestandardne ceskaexpedice/kramerius#690

**Comment by pavelkocourek** [comment]
16.9.  KNAV - DNNT fáze 2
Zobrazení přihlášeného uživatele bude umístěno pro DNNT dokument do Prohlížečky.

**Comment by JanMeritus** [comment]
Ahoj,

@honza-rychtar hlasim zatial sucasny stav, ktory by este trochu trebalo dotiahnut:

- [ ] Nad periodikami a mono sa v zakladnom nahlade zobrazuje oranzvovy zamok
- [ ] Monografie, pri rozkliknuti sa nad vsetkymy listami v nahlade zobrazuje oranzovy zamok (nie, stale je sedy)
- [ ] Perio: Druhostupnovy nahlad, grid i kalendar zobrazuje u oznaceneho oranzovy zamok (nie, stale je sedy)
- [ ] Perio: pri rozkliknuti sa nad vsetkymy listami v nahlade zobrazuje oranzovy zamok (nie, stale je sedy)
- [ ] Perio: (netestovane, do buducna ale mat pripravene, rozne prava u jedneho titulu)  Druhostupnovy nahlad, grid i kalendar zobrazuje u oznaceneho cisla oranzovy zamok alebo sedy, podla prav

**Comment by honza-rychtar** [comment]
Přidal jsem oranžový zámeček pro DNNT dokumenty u zobrazení ročníků, čísel a příloh periodika mřížkou a u zobrazení ročníků přes roky.
U zobrazení stránek je problém v tom, že info o DNNT se nevrací přes API u seznamu stránek.
Teoreticky můžu dat dotaz do SOLR a pak si stránky vrácené přes API namapovat na výsledky ze SOLR, které informaci o DNNT obsahují. Ale asi to raději přidejme do API.

**Comment by JanMeritus** [comment]
Ahoj, v tomto pripade som za to aby to bolo pridane do API.

**Comment by honza-rychtar** [comment]
Zavírám, dál řešme poslední chybějící tady #343
