### ISSUE TITLE
Zobrazení titulů s duplicitními čísly Volume a Issue

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius-web-client#212]
V knihovně Národního muzea jsem narazil na deník Prager Presse, který vycházel dvakrát denně. Stromová struktura titulu ve starém GUI Krameria tak obsahuje buď duplicitní volume pro ranní a odpolední vydání (např. 1921) nebo issues (např. 1922 -  http://kramerius.nm.cz/search/handle/uuid:646736bb-9fc6-4ef9-bf9f-8b4d088a41b2 ). 
To je samo o sobě dost matoucí, ale ve web-clientu se k duplicitním issues asi nedá vůbec dostat. 
V seznamu volumes jsou duplicitní hodnoty spojeny do jedné položky (myslím, že v předchozí verzi Digitální knihovny byly ještě zobrazovány duplicitně). Po jejím rozkliknutí se pak aspoň dá na zdvojený volume dostat kliknutím na navigační šipky vedle čísla volume. O úroveň níž v kalendářovém zobrazení Issues ale už navigační šipky nejsou a na zdvojené číslo issue už se nedá dostat.

**Comment by honza-rychtar** [comment]
U zobrazení mřížkou se zobrazí všechny ročníky.
<img width="1085" alt="Screenshot 2019-04-03 11 34 10" src="https://user-images.githubusercontent.com/1178142/55468876-9ae3f780-5604-11e9-98ed-5badc84affdc.png">

Zobrazení přes časovou osu roků je dostupné jen když mají všechny ročníky zadaný rok ve formátu yyyy, aby se dala osa jednoznačně zobrazit. Tady bychom mohli přidat ještě jednu podmínku - roky musí být unikátní. Pak by se tyto ročníky rovnou zobrazily v mřížce.

**Comment by vlahoda** [comment]
Dík za vysvětlení. Ta podmínka s unikátností je asi dobrý nápad, bylo by to intuitivnější. A myslím, že by to mohlo stejně fungovat i o úroveň níž pro issues.
