### ISSUE TITLE
Nový uživatelský klient - nevyhledání dalších knih přes proklik autora

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius-web-client#214]
Dobry den,
pokud si vyhledam v nasem Krameriovi (MSVK) v novem klientu pres Digitalni knihovnu knihu a prokliknutim pres autora se chci dostat k dalsim kniham, tak nedostanu zadny vysledek.

Napr. http://www.digitalniknihovna.cz/svkos/view/uuid:d515452e-b7b0-4876-b88f-d01b1809bb98?page=uuid:583b5352-44ab-11e9-995a-001b63bd97ba

Pres nabidku Prochazet se mi povede dohledat k danemu autorovi dalsi knihy.

Dekuji

Ales Drahotussky

**Comment by honza-rychtar** [comment]
Data v panelu s metadaty se berou z MODS
http://camea2.svkos.cz/search/api/v5.0/item/uuid:d515452e-b7b0-4876-b88f-d01b1809bb98/streams/BIBLIO_MODS
_name->namePart_: **Vyhlídal, Jan**
Pro vyhledávání (s filtrem autora) se data berou ze SOLRu, kam se autor dostane z DC
http://camea2.svkos.cz/search/api/v5.0/item/uuid:d515452e-b7b0-4876-b88f-d01b1809bb98/streams/DC
_creator_: **Vyhlídal, Jan, 1861-1937**
Filtr na autora se pak aplikuje na přesnou shodu a proto to nic nenajde.

Jak se vám dostalo do datum do pole pro autora v DC? Nemá to tam co dělat.
Proklikal jsem si několik vaších dokumentů a máte to takto všude.

Tenhle problém se brzo vyřeší přepsáním indexeru. Nový indexer už nebude DC vůbec používat a vše bude brát z MODS. 
Kramerius pak bude DC na vstupu ignorovat a bude jej jen generovat na výstupu z MODS. Tohle mimojiné odstraní problémy s nekonzistencí MODS a DC.

**Comment by Drahotussky** [comment]
Predpokladam,ze se nam to tam dostane atumaticky pri praci v editoru.  Rucne do DC nic nevkladame.

Dekuji moc za informaci

**Comment by Drahotussky** [comment]
Ohledne tohoto problemu jsem narazil jeste na jeden problem. 
Pokud si dam napr. vyhledat knihy jen od Adamus Alois, tak se mi zobrazi knihy, v jejichz zaznamu je autor rozepsan v samostatnych polich pro jmeno a prijmeni s atributy given a family a bez zivotopisnych dat. Nevypisi se mi ale knihy, kde je autor rozepsan v samostatnych polich pro jmeno a prijmeni s atributy given a family a s zivotopisnymi daty, ani knihy,kde je cele autorovo jmeno v jednom poli partName, at uz s zivotopisnymi daty nebo bez nich.
V rozhrani,ktere mame ted u Krameria 5.3.6 se po zadani jmena do vyhledavace vypisi knihy s obema typy zapisu autorova jmena.
Prijde mi, ze se vybere ta forma jmena, ktera je v nejvetsim poctu zaznamu knih.
Bude se dat toto nejak opravit, sjednotit?

**Comment by zabak** [comment]
Obávám se, že tady narážíme ještě na jeden, hlubší problém. V knihovních systémech používáme čísla národních autorit, která ale cestou do Krameria mizí. Přitom jde o jednoznačný identifikátor, přes který by se dalo s autoritami velmi dobře pracovat, aktualizovat je apod. Prvním krokem samozřejmě je zajistit, aby se v nových datech čísla národních autorit zachovávaly (a pro jistotu rovnou upozorňuji, že některé knihovní systémy interně používají jakási interní čísla autorit, ta musejí být během exportu pro digitalizaci nahrazena národními identifikátory).
