### ISSUE TITLE
Výběr stran pro tisk - přepisování první strany

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#215]
Když je hodnota u první strany vyšší než u druhé, tak se po kliknutí mimo pole přepíše na tu původní. Nejdřív se musí přepsat hodnota u poslední strany rozsahu, který chci tisknout, příp. generovat PDF. 

Postup: (Příklad tady: http://knav.kramerius.rychtar.cloud/uuid/uuid:6953fb61-4efb-11e9-960c-005056a2b051)
1. Prohlížím si třeba stranu 4 (aktuálně vybraná), ale pak se posunu trochu níž a chci tisknout až třeba od strany 10, ALE pořád mám aktuálně označenou stranu 4.

2. Takže v okně pro výběr stran je jako první i poslední strana vybrána strana číslo 19 (index strany 4).
![image](https://user-images.githubusercontent.com/21309201/55714694-63ee5700-59f3-11e9-957f-618e5fe1021f.png)

3. Ale já chci tisknout od strany 10, což je strana s indexem 25. Když tedy do políčka pro první stranu napíšu místo čísla 19 číslo 25 a pak kliknu do druhého políčka, kam je potřeba napsat číslo poslední strany, tak se číslo první strany změní na původní, tedy 19. Je prostě potřeba zadat nejdříve číslo poslední strany, aby nebylo číslo první strany nižší. Což je nelogické, ptž většinou chci zadat nejdřív číslo první strany a pak poslední. 

Samozřejmě je to ještě zkomplikované tím, že na náhledech stran je uvedeno číslo strany a okno pro tisk příp. generování PDF po mně chce index strany (viz. tady https://github.com/ceskaexpedice/kramerius-web-client/issues/12), ale to je mimo.

Nejlepší by bylo, kdyby mě to okno nechalo napsat tam cokoliv a radilo až když volbu potvrdím. Nebo jen řekne, že je něco špatně a nebude mi to hned přepisovat. Případně když tam bude napsaný nesmysl, jako třeba vyšší číslo u první stránky, tak se zneaktivní tlačítko pro potvrzení.

Prosím, aby bylo issue označeno jako chyba.

**Comment by honza-rychtar** [comment]
Řešením bude kompletní přepracování dialogu https://github.com/ceskaexpedice/kramerius-web-client/issues/12#issuecomment-480787080

**Comment by honza-rychtar** [comment]
Dávám label **Duplicitní**. Bude řešeno v rámci #12, resp. v nově navrhovaném řešení už k problému z tohoto issue nebude docházet.
