### ISSUE TITLE
Přístup k datům pro právě otevřený dokument 

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#216]
Pro kontrolu dat se knihovníkům a vývojářům hodí rychlý přístup k různým zdrojů, které souvísí s právě otevřeným dokumentem.

V předchozí Digitální knihovně to bylo po přihlášení přes ozubené kolečko v navbaru.
<img width="600" alt="Screenshot 2019-04-08 13 30 33" src="https://user-images.githubusercontent.com/1178142/55721927-f9dead80-5a04-11e9-8a98-8d1ecdce8b69.png">

S @zabak jsme se domluvili, že by se toto ozubené kolečko aktivovalo po navštívení nějaké specifikované stránky v klientovi, na kterou se nikde neodkazuje (musím znat odkaz, abych funkci aktivoval). Navštívením této stránky se zapíše hodnota do lokálního uložistě prohlížeče a v tomto prohlížeči pak bude dál funkce dostupná.

**Comment by pavelkocourek** [comment]
Tohle je na umístění do nového Administračního klienta.

**Comment by zabak** [comment]
Právě že úplně není. Ona tahle stránka je vlastně overlay přes právě otevřenou stránku a zobrazuje kontextově relevantní informace k dané stránce. Spíš je otázka jak bude koncipován nový administrační klient, který pro spoustu operací potřebuje znát dokument se kterým se pracuje. Jeho vyvolání z web klienta bude vhodné (z tohoto hlediska možná i dialog pro výběr stran pro PDF se bude možná v nějaké formě recyklovat pro administraci). Každopádně právě ta pasivní stránka zobrazující důležité informace adminovi může být prvním krokem k vývoji admin klienta - bude to něco hmatatelného, dosaženého s malým úsilím.

**Comment by pavelkocourek** [comment]
tak nějak  ... je to potřeba umistit do klienta a v kontextu ... nicmeně už je funkce pro knihovníka/admina

**Comment by JanMeritus** [comment]
Myslim, ze pokud nezobrazuje nic kritickeho, je to velmi vitana funkce pre kazdeho advanced usera, tj nutne ju netreba schovavat len do admina.

**Comment by honza-rychtar** [comment]
Zobrazení všech metadat celé hierarchie právě otevřeného dokumentu je teď dostupné pro všechny.
