### ISSUE TITLE
Typ dokumentu "Svazek knih"

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#219]
Vícedílné monografie se na úrovni celého titulu hlásí jako typ dokumentu "Svazek knih" (např. http://kramerius5.nkp.cz/periodical/uuid:db421620-2c4f-11e8-8cf8-005056827e52).
Je jistě v pořádku, že takový typ nefiguruje v nabídce typů dokumentů v Procházení a že na něj nelze uplatnit filtry. Méně příjemné už ale je, že se na něj v popisných údajích titulu (pravý sloupec) generuje klikatelný odkaz - ten totiž nikam nevede.
Technicky to sice snad ničemu nepřekáží, ale uživatelsky je to matoucí a nepůsobí to dobře. Nebylo by smysluplné (a možné) s tím prosím něco udělat? Např. to odstranit jako odkaz (nechat to jen jako text) nebo ten odkaz někam rozumně přesměrovat..?

**Comment by honza-rychtar** [comment]
Určitě. Opravíme.

**Comment by honza-rychtar** [comment]
Opraveno
