### ISSUE TITLE
Responzivni chovani aplikace

### ISSUE THREAD

**Issue by pkudela** [ceskaexpedice/kramerius-web-client#22]

**Comment by pkudela** [comment]
U home page dodelano responsivni chovani pro ruzna mobilni zarizeni, na ostatnich pohledech se pracuje, nasazeno na testovaci server -> http://sluzby.incad.cz/kramerius/, u me otestovano na tabletu, telefonu, prosim o otestovani na vasi strane

**Comment by krizovj** [comment]
Zkoušela jsem to zatím jen na mobilu a při přepnutí do angličtiny zůstává český popisek "Hlavní navigace"

**Comment by pkudela** [comment]
Ano, mate pravdu, zapomelo se zde na preklad, opraveno. Ke kontrole az pri nasazeni dalsi verze na testovaci server.

**Comment by krizovj** [comment]
Zkoušeli jsme na dvou mobilech a našli jsme tam dvě věci:

1) Když kliknu na hlavní navigaci a vyberu cokoliv z menu (procházet, sbírky, změna jazyka), tak se stránka změní, ale zůstanu v té navigaci. Spíš bych čekala, že mě to přímo hodí například do sbírek a navigace zaleze zpátky. V případě změny jazyka na stejnou stránku, kde jsem byla předtím, ale v tom jiném jazyce.
2) Po kliknutí na logo "Moravská zemská knihovna" se objeví černé okno s nápovědou "Domovská stránka" a je tam, dokud nekliknu někam jinam (normálně se objeví po najetí myší a když s ní uhnu jinam tak zmizí). Myslím, že by tam ta nápověda pro mobilní zařízení nemusela vůbec být.

**Comment by pkudela** [comment]
Dobry den, je to defaultni chovani sidenavbaru, nicmene v pristi verzi, kterou nasadim s dalsimi zmenami to bude opravene. Co se tyce tooltipu, ten zobrazovat tedy nebudu, jelikoz v mobilni verzi se meni chovani z hover (najeti mysi) na klik.

**Comment by pkudela** [comment]
Nasadil jsem novou verzi na testovaci server. Responsivni je nyni result page, browse a collections page. Stranka s vysledky funguje tak, ze pri rozliseni mensim nez 992px (tablety) se filtry "typ dokumentu" presunou z horniho toolbaru do facetoveho sloupce viz. screenshote 1. Pri rozliseni mensim nez 600px (mobily) - se filtry zabali a jsou dostupne pod ikonou, po kliknuti se rozbali. Podobne funguje stranka browse a collections viz. screenshots. Prosim o otestovani a jen podotykam, ze se jedna o responsivni chovani, ktere nikdy nemuze plne nahradit aplikaci/klienta urcenou pro mobily/tablety. Nyni pokracuji praci na responsivnim chovani periodik (vsechny pohledy) a ctecky, to bude trochu orisek.
-------
![image](https://user-images.githubusercontent.com/16591052/35047021-ff564564-fb98-11e7-83b6-c4d5c44f3b0e.png)
-------
![image](https://user-images.githubusercontent.com/16591052/35047374-04b461e8-fb9a-11e7-9356-dc301f015900.png)
-------
![image](https://user-images.githubusercontent.com/16591052/35047411-1f1a4598-fb9a-11e7-96f6-43ab8cd59f7a.png)

**Comment by pkudela** [comment]
Nasadil jsem novou verzi na testovaci server ->http://sluzby.incad.cz/kramerius Vyjma ctecky by se vsechny stranky mely chovat responsivne. Responsivni chovani ctecky bude dodelano a nasazeno behem pondeli. Prosim o otestovani. Otestovano na mobilu i na tabletu.

**Comment by krizovj** [comment]
Dobrý den, 
zase se mi zobrazují tooltipy u tlačítka "zpět na předchozí stránku" a pak při prohlížení u těch funkcí v levém sloupci (tisk, pdf,...).

**Comment by pkudela** [comment]
Dobry den, ohledne tooltipu, defaultne funguji u mobilnich zarizeni jinak, oproti dekstopu. U desktopu najedete mysi na odkaz/button a tooltip se zobrazi jen po dobu, nez mysi zase z odkazu/buttonu odejtete. U mobilnich zarizeni, jelikoz neni k dispozici mys, se tooltip zobrazi po kliknuti na odkaz/button a zmizi az tehdy, pokud kliknete na jine misto mimo odkaz/button, nebo na jiny odkaz/button. Toto chovani je dle meho spravne, jelikoz uzivatel ma tak napovedu k cemu konkretni button slouzi. Ted jsem to testoval na malem mobilu u periodika, kde si muzu zobrazit pomoci buttonu metadata a prepnout do jineho view. Jinak co se tyce prohlizecky, tak jeste neni hotova, bude behem dneska, dam vedet.

**Comment by pkudela** [comment]
Dobry den,
na testovacim serveru je nova verze. Nakonec jsme pro mobily skryly globalne tooltipy a je tam hodne zmen predevsim pro mobily - zobrazovani vsech moznych prvku - metadata, filtry, ruzne pohledy v periodicich, je hotovy prehravac + ctecka atd. Nyni to na mobilu pusobi jako mobilni aplikace, prosim otestujte na mobilu. Nize par screenshotu:
-------
![image](https://user-images.githubusercontent.com/16591052/35349383-0bcb38c0-013b-11e8-80a9-96096257386a.png)

![image](https://user-images.githubusercontent.com/16591052/35349401-1b8c1220-013b-11e8-8892-3d8d2e3a5246.png)

![image](https://user-images.githubusercontent.com/16591052/35349428-30305da8-013b-11e8-8f84-a61e7a0d54cc.png)

![image](https://user-images.githubusercontent.com/16591052/35349455-42275e3a-013b-11e8-9783-0d4179d44ba8.png)

![image](https://user-images.githubusercontent.com/16591052/35349482-558c3400-013b-11e8-8e52-b8dd446d3060.png)

![image](https://user-images.githubusercontent.com/16591052/35349497-64ca6d7e-013b-11e8-8426-3abd5fcddab0.png)

![image](https://user-images.githubusercontent.com/16591052/35349550-89a7b7aa-013b-11e8-91b9-09c321666d8b.png)

![image](https://user-images.githubusercontent.com/16591052/35349578-9e2b057e-013b-11e8-8ad0-c55406b048a0.png)

![image](https://user-images.githubusercontent.com/16591052/35349599-af6f8ac6-013b-11e8-9caf-cf2d68402bee.png)

![image](https://user-images.githubusercontent.com/16591052/35349633-c98cad6c-013b-11e8-83a8-0d117fe9ac2b.png)

**Comment by pkudela** [comment]
Dobry den, jen pro info, abyste to sem nepsali jsme objevili 2 bugy, ktere budeme resit.
----
1. Na iPhone se nezobrazuje u ctecky ikona pro fullscreen.  
2. Na iPhone se u prehravace automaticky nespusti prehravani audia ani nejde spustit, u jineho testovaneho mobilu samsung se audio take nespusti, ale po kliknuti na tlacitko play se audio na rozdlil od iPhone prehravat zacne
----

**Comment by pkudela** [comment]
Dobry den, nasadil jsem dalsi verzi. Strucne zmeny:

------
1. Ctecka -> navigace – prizpusobuju v rozliseni mensim nez 600px sirku nahledu po 100px, ted uz to myslim vypada dobre viz. screenshot nize
2. Navbar -> nyni pri rozliseni mensim nez 600px schovavam sipku “zpet” a pri rozliseni mensim nez 400px schovam search bar a je dostupny jen pod ikonou “search”. Myslim, ze pro mensi mobily to bylo potreba uz tam nebylo pro pouzitelny search bar dost mista viz. screenhost nize
------
![image](https://user-images.githubusercontent.com/16591052/35403969-b02fa826-0201-11e8-867b-681466556b05.png)
![image](https://user-images.githubusercontent.com/16591052/35403994-c7a2e3ce-0201-11e8-8bfc-9aa0850e0973.png)
![image](https://user-images.githubusercontent.com/16591052/35404018-d8315dba-0201-11e8-808a-2e07970bd0d2.png)

**Comment by krizovj** [comment]
Na mobilu je možné obrázkem otáčet i jinak než o 90 stupňů (jako je to v klasickém rozhraní). Ale to je dost nepohodlné, ptž když se zrovna netrefím a pootočím si obraz jen o kus (viz obrázek), tak potom nejde ten obrázek otočit do původní polohy. Šlo by tam dát spíš tu funkci otočení tak, jak funguje v klasickém rozhraní? Tedy otočení o 90 stupňů?


![otoceni](https://user-images.githubusercontent.com/21309201/35627000-d9ce8dec-0697-11e8-9470-aeec6dfc56b2.png)

**Comment by pkudela** [comment]
Otacet s obrazkem by jit nemelo, pro mobilni zarizeni, myslim tim ted telefony, to nema vyznam, proto jsou veskere navigacni prvky ctecky pro mobilni zarizeni skryte, dostupne je pouze listovani a fullscreen. To ze se da s obrazkem otacet i bez tlacitka tak nevim, jestli je to vlastnost telefonu, nebo jestli to lze pro mobilni zarizeni na nasi strane zakazat. Proverim to.

**Comment by krizovj** [comment]
Jestli je to mobilem, tak to asi budou dělat všechny, nemám nějakou speciální značku. Zkoušela jsem to ve vestavěném prohlížeči, pak v Chromu a pak v Opeře a obrázkem jde otáčet ve všech třech. Nemám až tak problém s tím, že jde obrázkem otočit, ale spíš, že když ho chci otočit zase zpátky do té výchozí polohy (aby šel v pohodě číst a člověk nemusel mít hlavu nakřivo), tak to jde strašně špatně a vždycky to zůstane trochu pootočené. 
Jinak v Opeře mi to celé funguje strašně pomalu, hrozně dlouho se všechno načítá, ostatní dva byly celkem v pohodě.

**Comment by honza-rychtar** [comment]
Na dotykovych zarizenich je mozne k otaceni pouzivat gesta. Otaceni gestem vypnu. 
Muzeme pridat tlacitka pro otoceni o 90 stupnu a pro vycentrovani (jako na webu).

@krizovj Jaky mate telefon? Vyrobce, model, OS, verze OS
Podle recenzi na Google Play doslo u posledniho updatu Opery k vyraznemu zpomaleni, takze to nejspis vubec nesouvisi s klientem.

**Comment by pkudela** [comment]
Pokud se vypne otaceni gestem, tak bych uz otaceni o 90 stupnu neresil, dle meho nazoru je to na mobilu zbytecne, to jsme preci uz probirali, ze pro mobily bohate staci sipky + fullscreen pokud to zarizeni podporuje.

**Comment by honza-rychtar** [comment]
@pkudela No hlavni argument pro schovani tech tlacitek na telefonu bylo to, ze se vse da delat gesty. Pokud ale gesto rotace vypneme, tak tlacitka zase davaji smysl, resp. bez gesta a tlacitka nebude rotace vubec mozna. Pri fyzickem otoceni telefoni o 90 stupnu dojde ke zmene orientace obrazovky, takze takto taky rotace nebude fungovat. 

Na druhou stranu potreba rotace je dost vzacna (chybny sken, poznamky na okraji stranky, ..), takze bychom na telefonu mohli rotaci uplne vypustit. 
Porad to muze uzivatel resit pres systemove zamknuti orientace obrazovky a fyzickeho otoceni zarizeni - stejnym zpusobem se resi otaceni fotek v galerii.

**Comment by pkudela** [comment]
Ano, s tim souhlasim.

**Comment by krizovj** [comment]
Podle mě by se rotace mohla u telefonu úplně vypnout.

**Comment by honza-rychtar** [comment]
Ok, #32
