### ISSUE TITLE
Označení periodik s částečně zveřejněnými ročníky ve vyhledávání

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#222]
Periodika, která mají uuid titulové uuid označené jako private, ale mají část příslušných ročníků jako public, se ve výsledcích vyhledávání zobrazují jako pouze neveřejná a při výsledcích vyhledávání akorát matou čtenáře. Navíc je lze najít ve vyhledávání pouze jako neveřejná, v seznamu "pouze veřejné" je to nezobrazí, ačkoli se jedná např. o periodika, která mají většinu svého obsahu veřejná.

Viz např.:

![image](https://user-images.githubusercontent.com/43028501/55960080-598ac200-5c6c-11e9-9439-089294823add.png)

![image](https://user-images.githubusercontent.com/43028501/55960110-690a0b00-5c6c-11e9-96d0-4f957cdf5a00.png)

![image](https://user-images.githubusercontent.com/43028501/55960154-7e7f3500-5c6c-11e9-999a-0a6028e67dee.png)

Bylo by možné, aby klient nějak označil, že se jedná o periodikum s částečně veřejným i neveřejným obsahem, tak jak se to řešilo např. u K5, viz: https://github.com/ceskaexpedice/kramerius/issues/259, https://github.com/ceskaexpedice/kramerius/issues/355 a https://github.com/ceskaexpedice/kramerius/issues/376? 

Případně šlo by, aby se rodič, který bude mít pod sebou byť jen jednoho potomka, automaticky přepisoval také na public, aby se toto nedělo? Lze to samozřejmě řešit ručně, ale není to efektivní a chyby se hůř dohledávají.

**Comment by honza-rychtar** [comment]
> Periodika, která mají uuid titulové uuid označené jako private, ale mají část příslušných ročníků jako public, se ve výsledcích vyhledávání zobrazují jako pouze neveřejná a při výsledcích vyhledávání akorát matou čtenáře. Navíc je lze najít ve vyhledávání pouze jako neveřejná, v seznamu "pouze veřejné" je to nezobrazí, ačkoli se jedná např. o periodika, která mají většinu svého obsahu veřejná.

Pokud má periodikum alespoň jedno číslo veřejné, tak by mělo být celé periodikum označeno jako veřejné. Tohle se netýká klienta. Dokumenty jsou buď _public_ nebo _private_, nic mezitím.

> Případně šlo by, aby se rodič, který bude mít pod sebou byť jen jednoho potomka, automaticky přepisoval také na public, aby se toto nedělo? Lze to samozřejmě řešit ručně, ale není to efektivní a chyby se hůř dohledávají.

Takto obecně to dělat nemůžeme. Neveřejné monografie mívají veřejnou titulní stranu a obsah a přesto chceme, aby celá monografie byla neveřejná.

Ale u periodika by se to automatizovat mohlo. 
Případně udělat nějaký proces, který to nastaví sám.
Indexovaly by se jen změněné periodika a ročníky nerekurzivně, takže by to bylo rychlé.
Přidala by se alespoň následující 2 pravidla:

1. Pro každý ročník se koukneme na všechna jeho čísla a pokud jsou všechna neveřejná, tak se nastaví ročník na _private_. Jinak se nastaví na _public_. (Jen pokud došlo ke změně).
2. Pro každé periodikum se koukneme na všechny jeho ročníky a pokud jsou všechny neveřejné, tak se nastaví periodikum na _private_. Jinak se nastaví na _public_. (Jen pokud došlo ke změně).

Každopádně to nesouvisí s klientem a je otázka, jestli by toto chování všichni v Krameriovi chtěli.

**Comment by zabak** [comment]
Nemělo by teda smysl pro tyhle případy zavést opravdu obojetný příznak na základě kterého by se zobrazila jiná ikona než zámek (třeba půl zámku)?

**Comment by annie-cz** [comment]
Ano, to by podle mě bohatě stačilo.

**Comment by honza-rychtar** [comment]
@zabak A čemu to pomůže? Jakože vážně - z pohledu uživatele - jak se zachováš, když uvidíš půl zámku? 
Pokud to neotevřeš, tak je to špatně, protože je část veřejná a zámek tě odradil.
Pokud to otevřeš, tak je to špatne, protože tam byl půl zámek zbytečně. 
Na vstupních dveřích od knihovny taky nemáte půl zámku, protože uvnitř existují dveře, které jsou zamčené.

Kramerius pracuje s příznaky _public_ a _private_. Nic mezi tím není a všechny aplikace/klienti s tím takto dál nakládají - jako s true/false hodnotou.
Změna by znamenala přepracovat kompet všechny části systému a přeindexovat komplet všechna data.
Uživatelům by to přineslo jen složitější systém vizuální indikace dostupnosti. K tomu komplikace u filtru. Místo výlučného výběru _Vše_, _Pouze veřejné_, _Pouze neveřejné_ by se daly kombinovat _veřejné_, _částečně veřejné_, _neveřejne_ - což je 7 kombinací (s vynecháním prázdného výběru).

**Comment by pavluska** [comment]
Rada pro vsechny - opravte si to v datech! Pokud je na periodiku zamek, znamena to, ze v metadatech je uvedeno "private", opravte si to rucne na "public". Tech periodik zas neni tolik a lehce vyfiltrujes ty, kterych se to tyka. Obojetné znaky jsou naprd. Zmate to uzivatele a zanesete si do digitalni knihovny dalsi balast.

**Comment by pavluska** [comment]
Mit data znamena nest za ne odpovednost, ne to nechavat vsechno na programatorech. V tomto pripade je opravdu jednodussi a zaroven spravne opravit si to u sebe.

**Comment by zabak** [comment]
@honza-rychtar Máš pravdu, tohle bude lepší vyřešit v datech a periodicky hlídat.

**Comment by annie-cz** [comment]
Prima, tak asi můžeme zavřít, což :)?
