### ISSUE TITLE
Doplnění tečky u řadových číslovek

### ISSUE THREAD

**Issue by BrozekAles** [ceskaexpedice/kramerius-web-client#223]
Při  prohlížení vyhledaného dokumentu nebo při hledání dokumentu se po levé straně objevuje výraz "X z Y stránek", např. v nápovědě https://www.mzk.cz/sluzby/navody/digitalni-knihovna-mzk
u Masarykovy knihy Světová revoluce "1 z 670 stránek", resp. v té části nápovědy k vygenerování pdf je výraz "2 z 670 stránek", což je matoucí, protože X  je řadová číslovka, tedy má být "1. z 670 stránek", resp. "2. z 670 stránek"

**Comment by honza-rychtar** [comment]
No ono je to první číslo editovatelné. Zobrazit tečku přímo do vstupního pole by bylo ještě víc matoucí. A tečka za vstupním polem by byla zase moc daleko od čísla. Nebo by se dal zarovnat obsah vstupního pole doprava, ale to by zase nevypadalo pěkně.

**Comment by BrozekAles** [comment]
Zrovna včera při školení v Národním archivu jsem nechal posluchače hádat, co ten výraz "X z Y stránek" má znamenat, a nikoho nenapadlo správné řešení. Takže srozumitelnost by měla mít prioritu před líbivostí. Časem asi se vysvětlení výrazu "X z Y stránek" dostane do nápovědy, což bude správný krok, ale nápovědu každý nečte...

**Comment by zabak** [comment]
@honza-rychtar Já do teď netušil, že se to číslo dá přepsat (pravda, nikdy jsem vůbec nevnímal, že tam ten řádek s čísly vůbec je a proč tam je). Tak jsem ho zkusil přepsat a pak kliknout na nějakou z těch ikon (tisk apod.). No a číslo zůstalo přepsané, ale i když jsem z toho okénka odešel, tak akce (tisk apod.) se vykonala ještě k tomu původnímu číslu, které už ale bylo přepsané. Tj. je tam drobný bug, že pokud do toho okénka něco napíšeš a pak ho opustíš, aníž dáš enter, tak se změna neaplikuje, ale zároveň se to číslo ani nezmění zpátky. 

Myslím, že by to ale chtělo celé vymyslet líp. Jestli si dobře pamatuju, tak to číslo je editovatelné hlavně kvůli možnosti skoků v rámci dozsáhlejších dokumentů. Nemělo by smysl to upravit aby to vypadalo víc jako navigační lišta? 

![image](https://user-images.githubusercontent.com/811537/56085416-15054f00-5e43-11e9-8c63-4d6f08ef5d35.png)

**Comment by BrozekAles** [comment]
No ono by bylo také řešení, kdyby se ukazoval text Stránka 15 z670, ale v porovnání s jinými issue je to prkotinové issue :-)

**Comment by honza-rychtar** [comment]
@BrozekAles udělali jsme to podle toho Vašeho posledního návrhu.
<img width="300" alt="Snímek obrazovky 2023-04-28 v 9 14 43" src="https://user-images.githubusercontent.com/1178142/235080280-bbfc820f-de9c-47d3-b314-d4992ebd8f86.png">

Dostupné ve verzi 2.4.7
