### ISSUE TITLE
Klikatelnost třetího atd. autora

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#224]
Pokud správně rozumím, tak v popisných údajích (panel vpravo) se zobrazují maximálně dva autoři titulu; když má titul autorů víc, je nutno si pro jejich úplný výpis rozkliknout zvláštní okénko (šedou šipku pod jmény).
Tam už ale jména nejsou klikatelná - takže u autorů, kteří "se nevešli" na ten základní panel, chybí možnost si kliknutím zobrazit výpis všech jejich prací. Např. http://kramerius5.nkp.cz/view/uuid:25b9b920-aa46-11e6-840e-005056827e52 - Havránek a Paclík ano, Myška ne.
Není to škoda? Nebylo by vhodnější (a možné) mít ta jména např. klikatelná i v tom vyskakovacím okénku?

**Comment by honza-rychtar** [comment]
Přidáme prokliky z dialogu.

**Comment by honza-rychtar** [comment]
Přidán proklik z dialogu.
