### ISSUE TITLE
Smazat odkaz na soc. síť Google+

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#225]
Prosím o smazání možnosti linkování na již zrušenou soc. síť Google Plus.

![image](https://user-images.githubusercontent.com/43028501/56806286-bd47ea00-682b-11e9-99f8-6d5ae9081fbb.png)

**Comment by honza-rychtar** [comment]
Už je odstraněno. Bude v dnešním buildu.
