### ISSUE TITLE
vylepšení linkování náhledů odkazů na (nejen) soc. sítě

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#226]
Prosím o vylepšení linkování odkazů z nového klienta na soc. sítě a další místa, kde se po odeslání odkazu zobrazují náhledy. Ve starší verzi Digitální knihovny se takto v náhledu zobrazovala adresa digitalniknihovna.cz, název titulu a reprezentativní obrázek. Dříve to býval Komenský. Nyní se zobrazuje pouze název stránky a heslo "Kramerius". Níže náhledy z FB a Skypu.

![image](https://user-images.githubusercontent.com/43028501/56810194-f6855780-6835-11e9-83de-c14013563ac0.png)
![image](https://user-images.githubusercontent.com/43028501/56810233-1157cc00-6836-11e9-8157-a965d0a0df13.png)

Je to sice drobnost, ale užitečná drobnost, která hodně zvyšuje důvěryhodnost a vylepšuje promo projektu :) Dříve se zobrazoval defaultně Komenský, nyní bych skoro navrhovala, aby se zobrazoval vždy náhled titulního listu nebo jiné zadané reprezentativní strany dokumentu.

**Comment by annie-cz** [comment]
Ahoj, jak to prosím vypadá? Počítá se s tím v nejbližší době?

**Comment by honza-rychtar** [comment]
Na www.digitalniknihovna.cz už to běží. Tohle nemůže být součástí klienta. Jde o nakonfigurování webserveru.
