### ISSUE TITLE
Hláška u neveřejného PDF dokumentu

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#227]

**Comment by krizovj** [comment]
Jak to prosím vypadá?

**Comment by krizovj** [comment]
Měl by tam být stejný text, jako u skenů. Pro anglickou verzi by tam měl být text v angličtině.

**Comment by honza-rychtar** [comment]
Hotovo.
http://www.digitalniknihovna.cz/knav/view/uuid:fa0cbc89-6c94-4762-9489-31bd8c043a6f?article=uuid:af534d7e-763a-49d7-a8c5-5cda862a534c

**Comment by tumovam** [comment]
Dobrý den, 
děkujeme za přidání hlášky k neveřejným PDF dokumentům. Mám ale dotaz... hyperlink "Autorský zákon" (v AJ verzi "The Copyright Law") vede sem: http://wwwold.nkp.cz/o_knihovnach/AutZak/Index.htm --> **Stránka nenalezena** . Na stránkách NKP jsem už Autorský zákon nenašla. Nabízí se dvě možnosti - 1. zrušit prolink, nebo 2. odkazovat např. na: https://www.zakonyprolidi.cz/cs/2000-121. 
Je možné, abychom si link v KNAV upravili sami. Dá se hláška měnit, a kde případně? 
Děkuji, M.

**Comment by honza-rychtar** [comment]
@tumovam Ten text je součástí konfigurace Krameria https://github.com/ceskaexpedice/kramerius/wiki/Instalace#konfigurace, ne klienta.
