### ISSUE TITLE
Škálování obrázků ve verzi 1.2.7

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius-web-client#228]
Při zmenšení okna (aby došlo k přepnutí obrázku do celoobrazovkového režimu) dojde k přeškálování obrázku tak, aby zaplnil celou plochu displeje. Výsledkem je něco takového: 

![Screenshot from 2019-04-30 08-55-55](https://user-images.githubusercontent.com/9445927/56944994-c84d9380-6b25-11e9-9cf5-754314826659.png)

Při zpětném roztažení to pak dopadne ještě hůř:

![Screenshot from 2019-04-30 08-56-48](https://user-images.githubusercontent.com/9445927/56945039-e74c2580-6b25-11e9-997b-6b9525453807.png)

**Comment by zabak** [comment]
Předpokkládám, že jde o problém totožný s #44 ale nenapadlo mě že se projevuje i takto.

**Comment by honza-rychtar** [comment]
Vyřešeno novou prohlížečkou.
