### ISSUE TITLE
Chyba 403 při tisku neveřejného dokumentu

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius-web-client#229]
Příprava k tisku v současnosti umožní u neveřejných děl vybrat rozsah stran a zadat požadavek - končí chybovou hláškou z krameria (čistá 403, která je pro uživatele nicneříkající). Funkce by se měla chovat jako generování pdf, které uživateli ohlásí, že daná funkce není u neveřejných děl k dispozici.

**Comment by honza-rychtar** [comment]
Generování PDF není u neveřejných děl k dispozici za všech okolností (i v budově knihovny), takže klient může funkci takto zakázat.
Příprava k tisku je za určitých okolností u neveřejných děl povolena (např. v budově knihovny), takže se to nedá řešit stejně jako u generování PDF.
Nejlepší by bylo nastylovat ten localPrint endpoint v Krameriovi.

**Comment by zabak** [comment]
Duplicitní s #108 - zavírám
