### ISSUE TITLE
Konfigurovatelnost povolené funkcionality klienta (generování pdf)

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius-web-client#230]
Navrhujeme rozšíření, které by umožňovalo konfigurovat, které funkcionality mají být k dispozici. V případě neumožnění by mělo být možné specifikovat hlášku, proč tomu tak je. Konkrétně nám jde o funkci generovat PDF.

Motivací je chráněný režim, který má uživatelům umožnit, aby si zobrazili chráněné dokumenty, ale nesmí jim umožnit tato data stáhnout - momentálně ošetřeno na úrovni OS, který ovšem zablokuje až manipulaci se staženým souborem - "chtěný" stav je, aby ke stažení vůbec nedošlo.

Výsledkem by tedy byla např. neaktivní ikona generování pdf, která by buď v tooltip-u, nebo po kliknutí zobrazila hlášku s odůvodněním.

**Comment by honza-rychtar** [comment]
V konfiguraci je možné nastavit viditelnost pro 9 tlačítek, které nějakým způsobem generují/zobrazují potencionálně chráněný zdroj. 
U všech je možné nastavit jednu z možností  '**always**' / '**never**' / '**public**'
* showMetadata
* showCitation
* showSharing
* showPdfGeneration
* showPrintPreparation
* showPageJpeg
* showPageOcr
* showTextSelection
* showImageCrop
