### ISSUE TITLE
Trvalý odkaz - dotaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#233]
V klientovi není možné vygenerovat odkaz na monografii, číslo periodika a všechno ostatní, kde jsou strany, příp. PDF. 

Když vlezu například do čísla, nebo do nějaké monografie, tak už jsem vlastně na první stránce (příp. na prvním článku), takže při vygenerování trvalého odkazu je to odkaz na tu konkrétní stránku. Ale když chci odkaz na celou monografii, nebo číslo, tak jsem pro to nenašla způsob. 

Šlo by tam tuto funkci nějak přidat? V jádru Krameria to jde.

**Comment by vjirousek** [comment]
Také bych se za funkci přimlouval, vzhledem k tomu že odkazy na stránky nejsou a ještě dlouho převážně nebudou perzistentní, bylo zjednodušené odkazování přes UUID vyšší než stránkové úrovně vhodné.

**Comment by zabak** [comment]
Stačí v URL ponechat první uuid a zbytek url počínaje otazníkem odmazat. Ale tohle issue upřesním: je nekonzistentní chování u citace versus odkazu sdílet. Osobně bych to sloučil do jednoho tlačítka "sdílet", které zobrazí citaci a pod tím link a sdílecí ikony. Hlavně ale musí i u okna "sdílet" být obdobné menu jako je u citace - tedy výběr toho jakou úroveň dokumentu cituji. A samozřejmě jak u citace, tak u sdílecího odkazu se musí doopravdy měnit uuid v tom linku. Teď se sice u citace mění textová část, ale uuid zůstává uuid stránky, i když jsem zvolil citaci periodika. Minimálně to poslední je bug.

**Comment by krizovj** [comment]
Ano, chybu jsem psala do issue k citacím (u kterých by ještě mělo být asi info o tom, podle jaké normy je ta citace složená)
https://github.com/ceskaexpedice/kramerius-web-client/issues/36

**Comment by honza-rychtar** [comment]
Generování odkazů u citace už je opraveno.
U sdílení použijeme stejný způsob výběru úrovně jako u citace, tj.
<img width="527" alt="Screenshot 2019-05-22 11 54 13" src="https://user-images.githubusercontent.com/1178142/58165606-64337080-7c88-11e9-989f-f92cee963558.png">
@zabak Zatím bych to neslučoval do jednoho tlačítka. Místa je tam dost a hlavně nevím, jestli by mě vůbec napadlo klikat na sdílení, pokud bych hledal citaci.

**Comment by honza-rychtar** [comment]
Hotovo.
Dá se vyzkoušet tady 
http://kramerius.rychtar.cloud/mzk/view/uuid:26594830-61e6-11dc-acde-000d606f5dc6?page=uuid:25473bf0-61e6-11dc-914c-000d606f5dc6
