### ISSUE TITLE
Klient zobrazuje jen jednu poznámku

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#234]
Dobrý den,

klient zobrazuje jen jednu poznámku, přestože jich má dokument více.

_Více poznámek v proarcu:_
![proarc](https://user-images.githubusercontent.com/11628774/57778207-d7d2fc00-7723-11e9-8f9d-66b05bf5257e.png)

_Rozkliknutý ročník, kde jsou uvedeny chybějící strany a dole v celkovém fyzickém popisu je jen první poznámka z proarcu:_
![k6-rocnik](https://user-images.githubusercontent.com/11628774/57778304-0cdf4e80-7724-11e9-9e84-f92fce031fab.png)

_Popis k celému periodiku - jen jedna poznámka k fyzickému popisu:_
![k6-cele-periodikum](https://user-images.githubusercontent.com/11628774/57778339-22547880-7724-11e9-9333-03c7ddb7bd6f.png)

**Comment by honza-rychtar** [comment]
Opraveno.

<img width="302" alt="Screenshot 2019-05-21 16 04 48" src="https://user-images.githubusercontent.com/1178142/58102814-31cf3800-7be2-11e9-8e58-1642ae7921ad.png">
