### ISSUE TITLE
Zobrazování měřítka a lokace u map v popisu

### ISSUE THREAD

**Issue by mjtecka** [ceskaexpedice/kramerius-web-client#236]
Zdravím,

mohly by se u map zobrazovat v popisu vpravo měřitko (mods:scale) a lokace (mods:coordinates)? V metadatech bývají...

MJ.

**Comment by honza-rychtar** [comment]
Určitě. Označuju to jako chybu, protože v tmavém klientovi kartografické údaje jsou. Tady mi nějak vypadly.

**Comment by zabak** [comment]
Myslím ale, že není nutné vypisovat souřadnice bounding boxu, jen to měřítko.

**Comment by honza-rychtar** [comment]
Hotovo.
http://kramerius.rychtar.cloud/mzk/uuid/uuid:c99c2915-dfe9-4cf1-8b94-dc215203cdce
