### ISSUE TITLE
ČDK - procházení podle zapojených knihoven (místa uložení)

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#238]
Testování UNNK nad daty z [ČDK#23](https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/23)
Bug? Dotaz?

**Comment by honza-rychtar** [comment]
Okomentoval jsem zde https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/23#issuecomment-499886572
