### ISSUE TITLE
ČDK - informace o původu dokumentu

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#239]
Testování UNNK nad daty z ČDK.... Šlo by zachovat tuto funkci? [ČDK#10](https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/10). Děkuji

**Comment by honza-rychtar** [comment]
Aby byla instituce pod místem uložení v podrobnostech klikatelná, je potřeba mít v konfiguraci klienta povolenou fasetu ** místo uložení** (locations),
např.
`      filters: ['accessibility', 'doctypes', 'authors', 'keywords', 'geonames', 'collections', 'locations', 'languages']
`
Pak bude možné přes místo uložení filtrovat - odkaz pod místem uložení vede do hledání s vybraným filtrem _místo uložení_.

**Comment by tumovam** [comment]
Ano, děkujeme. Nyní se z místa uložení (v podrobnostech) stane aktivní filtr. 
Rádi bychom ale, aby **v ČDK** bylo možné se přes tento odkaz přemístit do konkrétní knihovny. 
Např.: Z modrého klienta http://cdk.lib.cas.cz/client/handle/uuid:d0d0732e-ad88-11e9-a6a2-001b63bd97ba se po kliknutí na 
![obrazek](https://user-images.githubusercontent.com/31240271/63014200-48f28e80-be8e-11e9-81c9-3c34c526fc07.png) dostanu ke konkrétnímu titulu, do Jihočeské věd. knihovny => sem: http://kramerius.cbvk.cz/search/handle/uuid:d0d0250d-ad88-11e9-a6a2-001b63bd97ba.
V nového klientovi (https://cdk.lib.cas.cz/uuid/uuid:d0d0732e-ad88-11e9-a6a2-001b63bd97ba) se po kliknutí na místo uložení stane aktivní filtr, ale do Jihočes. věd. knihovny mě UNNK neodkáže. 
Dá se s tím něco dělat? Jedná se pouze data z ČDK... Díky

**Comment by honza-rychtar** [comment]
Hotovo, např. http://kramerius.rychtar.cloud/cdk/uuid/uuid:da26d1bb-fc24-11e9-b79b-001b63bd97ba
V konfiguraci je potřeba nastavit 
`originLink: true` v definici Krameria v **krameriusList**
