### ISSUE TITLE
Vyhledávání v plném textu konkrétního dokumentu

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#24]
Vyhledávání funguje nějak divně. Pokud zatím není hotové, tak se omlouvám. 
Zkoušela jsem to na knize "Pohřbívati či spalovati mrtvoly?":

1) Vyhledávací dotaz "mrtvoly" (zkoušela jsem bez uvozovek i v uvozovkách a výsledek je stejný): Najde nejen stránky kde se nachází výraz "mrtvoly", ale také ty, kde se nachází jenom výraz "mrtvol". Další problém je, že se zvýrazní jenom ten přesný vyhledávaný výraz "mrtvoly", ale už ne "mrtvol" a to ještě jen na stránce, kde je pouze ten přesný vyhledávaný výraz. Konkrétně: 

- Stránka 5 ve zmíněné knize: je na ní pouze výraz "mrtvoly" a je tedy vyznačený červeným ohraničením
- Stránka 6: je na ní výraz "mrtvoly" a zároveň taky "mrtvol" a červeně označený není ani jeden z nich

2) Vyhledávací dotaz mrtvo: Najde pouze jednu stránku (strana 7), kde takové slovo vůbec není. Je tam jen "mrtvol" a "mrtvolu".

**Comment by honza-rychtar** [comment]
Problem je v solru, resp. v novem lemmatizatoru. Tech problemu je tam hodne, resil jsem to nekolikrat s MZK a prechod na solr 6 se proste nepovedl - prinesl moznost hledani bez diakritiky a sklonovani, ale na druhou stranu prinesl spoustu problemu. 

Napr. slovo "nové" podle solru obsahuji vsechny stranky vsech dokumentu. Takze napr. pro hleddani fraze "nové město", solr vrati stejne vysledky jako pro hledani samostatneho slova "město". To stejne plati pro slovo "nebo".

Dalsi problem je, ze lemmatizator ma vetsi prioritu nez uvozovky a tedy i po vlozeni hledaneho slova do uvozovek jsou ve vysledcich ruzne tvary zadaneho slova.

Tohle dohromady vede k tomu, ze pokud hledate slovo "mrtvoly" (at uz v uvozovkach nebo bez), tak solr vrati i stranky, ktere obsahuji pouze jine tvary slova, napr. "mrtvol".
Zvyrzneni slova na strance se nasledne resi pres ALTO, kde se najdou vsechna hledana slova, vezmou se pozice z ALTO, prepocitaji se a zobrazi se obdelniky pres obrazek. 
Pri zpracovani ALTO uz vsak lemmatizator k dispozici neni, takze se zvyrazni pouze slova v presnem tvaru.

Jeste k

> Stránka 6: je na ní výraz "mrtvoly" a zároveň taky "mrtvol" a červeně označený není ani jeden z nich

Slovo "mrtvoly" zvyrazneny je. Je na strance vpravo dole, nejspis jste ho mela zakryte ovladacimi prvky.

**Comment by pavel-stastny** [comment]
Dobry vecer vespolek,  mam jenom par poznamek. 

>Dalsi problem je, ze lemmatizator ma vetsi prioritu nez uvozovky a tedy i po vlozeni hledaneho slova do
> uvozovek jsou ve vysledcich ruzne tvary zadaneho slova.

Nejde o prioritu. Zalezi  na tom, jake pole se pouzije pri hledani. Pokud lematizovane, pak ve vysledku budou i jine tvary hledaneho slova, pokud nelemtazivane, bude hledat presny vyskyt.

Ve schematu jsou nasledujici pole: 

* text_lemmatized: 
```
https://kramerius.mzk.cz/search/api/v5.0/search?q=text_lemmatized:mrtvola&fl=PID  -  ruzne tvary slova mrtvola
```
* text: 
```
https://kramerius.mzk.cz/search/api/v5.0/search?q=text:mrtvola&fl=PID  -  presny tvar
```
A to plati i v pripade hledani frazi. 


> vezmou se pozice z ALTO, prepocitaji se a zobrazi se obdelniky pres obrazek.
> Pri zpracovani ALTO uz vsak lemmatizator k dispozici neni, takze se zvyrazni pouze slova v presnem
> tvaru.

Doporucuju hledat se zapnutym hit highlightingem a tim ziskat informace od solru co nasel. Uvedu priklad:  

Hledani slova mrtvola na strance uuid:ec81a9c0-39b2-11e4-8c14-5ef3fc9bb22f

```
https://kramerius.mzk.cz/search/api/v5.0/search?q=text_lemmatized:mrtvola%20AND%20PID:%22uuid:ec81a9c0-39b2-11e4-8c14-5ef3fc9bb22f%22&hl=true&hl.fl=text_ocr&fl=PID
```
Nalezene vyskyty na strance : mrtvola, mrtvol a mrtvoly a to uz pak zvyraznit jde. 

> Napr. slovo "nové" podle solru obsahuji vsechny stranky vsech dokumentu. Takze napr. pro hleddani
> fraze "nové město", solr vrati stejne vysledky jako pro hledani samostatneho slova "město". To stejne
>  plati pro slovo "nebo".

Myslim, ze ta veta mela byt naopak. Slovo `nebo` a `nove` neni v zadnem zaznamu.  U `nebo` je to v poradku, je uvedeno v souboru stopwords (stejne jako ostatni spojky a predklozky), nicmene tam vidim i slovo `nove` coz je chyba. (Opravime v pristim buildu).

**Comment by honza-rychtar** [comment]
Pro hledani na strance nepouzivam text ani text_lemmatized, pouzivam primo pole text_ocr. A text_ocr pri upgradu solru se zacalo chovat jako lemmatizovane a neni mozne tohle chovani zrusit ani vlozenim hledaneho slova/fraze do uvozovek.
Pole text a text_lemmatized zahrnuji i klicova slova, nazev, popis - pro hledani na strance dava smysl pouze pole text_ocr. 
Navic pro pouziti text_lemmatized je potreba mit novy solr (a novou konfiguraci), coz ma jen mala cast knihoven, takze takto by klient nefungoval s vetsinou Krameriu vcetne KNAV.

Zahozeni spojek a predlozek neni v poradku, pokud nefunguji uvozovky - pri fulltextovem hledani ocekavam presnnou shodu se zadanou frazi, pokud ji vlozim do uvozovek.

Jinak dalsi priklad toho, co se zmenilo po prechodu na novy solr
https://kramerius.mzk.cz/search/api/v5.0/search?q=text:noviny%20AND%20fedora.model:periodical
- proc tento dotaz nenajde zadne vydledky? Periodik obsahujicich v nazvu slovo "noviny" jsou desitky.

**Comment by krizovj** [comment]
Omlouvám se, s tou stránkou 6 máte pravdu, je to označené a bylo to zakryté těmi ovládacími prvky.

**Comment by pavel-stastny** [comment]
Zdravim, jenom strucne: 

> Pro hledani na strance nepouzivam text ani text_lemmatized, pouzivam primo pole text_ocr. A text_ocr
>  pri upgradu solru se zacalo chovat jako lemmatizovane a neni mozne tohle chovani zrusit ani
> vlozenim hledaneho slova/fraze do uvozovek.
> Pole text a text_lemmatized zahrnuji i klicova slova, nazev, popis - pro hledani na strance dava smysl
> pouze pole text_ocr.
> Navic pro pouziti text_lemmatized je potreba mit novy solr (a novou konfiguraci), coz ma jen mala cast
> knihoven, takze takto by klient nefungoval s vetsinou Krameriu vcetne KNAV.

Prechod na solr 6 byl ovlivnen predevsim aplikaci `/search` a tim, ze (vlastne od zacatku) vyuzivala pro hledani pole text. Vyznacovani a vyhledavni ve strankach pak v kombinaci s hit highlight a polem text_ocr.  Vyuzivany query parser je edismax, kteremu nevadi, kdyz se aplikace pta na neexistujici pole. (Stare verze solru pouze pouziji pouze pole text, novejsi pak i ta lematizovana).   Pri pouziti na starem solru, vse fungovalo jako driv, pri upgradu na novy solr, byly vysledky jenom obohaceny jeste o jine tvary slov. A to byl  i cil. 


> Zahozeni spojek a predlozek neni v poradku, pokud nefunguji uvozovky - pri fulltextovem hledani
>  ocekavam presnnou shodu se zadanou frazi, pokud ji vlozim do uvozovek.

Zahozeni stop slov je standardni praxe pri implementaci podpdory cestiny.  Nicmene nechci se hadat, myslim ze se porad narazi na to same a to je ta unifikace.  At uz se jedna o text_ocr nebo  podporovane operace ( a k tem patri i ta presna shoda, i logicke operatory atd..). Treba u toho presneho matche. Musi existvat nekdo, kdo to preparsuje a vyhodnoti, ze se jedna o presny match a tedy musi pouzit neanalzyovane pole, atd.., atd.. 


> Jinak dalsi priklad toho, co se zmenilo po prechodu na novy solr
> https://kramerius.mzk.cz/search/api/v5.0/search?q=text:noviny%20AND%20fedora.model:periodical
> proc tento dotaz nenajde zadne vydledky? Periodik obsahujicich v nazvu slovo "noviny" jsou desitky.

To byla chyba ve schematu. Opraveno nekdy pred mesicem. Staci nasadit nove schema a reloadnout. (Neni potreba reindexovat data).

**Comment by honza-rychtar** [comment]
Nahradil jsem text_ocr a text, coz to ted docasne resi.
