### ISSUE TITLE
Konfigurace: krameriusList

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#241]
Rádi bychom zapnuli možnost přepínat do Kramériů jiných knihoven. Podle dokumentace se to nastavuje v konfiguraci v property 'krameriusList'. To je celkem jasné, mám ale trochu problém, kde vzít údaje o Kramériích ostatních knihoven. Asi by to šlo nějak vytáhnout z registru Kramériů, ale říkám si, že to už určitě musel někdo dělat. Napadají mě k tomu dvě věci:

* Bylo by možné někde zveřejnit 'krameriusList' se údaji všech knihoven a dát pak odkaz na wiki tady na githubu, aby ho další administrátoři snadno našli?

* Případně ještě lépe - bylo by možné údaje o ostatních Kramériích odněkud stahovat automaticky (třeba z registru Kramériů, když už ho máme)? Takhle totiž když si nějaká další knihovna pořídí Kraméria a já se o tom nedozvím, tak se do něj naši čtenáři nedostanou, protože ho nepřidám do konfigurace. Každou novou digitální knihovnu budou navíc muset přidat do konfigurace všichni administrátoři všech existujících Kramériů...

V tomhle případě by se v konfiguraci nejspíš nastavovalo pouze to, zda má nebo nemá jít přepínat do ostatních Kramériů.

**Comment by honza-rychtar** [comment]
> Bylo by možné někde zveřejnit 'krameriusList' se údaji všech knihoven a dát pak odkaz na wiki tady na githubu, aby ho další administrátoři snadno našli?

Ty konfigurace jsou dostupné v původní podobě.
Pro DK se všema Krameriema:
http://www.digitalniknihovna.cz/assets/shared/globals.js

> Případně ještě lépe - bylo by možné údaje o ostatních Kramériích odněkud stahovat automaticky (třeba z registru Kramériů, když už ho máme)? 

S @zabak jsme generování z Registru řešili. Ale ono se to ještě pořád dost měnilo a využití bylo jen pro DK.

> Každou novou digitální knihovnu budou navíc muset přidat do konfigurace všichni administrátoři všech existujících Kramériů...
> V tomhle případě by se v konfiguraci nejspíš nastavovalo pouze to, zda má nebo nemá jít přepínat do ostatních Kramériů.

Nechápu, proč by měla existovat víc než jedna instalace se stejnou konfigurací zpřístupňující všechny knihovny. Komu to pomůže?
Důvody pro více Krameriů v jednom klientovi jsou 2 
1. **Jeden** univerzální klient (www.digitalniknihovna.cz) 
2. Možnost zapouzdření správy více Krameriů. Například kraj může spravovat více Krameriů z knihoven pod sebou.

Základní myšlenka univerzálního klienta nebyla v tom, že všichni budou zpřístupňovat vše.
Ale že bude jedno místo se vším a všichni budou odkazovat na svou část.
Když je teď www.digitalniknihovna.cz pod správou a ve vlastnictví MZK, tak je to ještě jednodušší.

Ani MZK to nemá pod mzk.cz doménou a podobně jako MZK odkazuje na svá data přes
www.digitalniknihovna.cz/mzk
Tak vy můžete odkazovat na svá data přes
www.digitalniknihovna.cz/mlp

**Comment by zabak** [comment]
Já jen doplním: v MZK počítáme s tím, že zachováme stávající podobu odkazů na www.digitalniknihovna.cz trvale, aby se na ně dalo spolehnout - například i při linkování z wikipedie apod.

**Comment by svetlym** [comment]
> Nechápu, proč by měla existovat víc než jedna instalace se stejnou konfigurací zpřístupňující všechny knihovny.

Souhlasím, že v ideálním světě by měla existovat jen jedna digitální knihovna pro celou ČR (nebo klidně i pro celý svět). V ideálním světě ovšem nežijeme:

* Máme tady vedle sebe weby digitalniknihovna.cz a www.czechdigitallibrary.cz. Z pohledu čtenářů je dost těžké rozlišit, jaký je mezi nimi vlastně rozdíl. Jedno je agregátor, druhé umožňuje přepínat do digitálních knihovnen jednotlivých institucí. Jako čtenář ale chci prostě hledat dostupné digitální tituly a případně si zapnout filtr na konkrétní knihovnu. Čili jaký je vlastně důvod pro přepínání, když existuje ČDK?

V ideálním světě by také uuid jednoznačně identifikovalo digitální dokument, takže bych neměl potřebovat znalost kódu knihovny, ve kterém je uložený. V ČDK by klidně odkaz ve tvaru www.czechdigitallibrary.cz/uuid:8fc60aea-9124-42d9-8846-886429f7569d mohl fungovat, protože je to agregátor. Na adrese digitalniknihovna.cz by nefungoval.

* Dokud neměl web digitalniknihovna.cz institucionální zajištění, nebylo dost dobře možné ho považovat za standardní službu. Teď by to možná šlo, mohu to zkusit navrhnout. Otázka ale je, proč se pak neodkazovat raději do ČDK, která je z pohledu čtenářů lepší (protože umožňuje rovnou vyhledávat ve všem). Musela by se ale samozřejmě opravit provázanost metadat.

V obou případech by to znamenalo opět změnit všechny odkazy z našeho webového katalogu (plus by přestaly fungovat odkazy těm, kdo si je uložili), takže bych to asi spíš dělal tak, že bych tam stávající odkazy přesměrovával. V tom případě je už ale celkem jedno, jestli přesměrování povede na digitalniknihovna.cz/mlp nebo digitalniknihovna.mlp.cz/mlp.

* Výhledově bych rád viděl úzkou provázanost mezi digitální knihovnou a knihovními službami. Jako čtenář prostě hledám nějakou knihu. Když je k dispozici digitálně (nejlépe jako e-kniha), ocením, když ji rovnou uvidím. Když není k dispozici digitálně, chtěl bych vědět, kde si ji mohou půjčit - a ideálně bych si ji chtěl rovnou zarezervovat, nebo třeba objednat zaslání. To vše pokud možno bez toho, abych musel ručně procházet weby všech knihoven v ČR.


Otázka je, co s tím. V mém ideálním světě by existoval jeden institucionálně zajištěný web pro všechny knihovny, který by agregoval metadata (aby se v nich dalo najednou vyhledávat) a vedly by do něj všechny odkazy. Dokážeme se do takového stavu dopracovat? Pokud ano, kdy to bude? Do té doby budeme muset používat nějaké řešení, které se dá nasadit teď hned.

**Comment by indrakm** [comment]
@svetlym spam

**Comment by annie-cz** [comment]
@svetlym Dokud ČDK nedokáže správně sklízet data ze všech knihoven a reagovat na případné změny, tak to čtenáři příliš nepomůže.

**Comment by zabak** [comment]
@indrakm Michale, to co píše @svetlym ale není ireleventní a probrat se to musí a ať už by se o tom diskutovalo kdekoli, tak ti ta diskuse bude chodit :-)

@svetlym ČDK je projekt, který by měl poskytnout index všech Krameriů, se kterým by pak mohla digitalniknihovna.cz pracovat, čímž se vyřeší problém hledání v celém obsahu DK. Ten zbytek to už je spíš úkol pro knihovny.cz, kde to takhle v rámci možností funguje (máme tam jak index ČDK, tak NDK).

**Comment by svetlym** [comment]
@indrakm: Omlouvám se, pokud vás tohle téma nezajímá. Možná by pomohlo vypnout si odběr diskusí k issues, které založil někdo jiný?

Rozhodnutí, jestli provozovat vlastní instanci klienta, odkazovat se na doménu www.digitalniknihovna.cz, nebo ještě někam jinam, je pro nás docela důležité a je také relevantní vzhledem k této issue, protože pokud se rozhodneme používat doménu www.digitalniknihovna.cz nebo pokud zrušíme rozhodnutí dát našim čtenářům možnost přistupovat do Kramériů ostatních knihoven, tak ji bude možné zavřít.

Navíc se to netýká jen nás. Pokud je doména www.digitalniknihovna.cz zamýšlena jako univerzální pro všechny knihovny (jak ji teď používá MZK), tak by bylo dobré to tak prezentovat - mimo jiné i v dokumentaci tady na githubu.

@annie-cz: Souhlasím. Ve stávajícím stavu bychom asi ČDK nabízet čtenářům nemohli. Na druhou stranu funkčnost, kterou nabízí, je pro čtenáře určitě dobrá a pro doménu www.digitalniknihovna.cz by mi rozhodně dávala smysl také. Potom by ovšem už asi opravdu nebyl žádný důvod, proč by to měly být dvě různé domény, když by dělaly to samé.

Souvisí to také s perzistentními odkazy. Pokud se nakonec budeme všichni odkazovat na jednu doménu, kde půjde vyhledávat přes agregovaná metadata, tak nebude třeba, aby byl v persistentních odkazech kód knihovny. Na druhou stranu ignorovat část url je snadné, zato přimyslet si ji, když tam chybí, je obtížné (asi by to znamenalo poslat dotaz na všechny servery v seznamu Kramériů, jestli se k tomu uuid nějaký přihlásí)...

**Comment by zabak** [comment]
@svetlym k tomu odkazování - vzhledem k replikacím (totožné uuid ve více krameriích) a rozdílným přístupovým oprávněním v různých knihovnách není použití samotného uuid bez určení knihovny ani do budoucna spolehlivé a jednoznačné. Museli bychom pracovat s nějakou formou rozcestníku - pokud  se v indexu uuid vyskytuje 1x, tak se zobrazí dokument, jinak se zobrazí stránka s variantami: kniha je dostupná z fondu MKP (volná), NK (jen v budově), MZK (částečně přístupná).

**Comment by honza-rychtar** [comment]
> V obou případech by to znamenalo opět změnit všechny odkazy z našeho webového katalogu (plus by přestaly fungovat odkazy těm, kdo si je uložili), takže bych to asi spíš dělal tak, že bych tam stávající odkazy přesměrovával. V tom případě je už ale celkem jedno, jestli přesměrování povede na digitalniknihovna.cz/mlp nebo digitalniknihovna.mlp.cz/mlp.

@svetlym Není to jedno. Z pohledu uživatele je to velký rozdíl. Z pohledu Googlu a jeho hodnocení stránek pro relevanci vyhledávání je taky dost důležite, jestli je to jedna doména nebo stejný obsah na různých doménach. I z pohledu PR a marketingu je mnohem účinější propagovat jednu službu na jedné doméně - tady je ale potřeba dojít ke kompromisu mezi zaštiťujícím agregátorem (MZK), který to nesmí prezentovat jen ze své strany, a ostatními, kteří musí mít důvěru k agregátorovi a přenechat mu učitá práva - tomu se ale při jakékoli centralizaci nedá vyhnout.

**Comment by svetlym** [comment]
> Z pohledu uživatele je to velký rozdíl. Z pohledu Googlu a jeho hodnocení stránek pro relevanci vyhledávání je taky dost důležite, jestli je to jedna doména nebo stejný obsah na různých doménach. I z pohledu PR a marketingu je mnohem účinější propagovat jednu službu na jedné doméně.

To jsou velmi dobré argumenty. Přednesu je vedoucím, kteří o tom budou rozhodovat.

K tomu ještě jedna poznámka: Při předběžné diskusi padla docela podstatná námitka, že když čtenář napíše do prohlížeče adresu www.digitalniknihovna.cz, tak se mu jako "defaultní" knihovna zobrazí MZK. Je jasné, že nějaká knihovna to být musí a dává smysl, aby to byla instituce, která provoz domény zaštiťuje, ale je to poměrně silný argument proti tomu, abychom tuto doménu používali.

**Comment by svetlym** [comment]
> vzhledem k replikacím (totožné uuid ve více krameriích) a rozdílným přístupovým oprávněním v různých knihovnách není použití samotného uuid bez určení knihovny ani do budoucna spolehlivé a jednoznačné.

To je dobrá poznámka. Řekl bych ale, že to nebude až takový problém. Měl by to být obsahově stejný dokument (jeho kopie), takže z hlediska čtenáře je nejspíš jedno, který z nich se mu zobrazí. Tím, že jich existuje více, ho asi není potřeba zatěžovat.

Neplatilo by to asi pouze v případě, že by čtenář seděl u počítače v nějaké konkrétní knihovně - pak by se samozřejmě kvůli přístupnosti potřeboval dostat na kopii v této knihovně.

**Comment by svetlym** [comment]
> Při předběžné diskusi padla docela podstatná námitka, že když čtenář napíše do prohlížeče adresu www.digitalniknihovna.cz, tak se mu jako "defaultní" knihovna zobrazí MZK.

K této námitce jsem se ještě vrátili a padl návrh, že když čtenář zadá do prohlížeče adresu www.digitalniknihovna.cz, tedy bez kódu konkrétní knihovny, tak by se mu nezobrazil obsah konkrétního Kraméria, ale pouze seznam pro výběr knihovny - aby bylo zřejmé, že jde o soubor více digitálních knihoven a je třeba si vybrat, ve které budu vyhledávat a nemohlo tedy dojít k omylu, že si myslím, že hledám v nějaké knihovně a jsem přitom v jiné, nebo že jsem chtěl do konkrétní knihovny a přitom vidím, že jsem v nějaké jiné, takže usoudím, že mám asi špatnou adresu.

Po této změně bychom za Městskou knihovnu v Praze byli pro přechod na doménu www.digitalniknihovna.cz/mlp. Technicky to ale budeme moci realizovat až na podzim, protože do té doby nám IT oddělení plně zaměstnává nasazování RFID.

Pokud tedy někdo nemáte další komentáře, prosím o odložení této issue. Připomeneme se na podzim.

**Comment by indrakm** [comment]
@svetlym ja myslim, ze nejlepsi bude, kdyz si tam strcite dspace!

**Comment by svetlym** [comment]
@indrakm: Normálně bych debatu vedenou tímto stylem už dávno opustil. Bohužel je tohle ale moje práce a jde o úkol, který mi zadali moji nadřízení a musím ho splnit. Takže pokud nenavrhnete vhodnější komunikační kanál, který poslouží stejnému účelu, obávám se, že vašim námitkám nemohu vyhovět.

**Comment by zabak** [comment]
@svetlym v tomhle issue by se měl vyřešit technický problém s konfigurací, ten už ale v té diskuzi zapadl. Takže navrhuji tady zavřít a pokud bude nutné, otevřít na to nové issue. Diskusi na toto téma by bylo vhodné přenést na platformu vývojového týmu, tj. do konference. Až z toho něco vzejde, co bude zadáním na vývoj, tak z toho teprve udělat nové issue.
