### ISSUE TITLE
Doplnění dokumentace - obrázky k virtuálním sbírkám

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#243]
V dokumentaci k nasazení klienta jsem se dočetl:

f. richCollections (true|false) Vlastní stránka pro seznam sbírek (vyžaduje přidělení obrázků a popisů ke sbírkám).

Není mi z toho jasné, jak se obrázky a popisy ke sbírkám přidělují. To se dělá na serveru? Pokud ano tak by se asi hodilo do wiki klienta doplnit odkaz na wiki serveru, kde se to popisuje.

**Comment by honza-rychtar** [comment]
Tohle se dělá v jádru Krameria. Popis a odkazy doplníme.

**Comment by zabak** [comment]
připomínám tohle
