### ISSUE TITLE
Více Kramériů - filtrování typů dokumentů

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#244]
Předpokládám, že nastavení klienta se vztahuje na zobrazení všech Kramériů (když je povoleno). To ovšem znamená, že když například u nás v MKP vyfiltruju jen 4 typy dokumentů, které skutečně máme (aby na čtenáře zbytečně nesvítila šedivá tlačítka), tak se stejný filtr aplikuje i po přepnutí třeba na MZK, která má typů dokumentů více.

Platí to i obráceně: v MKP máme 4 typy dokumentů, ale když se na nás podívám z Kraméria MZK, tak jsou aktivní jen tři (zřejmě máme nějaký typ dokumentu, který v MZK nemají).

Řešením by asi bylo, číst dostupné typy dokumentů ze serverů a filtr podle nich automaticky upravovat. V konfiguraci klienta by se pak nastavovalo, jestli zobrazovat vyšedlá tlačítka nebo ne.

**Comment by svetlym** [comment]
Teď jsem si ještě všiml, že vyšedlé ikonky typů dokumentů mají ještě jeden význam - když zapnu nějaký filtr, třeba konkrétního autora, tak jsou vyšedlé ikonky typů dokumentů, které filtru neodpovídají. To má určitě význam. Čili neměly by se vypínat vyšedlé ikony úplně, ale jen pro typy dokumentů, které v digitální knihovně nejsou vůbec.

(Ale popravdě je tohle celé asi nedůležitá drobnost. Můžu prostě povolit všechny typy dokumentů, holt jich bude většina vyšedlých.)

**Comment by zabak** [comment]
Je to motivace k tomu, abyste od každého typu dokumentu alespoň něco zdigitalizovali :-)

**Comment by svetlym** [comment]
> Ale popravdě je tohle celé asi nedůležitá drobnost.

Tohle raději upřesním: Drobnost jsou vyšedlé ikony pro druhy dokumentů, které vůbec v Kramériovi nemáme. To, že se nastavením v konfiguraci filtruje automaticky i nabídka po přepnutí do jiného Kraméria, drobnost není. To by se určitě dít nemělo.

**Comment by honza-rychtar** [comment]
V konfiguraci se nastavují dostupné typy dokumentů pro každého Krameria zvlášť. Pokud u všech povolíte vše, tak se nic měnit nebude a i po přepnutí tam budou stejné typy dokumentů.

**Comment by svetlym** [comment]
> V konfiguraci se nastavují dostupné typy dokumentů pro každého Krameria zvlášť.

Jasně, to jsem si neuvědomil. V tom případě tahle poznámka nedává smysl, zavírám issue.
