### ISSUE TITLE
Více kramériů - persistentní url bez ${KRAMERIUS}

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#245]
Zatím to nemám jak vyzkoušet, protože mám nového klienta jen na testovacím serveru, ale napadá mě potenciální problém, když zapneme přepínání do ostatních kramériů:

Budou pak fungovat naše persistentní odkazy v následujícím tvaru?

https://digitalniknihovna.mlp.cz/uuid:15c55420-2ad1-11e0-b32a-0030487be43a

Souvisí s tím otázka, jestli by se vůbec odkaz ve tvaru třeba https://digitalniknihovna.mlp.cz/mzk/uuid:15c55420-2ad1-11e0-b32a-0030487be43a měl považovat za perzistentní - pokud se chci odkazovat na dokument v MZK, měl bych asi použít adresu začínající webem MZK, protože Městská knihovna v Praze těžko může ručit za to, že bude i v budoucnosti platný. Podobně když si někdo vezme "perzistentní" odkaz z Karméria MZK na nějaký dokument u nás, a nebude ve tvaru https://digitalniknihovna.mlp.cz/uuid:15c55420-2ad1-11e0-b32a-0030487be43a, tak to z našeho pohledu není perzistentní odkaz...

**Comment by honza-rychtar** [comment]
> Zatím to nemám jak vyzkoušet, protože mám nového klienta jen na testovacím serveru, ale napadá mě potenciální problém, když zapneme přepínání do ostatních kramériů:
> 
> Budou pak fungovat naše persistentní odkazy v následujícím tvaru?
> 
> https://digitalniknihovna.mlp.cz/uuid:15c55420-2ad1-11e0-b32a-0030487be43a
> 
Ne. Pokud zapnete přepínání do ostatních kramériů, tak musíte vybraného Krameria v url rozlišit a na to v současném perzistentním odkazu nemáte prostor.

> Souvisí s tím otázka, jestli by se vůbec odkaz ve tvaru třeba https://digitalniknihovna.mlp.cz/mzk/uuid:15c55420-2ad1-11e0-b32a-0030487be43a měl považovat za perzistentní - pokud se chci odkazovat na dokument v MZK, měl bych asi použít adresu začínající webem MZK, protože Městská knihovna v Praze těžko může ručit za to, že bude i v budoucnosti platný. Podobně když si někdo vezme "perzistentní" odkaz z Karméria MZK na nějaký dokument u nás, a nebude ve tvaru https://digitalniknihovna.mlp.cz/uuid:15c55420-2ad1-11e0-b32a-0030487be43a, tak to z našeho pohledu není perzistentní odkaz...

Je to **perzistentní** odkaz do klienta. Pokud změníte url klienta nebo smažete objekt v Krameriovi, tak samozřejmě přestane fungovat.

Perzistence tady předpokládá, že doména bude stálá a objekty nemění uuid, ale není závislá na klientské aplikaci.

U předchozího klienta na DK byl perzistentní odkaz na libovolný objekt libovolného Krameria ve tvaru
http://www.digitalniknihovna.cz/KOD_KRAMERIA/uuid/UUID_OBJEKTU

Teď http://www.digitalniknihovna.cz změníla správce, vlastníka i celou klientskou aplikaci a přesto je perzistentní odkaz na libovolný objekt libovolného Krameria stále ve tvaru
http://www.digitalniknihovna.cz/KOD_KRAMERIA/uuid/UUID_OBJEKTU

Stejně vám to bude fungovat s https://digitalniknihovna.mlp.cz, ale v případě více Krameriu na této doméně to nerozlišíte.
Může přesměrovat odkazy https://digitalniknihovna.mlp.cz/UUID na 
http://www.digitalniknihovna.cz/mlp/uuid/UUID
