### ISSUE TITLE
Zobrazení verze klienta

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#246]
Dá se někde z klienta vyčíst verze?

Pokud ne, určitě by se to hodilo, abychom ji mohli uvádět do issues. Mohla by se třeba logovat do konzole (takže když by někdo vykopírovával chybová hlášení z konzole, tak by tam byla uvedena).

**Comment by svetlym** [comment]
Verze by také mohla být součástí jména instalačního adresáře.

kramerius-web-client.zip
- kramerius-web-client-1.2.8

**Comment by honza-rychtar** [comment]
Verzi do klienta někde nenápadně propašujeme. Hodí se to.
Já ji teď zjišťuju přes zdrojový kód stránky, kde je uvedena v parametru za konfiguračním souborem.
`<script type="text/javascript" src="assets/shared/globals.js?v1.2.8"></script>
`

**Comment by honza-rychtar** [comment]
Verze klienta se zobrazí na stránce **Informace** vpravo dole
http://dk.kramerius.org/mzk/about
