### ISSUE TITLE
Nefunguje persistentní url ve tvaru https://digitalniknihovna.mlp.cz/${UUID}

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#247]
Narazil jsem na problém, který brání nasazení klienta. Potřebujeme, aby persistentní odkazy byly ve tvaru: https://digitalniknihovna.mlp.cz/uuid:5c0b1772-e027-4fe8-9c87-685c0b92d5cb, stejně jako v předchozí (šedé) verzi.

Možnost přepínat do jiných Kramériů mám zatím vypnutou. Zkoušel jsem následující hodnoty proměnné share_url, se všemi mi to hází 404ku:

share_url: "https://digitalniknihovna.mlp.cz/${UUID}",
share_url: "https://digitalniknihovna.mlp.cz/uuid:${UUID}",
share_url: "digitalniknihovna.mlp.cz/${UUID}",
share_url: "digitalniknihovna.mlp.cz/uuid:${UUID}"

Bez toho nám nebudou fugnovat prokliky z webového katalogu, což je kromě googlení jediný rozumný způsob, jak se čtenáři mohou do Kraméria dostat.

**Comment by svetlym** [comment]
Aha, ono to nastavení nejspíš ovlivňuje jen generování odkazů tlačítkem pro sdílení - to zjevně funguje dobře: https://digitalniknihovna.mlp.cz/uuid:d911da6f-70a5-43d3-97dc-f142423d0c55

Každopádně to ale potřebujeme i v opačném směru, tedy aby se tento odkaz správně zobrazil.

**Comment by svetlym** [comment]
Dobrý den,

chtěl bych u tohoto issue (funkčnost url ve tvaru https://digitalniknihovna.mlp.cz/uuid:d911da6f-70a5-43d3-97dc-f142423d0c55) poprosit o vyšší prioritu. Přechod na nového klienta jsme měli oficiálně stanoven na 3. 6. 2019 a museli jsme to odložit, protože bez funkčních prokliků z webového katalogu nasazení nedává smysl. Na dotazy "Kdy to tedy bude?" nemám jak odpovědět.

**Comment by honza-rychtar** [comment]
Chápu to správně, že chcete, aby odkaz https://digitalniknihovna.mlp.cz/uuid:d911da6f-70a5-43d3-97dc-f142423d0c55 vedl na nového klienta?
Tohle klient neovlivní. To musíte nastavit u sebe kam má být doména digitalniknihovna.mlp.cz nasměrována. Teď vede na tmavého klienta.

**Comment by svetlym** [comment]
> Chápu to správně, že chcete, aby odkaz https://digitalniknihovna.mlp.cz/uuid:d911da6f-70a5-43d3-97dc-f142423d0c55 vedl na nového klienta?
> Tohle klient neovlivní. To musíte nastavit u sebe kam má být doména digitalniknihovna.mlp.cz nasměrována. Teď vede na tmavého klienta.

Ten odkaz teď vede na tmavého klienta, protože jsem revertnul změnu a dal jsem tam zpátky tmavého klienta, aby to bylo pro čtenáře použitelné.

Problém je v tom, že když tam místo toho dám nového klienta, tak tento odkaz sice vede na nového klienta (zobrazí se), ale uvnitř něj hodí 404ku (dokument nenalezen).

**Comment by svetlym** [comment]
V network logu v chromu vidím nejdřív GET request:

Request URL: http://192.168.111.101/uuid:C2AED250-8162-11E0-B259-0030487BE43A

a po něm:

Request URL: http://192.168.111.101/mlp/uuid/uuid:C2AED250-8162-11E0-B259-0030487BE43A

což hodí tu 404ku.

Když to zkusím bez /mlp/, tak to funguje:

http://192.168.111.101/mlp/uuid/uuid:C2AED250-8162-11E0-B259-0030487BE43A

V konfiguraci mám jen jednoho Kraméria.

(Adresy vedou na našeho testovacího kraméria, který není vidět zvenku, takže prokliky vám nebudou fungovat.)

**Comment by honza-rychtar** [comment]
Aha, už tomu rozumím.
Tmavý klient (na kterého teď linkujete z katalogu) má v url vždy kód Krameria.
Světlý klient v případě pouze jednoho Krameria kód Krameria v url nemá (v takovém případě to není potřeba a vypadá to lépe).

Pokud máte jen jednoho Krameria v konfiguraci, tak to chybějící **/mlp** dejte přímo do **share_url**
`https://digitalniknihovna.mlp.cz/mlp/${UUID}`

Pokud tam budete mít více Krameriu, tak přes 
`https://digitalniknihovna.mlp.cz/${KRAMERIUS}/uuid/${UUID}`
se ${KRAMERIUS} vyhodnotí na **mlp** pro vašeho Krameria a budou ty odkazy fungovat i v případě více Krameriů v jednom klientovi.

**Comment by svetlym** [comment]
> Pokud máte jen jednoho Krameria v konfiguraci, tak to chybějící /mlp dejte přímo do share_url https://digitalniknihovna.mlp.cz/mlp/${UUID}

To udělá něco jiného, než potřebujeme a navíc to stejně nefunguje.

Když nastavím share_url: "http://192.168.111.101/mlp/${UUID}", tak klient generuje odkazy takto:

![share_url](https://user-images.githubusercontent.com/11628774/59260594-34024080-8c3c-11e9-8de4-3490f7be8886.png)

My ale potřebujeme odkazy ve tvaru, jak jsem ho původně uváděl, tedy bez /mlp/.

Když navíc tento odkaz zkusím otevřít, výsledkem je opět 404:

![mlp404](https://user-images.githubusercontent.com/11628774/59260776-84799e00-8c3c-11e9-9264-ab09d43863cd.png)


Pro jistotu ještě zopakuji, jaký je pro nás žádoucí stav:

Share url v tomto tvaru (v ostrém provozu samozřejmě na adrese digitalniknihovna.mlp.cz a přes https, tohle je testovací server):

```
share_url: "http://192.168.111.101/${UUID}"
```

A následně aby odkaz http://192.168.111.101/uuid:d911da6f-70a5-43d3-97dc-f142423d0c55 nehodil 404ku, ale korektně se otevřel.

**Comment by svetlym** [comment]
Ještě přikládám screenshoty, co myslím tím, co vidím v network logu chromu (jsou to první dva řádky toho samého logu):

![url0](https://user-images.githubusercontent.com/11628774/59261374-9f98dd80-8c3d-11e9-8901-faa9f94b9d9b.png)

![url1](https://user-images.githubusercontent.com/11628774/59261386-a32c6480-8c3d-11e9-94a3-5deebba2ce40.png)

**Comment by svetlym** [comment]
Dobrý den,

můžu se zeptat, zda bude možné tento problém vyřešit, a pokud ano, kdy by to mohlo být? Potřebujeme vědět, na jaký termín máme přechod na nového klienta odložit, případně zda ho úplně odvolat.

**Comment by svetlym** [comment]
Napadlo mě, že bych to mohl zkusit obejít přepisovacím pravidlem v Apachi... a zjistil jsem, že i šedivý klient to řešil přepisovacím pravidlem. Takže jsem ho upravil a funguje to. Škoda, že mě to nenapadlo dřív.

Problém je každopádně vyřešen, takže issue zavírám.

**Comment by JanMeritus** [comment]
@svetlym hej, apachom sa to da pekne poriesit. Ale nebolo by to lepsie ak by to nastavenie bolo na jednom mieste, a nie medzi systemom a app ?

**Comment by svetlym** [comment]
@JanMeritus: Přesměrovávat to na úrovni web serveru má výhodu v tom, že když se změní klientská aplikace, můžeme snadno zachovat funkčnost stávajících url. Takže mě tohle řešení ve výsledku přijde dobré, přestože jsem ho původně považoval za provizorní.
