### ISSUE TITLE
Error 404 - klient nepředává informaci do hlavičky

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#248]
Pokud zadám dotaz na server pomocí CURL s neexistujícím UUID - vrátí se mi HTTP/1.1 200 OK. 
Pro ověření, zda dokument existuje, bychom potřebovali, aby nový klient předával do hlavičky chybový kód.

**Comment by svetlym** [comment]
@jahhoo: Když pošlete http dotaz přímo na server, tak se o tom klient vůbec nedozví. Řekl bych tedy, že tento požadavek by měl být spíš na jádro Kraméria, tedy zde: https://github.com/ceskaexpedice/kramerius/issues

**Comment by honza-rychtar** [comment]
@jahhoo 
Pro test existence uuid je určitě lepší dotaz na API Krameria, tj. 
http://kramerius5.nkp.cz/search/api/v5.0/item/uuid:ab05e3b0-0bbc-11dd-acc7-000d606f5dc6
vrací 200 OK
http://kramerius5.nkp.cz/search/api/v5.0/item/blabla
vrací 404 Not Found

Klient je single page application, kde se obsah stránky vyhodnocuje až na straně uživatelova prohlížeče javascriptem, ktery třeba CURL vůbec neinterpretuje.
