### ISSUE TITLE
BUG - Zobrazení části jiné stránky

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#249]
Narazili jsme na problém při zobrazení http://kramerius5.nkp.cz/view/uuid:c1ea4350-86b7-11e4-9d8c-005056827e51?page=uuid:1a7b84c0-abcf-11e4-a7a2-005056827e51 - zobrazí se část jiné strany (viz. screen)

![Snímek z 2019-06-18 16-41-25](https://user-images.githubusercontent.com/33415849/59693966-1f97e800-91e8-11e9-9b21-051713f0b5f4.png)

**Comment by zabak** [comment]
@jahhoo toto je zdá se vyřešené, prosim o potvrzení.

**Comment by zabak** [comment]
protože je to bez reakce, zavírám jako vyřešené
