### ISSUE TITLE
Špatně seřazená čísla u ročníku

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#250]
Špatně seřazená čísla u ročníku - čísla nejdou za sebou (1, 2, 3 ...), ale řadí se 1, 10, 11 ... 2, 20, 21 ... 3, 30, 31...

viz. http://kramerius5.nkp.cz/periodical/uuid:b776c280-948d-11e3-8e84-005056827e51

**Comment by krizovj** [comment]
https://github.com/ceskaexpedice/kramerius-web-client/issues/124

https://github.com/ceskaexpedice/kramerius-web-client/issues/86

**Comment by krizovj** [comment]
Nám to dělá taky:
https://kramerius.lib.cas.cz/uuid/uuid:2848e915-2a0a-4588-87df-a9765b6432a1

**Comment by honza-rychtar** [comment]
Čísla se řadí podle data (zde všude stejné), pokud jsou data shodná, tak se seřadí podle názvu, kde číslo je, ale jako řetězec, který se seřadí lexikograficky a ne numericky.

Součástí optimalizace SOLR bude také indexace čísel (issue_number/part_number) u čísel (výtisků).
To bude číselná hodnot a řazení bude pak probíhat správně i v případě čísel se stejným datem.

**Comment by luckajirku** [comment]
Víme, kdy asi to bude vyřešené? Už je to zas další rok...

**Comment by honza-rychtar** [comment]
Opraveno. S novým indexem se spraví řazení přímo. U starého se řazení po načtení upraví na straně klienta.
Takže by to mělo fungovat ve všech Krameriich.

http://www.digitalniknihovna.cz/nkp/periodical/uuid:b776c280-948d-11e3-8e84-005056827e51
http://www.digitalniknihovna.cz/knav/periodical/uuid:2848e915-2a0a-4588-87df-a9765b6432a1
