### ISSUE TITLE
Nezobrazení názvu přílohy

### ISSUE THREAD

**Issue by AdamJasko** [ceskaexpedice/kramerius-web-client#253]
Dobrý den,
v novém klientovi se vůbec nikde nezobrazuje název příloh, které jsou nedílnou součástí hlavního vydání, byť pojmenování mají. Ve starém klientovi se všechny přílohy paušálně jmenují _Rudé právo_. 

Příklad:
13.11.1920 byla součástí vyd. _Rudého práva_ příloha s názvem _Sobota_. V nové instalaci klienta se však tato informace nezobrazí ani v pravém sloupci s metadaty, ani při najetí myší na náhled stránky. Nebo špatně hledám.
![KNM_neu](https://user-images.githubusercontent.com/37698032/60963848-3971aa00-a312-11e9-9551-5959112c5808.png)
http://kramerius.nm.cz/view/uuid:c60d3b67-d185-4061-8d70-94296f4e9125?page=uuid:576095bb-8a13-11e9-9aeb-001b63bd97ba

Šlo by v novém klientovi (např. do pravého sloupce s metadaty) přidat pole, kde by bylo jasně vidět, jak se která aktuálně označená příloha jmenuje?

Dlužno podotknout, že u případu výše je v metadatech správné pojmenování přílohy uvedeno v poli mods:partName: a nikoliv v poli mods:title.

<mods:titleInfo ID="MODS_SUPPLEMENT">
mods:titleRudé právo</mods:title>
mods:partNumber41</mods:partNumber>
mods:partNameSobota - dělnická kulturní hlídka.</mods:partName>
</mods:titleInfo>

**Comment by krizovj** [comment]
Řekla bych, že to souvisí s tímhle issue: https://github.com/ceskaexpedice/kramerius-web-client/issues/189

**Comment by honza-rychtar** [comment]
Metadata o příloze jsou teď vpravo v podrobnostech.

http://nm.kramerius.rychtar.cloud/view/uuid:c60d3b67-d185-4061-8d70-94296f4e9125?page=uuid:576095bb-8a13-11e9-9aeb-001b63bd97ba

![Screenshot 2019-07-23 14 28 27](https://user-images.githubusercontent.com/1178142/61712251-33d68400-ad56-11e9-89dc-d22841632eef.png)

**Comment by AdamJasko** [comment]
Dobrý den,
děkuji za vyřešení. Tohle vypadá daleko lépe. Nicméně:

Z tohoto URL se pole s názvem příloh doopravdy zobrazí.
http://nm.kramerius.rychtar.cloud/view/uuid:e28ee2a8-3332-4ad9-ac6c-b8ecd59767e1?page=uuid:87fbf0e8-8a21-11e9-a196-001b63bd97ba

Z tohoto URL jej však již nevidím.
http://kramerius.nm.cz/view/uuid:e28ee2a8-3332-4ad9-ac6c-b8ecd59767e1?page=uuid:87fbf0e8-8a21-11e9-a196-001b63bd97ba

Asi bych potřeboval vysvětlit, jaký je v těchto dvou přístupech rozdíl a kdy se změna projeví i u toho druhého (např. po aktualizaci klienta?). Laicky bych řekl, že rozdíl patrně bude v "příjezdové cestě".
