### ISSUE TITLE
Název versus alternativní (variantní) název ve výsledcích vyhledávání

### ISSUE THREAD

**Issue by helena-oks** [ceskaexpedice/kramerius-web-client#256]
U monografií, kde je <mods:titleInfo type="alternative">, se zobrazuje u náhledu ve výsledcích vyhledávání poslední výskyt tagu titlez toho tagu, místo hlavního názvu, který je uvnitř <mods:titleInfo> hned na začátku.  Vyskytuje se u digitalizace MZK i NK v obou krameriích, takže popis bude podle pravidel. 

Příklad: 3 dokumenty vyhledané následujícím dotazem mají naprosto stejný hlavní název Tajná kniha o digitální fotografii.
 http://www.digitalniknihovna.cz/mzk/search?q=Tajn%C3%A1%20kniha%20o%20digit%C3%A1ln%C3%AD%20fotografii.

Ukázka metadat:       
<mods:titleInfo>
            <mods:title>
                Tajná kniha o digitální fotografii
            </mods:title>
        </mods:titleInfo>
        <mods:titleInfo type="alternative">
            <mods:title>
                Tajná kniha digitální fotografie
            </mods:title>
        </mods:titleInfo>
        <mods:titleInfo type="alternative">
            <mods:title>
                Digitální fotografie
            </mods:title>
        </mods:titleInfo>

**Comment by honza-rychtar** [comment]
Opraveno.
http://kramerius.rychtar.cloud/mzk/search?q=Tajn%C3%A1%20kniha%20o%20digit%C3%A1ln%C3%AD%20fotografii
