### ISSUE TITLE
Problémy s vyhledáváním dokumentů se znakem "&"

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#257]
Při vyhledávání dokumentů, jejichž  název obsahuje znak &, se v Digitální knihovně uživatel nedobere žádného výsledku, resp. nenačte se mu vůbec výsledek vyhledávání. Pokud název zadám bez toho znaku, již se najde. Viz např.

Vyhledávám časopis Bazén & sauna:

http://www.digitalniknihovna.cz/mzk/search?q=Baz%C3%A9n%20%26%20sauna&sort=relevance
http://www.digitalniknihovna.cz/mzk/search?q=Baz%C3%A9n%20%20sauna&sort=relevance

Testováno na DK MZK i NK. Kramerius s tím problémy nemá, viz http://kramerius4.nkp.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=Baz%C3%A9n+%26+sauna&issn=&title=&keywords=&author=&rok=&udc=&ddc=.

**Comment by honza-rychtar** [comment]
Opravím

**Comment by honza-rychtar** [comment]
Opraveno.

**Comment by annie-cz** [comment]
Stejný problém u jiných speciálních znaků. Kontrolováno přes aktuálního klienta digitalniknihovna.cz v NKP.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/43028501/204327650-332054c6-71b0-4ecb-b413-340c9517c27e.png">

https://www.digitalniknihovna.cz/nkp/uuid/uuid:1d487d40-b635-11e5-b404-005056825209

Podobně jsem si před cca 2 týdny všimla, že se stejně chovaly dokumenty v nové ČDK s dalšími speciálními znaky, např. s apostrovem. Bylo by asi dobré zkontrolovat, jak se obecně chovají speciální znaky v názvech v klientovi.
