### ISSUE TITLE
V prohlížeči Chrome se nezobrazují se tlačítka pro generování PDF a JPEG

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#260]
U dokumentů v Digitální knihovně se nezobrazují tlačítka pro tisk, generování PDF a JPEG a vygenerování OCR stránky. V aktuálních verzích Firefox a Edge jsem na problém nenarazila, projevuje se zatím pouze u Google Chrome. Tlačítka se náhodně nezobrazují buď vůbec, nebo z části a nebo úplně v pořádku a to jak u periodik, tak u monografií. Testováno na datech MZK i NK přes digitalniknihovna.cz a přes kramerius5.nkp.cz, všude se to chová stejně.

U sebe mám aktuální Chrome Verze 76.0.3809.100 (Oficiální sestavení) (64bitový)

Nějaké příklady zde:

periodika:

a) nezobrazují se částečně
http://www.digitalniknihovna.cz/mzk/uuid/uuid:640d7520-10c7-11e8-8ee4-005056825209
![image](https://user-images.githubusercontent.com/43028501/63028345-f1b0e600-beae-11e9-92fa-a02b9bcd5869.png)

b) nezobrazují se vůbec
http://www.digitalniknihovna.cz/mzk/uuid/uuid:ea670593-9eda-4618-b70f-bb9b989a8a86
![image](https://user-images.githubusercontent.com/43028501/63028490-36d51800-beaf-11e9-8bf5-d866befb714d.png)

monografie:

a) nezobrazují se částečně
http://www.digitalniknihovna.cz/mzk/uuid/uuid:c07f5eec-1083-41d4-ba7b-1f944d990c41
![image](https://user-images.githubusercontent.com/43028501/63029136-53be1b00-beb0-11e9-9cba-7fc5d6c1d030.png)

b) nezobrazují se vůbec
http://www.digitalniknihovna.cz/mzk/uuid/uuid:493b273d98031bc6a87a27f49b541523
![image](https://user-images.githubusercontent.com/43028501/63029071-38eba680-beb0-11e9-83b6-104ae26002fe.png)

Na tento jev si u nás několikrát stěžovali čtenáři, ale do teď se chyba neprojevila na našich počítačích, přisuzovali jsme tedy chybu používání zastaralých prohlížečů u uživatelů, kteří zpravidla nereagovali na další dotazy, jaký prohlížeč používají, abychom se na problém mohli více zaměřit.

**Comment by honza-rychtar** [comment]
Zajímavé. Začalo se to projevovat až po updatu Chrome na nejnovější verzi.
Opravil jsem to. 
http://dk.kramerius.org/mzk/uuid/uuid:493b273d98031bc6a87a27f49b541523
