### ISSUE TITLE
V položce [Nejnovější] se zobrazují pouze volně dostupné dokumenty

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#261]
Zdravím,
mám otázku k fungování položky [Nejnovější] na hlavní stránce klienta. Podle všeho to vypadá, že se v této položce zobrazují pouze volně dostupné dokumenty (bez zámečku). Díval jsem se namátkou na různé instance klienta a všude to vypadalo stejně.

Je to tedy "vlastnost" klienta, nebo se dá někde toto chování ovlivnit konfigurací (hledal jsem na wiki ale nenašel)?

V jádře se v položce [Nejnovější] zobrazují i dokumenty neveřejné (myšleno samozřejmě jen náhledy, nikoliv plné texty).

Díky, MD

**Comment by pavelkocourek** [comment]
KNAV 16.9.
"Nejnovější" bude v souladu s checkboxem Veřejné.
