### ISSUE TITLE
V případě výskytu více příloh u periodik se nezobrazují všechny přílohy

### ISSUE THREAD

**Issue by jbil7** [ceskaexpedice/kramerius-web-client#262]
Nachází-li se v dokumentu více příloh (SUPPL) pod úrovní čísla (ISSUE), nejsou všechny tyto přílohy viditelné. Příloha, která v dokumentu není vidět, je dohledatelná pouze skrze fulltextové vyhledávání. Po jejím vyhledání (např. na základě OCR textu) se zobrazí náhled, při jehož rozkliknutí se otevře prázdný dokument.

Problém byl zjištěn u periodika Práce, např. výtisk ze dne 6. 3. 1993. Viz: 
http://kramerius5.nkp.cz/uuid/uuid:1d373700-6c1d-11e9-80b3-5ef3fc9ae867

Při testování více příloh u jiného periodika (a simulaci jiné posloupnosti ve strukturálních mapách - ISSUE_0001, SUPPL_0001, SUPPL_0002) došlo k témuž problému.

**Comment by krizovj** [comment]
https://github.com/ceskaexpedice/kramerius-web-client/issues/177

**Comment by kenji1322** [comment]
Ja by som len dodal, že sa zobrazí iba jedna príloha a to tá ktorá má v tripletoch vazbu <http://www.nsdl.org/ontologies/relationships#hasIntCompPart> ako prvá.

**Comment by honza-rychtar** [comment]
Opraveno.
