### ISSUE TITLE
Popisky název: podnázev u náhledů titulů

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius-web-client#263]
U náhledů se nám u určité části dokumentů nezobrazuje správně "název: podnázev", ale jen "podnázev". Když takový dokument zreindexuju, objeví se místo podnázvu název - což pořád není ideální stav, ale už je to lepší než jen ten matoucí podnázev místo názvu. Když ten dokument otevřu, tak v popisu vpravo už je vše jak má být, týká se to jen popisků u náhledů.
Co jsme to procházeli, tak jde u nás o importy do června 2015, u nově naimportovaných titulů od podzimu 2015 je vše v pořádku. (Ten problém se neobjevil teď, měli jsme ho už v předchozím klientovi, ale tam jsme to řešili úpravou zobrazovací šablony, takže nás to netrápilo.) 
Když srovnáme metadata u starších i novějších, je to stejné, oblast titleinfo se jinak neliší. Nějaký nápad, co s tím? Jak docílit toho, aby se u všech dokumentů (jasně, u těch, které mají i podnázev) objevoval správně "název: podnázev"?
Tady je třeba hezký příklad: https://kramerius.svkhk.cz/search?q=Červenokostelecko&sort=relevance - všechny ty orgány jsou jen podnázvy...

**Comment by luckajirku** [comment]
[Honzo](@honza-rychtar), dá se říct, kdy bude tohle vyřešeno? Jde mi o to, že chceme některé tituly, kterých se to týká, vystavit do doporučených, ale vypadá to blbě, když je tam jen podnázev. Tak jestli to bude někdy v dohledné době, nebo jestli to ještě potrvá a pak je lepší se jim vyhnout, ať na úvodní stránce neukazujeme podivnosti.

**Comment by honza-rychtar** [comment]
@luckajirku Problém je v indexu.
Např. tento dokument https://kramerius.svkhk.cz/periodical/uuid:27ed13da-d24f-424c-9054-fd16819adcf0
má v MODS
```
<mods:titleInfo>
  <mods:title>Nový čas</mods:title>
  <mods:subTitle>orgán OV KSČ a ONV v Náchodě</mods:subTitle>
</mods:titleInfo>
```
a v indexu má
```
"root_title": "orgán OV KSČ a ONV v Náchodě",
"title": "Nový čas",
```

Ve výsledcích hledání se pak podle toho, jestli je zadán i hledaný řetězec zobrazuje 
`root_title` pokud **je** zadán vyhledávací řetězec
`title` pokud **není** zadán vyhledávací řetězec

V obou případech se to pak zobrazuje špatně, protože správně by se mělo uvedené `titleInfo` zaindexovat v obou polích (`title` i `root_title`) jako
`title: subtitle`, konkrétně **Nový čas: orgán OV KSČ a ONV v Náchodě**

@pavel-stastny nevíš proč se to indexuje takto zvláštně? Může to být tím pořadím elementů (titleInfo je až poslední) a konfliktem se zanořeným`titleInfo` v `relatedItem`?

**Comment by pavel-stastny** [comment]
@honza-rychtar  Při pohledu do indexační šablony to vypadá, že informace bere z [DC](https://kramerius.svkhk.cz/search/api/v5.0/item/uuid:27ed13da-d24f-424c-9054-fd16819adcf0/streams/DC) a že očekává jeden element `dc:title` místo dvou.  Ta rozdílná hodnota `title` a `root_title` bude pravděpodobně tím, že se používají jiné xpath pro ty dvě hodnoty.

**Comment by luckajirku** [comment]
o tom, že je problém v DC, víme od r. 2015, spíš jde o to, co (jestli vůbec něco) s tím teď můžeme udělat, aby se to zobrazovalo správně. V K4 rozhraní jsme měli upravenou zobrazovací šablonu, tady tu možnost nemáme.

**Comment by zabak** [comment]
@luckajirku přejít na K7 hned jak to bude možné.

**Comment by honza-rychtar** [comment]
K7 to vyřeší, ale stejně tak to vyřeší úprava DC, pokud je problém v DC.

**Comment by honza-rychtar** [comment]
Řešeno v K7.
