### ISSUE TITLE
DNNT: Informacni panel - Doplneni prav/dostupnosti

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius-web-client#264]
Ahoj, chcel by som poprosit o doplneni prav do informacniho panelu. Suvis s #210 . V pravem panelu pri zobrazeni dila by bolo vhodne pridat povinne/volitelne - dle konsenzu a nasledne nastaveni moznost zobrazit v klientovi Prava nad dilem: eg. Verejne, Neverejne, DNNT, pripadne jina specialni opravneni s odkazem na info tykajici se zminenych prav - stejna hlaska aka je pri zobrazeni dila.

User case: Uzivatel v specialnim rezimu full NK si prohlizi dila, chtel by vedet jestli to co si prohlizi je DNNT nebo Neverejny.

Obecne: je to dulezita informace k titulu a jeho soucastim.

**Comment by zabak** [comment]
Tam už by ale chtělo zobrazovat nejen krátký text, ale i nějaké vysvětlení, které může být i poměrně dlouhé - zvlášť u DNNT. Může to být na rozkliknutí. Ta práva mohou být teoreticky i hodně specifická - třeba u časopisů vydávaných ústavy AV, u hudebnin apod. takže by bylo dobré ten podrobnější popis mít ke každému druhu oprávnění v Krameriu mít.

**Comment by JanMeritus** [comment]
Ahoj, jj, je to presne ako pisem v metodice. Tu by bol vizualne len konkretny druh prav, po rozkliknuti odkaz na informacni panel s rozkliknutim

**Comment by JanMeritus** [comment]
@honza-rychtar, pripominam sa, prosime o doplnenie sekcie Prava : XY, do informacneho panelu moznost prekliknut z XY na dalsi vysvetlujuci text

**Comment by honza-rychtar** [comment]
U neveřejného dokumentu se zobrazí v pravém panelu zámeček s textem **Dokument není veřejně dostupný** a ikonou otazníku, na kterou když kliknu, tak se zobrazí dialog s nastavitelnou hláškou rightMsg z Krameria.
<img width="302" alt="Screenshot 2020-02-12 11 53 13" src="https://user-images.githubusercontent.com/1178142/74328522-5c73a900-4d8e-11ea-9dc3-19b622a16b55.png">

<img width="1625" alt="Screenshot 2020-02-12 11 56 03" src="https://user-images.githubusercontent.com/1178142/74328794-d7d55a80-4d8e-11ea-88f8-dedf847bd7cd.png">

V případě neveřejného DNNT dokumentu je zámeček oranžový, text je **Dílo nedostupné na trhu** a dialog obsahuje hlášku o DNNT.
Pro fungování DNNT je potřeba mít verzi Krameria, která dává info o dnnt do API.

V případě veřejného dokumentu se nic nevypisuje.

**Comment by zabak** [comment]
@honza-rychtar problém vidím v tom, že ta rightMsg je jen jedna. Předpokládám, že by se muselo API naučit vracet různé informace o právech podle nějaké kombinace parametrů, nebo by se muselo něco dávat do solru nebo přimo do metadat, podle čeho by se rozhodovalo, jaká zpráva se má zobrazit.

**Comment by honza-rychtar** [comment]
@zabak Není. Dnnt má vlastní hlášku. Klient má v sobě hlášky pro dnnt dokument a nedostupný dokument.
V konfiguraci je pak možné nastavit, že pro nedostupný dokument se nepoužije hláška z klienta, ale natáhne se z Krameria.
Jinak ano, pokud se dnnt rozšíří do více Krameriů a bude tedy dávat smysl, aby byla dnnt hláška pro každou instalaci jiná, pak ji můžem přidat do Krameria a natahovat ji jako tu současnou hlášku o nedostupnosti.
