### ISSUE TITLE
mapa s deskami

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#266]
http://dk.kramerius.org/mzk/view/uuid:534faf37-9e4f-4385-be1b-6d86dbfdbb90?page=uuid:811e8754-1829-413e-b7ba-29e97929f983

mapa má dva obrázky, první jsou desky, druhý je mapa. V takovýchto případech by bylo lepší v geo hledání zobrazovat rovnou tu mapu. 

Ale v tomto případě
http://dk.kramerius.org/mzk/view/uuid:43248e88-d815-4982-925e-045098218ade?page=uuid:db1d01f7-31ab-406c-b165-44a84f11b8a9
by relevantní mapa byla taky hned druhý obrázek, ale ten je označen přední přídeští.

Navíc tam zatím takových případů moc není, takže asi bude lepší toto issue zatím zavřít a nedělat s ním nic.

**Comment by honza-rychtar** [comment]
@zabak Tohle by měla řešit podpora georeference na úrovni stran.
