### ISSUE TITLE
Informace o nedostupnosti dokumentu - HTML formátování

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#268]
Potřebovali bychom upravovat hlášku o nedostupnosti dokumentu pomocí HTML formátování (aby bylo možné vložit více textu do ostavců a používat odkazy).

**Comment by JanMeritus** [comment]
pripadne markdown

**Comment by honza-rychtar** [comment]
Hláška o nedostupnosti se bere z rightMsg, která je nastavena v Krameriovi a umožňuje HTML formátování.
Klient hlášku zobrazí s tím formátováním.
MZK: http://dk.kramerius.org/mzk/view/uuid:542ad020-d3a4-11e9-84ef-005056827e51?page=uuid:7be17c17-b1aa-44b5-967b-dc3fd4869bfc
NKP: http://dk.kramerius.org/nkp/view/uuid:9d71a340-a932-11e9-9209-005056827e51?page=uuid:3f388c61-2260-4270-ae5a-99d24654a5fb
