### ISSUE TITLE
V Chrome nefungují citace

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#269]
V prohlížeči Chrome nefunguje zobrazení citací. Když se otevře okno s citacemi, hrozně dlouho se načítá a nic se nezobrazí. Ve Firefoxu to funguje v pořádku.

**Comment by krizovj** [comment]
![citace](https://user-images.githubusercontent.com/21309201/65761560-4dfa5d00-e11f-11e9-81ff-2f0d34e254cd.jpg)

**Comment by honza-rychtar** [comment]
Opraveno. 
Stáhněte si prosím novou verzi, která chybu opravuje.
https://github.com/ceskaexpedice/kramerius-web-client/releases/tag/v1.2.12
