### ISSUE TITLE
Mobilni Safari neprehraje mp3

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#27]
zkusit ogg a wav

**Comment by filipsir** [comment]
mozna aktualizuji problem - nic na iOS nefunguje. tedy, chrome, safari ani google. s mp3 to nema nic spolecneho - kramerius jako user copy dava pouze a jen mp3. Takze je chyba nekde jinde

**Comment by honza-rychtar** [comment]
Opraveno
