### ISSUE TITLE
Vícedílné monografie - trvalý odkaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#270]
Pokud už je na to založeno issue, tak se omlouvám a klidně to zavřete.

U vícedílných monografií, když chci vygenerovat odkaz na jeden z dílů té monografie, tak se mi zobrazí možnosti: stránka a dokument. 

Stránka je jasná, ale když jsem v té monografii, tak předpokládám, že "dokument" je odkaz na ten jeden díl té monografie. Ale je to odkaz na celou tu vícedílku. Bylo byl prosím možné přidat u vícedílných monografií ještě úroveň "svazek knih" (aby to bylo pojmenováno stejně, jako už to je), kdy odkaz dokument by vedl na konkrétní díl monografie a odkaz svazek knih by vedl na tu vrchní úroveň?

**Comment by honza-rychtar** [comment]
Ano, přidám. U zobrazení metadat ve vývojové verzi to už takto udělané je. Přidám to i ke sdílení a citaci.
<img width="1638" alt="Screenshot 2019-10-03 14 41 40" src="https://user-images.githubusercontent.com/1178142/66127464-0591e200-e5ec-11e9-8fa6-6b2b044ed786.png">

**Comment by honza-rychtar** [comment]
<img width="701" alt="Screenshot 2020-01-12 11 57 52" src="https://user-images.githubusercontent.com/1178142/72217747-d5cf7000-3532-11ea-8f3b-6afff1396d24.png">

Podobně u citace.
