### ISSUE TITLE
Počty dokumentů ve filtrech

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#271]
Všimli jsme si, že se nám ve filtrech zobrazují výrazně menší počty dokumentů, než by měly. Dokumentů v němčině máme například přes 2000 a filtr říká 44. Obdobně dokumentů v češtině určitě máme víc než 365

V datech ale jazyk uveden je - u dokumentu https://digitalniknihovna.mlp.cz/uuid:295692e3-4b56-4b08-b537-575028e2c2ad je například uveden jazyk: němčina, ale ve výpisu všech dokumentů v němčině (https://digitalniknihovna.mlp.cz/search?sort=newest&languages=ger) není.

Čím by to mohlo být?

**Comment by honza-rychtar** [comment]
Konkrétně u tohoto dokumentu není jazyk zaindexovaný.
V MODS jazyk je 
http://kramerius4.mlp.cz/search/api/v5.0/item/uuid:295692e3-4b56-4b08-b537-575028e2c2ad/streams/BIBLIO_MODS
V SOLR není
http://kramerius4.mlp.cz/search/api/v5.0/search?q=PID:%22uuid:295692e3-4b56-4b08-b537-575028e2c2ad%22

**Comment by svetlym** [comment]
A čím může být, že se jazyk neindexuje?

Dokument je vyrobený v proarcu, takže se importoval jako NDK mods.

**Comment by honza-rychtar** [comment]
@pavel-stastny nevíš, čím to může být?

**Comment by svetlym** [comment]
Problém se možná netýká jen indexování jazyka, ale třeba i klíčových slov.

Dokument https://digitalniknihovna.mlp.cz/uuid:7af5c720-fb2d-11dc-8962-000d606f5dc6 například zobrazuje pouze jedno klíčové slovo, přestože v MODSu jich má několik:

```
<mods:subject>
  <mods:topic>čp.52 (Mari&aacute;nsk&eacute; hradby 1)</mods:topic>
  <mods:topic>forma: text</mods:topic>
  <mods:topic>Kr&aacute;lovsk&yacute; letohr&aacute;dek</mods:topic>
  <mods:topic>nosič: pap&iacute;r</mods:topic>
  <mods:topic>půdorysy</mods:topic>
  <mods:topic>řezy (architektura)</mods:topic>
  <mods:topic>&uacute;roveň zpracov&aacute;n&iacute;: jednoduch&aacute;</mods:topic>
  <mods:topic>způsob vyd&aacute;v&aacute;n&iacute;: monografie</mods:topic>
  <mods:topic>fotografie (obrazov&eacute; materi&aacute;ly)</mods:topic>
  <mods:topic>pragensia</mods:topic>
  <mods:topic>stati</mods:topic>
</mods:subject>
```

Tento dokument je ale pro změnu importovaný z K3 formátu.

**Comment by honza-rychtar** [comment]
@svetlym To je jiný problém. Klíčová slova v solru jsou, zjistím proč se zobrazuje jen první.

**Comment by svetlym** [comment]
@honza-rychtar: Díky.

Založil jsem na to pro přehlednost novou issue (#272).

**Comment by svetlym** [comment]
S dovolením bych se připomenul s původní otázkou: Čím může být, že se jazyk ve většině případů neindexuje?

**Comment by luckajirku** [comment]
není to stejný problém jako se řešil tady https://github.com/ceskaexpedice/kramerius/issues/436?

**Comment by pavel-stastny** [comment]
> S dovolením bych se připomenul s původní otázkou: Čím může být, že se jazyk ve většině případů neindexuje?

Zdravím. To je otázka na mě.  Podívam se dám sem vědět.

**Comment by pavel-stastny** [comment]
@svetlym  Zkousel jsem si u sebe zmenit monografii tak, aby tam bylo stejne BIBLIO_MODs a predindexovat.  Language se v indexu objevil.  Bylo by mozne zaslat cely titul na otestovani ?

**Comment by svetlym** [comment]
@pavel-stastny: Dokument je neveřejný, poslal jsem FOXML mailem (snad jsem trefil adresu).

**Comment by pavel-stastny** [comment]
Dobrý den, zkoušel jsem u sebe importovat a indexovat originální data.  Po indexaci položku language vidím: 

```
<arr name="language">
   <str>ger</str>
</arr>
```
Muzete zkusit dokument preindexovat ?

**Comment by svetlym** [comment]
> Muzete zkusit dokument preindexovat ?

Vyzkoušel jsem. Po reindexaci jazyk v SOLRU je, viz:

http://kramerius4.mlp.cz/search/api/v5.0/search?q=PID:%22uuid:295692e3-4b56-4b08-b537-575028e2c2ad%22

**Comment by svetlym** [comment]
Jelikož by kompletní přeindexování našeho Kraméria zabralo několik dní a vzhledem k tomu, že to stejně budeme v dohledné době dělat v rámci přechodu na novou verzi jádra, vedení rozhodlo, že s tím zatím počkáme.

Navrhuju tedy tuto issue prozatím odložit. Ozvu se po přechodu na novou verzi jádra, jestli se tím tento problém vyřešil.

**Comment by honza-rychtar** [comment]
@svetlym tohle můžeme zavřít že? Netýkalo se klienta, problém byl v datech, které reindexace opravuje.

**Comment by svetlym** [comment]
Souhlasím. Kdyžtak se ozvu, kdyby se to opakovalo.
