### ISSUE TITLE
Nespolehlivost řazení dle relevance

### ISSUE THREAD

**Issue by BrozekAles** [ceskaexpedice/kramerius-web-client#273]
Hledal jsem výraz "látky na prapory" (použity uvozovky, protože je to termín technicus odpovídající výrazu Fahnenstoffe). V Krameriu MZK mi to nabídne 11 výskytů v Lidových novinách. Když vstoupím do Lid. novin, je výsledků 649, protože na stránce našlo jak výraz prapory, tak látky na šaty. Chci vidět těch 11 relevantních bez prohlížení všech 649 výsledků, a tak dám řadit podle relevance, což nepomáhá. Co s tím?

**Comment by BrozekAles** [comment]
Nespolehlivost podle relevance je i v případě, kdy hledané sousloví nedám do uvozovek. Odzkušováno v DK KNAV a hledán Karel Čapek v časopise Vesmír, najde to 125x
 a při řazení podle relevance nabízí stránky, kde není Karel Čapek, a to
jako 31. záznam: 15.11.1940, 19(3). s. 86, kde je Milič Čapek a Karel Černocký viz
http://www.digitalniknihovna.cz/knav/uuid/uuid:cffa9c56-3c93-4e68-9cf0-0c89412de355
 jako 34. záznam: 15.3.1939, 17(7). s. [180], kde je Čapek, Milič a Karel Křenek
http://www.digitalniknihovna.cz/knav/uuid/uuid:0d74f1c3-278c-449f-a3dc-321af77f803e
(Pokud napíši do uvozovek "Karel Čapek" při hledání přímo ve Vesmíru, stále dává výsledek 125 záznamů, avšak při hledání Karla Čapka v uvozovkách přes celou DK, hlásí to 101 výskytů u Vesmíru, těch správných 101 výskytů se však neseřadí za sebou, ale jsou schovány mezi 125 výskyty). Co s tím?

**Comment by BrozekAles** [comment]
Zdá se, že je to problém pouze klienta DK a ne klienta K. Protože se snažíme, aby uživatelé digitálních Knihoven Kramerius už neužívali klient K, ale klient DK, který byl vypuštěn téměř před rokem (2.4.2020), prosím o urychlené řešení tohoto issue. Díky.

**Comment by honza-rychtar** [comment]
Opraveno.
http://www.digitalniknihovna.cz/mzk/periodical/uuid:bdc405b0-e5f9-11dc-bfb2-000d606f5dc6?fulltext=%22l%C3%A1tky%20na%20prapory%22&accessibility=public
