### ISSUE TITLE
Chyby v abecedním řazení 

### ISSUE THREAD

**Issue by BrozekAles** [ceskaexpedice/kramerius-web-client#274]
O tom, že DK při řazení nehledí na člen Der, die, das  a řadí podle dalšího slova na rozdíl od klienta K4, je zřejmě už napsáno issue. Někdy však DK řadí podle členu jen jedno vydání (!) a druhé vydání ne. SVKUL má zdigitalizován titul Der Schreckenstein: eine Beschreibung und Geschichte der Burg ( z r. 1926 a 1939), v Klientu K4 verze 5.3.9 jsou v titulovém seznamu uvedena obě vydání v https://kramerius.svkul.cz/search/#intro6
zatímco DK v http://www.digitalniknihovna.cz/svkul/search?sort=alphabetical ukáže náhled  vydání z r. 1939 u písmene D a vydání z r. 1926 u písmene S

**Comment by annie-cz** [comment]
Může souviset s #333

**Comment by honza-rychtar** [comment]
Tohle je zrovna problém v datech. Za rozeznání členů kvůli řazení není zodpovědný solr ani indexer.
Na tohle je **nonSort** element jako část názvu (**titleInfo**) v MODS.
V Indexu je pak podle účelu tento element předřazeny před hlavní název (pole pro řazení zahodí, pole pro zobrazení zřetězí).
No a ty dva uvedené dokumenty se liší tím, že u jednoho je pole **nonSort** použité a u druhého není 

**1926**
http://www.digitalniknihovna.cz/svkul/uuid/uuid:6aa1b7b4-1953-4c4a-ba50-8b1b92d004a5
```
    <mods:titleInfo>
      <mods:title>Schreckenstein</mods:title>
      <mods:subTitle>eine Beschreibung und Geschichte der Burg</mods:subTitle>
      <mods:nonSort>Der </mods:nonSort>
    </mods:titleInfo>
```

**1939**
http://www.digitalniknihovna.cz/svkul/uuid/uuid:c2bca4dd-2588-4196-89e7-32ee988a130d
```
    <mods:titleInfo>
      <mods:title>Der Schreckenstein</mods:title>
      <mods:subTitle>eine Beschreibung und Geschichte der Burg</mods:subTitle>
    </mods:titleInfo>
```
