### ISSUE TITLE
Dialog pro výběr stran pro generování pdf/tisk - volba vybrat vše

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#277]
Přepracovaný dialog pro výběr stran u tisku a generování PDF se nám líbí a vítáme jej, viz issues #12  a #50  - nicméně pokud chce uživatel vygenerovat celý dokument (pokud mu to počet stránek dokumentu umožní), je volba shift a označení první a poslední stránky značně neintuitivní (bohužel ne každý uživatel ví, co je to "shift"). Šlo by to prosím vyřešit nějakým tlačítkem typu označit vše, plus tam pro advanced uživatele nechat tuhle volbu?

**Comment by krizovj** [comment]
Souhlasím. Bylo by dobré mít tlačítko označit/odznačit vše taky proto, že uživatel neví, jaký limit má konkrétní knihovna nastavený. Takže když si označím 50 stran, a pak mi Kramerius řekne, že můžu jen dvacet, tak je musím po jedné odznačovat... 

S tím souvisí také to, že by ten limit mohl být někde uvedený ještě dřív než ty stránky označím.

**Comment by zabak** [comment]
Navíc by nemělo být možné označit víc stran než je limit. Dokonce by bylo hezké při zatržení jedné stránky mít možnost označit tolik stránek kolik je limit. Jinými slovy: označit vše nemá smysl, pokud pak s tím "vším" nejde nic udělat. Raději tam mít něco jako "označit 50 stran počínaje touto stránkou"...

**Comment by honza-rychtar** [comment]
Určitě, tohle budeme dál doplňovat.
Ono by bylo jednoduché přidat tam 20 tlačítek a kopu textu, popisků a upozorění.
Záměr byl takový udělat to co nejvíce minimalisticky a pak přidávat jen ty opravdu nutné prvky, které při používání chybí.

**Comment by jahhoo** [comment]
Určitě by nebylo špatné, kdyby byl vidět limit stran a počet označených stran.

Např. "Vybráno: 21 z 60 stran"

**Comment by honza-rychtar** [comment]
Přidal jsem informaci o počtu vybraných stran, limitu a možnost označit/odznačit vše.
Možno vyzkoušet na http://www.digitalniknihovna.cz/
<img width="746" alt="Screenshot 2020-08-03 14 32 45" src="https://user-images.githubusercontent.com/1178142/89205986-e3287680-d5b8-11ea-9e03-bda7f18072cf.png">
