### ISSUE TITLE
Chybí tlačítko pro dvoustránkový režim

### ISSUE THREAD

**Issue by vjirousek** [ceskaexpedice/kramerius-web-client#278]
U některých titulů se bez zjevné příčiny nenabízí dvoustránkový režim. Je to chyba nebo vlastnost? :) Měl jsem dojem že už se to v minulosti řešilo, ale ticket jsem nenašel.

Tady jeden příklad:
http://www.digitalniknihovna.cz/mzk/uuid/uuid:8d68e780-f4f8-11e9-8f23-5ef3fc9bb22f

**Comment by honza-rychtar** [comment]
Tohle se pokud vím neřešilo.

Díval jsem se na to a je to způsobeno tím, že heurestika rohodující o tom, jestli bude stránka vlevo, vpravo, nebo samostatně, považuje obálky za stránky, které jsou na začátku - ona a vše před ní je samostatně.
Funguje to tak, že podle typu stran se najde poslední samostatná strana na začátku, první samostatná strana na konci a strany mezi tím se rozřadí vlevo/vpravo jak to vyjde ještě s možnou korekci přes titulní stranu, která je vždy vpravo.

**Stručně. Dvoustránkový režim teď neumožnujě mít obálky na konci.**

Opravím to tak, že pokud je obálka na konci (nebo za ní následují už jen další obálky nebo desky), tak neovlivní dvoustránkové zobrazení předcházejících stránek.

**Comment by honza-rychtar** [comment]
Opraveno.
