### ISSUE TITLE
Řazení dle počtu výskytů

### ISSUE THREAD

**Issue by ochrpa** [ceskaexpedice/kramerius-web-client#279]
Zdravím,

mám návrh na vylepšení: Řazení dle počtu výskytů

Aktuálně je možné výsledky řadit:
- Podle relevance
- Abecedně
- Nově přidané
- Od nejnovějších
- Od nejstarších

Bylo by možné přidat volbu "Podle počtu výskytů"?

Např. u http://www.digitalniknihovna.cz/mzk/search?q=Sm%C3%ADchov&sort=relevance

Předem díky za vyjádření.

**Comment by zabak** [comment]
Spíš se přikláním k tomu, abychom víc pracovali s relevancí přímo v solru. Počet výskytů je totiž i jedno z důležitých kritérií, které se používají při řazení podle relevance. Na portálu knihovny.cz s tím takto pracujeme. Jaký je use-case toho řazení dle počtu výsledků? Kdy je to potřeba? Reálně by to způsobilo, že na začátku seznamu budou u běžných slov velké noviny, pak menší periodika a na konci monografie.

**Comment by pavelkocourek** [comment]
Četnost je jedním z parametrů, který je využívá v hodnocení relevance, obvykle v nějakém vztahu k velikosti dokumentu. K tomu platí, co napsal PetrŽ o typech dokumentů.
Samotný počet výskytů je nepoužitelný - víceslovné dotazy, následná interakce s využitím faset apod.
Co bylo prosím očekávaným výsledkem u příkladu s dotazem Smíchov?

**Comment by honza-rychtar** [comment]
Tohle nebudeme dělat.
