### ISSUE TITLE
Vícedílná monografie - partName jednotlivých dílů

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#280]
Mám dotaz na vícedílnou monografii, u které se nám nezobrazují názvy jednotlivých částí. Čísla částí nejsou vyplněna, takže je správně, že tam nic není, ale partName vyplněný je:
![image](https://user-images.githubusercontent.com/21309201/70521261-312ace80-1b3f-11ea-82f0-2e48db086910.png)

https://kramerius.lib.cas.cz/uuid/uuid:d415dd58-a621-4c45-b6c4-dc64d732ada5

Zkoušeli jsme titul samozřejmě reindexovat a jeden z dílů smazat a znovu nahrát, ale pořád se nezobrazují. 

U jiné vícedílné monografie jsou názvy normálně vidět:
https://kramerius.lib.cas.cz/uuid/uuid:df7687db-d7a6-4398-b1e4-6cfc2bbea041 

Nevíte, čím by to mohlo být? 
Díky

**Comment by honza-rychtar** [comment]
@pavel-stastny Nevíš proč se u monographunit nepropíše partName do indexu?
MODS:
https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:21b1c921-030d-4fd7-8a32-016c64ae71db/streams/BIBLIO_MODS
V titleInfo -> partName je **Anno 163**
SOLR: 
https://kramerius.lib.cas.cz/search/api/v5.0/search?q=PID:%22uuid:21b1c921-030d-4fd7-8a32-016c64ae71db%22
V detail je **##**
Mělo by tam být **##Anno 163**

**Comment by pavel-stastny** [comment]
@honza-rychtar   Klasická odpověď.  Nevím, podívám se a dám vědět.  :-)

**Comment by honza-rychtar** [comment]
Vyřešeno v K7.
