### ISSUE TITLE
U hudebniny se nezobrazují všechny hlasy (přílohy)

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#281]
Narazili jsme na hudebninu, u které se ve starém klientovi zobrazují oba hlasy: http://kramerius4.mlp.cz/search/i.jsp?pid=uuid:f9342ef2-9668-4111-878b-78b19afbe65c ale v novém jen jeden: http://digitalniknihovna.mlp.cz/uuid:f9342ef2-9668-4111-878b-78b19afbe65c.

Pravděpodobně to souvisí s issue #262 případně #177, ale jde o hudebninu, tak jsem pro přehlednost založil novou issue.

**Comment by honza-rychtar** [comment]
Opraveno.
