### ISSUE TITLE
Textový přepis stránky - pomalé načítání

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#282]
V NK máme problém s načítáním textového přepisu. Načítání trvá dlouho nebo se přepis vůbec nezobrazí. 

Je nutné získávat citace přes stránku citace.kramerius.cloud ? Nešlo by to řešit přes Kramerius api?

**Comment by honza-rychtar** [comment]
Nemáte úplně v pořádku SSL certifikát pro doménu kramerius5.nkp.cz
Výstup z SSL analyzátoru
![Screenshot 2019-12-12 10 13 41](https://user-images.githubusercontent.com/1178142/70698905-9b22af80-1cc8-11ea-8121-d9a9e6c92257.png)

Některé prohlížeče a webové služby s tím můžou mít problém.
U citačního serveru jsem zrušil SSL validaci, takže teď už by to mělo fungovat.

Každopádně doporučuju ten problém s certifikátem vyřešit.

**Comment by JanMeritus** [comment]
Ahoj, skus to checknut teraz.

**Comment by honza-rychtar** [comment]
Teď je to ok.
