### ISSUE TITLE
Viacnasobny donator + popis projektov v Klientovi

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius-web-client#284]
Prosim o overenie a pripadne doplnenie do klienta Krameria zobrazenie viacnasobneho donatora, ak je pritomny. Eg. Norske fondy + K3TOK5. V ramci upravy by bolo mozne zadavat samostatne informacne stranky s popisom donatorov a prip. odkazmi na ich projekti.

Case: niekedy stranky donatorov po urcitom case, na ktore sa malo odkazovat uz nefunguju. Administrator by pre uzivatela mal mat moznost dostat prvotny popis projektu na strankach klienta.

**Comment by honza-rychtar** [comment]
Vyžaduje nový index
<img width="284" alt="Snímek obrazovky 2020-09-17 v 20 33 44" src="https://user-images.githubusercontent.com/1178142/93512797-25b5d080-f925-11ea-9ee8-f8d67d4bab3b.png">

**Comment by zabak** [comment]
zavírám bez kontroly, v případě potřeby prosím o založení nového issue.
