### ISSUE TITLE
Pokročilé vyhledávání - překlep Klcové slovo

### ISSUE THREAD

**Issue by KarolinaKostalova** [ceskaexpedice/kramerius-web-client#288]
V rozbalovací nabídce Pokročilého vyhledávání je překlep - **klčové** místo **klíčové**.
![image](https://user-images.githubusercontent.com/19569795/71362477-77981880-2596-11ea-95c6-0536204c7474.png)

U nás už je opraveno, ale chyba je i v původním klientovi. Můžu poprosit o opravu i tam?
Díky
KK

**Comment by honza-rychtar** [comment]
Opraveno
