### ISSUE TITLE
v1.4.0 - nefunkční konfigurace

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#289]
Zdravím,

nainstaloval jsem poslední verzi klienta 1.4.0. Nastavil jsem propertu `login: false`, protože u dané instance nechci povolit přihlašování, nicméně položka v menu nezmizela a přihlašovací formulář je pořád dostupný (zkoušeno v různých prohlížečích, promazaná keš i anonymní mód).

MD

**Comment by krizovj** [comment]
Taky jsem si všimla, že v té nové verzi se nemůžu dostat na metadata.

**Comment by honza-rychtar** [comment]
@mduda100871 property `login` se nepoužívá a není ani uvedená v dokumentaci https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta
Položka **Přihlásit** v menu se zobrazí ve dvou případech.

1. V konfiguraci je `dnnt: true`
Přihlášení se dělá vůči Krameriovi, který umí DNNT 
2. V konfiguraci je `cloudEnabled: true` 
_(zatím nezdokumentováno)_
Přihlášení se dělá vůči Správě uživatelů

Jedno z toho musí být nastaveno na `true`

@krizovj Zítra vydám novou verzi, kde budou ta kompletní formátována metadata dostupná všem, jak jsme se domluvili na poslední schůzce.

**Comment by mduda100871** [comment]
Properta `login: true` je/byla obsažena v souboru `globals.js` v distribučním balíčku klienta, který jsem stáhl. Z jejího názvu jsem vyvodil, že se týká přihlašování. Nastavil jsem tedy `cloudEnabled: false` a přihlášení zmizelo z nabídky.

MD

**Comment by mduda100871** [comment]
Zdravím,

nasadili jsme, zatím na testovací server, poslední verzi klienta v1.5.0 a máme s ním trochu problém. 

U předchozích verzí bylo možné se přihlásit v jádře a ustavená session byla pak platná i v klientovi => šlo se dívat i na neveřejný obsah a tak provádět kontroly i v klientovi. S touto novou verzí klienta to již nefunguje, což je celkem nepříjemné.

Nově implementované přihlašovaní v klientovi (dnnt, cloud) podle všeho nepodporuje tedy lokální účty.

Co s tím? Bude se implementovat přihlašování v klientovi proti lokálním účtům v jádře?

Díky, MD
