### ISSUE TITLE
Prechod na predchozi/dalsi stranku

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#29]
Prechod na predchozi/dalsi stranku se dela tlacitky v ovladacich prvcich dole v prohlizecce.
Dalsi moznosti je vyjmout je z ovladacich prvku a mit je samostatne po stranach prohzlizecky (jako je to v Digitalni knihovne).

Tohle je otevreni k diskuzi.

**Comment by krizovj** [comment]
Mě se to zdá určitě lepší, mít je po stranách jako je to v Digitální knihovně. 

A taky by se mi zdálo lepší, kdyby byl panel s ovládacími prvky průsvitný, jako v Digitální knihovně.

**Comment by krizovj** [comment]
Bylo by možné, aby se dalo mezi stránkami přecházet i pomocí šipek na klávesnici? Je to tak i Digitální knihovně.

**Comment by honza-rychtar** [comment]
> Bylo by možné, aby se dalo mezi stránkami přecházet i pomocí šipek na klávesnici? Je to tak i Digitální knihovně.

Pridam, #41

**Comment by zabak** [comment]
Toto by mělo taky jít do hlasování. Osobně jsem pro ovládací tlačítka po stranách.
