### ISSUE TITLE
Špatné zobrazení PDF článků

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#290]
Dobrý den,
na testovacím serveru máme nasazenou poslední verzi klienta (asi v1.5.0?) a špatně se nám zobrazují (resp. lépe řečeno nezobrazují) články v PDF. 

Nefunguje to u private, ani public periodik. Chybová hláška je "Stránka nebyla nalezena. Přejděte na úvodní stránku. 404." Posílám náhled, protože nevím jak popsat, že se celý horní řádek zobrazuje 2x a je jakoby vnořený na místě, kde bývala čtečka PDF :) 
![obrazek](https://user-images.githubusercontent.com/31240271/72530211-2c101c00-386f-11ea-9dc2-e9cfbd2503db.png)

Když kliknu na "Přejděte na úvodní stránku", stane se toto:
![obrazek](https://user-images.githubusercontent.com/31240271/72530387-91fca380-386f-11ea-8050-712d388f4658.png)

A spíše pro pobavení, když zopakuji dotaz (vyhledávám konkrétní číslo časopisu), vznikne:
![obrazek](https://user-images.githubusercontent.com/31240271/72530521-d38d4e80-386f-11ea-9336-218adc1ce4ed.png)

Jde s tím něco udělat? Je to docela vtipné, ale pro práci jaksi nepohodlné :D 
Děkuji
Markéta T.

**Comment by honza-rychtar** [comment]
Takto by se to určitě nemělo chovat.
Tady je verze 1.5.0 a stejný dokument http://dk.kramerius.org/knav/uuid/uuid:367b3a81-67e6-421b-94a1-578ebd1a0a86
Děje se vám to tady taky?

**Comment by tumovam** [comment]
V tom odkazu to funguje správně. Je tedy chyba na naší straně? Myslím totiž, že máme nasazenou právě tu verzi 1.5.0. Díky moc, M.

**Comment by honza-rychtar** [comment]
Zkuste to ještě otevřít  v jiném prohlížeči nebo promazat cache prohlížeče.
Je ta testovací verze veřejně dostupná?

**Comment by tumovam** [comment]
Promazáno. Vyzkoušeno v Chromu, Firefoxu a Opeře a vidím to pořád chybně.
Nejsem si jistá: https://new-client-test.lib.cas.cz/view/uuid:41c450b3-4e90-4183-86ae-dd73eefef348?article=uuid:367b3a81-67e6-421b-94a1-578ebd1a0a86

**Comment by tumovam** [comment]
Tato chyba se znovu neobjevila. Navrhuji zavřít.
