### ISSUE TITLE
Bocni panely a jak na ne

### ISSUE THREAD

**Issue by mtravnicek** [ceskaexpedice/kramerius-web-client#292]
_Kdyz jsem narazil na commit https://github.com/ceskaexpedice/kramerius-web-client/commit/041eabfb7fc9d746b9666dfd297ea465a8ce70d8  "Oprava…… postranich panelu", vypadalo to, ze to je opraveno, ale neni... viz take #44_
U bocnich panelu je pocitam uz nejakou dobu problem, ktery se projevuje u praveho panelu: pokud se panel schova, tak se vlastne neschova a porad tam je, jen je mimo obrazovku, potom je krom toho, ze to ukazuje posuvnou listu dole, ktera naznacuje, ze je neco napravo, tak pokud prochazim stranky pres thumbnaily pomoci tlacitka sipky doprava na klavesnici, tak pak podle toho, jak dlouho to podrzim, ujizdi mi obrazovka doprava....  tato vec vznika na zaklade jednoduche CSS sablony v ramci styles.css
``@media only screen and (max-width: 992px) {
    app-root main app-book .app-book-wrapper app-metadata.app-book-metadata.app-panel-mobile-hidden {
        **margin-right:-300px;**
        overflow: hidden
    }``
pokud se klikne na tlacitko schovat pravy panel/metadata - jednoduse se prepne sablona CSS pro tento panel z margin-right:0 na margin-right:-300px - tedy minus 300 pixelu a dava pak smysl, ze to skutecne nezmizelo.... 
https://stackoverflow.com/questions/12801487/hiding-the-sidebar-marginright-display-css-bug-with-javascript
https://stackoverflow.com/questions/8231282/hiding-elements-with-negative-margin
_Libi se mi a dava smysl komentar zacinajici na:_ 
```Either you have been dreaming or you have become a victim of "cargo cult coding" (viz google).```
Spravne je tedy treba pouzit misto zaporneho margin neco jako "display: none" v ramci CSS.
tim se sice instantne zrusi cool animace, co tam ted je (ale je tam vubec potreba?), ale panel se skutecne skryje.  Co tam ale dal strasi jsou tlacitka pro skryti a zobrazeni tech bocnich panelu.
Zejmena to prave tlacitko tam prekrvyva/blokuje scrollovaci listu od PDF prohlizece, coz znemoznuje ji pouzivat v miste kde je toto tlacitko...nebo pokud se skryje jak levy a pravy panel, tak tam na obrazovce zustavi tyto nehezke "capliky". Videl bych to asi tak, ze by se tato tlacitka presunula na horni listu, ktera tam je trvale, pricemz by se zrusily nebo posunuly stavajici tlacitka - viz obrazek (tlacitko ZPET je celkem zbytecne, to je v kazdem prohlizeci)
nebo to nejak udelat aby se to zasouvalo-vysouvalo horizontalne, teda nejake tlacitko, vysuvny panel nad, pod urovni tlacitek jako Tisk, Download atd... 

![RasplePanely](https://user-images.githubusercontent.com/23079541/72672279-e06c9680-3a57-11ea-841d-933329e97df8.png)

**Comment by honza-rychtar** [comment]
@zabak Tohle můžeme zavřít ne?

**Comment by zabak** [comment]
Popsané chování se mi nepodařilo reprodukovat, takže asi vyřešeno v minulých verzích.
