### ISSUE TITLE
DNNT: zámečky

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#295]
U dokumentů označených DNNT je při vyhledávání zobrazen oranžový zámeček. Při rozkliknutí dokumentu se dále zobrazuje zámeček pouze černý (výběr roku, na náhledech)

Příkladám zprávu od p. Matušíka:
U vybraného dokumentu se sice otevře další obrazovka, ale pole k zobrazení vybrané stránky je prázdné, i když se vlevo zobrazují stránky (bez ohledu na to, zda je na náhledech zámeček jedné či druhé barvy, nebo tam vůbec není).

**Comment by honza-rychtar** [comment]
Řešme tady #343
