### ISSUE TITLE
Neúnosně dlouhé načítání titulu

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#296]
Dobrý den,

titul http://www.digitalniknihovna.cz/mlp/view/uuid:eb4ae190-63b0-11dd-83c1-000d606f5dc6 se v novém klientovi načítá několik minut, přitom ve starém rozhraní se načte mnohem rychleji: http://kramerius4.mlp.cz/search/handle/uuid:eb4ae190-63b0-11dd-83c1-000d606f5dc6

V konzoli nejsou žádné chybové hlášky a ani to nevypadá, že by se čekalo na stahování dat.

**Comment by honza-rychtar** [comment]
Vypadá to, že máte něco s Krameriem. Vše se načítá strašně pomalu nebo vůbec.

**Comment by svetlym** [comment]
Náhodně jsem proklikal zhruba 20 titulů a všechno se mi načetlo okamžitě. Aha, tak ne, tenhle se taky načítá dlouho: https://digitalniknihovna.mlp.cz/uuid:8fdbc7e0-e315-11e2-b58a-0030487be43a. Rozhodně to ale nedělají všechny tituly.

**Comment by svetlym** [comment]
Přikládám log tomcatu:


[catalina.out.txt](https://github.com/ceskaexpedice/kramerius-web-client/files/4103491/catalina.out.txt)

**Comment by svetlym** [comment]
Udělal jsem ještě jeden test s druhým zmíněným titulem čerstvě po restartu Kraméria, abych měl čistý log.

Ve starém klientu se načte okamžitě:  https://digitalniknihovna.mlp.cz/uuid:8fdbc7e0-e315-11e2-b58a-0030487be43a, v novém to trvá přes minutu: https://digitalniknihovna.mlp.cz/uuid:8fdbc7e0-e315-11e2-b58a-0030487be43a. V logu tomcatu nejsou žádné errory ani warningy:
[catalina.out.txt](https://github.com/ceskaexpedice/kramerius-web-client/files/4116626/catalina.out.txt)

**Comment by zabak** [comment]
Teď se to načítá rychle, zavírám.
