### ISSUE TITLE
Přenos vyhledávaného dotazu do jiné knihovny (www.digitalniknihovna.cz)

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#298]

**Comment by zabak** [comment]
Co kdyby bylo možné změnit knihovnu i na stránce s výsledky vyhledávání? Tj. 
![image](https://user-images.githubusercontent.com/811537/73465390-9dc48b80-4380-11ea-9575-611dfd9e6efe.png)

**Comment by honza-rychtar** [comment]
Řešeno #341
