### ISSUE TITLE
Noviny a časopisy - zobrazení - dotaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#3]
Podle čeho se určuje, jak bude periodikum zobrazeno? Některá periodika se zobrazují s náhledy obálek ročníků a čísel (např časopis "Host") a některá se zobrazují jako kalendář (například Třeboňské listy). Čím je to rozdílné zobrazení určeno?

**Comment by honza-rychtar** [comment]
Seznam rocniku:
a) Pokud maji vsechny rocniky rok ve tvaru yyyy, tak se zobrazi jako seznam roku. V seznamu se zobrazi i roky, ktere nejsou k dispozici (rozsah se spocita z jednotlivych rocniku a z dat vydani z metadat periodika). Zaroven je mozne se prepnout do zobrazeni mrizky s nahledy obalek.
b) Pokud nektery z rocniku nema rok ve tvaru yyyy, tak se pouzije zobrazeni mrizky s nahledy a neni mozne se prepnout do zobrazeni pres seznam roku.

Seznam cisel:
a) Pokud ma rocnik rok ve tveru yyyy a zaroven vsechna cisla maji datum vydani ve tvaru dd.mm.yyyy, tak se pouzije jako vychozi zobrazeni kalendare a je mozne se prepnout do zobrazeni mrizky s nahledy.
b) Pokud ma rocnik rok ve tvaru yyyy a existuje nejake cislo, ktere nema datum vydani ve tvaru dd.mm.yyyy, tak se jako vychozi zobrazeni pouzije mrizka s nahledy a je mozne se prepnout do zobrazeni kalendare.
c) Pokud rocnik nema rok ve tvaru yyyy, tak se pouzije zobrazeni mzrizky s nahledy a neni mozne se prepnout do zobrazeni kalendare.

Takze celkove se preferuje seznam roku a kalendare, ale pouze pokud jsou na to vhodna data.
Konkretne u casopisu Host se nepouzije zobrazeni kalendare, protoze tam jsou rocniky jako 1926-1927. Kalendarum tady nejde pridarit rok. A i kdyby se to interpretovalo jako dva roky, tak by musely byt kalendare v tomto pripade pro 24 mesicu a vzhledem k tomu, ze je tam jen 10 cisel, tak by to stejne nemelo smyl.

**Comment by vjirousek** [comment]
Nevím jestli tahle logika není pro uživatele málo předvídatelná a chování klienta v tomto matoucí. Při procházení jednotlivých ročníků se mi pokaždé nabídne jiné obrazení například na základě toho, že jsou u některých ročníků samostatně zpracovaná čísla s obálkami, obsahy ročníků, nebo prostě proto že se měnilo vydávání ročníků mezi kalendářními roky a školními roky. Preferoval bych defaultní nastavení na zobrazení mřížky a zobrazení kalendáře až jako volitelné. Na úrovni titulu myslím kalendář žádné zvláštní výhody oproti mřížce neposkytuje a na úrovni ročníku vidím výhodu kalendáře až u denního tisku. To je ale samozřejmě jen názor, o chybu se nejedná :)

Hodně nepřívětivé je ale to, že při použití tlačítka zpět (zatím ověřeno zpět v prohlížeči, v digitální knihovně ale ověřeno i tlačítko v klientovi) se mi přehled čísel/ročníků zobrazí zpět v defaultní podobě a nikoliv v podobě ve které jsem si je naposledy nastavil.

**Comment by honza-rychtar** [comment]
@vjirousek 
**Seznam rocniku**
Tady by asi molo byt vychozi zobrazeni pres mrizku. Zobrazeni pres roky ma tu vyhodu, ze to ukazuje kdy se periodiku vydavalo a ne to, ktere konkretni roky ma knihovna digitalizovane. Roky se pocitaji i z data vydani, takze tam potom jdou videt i roky (neaktivni karty), ktere knihovna nema digitalizovane.

**Seznam cisel**
Tady bych uprednostnoval zobrazeni kalendarem kdykoli je to mozne. U denniku je to mnohem mnohem prehlednejsi nez zobrazeni stovek _"stejnych"_ nahledu.
A nekonzistentni zobrazeni mi tady naopak dava smysl. Mesicniky, ktere nemaji vyplneno plne datum, se zobrazi jako dvanact obalek a dennik jako kalendar.

Pokud si uzivatel zobrazeni zmeni, pak se mu bude dal jako vychozi nabizet toto zmenene zobrazeni (pokud je dostupne), viz #17

**Comment by honza-rychtar** [comment]
> Hodně nepřívětivé je ale to, že při použití tlačítka zpět (zatím ověřeno zpět v prohlížeči, v digitální knihovně ale ověřeno i tlačítko v klientovi) se mi přehled čísel/ročníků zobrazí zpět v defaultní podobě a nikoliv v podobě ve které jsem si je naposledy nastavil.

Souhlasim, vyresi #17

**Comment by krizovj** [comment]
Takže pokud časopis vychází pouze jednou ročně a v metadatech jsou u všech jeho dosavadních čísel data vydání zapsána ve formátu dd.mm.yyyy, tak se bude zobrazovat primárně kalendář?

**Comment by krizovj** [comment]
Ještě bych měla dotaz ohledně toho zobrazování i těch nedostupných ročníků. Bere to v úvahu, že v některých letech nemuselo periodikum vycházet? Dívá se i na číslování ročníků nebo jen na roky vydání?

**Comment by honza-rychtar** [comment]
> Takže pokud časopis vychází pouze jednou ročně a v metadatech jsou u všech jeho dosavadních čísel data vydání zapsána ve formátu dd.mm.yyyy, tak se bude zobrazovat primárně kalendář?

Ano. 
Muzem to upravit tak, ze kalendar se pouzije az pri 13 polozek a vice.

> Ještě bych měla dotaz ohledně toho zobrazování i těch nedostupných ročníků. Bere to v úvahu, že v některých letech nemuselo periodikum vycházet? Dívá se i na číslování ročníků nebo jen na roky vydání?

Zobrazeni rocniku pres roky je bez mezer - i kdyz se nekde uprostred periodikum nevydavalo.

**Comment by honza-rychtar** [comment]
Diskuze se presunula sem #46
