### ISSUE TITLE
Kompletní metadatový záznam

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#30]
Není to tu zadané jako issue, ale myslím, že se o tom někde už diskutovalo. Někde v pravém sloupci u metadat by měla být funkce pro zobrazení kompletního metadataového záznamu v MODS.

**Comment by pavelkocourek** [comment]
Probereme na schůzce .. funkce by mohla patřit do admin rozhraní

**Comment by pavelkocourek** [comment]
Navrhujeme, aby funkcionalita zobrazení datových objektů byla dostupná v Admin rozhraní. To zahrnuje MODS, DC, OCR, ALTO ... atd

**Comment by pavelkocourek** [comment]
Schůzka VT 14.5. : Do klienta bude doplněno zobrazení MODS formátu (obdoba K4 klienta)

**Comment by honza-rychtar** [comment]
Hotovo. Je mozne zobrazit vsude, kde je panel s metadaty - pres tlacitko <> (v panelu s metadaty vedle sdileni) se zobrazi dialog s vypisem MODS pro vsechny urovne, ktere klinet pro prave otevreny dokument pouziva.
Takze napr. pro clanek v cisle periodika (http://knav.kramerius.rychtar.cloud/view/uuid:d118a57e-8d42-4744-9b2b-e76484f4df16?article=uuid:14c1eeac-5a52-4515-90fa-f11718bd4114) se v dialogu da prepinat mezi MODSem periodika, rocniku, cisla a clanku.
