### ISSUE TITLE
Při dotazech na ImageProperties.xml není respektováno přesměrování. 

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius-web-client#303]
Dobrý den,
rád bych poprosil o radu. Právě řešíme aktualizaci klienta krameria a narazili jsme na problém při přechodu mezi verzemi 1.1 a 1.2 (u všech dalších verzí je stejný problém). 

Aktuálně máme krameria a jeho komponenty vedeny přes apache, co funguje jako proxy kdy komunikace z vnějšku jde přes https ale jednotlivé komponenty na tomcatu mezi sebou používají http. Což ale také způsobuje že v api mají handle a odkazy na čtečku zoomify generovány odkazy s http.

Na verzi 1.1 nám normálně fungovalo že se klient sice nejprve zkusil dotázat přes nezabezpečené připojení ale byl apachem přesměrován a obrázky normálně načetl už zabezpečeně.
```
[dobiasj@pc812 ~]$ curl -I http://kramerius.techlib.cz/search/zoomify/uuid:ce27d729-9eca-11e8-8c68-001b63bd97ba/ImageProperties.xml
HTTP/1.1 301 Moved Permanently
Date: Thu, 06 Feb 2020 15:30:58 GMT
Server: Apache/2.2.15 (Red Hat)
Location: https://kramerius.techlib.cz/search/zoomify/uuid:ce27d729-9eca-11e8-8c68-001b63bd97ba/ImageProperties.xml
Connection: close
Content-Type: text/html; charset=iso-8859-1
```

Když to ale zkouším v nových verzích tak potom co si klient stáhne info z API tak se i přes stejnou odpověď stejně dotáže přes http a prohlížeč pak ImageProperties.xml ze Zoomify zablokuje kvůli mixed contentu. Když ochranu vypnu tak se stránka normálně načte. Kdyžtak je možno otestovat tady: https://kramerius.techlib.cz/kramerius-web-client15/uuid/uuid:ce27d729-9eca-11e8-8c68-001b63bd97ba

Díval jsem se na rozdíly mezi verzemi a podle d06e1ae se měnil modul pro HTTP. Jestli správně chápu tak se asi děje to, že se uloží do cache původní request s http  a ten je potom použit?

Můžeme to nějak řešit přes webserver nebo budeme muset přejít na https v tomcatu a spol.?

**Comment by jdobiasovsky** [comment]
Jinak configuration.properties máme nastavené 
```
#core access
k4.host=http://localhost:8080/search
#api endpoint
api.point=http://localhost:8080/search/api/v5.0
```

A globals.js:
```
var APP_GLOBAL = {
  share_url: "https://kramerius.techlib.cz/kramerius-web-client/uuid/${UUID}",
  ga: 'UA-2503184-21',
  enablePeriodicalVolumesYearsLayout: true,
  enablePeriodicalIsssuesCalendarLayout: true,
  defaultPeriodicalVolumesLayout: "years",
  defaultPeriodicalIssuesLayout: "years",
  publicFilterDefault: false,
  dnnt: false,
  bigHomeLogo: true,
  hideHomeTitle: true,
  advancedSearch: false,
  krameriusList: [
    {title: 'Národní technická knihovna',
     code: 'NTK',
     logo: 'https://www.techlib.cz/files/download/id/80515/logo-1-png.png',
     url: 'https://kramerius.techlib.cz',
     richCollections: true,
     joinedDoctypes: true,
     lemmatization: false,
     iiif: false,
     customRightMessage: true,
     doctypes: ['monograph', 'periodical', 'map', 'graphic', 'archive', 'manuscript', 'soundrecording', 'sheetmusic'],
     filters: ['accessibility', 'doctypes', 'authors', 'keywords', 'geonames', 'collections', 'locations', 'languages']
    }]
}
```

Je dost možné že jsem jenom něco přehlédnul

**Comment by honza-rychtar** [comment]
Problém v Krameriovi běžícím na http a přes proxy ven na https je v tom, že Kramerius API běžící na https vrací url na zdroje zpět na sebe, ale na http.
Konkrétně https://kramerius.techlib.cz/search/api/v5.0/item/uuid:ce27d727-9eca-11e8-8c68-001b63bd97ba
URL pro zoomify a iiif.

Nejrychlejší řešení je přidat do hlavičky v index.html následující řádek.
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`
Prohlížeč pak bude sám všechny http překlápět na https. 
Pozor, nefunguje v IE.

Klient si teď bere ty odkazy na zoomify a iiif podle toho, co mu vrací API. To ale přináší více škody než užitku, takže to předělám, aby klient z API jen zjistil, který zdroj má použít, ale url si zkonstruuje sám - url pro JPEG/Zoomify/IIIF by mělo mít/má pevně danou strukturu.
Takže pokud bude API na https, pak i odkaz na zoomify/iiif.

Budu dneska (11.2.2020) vydávat novou verzi klienta, kde už bude změna zahrnuta a pak by vám to mělo fungovat i bez zásahu do index.html.

Ale i tak tam můžou být další problémy, když běží Kramerius na různých protokolech.
Např. url pro náhledy obrázku https://kramerius.techlib.cz/search/api/v5.0/item/uuid:ce27d727-9eca-11e8-8c68-001b63bd97ba/thumb
se přesměruje na http.
Tohle zatím prohlížeč vyhodnotí jen jako warning, ale v budoucnu to může zakázat taky.

**Comment by jdobiasovsky** [comment]
Super, tak my počkáme na release a otestuju.

**Comment by honza-rychtar** [comment]
Ok, vyřešeno konstrukcí url na klientovi. 
https://github.com/ceskaexpedice/kramerius-web-client/releases/tag/v1.5.2
