### ISSUE TITLE
U některých titulů se nezobrazují strany (problém s IIIF?)

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius-web-client#304]
V novém klientovi se nezobrazují strany: https://digitalniknihovna.mlp.cz/uuid:9DCE4BD0-8973-11DD-9B83-0030487BE43A

Ve starém ano: http://kramerius4.mlp.cz/search/handle/uuid:C27C6A30-8977-11DD-B5D5-0030487BE43A

Předpokládám, že jde o problém, o kterém jsme mluvili na poslední vývojové schůzce, tedy že u některých titulů imageserver přes IIIF nevrací požadovaná data. Jelikož jsem na to nenašel issue a zrovna nám to přišlo jako report od knihovníků, tak ji zakládám.

Používáme dockerovou instalaci imageserveru, kterou vyrobil Martin Rumánek.

**Comment by honza-rychtar** [comment]
Problém je v tom, že Kramerius při dotazu na IIIF resource používá dost striktní validaci UUID.
Pokud není UUID validní, pak vrátí 404.
To nedává smysl, když se to jinde nekontroluje.

V klientovi jsem to změnil tak, aby se v případech kdy IIIF vrátí 404, použil Zoomify.

Takže např.
Nevalidní UUID -> IIIF 404 -> Prohlížečka použije Zoomify
http://www.digitalniknihovna.cz/mlp/uuid/uuid:523CD3E0-C647-11DF-A27D-0030487BE43A
Validní UUID -> IIIF OK -> Prohlížečka použije IIIF
http://www.digitalniknihovna.cz/mlp/uuid/uuid:f355be26-fdb3-465c-b6ad-1c2d0a450281

Validaci UUID pro IIIF z Krameria odstraníme.

**Comment by svetlym** [comment]
Nevalidnost UUID je, předpokládám, způsobena velkými písmeny?

**Comment by honza-rychtar** [comment]
@svetlym Ano.

**Comment by svetlym** [comment]
UUID ve starém formátu (s velkými písmeny) bych se nejraději zbavil, ale přestanou nám pak fungovat staré odkazy, takže to budeme ještě muset zvážit. Možná by na to mohlo pomoci přepisovací pravidlo v Apachi. A bude to taky znamenat přeimportovat hromadu dokumentů, takže to určitě nebude hned.

Každopádně děkuju za workaround, nasadil jsem novou verzi klienta a funguje to.
