### ISSUE TITLE
V novém klientu se nevyhledají některé názvy, které se v původním rozhraní vyhledají 

### ISSUE THREAD

**Issue by helena-oks** [ceskaexpedice/kramerius-web-client#305]
Některé dokumenty se v původním rozhraní vyhledají, v novém klientu nikoli (ani v NKP, ani v MZK, jsou v obou krameriích). Narazila jsem na to náhodně při prověřování údajů z registru digitalizace a vyskytlo se to víckrát.
 
1/ Dotaz "Liber viaticus" 

http://www.digitalniknihovna.cz/nkp/periodical/uuid:b8c4e130-3078-11e9-b81e-005056827e52

2/ Dotaz "kristus a antikrist" nebo "vzkříšení bohové" 

www.digitalniknihovna.cz/mzk/view/uuid:3e53fd80-c1d7-11e6-92d3-005056827e51

**Comment by honza-rychtar** [comment]
Nemáte zaškrtnutý filtr "Pouze veřejné"?
V minulé verzi se měnilo chování našeptávače, že teď respektuje vybrané filtry.
Takže pokud máte zaškrtnutý filtr "Pouze veřejné", pak hledaný dotaz nenabízí ani našeptávač.
S vypnutým filtrem se oba dotazy našeptají i vyhledají.

**Comment by helena-oks** [comment]
Děkuju za vyřešení. Nemyslím, že bych si filtr záměrně nastavovala (prověřuju existenci zdigitalizovaných věcí, čili potřebuju najít všechno), ale asi se tam "nějak" dostal... Doufám, že není zaškrtnut implicitně, to by možná mohlo vadit i jiným uživatelům.
