### ISSUE TITLE
Import FOXML - kapitoly a články - neprojeví se v klientovi

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#307]
Když naimportuji do Krameria FOXML monografie s kapitolami nebo periodika s články, tak v jádru jsou záznamy článků / kapitol vidět, ale v klientovi ne. Také tam nejsou vidět čísla stran, ale to souvisí s tímto: https://github.com/ceskaexpedice/kramerius/issues/727

![testndkstranykapitly](https://user-images.githubusercontent.com/21309201/74413040-ef6c1c00-4e3e-11ea-931b-a0b321a15c9e.jpg)

Ta samá monografie v klientovi:
![kapitolyklient](https://user-images.githubusercontent.com/21309201/74413062-f7c45700-4e3e-11ea-8163-5b5db4e8aa13.jpg)

**Comment by honza-rychtar** [comment]
Tohle by mělo fungovat. Pokud ne, pak prosím nějaký příklad do veřejné instalace.

**Comment by kerschfilip** [comment]
Funguje to, na žádný problém jsme s tím v poslední době nenarazili.
