### ISSUE TITLE
DNNT - sloučená faseta "pouze veřejné" a "DNNT"

### ISSUE THREAD

**Issue by jandera** [ceskaexpedice/kramerius-web-client#308]
Pro DNNT web klienta by bylo dobré buď přidat sloučenou fasetu "pouze veřejné" a "DNNT", která by se mohla jmenovat nějak jako "vše  k čemu se dostanu" a nebo mít možnost spojit tyto dvě fasety s OR.

**Comment by JanMeritus** [comment]
@jandera alebo formou checkboxu (tj vic vybraneho nez jeden je povoleno)

**Comment by jandera** [comment]
Tak jsem to myslel v té druhé vatiantě. A taky by se tahle faseta, nebo možnost vybrat dvě, měla oběvit až po autentizaci a autorizaci uživatele, tj. po vstupu do možnosti prohlížet DNNT.

**Comment by zabak** [comment]
Komentář od MB: 
"bylo by možné udělat v Krameriovi filtr, který by umožnil uživateli
vyfiltrovat všechny dokumenty s veřejně (vzdáleně) dostupným plným
textem? Ať již je důvod pro otevření plného textu jakýkoliv -
dílo nedostupné na trhu, dílo v public-domain, whatever...

Uživatele zajímá, co má v Krameriovi volně dostupné a nezajimá ho
důvod pro otevření. Pokud jsem pochopil dobře současné nastavení
Kraméria, tak mohu filtrovat jen samostatně podle "díla nedostupná
na trhu" a samostatně "veřejně dostupná", ale nejsem schopen
propojit ty dva filtry do jednoho."

**Comment by zabak** [comment]
Pokud bude možno spojovat fasety přes OR, mohla by být granularita faset public/dnnt/private s tím, že se víceméně nepřekrývají. Po přihlášení se tyto fasety mohou spojit na dostupné/nedostupné.

Ale když je přihlášený, tam musí být jasné, proč daný dokument není možné stáhnout (tj. příslušné funkce (ikony) by měly existovat, být jen zašedlé a po kliknutí zobrazit vysvětlení, proč nefungují.

**Comment by vjirousek** [comment]
Asi bych se přikláněl k první nastíněné variantě, kdy by se mi po přihlášení objevila navíc jedna faseta "Všechny dostupné dokumenty," která by zastupovala "veřejné OR DNNT." 

- Pouze veřejné
- Pouze neveřejné
- Díla nedostupná na trhu
- **Všechny dostupné dokumenty**
- Vše

Zůstála by tím zachována jednoduchá možnost filtrování dokumentů jen na skutečně veřejné a přijde mi to stále dostatečně přehledné (pokud chápu co jsou DNNT) a jednodušší než výběr více faset přes checkboxy. Úplně ideální by asi bylo kdyby se pod "Všechny dostupné dokumenty" filtrovaly i neveřejné zpřístupněné na základě jiného dynamického pravidla - třeba pohyblivé zdi.

**Comment by honza-rychtar** [comment]
@vjirousek Tohle dává největší smysl. Před přihlášením se nic nemění a až po přihlášení mam navíc jednu možnost. Takže uživatel bude mít 5 jasně pojmenovaných možností. Což je určitě lepší než 7 kombinací v případě nejasných OR vazeb mezi veřejné/neveřejné/dnnt.

Pohyblivá zeď by vůbec neměla být dynamickým pravidlem (a myslím, že už není). Dynamická pravidla neupravují záznam v indexu, jen upravují oprávnění přistupovat k obrázkům. Takže dokud si uživatel dokument nezobrazí, tak s dokumentem všude klient zachází jako z neveřejným - filtry, zámky. 
Proces pohyblivé zdi by měl periodicky upravovat přístupnost přímo v datech.

> Uživatele zajímá, co má v Krameriovi volně dostupné a nezajimá ho
> důvod pro otevření. 

Možná ho to nezajímá, ale je tom obrovský rozdíl. V případě DNNT musí byt autorizovaný, bude indentifikovaný a sledovaný, jeho data budou předávána třetí straně a v případě šíření dokumentu bude jednat nelegálně a ponese následky.
Tohle by mělo byt s uživateli jasně komunikováno i za cenu určitého diskomfortu.

**Comment by jandera** [comment]
Souhlasim se sloučenou fasetou "Všechny dostupné dokumenty", která se objeví až po přihlášení. Určitě bude dobré udělat pro DNNT na náhledech, jak ve výsledcích vyhledávání, tak i při prohlížení dokumentu  po levé straně, jiný obrázek než zámeček. Bude se pak lépe vysvětlovat, že když je tam, třeba "přešktnutej foťák", tak je to právě DNNT a nesmí s tím to a to.

**Comment by jahhoo** [comment]
@honza-rychtar jak to prosím vypadá s touto funkcionalitou?

**Comment by JanMeritus** [comment]
@honza-rychtar ako to teda vyzera?

**Comment by honza-rychtar** [comment]
U přihlášeného uživatele je teď přidaný filtr dostupnosti **Všechny dostupné dokumenty**.
Logika je taková, že se filtruje (_dostupnost_ je **public** nebo _dnnt_ je **true**)
Není to jen součet **Pouze veřejné** + **Díla nedostupná na trhu**, protože mezi dnnt jsou i veřejé dokumenty. 
To číslo u filtru **Všechny dostupné dokumenty** je pak dopočítané přes jeden dotaz do solru navíc.
Taky pokud je uživatel přihlášený, pak se dnnt ikony oranžového zámečku změní na přeškrtnutý foťák.

MZK teď nefunguje testovací dnnt Kramerius, takže to zatím není nikde nasazené, ale mělo by to fungovat. 


_Odhlášený uživatel:_
<img width="1123" alt="Snímek obrazovky 2020-09-03 v 19 55 06" src="https://user-images.githubusercontent.com/1178142/92153467-9e486780-ee24-11ea-9972-04eacb098aa2.png">

_Přihlášený uživatel:_
<img width="1125" alt="Snímek obrazovky 2020-09-03 v 19 57 12" src="https://user-images.githubusercontent.com/1178142/92153473-a1dbee80-ee24-11ea-8f39-1cd6188cdd9e.png">

**Comment by JanMeritus** [comment]
@honza-rychtar dle tech filtru na obrazku mi pouze verejne + DNNT vychazi 368 (vys pises jak se to pocita, ale nevim jestli pro uzivatele to neni kontraintuitivni)

diki za preskrtnute fotaky

**Comment by jandera** [comment]
Za mě dobrý, jen bych, pro zachování vizuální konzistence, dal u DNNT ikonu přeškrtnutého foťáku až na úroveň thumbnailů přímo v dokumentu, nyní jsou stále v náhledech jednotlivých stran zamknuté zámečky.

**Comment by honza-rychtar** [comment]
> dle tech filtru na obrazku mi pouze verejne + DNNT vychazi 368 (vys pises jak se to pocita, ale nevim jestli pro uzivatele to neni kontraintuitivni)

@JanMeritus Možná, ale pokud by to byl součet, pak by to po kliku bylo ještě víc zmatené. Protože by to číslo neodpovídalo skutečnému počtu dokumentů.

> Za mě dobrý, jen bych, pro zachování vizuální konzistence, dal u DNNT ikonu přeškrtnutého foťáku až na úroveň thumbnailů přímo v dokumentu, nyní jsou stále v náhledech jednotlivých stran zamknuté zámečky.

@jandera  Tohle už jsme tady řešili, informace o dnnt se nevrací pro seznam stran přes API.
Možnosti jsou
1. paralelně se zeptat na všechny stránky ještě jednou přes solr a pak si je namapovat přes uuid a tím získat informaci o dnnt pro každou stranu. 
2. upravit API
3. počkat na nové schéma solr, kde už klient nebude používat API pro seznam stránek, ale bude se ptát rovnou solru.

**Comment by JanMeritus** [comment]
@honza-rychtar 

ad soucty, at si to vyresi obsahovy spravci, kedze je to od nich, nicmene budou muset uzivatelum vysvetlit kontraintuitivnost tohto modelu

ad UUID, bol by to dobre vyriesit cim skor, idealne aby sme to mohli pouzivat este na jadre K5 a ne locknut to az do K7, proto som myslel este jedno vydani. Ad to API aky je obecny vyvoj, v jinom issue je to zas, ze vsechno se bude komunikovat via API (aj to SOLR) a nativni SOLR API bude jenom v pozadi

**Comment by honza-rychtar** [comment]
@JanMeritus 
> ad soucty, at si to vyresi obsahovy spravci, kedze je to od nich, nicmene budou muset uzivatelum vysvetlit kontraintuitivnost tohto modelu

Obsahovi spráci mohou zařídit, aby tam nebyly dokumenty, které jsou zároveň **public** a **dnnt**, ale pokud toto není splněno, tak počet všech dostupných dokument se prostě nebude rovnat součtu počtu dnnt a veřejných dokumentů. Tento údaj se hlavně přenese po použití filtru **Všechny dostupné dokumenty** a tam to číslo musí sedět se skutečným počtem nalezených a tedy po použití filtru i zobrazených dokumentů.

> ad UUID, bol by to dobre vyriesit cim skor, idealne aby sme to mohli pouzivat este na jadre K5 a ne locknut to az do K7, proto som myslel este jedno vydani. Ad to API aky je obecny vyvoj, v jinom issue je to zas, ze vsechno se bude komunikovat via API (aj to SOLR) a nativni SOLR API bude jenom v pozadi

A https://github.com/ceskaexpedice/kramerius-web-client/issues/343 to teda nevyřeší?
I když bude technicky možné označovat dnnt na úrovni stran, tak jaký k tomu bude vlastně důvod. To jsou vážně nějaké tituly, u kterých jsou na trhu dostupné jen některé stránky?
