### ISSUE TITLE
Zámek pro funkci Zoom

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#31]
Šlo by přidat do prohlížečky funkci lock zoom? Je to tak v současném klientovi a funguje i při přechodu mezi stránkami. Příklad
https://kramerius.lib.cas.cz/client/handle/uuid:19e4cf17-8589-4f6c-962a-6a55e1facf54

Přiblížím stránku a kliknu na Lock zoom
Překliknu na další stránku a ta už je přiblížena jako ta předchozí, takže to nemusím dělat ručně.

**Comment by honza-rychtar** [comment]
Zamkne se šířka/zoom
Po zamknutí se místo zoomu myší/gestem bude posouvat nahoru a dolů.
Po přepnutí stránky se zobrazí nová strana v zamknuté šířce/zoomu a posune se nahoru vlevo.

**Comment by honza-rychtar** [comment]
V ovládacích prvcích v prohlížečce je teď (verze **2.3.8**) zámek.
<img width="403" alt="Snímek obrazovky 2022-09-16 v 18 02 20" src="https://user-images.githubusercontent.com/1178142/190681857-ee474965-f9be-4dd8-adfe-64e463f4944e.png">

Přes něj se uzamkne aktuální zoom, zmizí ovládací prvky způsobující změnu rozměrů, kolečkem myši nebo gesty na trackpadu se obrázek místo zoomování vertikálně posouvá (jako když čtu na webu) a po přechodu na jinou stranu se strana automaticky zazoomuje na uzamčený level a posune se nahoru a vlevo.

<img width="204" alt="Snímek obrazovky 2022-09-16 v 18 02 56" src="https://user-images.githubusercontent.com/1178142/190681841-b9ad1e81-b01c-4ef9-971d-129b8d21f71e.png">
Dalším klikem na uzamčený zámek ze zoom level odemkne.

**Comment by zabak** [comment]
@honza-rychtar myslím, že ty ovládací prvky by zmizet neměly. Ten zámeček jen říká, že se má dané nastavení použít při přechodu na jiné stránky. Není ale důvod, aby si uživatel i při zamknutém zámečku nemohl zoom upravit, přejít na fullscreen, otočit stránku apod. Při prvním použití jsem měl zapnutý dvoustránkový režim a zjistil jsem, že to u zamknutého zoomu není dobrý nápad, ale abych přepnul do jednostránkového zobrazení, musel jsem kliknout 3x: odemknout zoom, přepnout na jednostránkové zobrazení, zamknout zoom.

**Comment by zabak** [comment]
Zámek zoomu je ignorován při návratu z fullscreen zobrazení

**Comment by zabak** [comment]
U zámku zoomu chybí překlad tooltipu (pro zamčenou i odemčenou verzi)

**Comment by honza-rychtar** [comment]
> U zámku zoomu chybí překlad tooltipu (pro zamčenou i odemčenou verzi)

Nechybí, tohle se projevuje jen u DK. U všech ostatních instalací to funguje správně.
Neděláte tam pořád nějaké vlastní úpravy u těch lokalizačních souborů?

**Comment by zabak** [comment]
@honza-rychtar máš pravdu, opraveno. To ostatní ale platí.

**Comment by zabak** [comment]
Ještě jedna drobnost: pokud otočím stránku a použiju tlačítka "přizpůsobit obrazovce" nebo "zapnout fullscreen" tak se dokument otočí do původní polohy. Pokud udělám výřez obrazovky, tak je výsledný obrázek taky v původní rotaci: ...max/0/default.jpg místo např. ...max/90/default.jpg

**Comment by kerschfilip** [comment]
ve verzi 2.4.4 přestal zámek zoomu fungovat

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.4.7**

**Comment by zabak** [comment]
funguje
