### ISSUE TITLE
Vyhledávání podle autora - záznamy článků

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#310]
Když v pokročilém vyhledávání vyhledám autora "Blahoš" - najde mi to čtyři články ve dvou časopisech. 

Ale toho samého autora mi to nenajde, pokud ho zkouším vyhledat přes "Procházet". Vypadá to, že do "Procházet" se neberou metadata článků... 

Zkoušela jsem to na víc autorech, kteří jsou uvedeni jen u článku.

**Comment by kerschfilip** [comment]
Ve verzích 5.8.4.3 jádra a 2.4.9 klienta, které teď máme v KNAV nasazené, mi to funguje už i přes "Procházet". Takže issue zavírám :-)
