### ISSUE TITLE
Pokud je k dispozici IIIF manifest, zobrazit IIIF ikonu jako jednu možnost v rámci sdílení

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#311]
viz např. https://app.digitale-sammlungen.de/bookshelf/ - ikona jde přesunout do jiné aplikace, např. do nástroje pro anotace a jejich sdílení Recogito. Ideální by bylo kdyby se kliknutím na ikonu URL manifestu zkopírovalo do schránky.

Výsledek může pak vypadat např. takto: https://recogito.pelagios.org/document/hr7e3rtxrig9nx/part/1/edit

**Comment by JanMeritus** [comment]
v akom je to stavu @honza-rychtar ? bolo by dobre to implementovat cim skor

zaroven bolo by dobre niekde pre uzivatela (neznaleho problematiky) popisat ako sa s tym pracovat

**Comment by zabak** [comment]
@JanMeritus podpora IIIF presentation api je ještě silně experimentální. Přes léto budeme v MZK psát metodiku jak by se IIIF mělo implementovat v Krameriu (ne jen presentation, ale i další API). Ta potom bude zčásti sloužit i jako návod pro neznalé.

**Comment by honza-rychtar** [comment]
<img width="695" alt="Snímek obrazovky 2024-12-10 v 17 55 55" src="https://github.com/user-attachments/assets/67dc7a4f-7e74-43e2-a48a-43264b00c81e">

Do schránky se zkopíruje url s IIIF manifestem pro Image API je-li zvolená stránku, jinak pro Presentation API.
