### ISSUE TITLE
Při zobrazení obsahu IIIF manifestu zobrazit i jeho URL

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#312]
Nebo toto dělat obecně u všech zobrazovaných metadat. Stačí přes nějakou ikonu typu "link".

**Comment by zabak** [comment]
Koukám, že už se URL zobrazuje u MODSu, teď už to jen rozšířit na ostatní věci.

**Comment by SPXcz** [comment]
Když si zapnu sledování provozu, tak mi to nevyhodí žádnou komunikaci u 'children' a 'item'. Tyhle dvě položky chceš taky vyřešit?

**Comment by zabak** [comment]
Children je https://kramerius.mzk.cz/search/api/v5.0/item/uuid:bdc405b0-e5f9-11dc-bfb2-000d606f5dc6/children

**Comment by honza-rychtar** [comment]
Endpointy `children` a `item` jsou interní formáty Krameria. V konzoli to při otevření nenajdete, protože se už použily pro vykreslení obrazovky a jsou nacachované.  V K7 už children není vůbec a item je nahrazeno něčím jiným a pro jiné účely.

Bylo by dobré oddělit MODS, DC, IIIF, což jsou standardní formáty a někdo to může použít. A pak interní API Krameria, což by běžný uživatel vůbec neměl vidět.

**Comment by SPXcz** [comment]
Takže URL na children a item nechceme vůbec nabízet/zobrazovat?

**Comment by zabak** [comment]
@SPXcz Nebudeme

**Comment by SPXcz** [comment]
Tak to můžeme uzavřít
