### ISSUE TITLE
Pokročilé vyhledávání - uvozovky

### ISSUE THREAD

**Issue by D-Benes** [ceskaexpedice/kramerius-web-client#314]
Uzavření hledaného řetězce do uvozovek by v pokročilém vyhledávání mělo omezit výsledek na výskyty přesné fráze.
Zdá se ale, že se tak neděje - dostávám stejné výsledky bez uvozovek i s nimi.
Např.: http://kramerius5.nkp.cz/periodical/uuid:ae767058-435d-11dd-b505-00145e5790ea?fulltext=%22horn%C3%AD%20konec%22 a http://kramerius5.nkp.cz/periodical/uuid:ae767058-435d-11dd-b505-00145e5790ea?fulltext=horn%C3%AD%20konec

**Comment by BrozekAles** [comment]
To musíte nejprve zadat dotaz http://kramerius5.nkp.cz/search?q=%22horn%C3%AD%20konec%22 a dozvíte se, že v tomto případě přesné frázi odpovídá u daného titulu 11 výskytů. A ty pak najdete pomocí ctrlF, když napíšete ten hledaný řetězec :-)  Takhle to učím při školení a studenti jen kroutí hlavou. Ale co mám dělat, když jsem to jako issue dával někdy loni a stále se nic neděje...:-(

**Comment by BrozekAles** [comment]
Ještě upřesňuji, že jsem to dával jako issue 273 6. října, takže se to třeba teď vyřeší najednou. Díky.

**Comment by honza-rychtar** [comment]
Opraveno, #273
