### ISSUE TITLE
Bug: Vyhladavacie pole: V klientovi ostava filter ako sucast navodneho textu

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius-web-client#317]
V klientovi ostava nezelany filter vo vyhladavacom poli:

1. Po vyhladani titulu pomocou vyhladavacieho riadku vlavo hore - OK
2. Spravanie otestovano v NK i MZK (na produkcii), po odmazani hladaneho a kliknuti vedla:

<img width="967" alt="Screenshot 2020-04-04 at 16 02 48" src="https://user-images.githubusercontent.com/25201690/78452840-0afce180-768e-11ea-8e75-e10825dff5bb.png">

<img width="910" alt="Screenshot 2020-04-04 at 16 05 49" src="https://user-images.githubusercontent.com/25201690/78452854-34b60880-768e-11ea-9898-1eb00d67630b.png">

verze: NK 1.6.2.

**Comment by honza-rychtar** [comment]
Nedokázal jsem replikovat. Děje se to ještě?
