### ISSUE TITLE
Zamky: Diela v specialnom rezime ale aktualne pristupne

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius-web-client#318]
Navrh: Ak budes @honza-rychtar robit novu verziu, bolo by dobre rozsirit paletu priznakov na dielach o ich verejnost/neverejnost ak si ich clovek prehliada z miesta kde neverejne/dnnt/specialny rezim su dostupne. Napr img otvoreneho zamku  (sedeho/oranzoveho). Ich povolenie by malo byt dostupne z konf.

**Comment by honza-rychtar** [comment]
Můžeš to prosím trochu rozvést. Moc tomu nerozumím. Souvisí to s https://github.com/ceskaexpedice/kramerius-web-client/issues/308?

**Comment by JanMeritus** [comment]
@honza-rychtar je to easy

pokial si prihlaseny - a prehliadas si odomknute - ktore su inak zamknute, mal by tam byt priznak ze su odomknute (moze to byt graficky hocico - napr. odomknuty zamok)
pokial nie si prihlaseny/rsp si na Kcku co to neposkytuje - vidis veci ktore su neverejne/specialny rezim / dnnt s priznakom zamku

**Comment by honza-rychtar** [comment]
@JanMeritus  Řeší to https://github.com/ceskaexpedice/kramerius-web-client/issues/308#issuecomment-686679766?

**Comment by JanMeritus** [comment]
@honza-rychtar jop, uzavieram
