### ISSUE TITLE
U procházení periodika se stále zobrazuje filtr dostupnost, i když jej mám vypnutý v konfiguraci klienta

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#319]

**Comment by zabak** [comment]
souvisí s #491

**Comment by honza-rychtar** [comment]
Tohle už je vyřešeno. Problém zůstává naopak s chybějícím filtrem pro licence a nového typu dostupnosti u periodika, ale tomu se věnují jiná issues.
