### ISSUE TITLE
Nenačítají se náhledy skenů v prohlížečích přes telefon/tablet

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#321]
Z telefonu či tabletu se špatně načítají skeny v navigaci (zkoušeno z Chrome, proběhly testy ale i z dalších prohlížečů). Hází mi to šedá okna. Dlaždice se překreslí na začátku a pak vždy po scrollu. Pokud je okno původně nějak překryto nebo v tomto případě schované jako neaktivní tab, tak vlastně nedojde k tomu počátečnímu vykreslení.
![image](https://user-images.githubusercontent.com/43028501/78910056-a32b0a00-7a84-11ea-8cb0-06cbb45b59ab.png)

**Comment by zabak** [comment]
Mě to na DK funguje.

**Comment by zabak** [comment]
Už to vidím, fakt nefunguje. A je jedno odkud to je. Když si udělám na počítači úzké okno a pak teprve vlezu do klienta, tak je to stejné.

**Comment by JanMeritus** [comment]
stejne u nas, bude nutny hotfix a informovat uzivatele o rozsahu problemu. @honza-rychtar na com vsetkom a za akych podmienok sa to moze vyskytnut

@jahhoo FYI

**Comment by honza-rychtar** [comment]
Opraveno.
