### ISSUE TITLE
citace v angličtině

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#323]
Pokud vyvolám citaci v angličtině, měla by být anglicky, je tam přinejmenším text "Dostupné také z:" a "s.". Anglický text by neměl být "Citation of the (ČSN ISO 690)" ale "Citation style: ISO 690"

**Comment by honza-rychtar** [comment]
Na klientovi se pro angličtinu teď použije **Available also from:** a citační služba přebírá parametr s jazykem - jediná změna pro angličtinu je označení stránky **p.** místo **s.**

Pokud jde o _Citation of the (ČSN ISO 690)_, tak to je myšleno jinak.
Je to napsané tak, aby se zvýrazněné části četly jako souvislá věta. V češtině je to skloňováním 
Citace .... stránk**y** ...
V angličtině předložkou
Citation **of the** ... page ...

Ta norma by pak měla být zvlášť jako dropdown menu, kde by si uživatel normu zvolil sám. Klient pak citační službě pošle vybranou normu přes parametr a všechna logika bude na citační službě.
