### ISSUE TITLE
Přidání metadat

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#324]
Bylo by možné přidat do metadat v pravé části obrazovky další nakladatele a místa vydání? Teď se zobrazuje pouze první uvedený. Všechny údaje nemusejí být vidět najednou, ale bylo by to na rozkliknutí jako je to třeba u autorů.

Také bychom potřebovali, aby se zobrazoval identifikátor DOI (máme ho u některých článků, ale dokážu si představit, že by mohl být třeba taky u monografií).

Šlo by to?

**Comment by honza-rychtar** [comment]
> Bylo by možné přidat do metadat v pravé části obrazovky další nakladatele a místa vydání? Teď se zobrazuje pouze první uvedený. Všechny údaje nemusejí být vidět najednou, ale bylo by to na rozkliknutí jako je to třeba u autorů.

Jednotlivé **mods:originInfo** se zobrazují pod sebe, např.
http://www.digitalniknihovna.cz/mzk/periodical/uuid:bdc405b0-e5f9-11dc-bfb2-000d606f5dc6
Pošlete mi odkaz na dokument, kde se tak neděje.

> Také bychom potřebovali, aby se zobrazoval identifikátor DOI (máme ho u některých článků, ale dokážu si představit, že by mohl být třeba taky u monografií).

Pro koho je ten identifikátor? Existuje uživatel, který by ho k něčemu potřeboval a zároveň ho neuměl najít v MODS záznamu, který si na jeden klik otevře?
Pošlete mi odkaz na dokument s vyplněným DOI.

**Comment by krizovj** [comment]
Ohledně originInfo to bude asi tím, že máme ten záznam jiný... máme to všechno v jednom originInfo a opakují se jen nakladatelé a místa vydání... Například zde: https://kramerius.lib.cas.cz/uuid/uuid:440337bd-5625-11e1-9505-005056a60003
Chápu, že by se tam asi blbě kombinovalo, co k čemu patří (který vydavatel ke kterému místu, příp datu)... zřejmě bude lepší opravit záznam...

Příklady dokumentů s DOI (články):
https://kramerius.lib.cas.cz/uuid/uuid:4f4a6827-be7a-11e2-9ddd-001e65b2b442
https://kramerius.lib.cas.cz/uuid/uuid:4728a692-31ac-4e56-9132-a7abbfffbfb9

DOI je možné taky vykopírovat přímo z toho PDF, ale to je jen u nových čísel, lze ho přidělovat i zpětně a to by musel uživatel hledat v MODS a myslím, že ho to rozhodně nenapadne (pokud vůbec ví, co to je). Že tam chtějí DOI zobrazit vím přímo od některých uživatelů (konkrétně redakce a čtenáři odborných periodik).

**Comment by zabak** [comment]
U toho DOI je důležité i to, že by se mělo dávat do citace.

**Comment by honza-rychtar** [comment]
> Ohledně originInfo to bude asi tím, že máme ten záznam jiný... máme to všechno v jednom originInfo a opakují se jen nakladatelé a místa vydání... Například zde: https://kramerius.lib.cas.cz/uuid/uuid:440337bd-5625-11e1-9505-005056a60003
Chápu, že by se tam asi blbě kombinovalo, co k čemu patří (který vydavatel ke kterému místu, příp datu)... zřejmě bude lepší opravit záznam...

@krizovj Ano, raději v záznamu.

> DOI je možné taky vykopírovat přímo z toho PDF, ale to je jen u nových čísel, lze ho přidělovat i zpětně a to by musel uživatel hledat v MODS a myslím, že ho to rozhodně nenapadne (pokud vůbec ví, co to je). Že tam chtějí DOI zobrazit vím přímo od některých uživatelů (konkrétně redakce a čtenáři odborných periodik).

@krizovj Ok, DOI přidám. Podobně jako ISSN nebo ISBN, jen to bude pod článkem (ale ne nutně pouze článkem, zobrazí se u libovolného typu, pokud bude přítomen).

> U toho DOI je důležité i to, že by se mělo dávat do citace.

@zabak Jak by ta citace pak měla vypadat?

**Comment by zabak** [comment]
CitacePro to generují takto: 

ŠÍCHA, Vojtěch. Jazyková skladba pražské tiskařské produkce 16. století - přehledová studie. Knihy a dějiny. 2018, 25(1), 47-67. DOI: http://dx.doi.org/10.23852/KAD.2018.25.03. ISSN 1210-8510.

**Comment by honza-rychtar** [comment]
@zabak @krizovj Ok, tak DOI u článku jsem přidal do generované citace. Ta citační služba je mimo, takže to hned funguje u všech Krameriů.
Např.:
https://kramerius.lib.cas.cz/uuid/uuid:4728a692-31ac-4e56-9132-a7abbfffbfb9
![Screenshot 2020-06-01 16 49 38](https://user-images.githubusercontent.com/1178142/83421222-06ec0680-a428-11ea-8bba-73e8697446b2.png)

Je to mezi rozsahem stran a issn ve tvaru
DOI: [DOI_URL].

DOI_URL je pak obsah elementu 
`<identifier type="doi">`
s dopněným prefixem `http://dx.doi.org/`, pokud chybí.

V uvedeném příkladu v MODS zrovna chybí
` <mods:identifier type="doi">10.23852/KAD.2018.25.03</mods:identifier>`

V druhém příkladu prefix je
https://kramerius.lib.cas.cz/uuid/uuid:4f4a6827-be7a-11e2-9ddd-001e65b2b442
` <mods:identifier type="doi">http://dx.doi.org/10.1135/cccc2010009</mods:identifier>
`

**Comment by honza-rychtar** [comment]
DOI je v panelu s metadaty klientovi i v citaci.
