### ISSUE TITLE
v 1.7.5 problém s podporou iiif

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#325]
Zdravím,
poslední klient 1.7.5 má problém s imageserverem, pokud je zapnuta podpora iiif protokolu. V případě nastavení property `iiif=true` přestane klient zobrazovat dlaždice. Po nastavení `iiif=false` to sice funguje, ale musí se dodat přepisovací pravidlo do webserveru.
```
# iiif image request (identifier/region/size/rotation/quality.jpg)
RewriteCond %{QUERY_STRING} ^Zoomify=([a-zA-Z0-9_\/\.\-]+)\/([a-zA-Z0-9\.\,\:]+)/([a-zA-Z0-9\.\,\:\!]+)/([0-9\.\!]+)/([a-zA-Z0-9]+).jpg$ [OR]
RewriteCond %{QUERY_STRING} ^FIF=([a-zA-Z0-9_\/\.\-]+)\/([a-zA-Z0-9\.\,\:]+)/([a-zA-Z0-9\.\,\:\!]+)/([0-9\.\!]+)/([a-zA-Z0-9]+).jpg$
RewriteRule ^/cgi-bin/iipsrv.fcgi http://%{HTTP_HOST}/cgi-bin/iipsrv.fcgi?IIIF=%1/%2/%3/%4/native.jpg [L]
```
A také přestanou fungovat výřezy.

Na tento problém jsem narazil už při nasazovaní této verze klienta pro "karanténního" Krameria.

Máme nějaké řešení? Posunulo se to?

Díky, MD

**Comment by honza-rychtar** [comment]
Nevzpomínám si, že bych u toho funkcionalitu měnil a u jiných Krameriů to funguje.
Pošli mi prosím odkazy na pár dokumentů, které máte v Image Server se Zoomify/IIIF.
Většinu máte pořád v JPEG a typ zdroje není v indexu. Po náhodném procházení mi vše vrací JPEG a nerozeznám, jestli se náhodně trefuju do dokumentů mimo Image server, nebo jestli je někde chyba a JPEG se použije jako fallback.

**Comment by mduda100871** [comment]
Například:
https://kramerius.lib.cas.cz/uuid/uuid:48652320-62bd-11ea-889a-005056a2b051
nebo si dát filtr `Místo uložení Národní knihovna České republiky...` kde jsou dokumenty v imegserveru.

Jinak zvenku máme přistupného pouze staršího klienta, kde to funguje včetně výřezů. Poslední verzi máme na interním testovacím serveru, ten zvenku vidět není, ale tady je screenshot, kde je vidět chyba v konzoli a hlavní obrázek se nenatáhne:

![klient-01](https://user-images.githubusercontent.com/8750622/83437154-8b964f00-a43f-11ea-83ae-127f835ef852.png)

Pokud v novém klientu nastavím `iiif=false`, tak se hlavní obrázek zobrazí, ale bez možnosti vytvářet výřez:

![klient-02](https://user-images.githubusercontent.com/8750622/83437863-c947a780-a440-11ea-8e08-8f8ee37484ce.png)

Je dobré to testovat v anonymním okně prohlížeče, protože se to kešuje a změna nastavení výše uvedené property se pak neprojeví hned v případě "normálního" okna.

MD

**Comment by honza-rychtar** [comment]
Už tomu rozumím. 
Produkčního klienta na https://kramerius.lib.cas.cz/ máte ještě ve verzi, která nemá IIIF prohlížečku. Výřezy jedou přes IIIF, ale obrázek se skládá ze Zoomify dlaždic. 
`iiif:true` v konfigu jen přidá možnost výřezů. 
Mezitím se do klienta přidala plnohodnotná IIIF prohlížečka. Tedy v nové verzi už `iiif:true` nejen povoluje výřezy, ale komplet se zbavuje závislosti na Zoomify a i dlaždice generuje přes IIIF. 
K tomu, aby se prohlížečka správně nastavila, je potřeba IIIF manifest a tady je problém. Kramerius vám kdovíproč generuje prázdný IIIF manifest
https://kramerius.lib.cas.cz/search/iiif/uuid:65fd95e2-62bd-11ea-889a-005056a2b051/info.json
Stejný objekt na konkrétní výřez funguje.
https://kramerius.lib.cas.cz/search/iiif/uuid:65fd95e2-62bd-11ea-889a-005056a2b051/349,1127,822,649/full/0/default.jpg
IIIF manifest z Krameria má vypadat nějak takto
https://kramerius.mzk.cz/search/iiif/uuid:df55ce14-2ead-4267-88a1-cae2b6e72b88/info.json

Proto výřezy fungují (sáhne se po výřezu na daných souřadnicích) a prohlížečka ne - tady je potřeba znát rozměry a úrovně zoomu, aby bylo možné prohlížečku iniciovat - to se získá z IIIF manifestu, který nefunguje.

Takže problém není v klientovi, ale v Krameriovi.

**Comment by zabak** [comment]
Doplním - ty manifesty generuje imageserver. @mduda100871 zkuste lokálně, jestli je vytvoří - možná že jen neprojdou skrz Krameria ven kvůli nastavení něčeho po cestě.

**Comment by mduda100871** [comment]
Vypadá to, že se mi podařilo problém vyřešit přepisem url v apachi:
```
        RewriteCond %{QUERY_STRING} ^Zoomify=(.*)/info.json$
        RewriteRule ^(.*)$ http://%{HTTP_HOST}/cgi-bin/iipsrv.fcgi?IIIF=%1/info.json [L]

        RewriteCond %{QUERY_STRING} ^Zoomify=([a-zA-Z0-9_\/\.\-]+)\/([a-zA-Z0-9\.\,\:]+)/([a-zA-Z0-9\.\,\:\!]+)/([0-9\.\!]+)/([a-zA-Z0-9]+).jpg$ [OR]
        RewriteCond %{QUERY_STRING} ^FIF=([a-zA-Z0-9_\/\.\-]+)\/([a-zA-Z0-9\.\,\:]+)/([a-zA-Z0-9\.\,\:\!]+)/([0-9\.\!]+)/([a-zA-Z0-9]+).jpg$
        RewriteRule ^/cgi-bin/iipsrv.fcgi http://%{HTTP_HOST}/cgi-bin/iipsrv.fcgi?IIIF=%1/%2/%3/%4/native.jpg [L]

```
MD
