### ISSUE TITLE
Řazení ročníků v časopisech

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#33]
Šlo by přidat do rozhraní přepínač řazení ročníků v časopisech? Defaultně se ročníky řadí od nesjtaršího po nejnovější, ale mohl by si to uživatel nějak přepnout? A ideálně aby si to pamatovalo a každý časopis řadilo stejně, dokud to zase nepřepne.

**Comment by honza-rychtar** [comment]
Udelame.

**Comment by honza-rychtar** [comment]
Pridano razeni (tlacitko vedle volby zobrazeni - mrizka/roky/kalendar).

V pripade seznamu rocniku a cisel je mozno zvolit razeni **Od nejstarších** nebo **Od nejnovějších**, pricemz **Od nejstarších** je vychozi razeni. Volba se po zmene zapamatuje a to pro seznam rocniku a seznam cisel zvlast. Takze muzu zobrazit rocniky od nesjtarsich a cisla od nejnovejsich a takto se mi budou dal radit vsechna periodika, dokud razeni nezmenim.

V pripade fulltextu je mozno zvolit razeni  **Od nejstarších**, **Od nejnovějších** nebo **Podle relevance**,  pricemz **Podle relevance** je vychozi razeni. Razeni se nezapamatuje - pri kazdem novem dotazu dava dal smysl pouzit razeni **Podle relevance** jako vychozi.
