### ISSUE TITLE
Custom adresa solru

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#330]
Umožnit samostatně konfigurovatelnou adresu solru

**Comment by honza-rychtar** [comment]
@zabak Už nevím, proč jsme tohle navrhovali, ale je to vlastně špatně. Klient nepřistupuje k Solru napřímo, ale přes api a to by mělo být fixní.

**Comment by zabak** [comment]
Souhlasím, zavírám.
