### ISSUE TITLE
Nespolehlivost řazení podle abecedy

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#333]
Klient řadí podle abecedy trošku nespolehlivě. Vypadá to, že neumí dobře pracovat minimálně se znaky s diakritikou, viz např. řazení "ž" před "z". Jako příklad uvádím ukázku ze sbírky MZK Fauna a Flora. Výše je podobný problém i u "ř", viz: 

![image](https://user-images.githubusercontent.com/43028501/87144253-bd54ce00-c2a7-11ea-9228-e7a4575bb034.png)
![image](https://user-images.githubusercontent.com/43028501/87144354-e70df500-c2a7-11ea-9276-5d429e6cbae1.png)

http://www.digitalniknihovna.cz/mzk/search?page=2&sort=alphabetical&collections=vc:819363b2-a2ac-44c6-869b-83597a3c7e9c

Možná souvisí s #76 ?

**Comment by honza-rychtar** [comment]
Tak problém je v tom, že v indexu v poli **title_sort** se špatně převádí písmeno s diakritikou.
Třeba Š by se mělo převést na "S|", čímž se přirozeně zařadí za SZ (symbol | je za posledním písmenem abecedy).
Ale místo toho se převádí na "S " (mezera místo |), čímž se zařadí před SA (symbol mezery je před prvním písmenem abecedy). 

Každopádně se tak děje jen u vás v MZK, @annie-cz nemáte tam nějaké změny v indexaci, které tohle způsobily?

**Comment by kazooo** [comment]
@honza-rychtar Ahoj, pokud vím, změny v **title_sort** nemáme, kde se prosím můžu podívat jak se takhle špatně převádí písmena? V *Analysis* Solru mě se to **Š** zpracovává takhle
![Screenshot from 2020-09-15 09-32-35](https://user-images.githubusercontent.com/22412267/93180630-bfb82600-f737-11ea-866f-759283e42dea.png)

**Comment by honza-rychtar** [comment]
@kazooo Jde to přímo v DK
http://www.digitalniknihovna.cz/mzk/view/uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23?page=uuid:71a80bc3-9361-4d5e-8207-179aba225342
<img width="299" alt="Snímek obrazovky 2020-09-15 v 11 26 16" src="https://user-images.githubusercontent.com/1178142/93192779-525fc180-f746-11ea-9c08-e273e35afb5a.png">
<img width="619" alt="Snímek obrazovky 2020-09-15 v 11 28 15" src="https://user-images.githubusercontent.com/1178142/93193158-c601ce80-f746-11ea-8264-c6c4164c057c.png">

NK
http://www.digitalniknihovna.cz/nkp/view/uuid:07d43c00-9b63-11dd-bccc-000d606f5dc6?page=uuid:1a1488c0-f5c3-11e6-85e6-5ef3fc9ae867
<img width="593" alt="Snímek obrazovky 2020-09-15 v 11 30 27" src="https://user-images.githubusercontent.com/1178142/93193372-0e20f100-f747-11ea-8be4-8263c951b985.png">

**Comment by kazooo** [comment]
@JanMeritus Ahoj, můžu se prosím zeptat jaký máte v NK soubor [**unicode_map.st**](https://github.com/ceskaexpedice/kramerius/blob/kramerius5/common/src/main/java/cz/incad/kramerius/utils/unicode_map.st)? 
Používá se indexerem na nahrazení písmen s diakritikou. Je stejný jako na upstreamu?

**Comment by kazooo** [comment]
[Utilita pro konverzi písmen](https://github.com/ceskaexpedice/kramerius/blob/kramerius5/common/src/main/java/cz/incad/kramerius/utils/UTFSort.java) načítá **unicode_map.st** do HashMap struktury. Ta ale [nezajišťuje](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html) žádné pořadí symbolů v ní. Proto po písmenu **Š**, které se stává **S|** následuje zpracování **|**, a to se nahrazuje mezerou. Udělám opravy a pošlu do upstreamu Krameria. Zkusím vyhledat co všechno je potřeba opravit v indexu a opravím také.

**Comment by kazooo** [comment]
K tomu ještě doplním, že se to u nás týkalo nejenom **title_sort** ale i **browse_title**, **browse_author** a **search_title** (je copyField **browse_title**), tam se také aplikovala ta nesprávná utilita.

**Comment by kazooo** [comment]
V indexu opraveno, už by se nemelo objevit.

**Comment by honza-rychtar** [comment]
Ok, super.
