### ISSUE TITLE
Možnost řazení virtuálních sbírek u sbírek s náhledy a popisky / v DK MZK

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#334]
V MZK by nám velmi pomohlo, aby si uživatel mohl dle svého vkusu řadit virtuální sbírky. Máme variantu s náhledy a popisky sbírek, nicméně s touto verzí se dál pracovat nedá. Tak jak leží a běží se navíc automaticky ani neřadí např. podle abecedy, což je při našem počtu VS už dost problém. Se sbírkami navíc hodláme do budoucna dále pracovat a vytvářet hodně nových, takže se problém jen prohloubí.

Potřebovali bychom, aby bylo možné s nimi pracovat, jako to je např. teď u NK, tedy možnost abecedního řazení a řazení podle výskytů (nicméně ten název mi nepřijde moc uživatelsky přívětivý, spíš "podle četnosti dokumentů").

Viz:

NK
![image](https://user-images.githubusercontent.com/43028501/87146517-576a4580-c2ab-11ea-8a9f-4e289f76b6f1.png)

vs

MZK
![image](https://user-images.githubusercontent.com/43028501/87146552-69e47f00-c2ab-11ea-9553-3579af7d57dd.png)

**Comment by honza-rychtar** [comment]
Sbírky se seřadí podle abecedy.
