### ISSUE TITLE
Content description // SEO

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#335]
Monografie (a nejspíš i další dokumenty) mají napsaný jako název mají H5 nadpis místo toho, aby byl H1. Z hlediska SEO je to  problematické, protože Google si všímá především H1.

**Comment by JanMeritus** [comment]
@annie-cz mate nejaku hlbsiu SEO analyzu klienta ?

**Comment by honza-rychtar** [comment]
Vpravo v podrobnostech jsou teď vždy názvy dokumentu přes H1
