### ISSUE TITLE
Pomalé načítání velkých děl

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#336]
U děl, které mají přes 1000 stránek dochází k velice pomalému načítání a občas to způsobuje i zamrzání prohlížeče. Navrhuji, aby klient načítal náhledy postupně při scrollování a ne při načítání první stránky.

Jedná se např. o dílo: http://www.digitalniknihovna.cz/nkp/view/uuid:eafae090-fb7d-11e2-9923-005056827e52?page=uuid:94b01900-3d7a-11e3-b718-5ef3fc9bb22f

**Comment by pavelkocourek** [comment]
Prosím doplnit informaci o tom klientovi a prohlížeči.
U mne 2s na tom uvedeném příkladu.

**Comment by JanMeritus** [comment]
@jahhoo prosim o overenie, ci sa nahlady nacitaju postupne pri scrollovani (a v akom pocte), alebo naraz

**Comment by zabak** [comment]
@JanMeritus @jahhoo co s tím? Můžeme zavřít nebo tam pořád vidíte problém?

**Comment by zabak** [comment]
@JanMeritus @jahhoo nepozoruju žádný problém, prosím o upřesnění nebo zavření.

**Comment by zabak** [comment]
Bez odezvy, takže zavírám. Kdyby se to opakovalo, tak prosím založte nové issue.
