### ISSUE TITLE
Problém při vyhledávání použití filtrů vs použití vyhledávače

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#337]
Vypadá to, že klient při použití filtrů a vyhledávacího dotazu vs. využití pouze vyhledávacího dotazu hází hodně odlišné a hodně zvláštní výsledky. Působí to na mě, jako kdyby při použití filtru autor se přeplo vyhledávání z fulltextu jenom na tituly.

Když člověk např. zadá "bratranec chrobák" (co zadal i uživatel, který nám problém hlásil) a zadá se filtr na autora Steklač, Vojtěch, vyjede toto http://www.digitalniknihovna.cz/mzk/search?q=bratranec%20chrob%C3%A1k&sort=relevance&authors=Stekla%C4%8D,%20Vojt%C4%9Bch

... naopak když se zadá jenom "bratranec chrobák" bez filtru autora, vyjede toto: http://www.digitalniknihovna.cz/mzk/search?q=bratranec%20chrob%C3%A1k&sort=relevance, kde je mezi prvními knížkami vyjede knížka Čenda a já, kde je dotyčný autor v metadatech uvedený.. 

Není to první email, kde se uživatelé pozastavují nad tím, jakým způsobem se v DK vyhledává, ale tento je aktuální i s konkrétním příkladem. Může souviset s #76 .

**Comment by honza-rychtar** [comment]
Protože to našlo výsledky ve fulltextu na úrovni stánek. No a stránky nemají autora. Takže nebyl nalezen žádný objekt, který obsahuje hledaný text a autora zároveň. 
Autor je v objektu monografie, text v objektu stránky.

**Comment by honza-rychtar** [comment]
V K7 se už autoři při indexaci propisují do stran a je tedy možné kombinovat fulltextové hledání s filtrem autora.
http://k7.kramerius.org/search?q=bratranec%20chrob%C3%A1k&sort=relevance&authors=Stekla%C4%8D,%20Vojt%C4%9Bch
