### ISSUE TITLE
Zobrazení více vydání novin (ranních/odpoledních) z jednoho dne v režimu kalendář

### ISSUE THREAD

**Issue by vjirousek** [ceskaexpedice/kramerius-web-client#34]
Při zobrazení novin, u nichž vycházelo více než jedno číslo denně (ranní/odpolední/večerní vydání) se z kalendáře uživatel proklikne jen na jedno (patrně první) vydání. Ostatní vydání z daného dne jsou v tomto režimu skryta, ani při zobrazení vybraného čísla se uživatel nedozví, že ten stejný den vyšlo např. také odpolední vydání.

Příklad viz http://sluzby.incad.cz/kramerius/periodical/uuid:b2b3307b-435d-11dd-b505-00145e5790ea

Týká se též klienta digitální knihovny.

**Comment by pavelkocourek** [comment]
Kalendář to graficky neumožňuje. 
Řešeno v metadatech (vydání ve stejný den) - zobrazeny údaje včetně samotného data vydání.
