### ISSUE TITLE
Sdílení a citování eČlánků

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#340]
Dobrý den,
při procházení eČlánků jsme si v KNAV všimli nesrovnalosti ve sdílení, citování a dokonce v MODSu. 

Příklad: 

chci sdílet článek _"Purkyňova Živa a vědecká komunita v českých zemích"_. Dostanu tento odkaz: https://kramerius.lib.cas.cz/uuid/uuid:f2455b40-1c9a-41c6-9e35-4831b313ca5b
Poté chci sdílet další článek (např. _"Šumavská rašeliniště...."_). Získám správný správný odkaz s jiným uuid: https://kramerius.lib.cas.cz/uuid/uuid:cfddffdb-d9f6-497d-a621-09f7044158bd
Z nějakého divného důvodu ale potřebuju citaci prvního článku (v tomto případě) _"Purkyňova Živa a vědecká komunita v českých zemích"_. Očekávám persistentní odkaz s uuid:f2455b40-1c9a-41c6-9e35-4831b313ca5b, ale v citaci je https://kramerius.lib.cas.cz/uuid/uuid:cfddffdb-d9f6-497d-a621-09f7044158bd a navíc i názvové údaje k článku _"Šumavská rašeliniště...."_ , a dokonce i v MODSu jsou metadata článku _"Šumavská rašeliniště...."_  a ne _"Purkyňova Živa a vědecká komunita v českých zemích"_. 

Vypadá to, jako by nefungoval refresh dotazu. Respektive problém je jen v případě, že se k nějakému článku vracím. Tzn. kdykoli se vrátím na článek, který jsem už citovala/sdílela/dívala se na MD, tak se mi zobrazí údaje z předchozího dotazu (= článku, s níž jsem pracovala - četla, sdílela, citovala,... - naposledy). 

Zkoušela jsem to v Chromu a Firefoxu se stejným výsledkem. Nejsem si jistá, co máme za verzi (asi 1.7.8), ale nefunguje to ani zde: http://dk.kramerius.org/knav/. 

Děkuju, Markéta T.

**Comment by tumovam** [comment]
Považuji za chybu, ne Návrh na rozšíření. Chyba se nově objevuje i v případě, že si zobrazuji metadata eČlánků.

**Comment by zabak** [comment]
Otestováno na 2.1.3
