### ISSUE TITLE
Změna zdrojového Krameria se zachovaným dotazem a některými filtry na obrazovce hledání

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#341]

**Comment by honza-rychtar** [comment]
Zdrojový Kramerius se teď dá na obrazovce vyhledávání změnit přes šiku (vizte screenshot).
Po změně zdrojového Krameria se zachová vyhledaný dotaz, způsob řazení a filtry _dostupnost_, _typ dokumentu_ a _rok_
Je to nasazeno http://www.digitalniknihovna.cz/

<img width="680" alt="Snímek obrazovky 2020-09-03 v 19 43 39" src="https://user-images.githubusercontent.com/1178142/92154267-d308ee80-ee25-11ea-8f5b-bd7603cbd50b.png">
<img width="677" alt="Snímek obrazovky 2020-09-03 v 19 44 46" src="https://user-images.githubusercontent.com/1178142/92154273-d7350c00-ee25-11ea-9300-e8687277470d.png">

**Comment by zabak** [comment]
funguje, možno zavřít
