### ISSUE TITLE
Poslední verze klienta 1.7.10 nepřepíná mezi anglickou a českou verzí Informací

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#342]
Zdravím,

nainstaloval jsem poslední verzi klienta `1.7.10` a přestalo tam fungovat natažení anglického překladu textu v položce `Informace` uložené v souboru `about.en.html` v adresáři `shared/`.

V předchozí verzi `1.7.8` to fungovalo bez problému.

![cs-01](https://user-images.githubusercontent.com/8750622/92701465-4fcd2880-f350-11ea-9981-74c872fa55af.png)

![en-01](https://user-images.githubusercontent.com/8750622/92701467-5065bf00-f350-11ea-88fa-4dd12cef6b5f.png)

MD

**Comment by honza-rychtar** [comment]
Asi překlep v konfigu

```
  aboutPage: {
    cs: '/assets/shared/about.cs.html',
    en: '/assets/shared/about.cs.html',
  },
```

Pro en verzi je odkaz na cs souboru.

**Comment by mduda100871** [comment]
Uff, pravda, pro les nevidím stromy, hloupá chybka :(

Díky, MD
