### ISSUE TITLE
DNNT zámečky na náhledech v prohlížečce

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#343]
> U zobrazení stránek je problém v tom, že info o DNNT se nevrací přes API u seznamu stránek.
> Teoreticky můžu dat dotaz do SOLR a pak si stránky vrácené přes API namapovat na výsledky ze SOLR, které informaci o DNNT obsahují. Ale asi to raději přidejme do API.

**Comment by honza-rychtar** [comment]
@JanMeritus DNNT není nikdy určováno až na úrovni stránek že? Ale na celé monografii, periodiku, případně ročníku a čísla.
Pak není problém s chybějícím dnnt příznakem v API. Stačí vzít dnnt příznak otevřeného dokumentu  prohlížečce (monografie, číslo periodika) a uplatnit ho na všechny stránky.

**Comment by zabak** [comment]
@honza-rychtar je to tak jak píšeš. Možná někdy v budoucnu by mohly nastat nějaké případy, kdy je dílo na seznamu DNNT a v Krameriu se objeví jako součást nějaké antologie, kde budou jak chráněná tak nechráněná díla. Ale to je zatím hodně teoretická konstukce. Seznam DNNT vychází z monografií co jsou v Souborném katalogu.

**Comment by JanMeritus** [comment]
@zabak zatim to tak neni, ale len kvuli technickym omezenim povahy setu, neni to teoreticka konstrukce, pocitame s tim az bude dodelana aplikace, bude moci se oznacovat na urovni stranek, evidence bude tam overitelna primo via rychly dotaz na REST API

**Comment by zabak** [comment]
Jo, ale to by někdo musel vytvářet u těch antologií analytický rozpis svazku včetně jednoznačných identifikátorů díla linkovaných na seznam DNNT.
@honza-rychtar příznak DNNT je v solru u každé stránky?

**Comment by honza-rychtar** [comment]
> příznak DNNT je v solru u každé stránky?


@zabak Ano

**Comment by zabak** [comment]
Zavírám, otestováno na 2.1.1
