### ISSUE TITLE
podpora epub v klientovi

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#346]
Dle dohody NK, MZK a KNAV: specifikovat požadavky na podporu epub v klientovi Krameria

**Comment by honza-rychtar** [comment]
Možnost vyzkoušet zde http://dk.kramerius.org/mzk/view/epub 
klikem na ikonu pdf si můžete načíst libovolný epub, který máte stažený i sebe.
<img width="301" alt="Snímek obrazovky 2022-02-07 v 16 11 41" src="https://user-images.githubusercontent.com/1178142/152815326-843f6e08-7b39-49b1-a2d6-ad02f0508c51.png">

**Comment by zabak** [comment]
- [ ] Zobrazení na širších displejích je dvousloupcové, což není vždy optimální. Prosím o zavedení přepínače pro jedno/dvousloupcové zobrazení (může být shodný s přepínačem jednostrana/dvoustrana u skenovaných dokumentů). 
- [ ] V určitých kombinacích zvěšování a zmenšování textu a překlikávání kapitol se neaktualizují správně počty stránek, takže dochází ke stavům jako 
<img width="181" alt="image" src="https://user-images.githubusercontent.com/811537/155038530-e4d00d4b-ee1d-471b-8532-a1635d37bbd0.png"> - asi to souvisí s neaktualizací linků na kapitoly v obsahu.

**Comment by zabak** [comment]
Po dohodě s @honza-rychtar toto issue zavírám a další připomínky k epub implementaci budou dávány jednotlivě do nových issue.
