### ISSUE TITLE
Prefix v identifikátoru DOI a příp. hyperlink

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#348]
Dobrý den,
šlo by, prosím, změnit prefix v identifikátoru DOI?
Nyní se v Krameriovi zobrazuje "http://dx.doi.org/...", ale správně by mělo být "https://doi.org/..." (https://www.crossref.org/education/metadata/persistent-identifiers/the-structure-of-a-doi/).

V MODu máme DOI bez prefixu, např. https://kramerius.lib.cas.cz/uuid/uuid:7b05bd75-bda2-43d7-b507-31b2211063fb nebo https://kramerius.lib.cas.cz/uuid/uuid:9a0648f8-96b7-44f6-b42c-3e51734466d7, případně i zde: https://kramerius.lib.cas.cz/uuid/uuid:0e2820ea-311f-46e6-a651-5b530d7cd528.

V tomto případě https://kramerius.lib.cas.cz/uuid/uuid:b1656a92-be79-11e2-9ddd-001e65b2b442 máme DOI i s prefixem, ale to je chyba v našich datech... 

Problém s DOI už se částečně řešil zde: https://github.com/ceskaexpedice/kramerius-web-client/issues/324

A ještě dotaz - bylo by možné z "DOI" udělat hyperlink?
Děkuji,
MT

**Comment by honza-rychtar** [comment]
Upravil jsem prefix. Pokud není v MODS uveden, tak se použije  `https://doi.org/`
Zobrazí se jako odkaz, který otevře DOI link v novém tabu.
U citace to už funguje bez nutnosti aktualizace klienta.
<img width="697" alt="Snímek obrazovky 2020-10-18 v 11 33 36" src="https://user-images.githubusercontent.com/1178142/96363690-100b1500-1136-11eb-891e-925de8628fd9.png">

V podrobnostech v klientovi se taky použije odkaz s upraveným prefixem.
Tohle bude dostupné v nové verzi klienta.
<img width="297" alt="Snímek obrazovky 2020-10-18 v 11 36 32" src="https://user-images.githubusercontent.com/1178142/96363747-5d878200-1136-11eb-9d62-5c422243e799.png">
