### ISSUE TITLE
Chybějící úroveň čísla 

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#35]
Když u periodika chybí úroveň čísla (pod úrovní ročníku by se měly zobrazit rovnou jednotlivé strany), nic se nezobrazí. 
Příklad: časopis Powjdatel...
Rozkliknu titul, objeví se tři ročníky. Rozkliknu jeden ročník a není tam nic.

**Comment by krizovj** [comment]
Celkově by mělo být nějak vyřešeno, aby bylo možné zobrazit pod úrovní ročníku nejen čísla, ale také samostatné stránky (případně kombinace). Máme to u docela dost dokumentů. Příklad: 
Ročník 1814 obsahuje 6 čísel a 15 stránek:
https://kramerius.lib.cas.cz/client/handle/uuid:490185a2-b934-11e1-5015-001143e3f55c

**Comment by honza-rychtar** [comment]
@krizovj Tohle jsem udelal stejne jako v Digitalni knihovne, ale ted jsem si vsimnul, ze jsem tam zanesl chybu. Dneska uz to nestihnu opravit.
Kazdopadne resenim je vytvoreni "virtualniho" cisla v pripadem, ze rocnik obsahuje primo pod sebou cisla. Takze u toho prikladu s 6 cisly a 15 strankami - http://www.digitalniknihovna.cz/knav/periodical/uuid:490185a2-b934-11e1-5015-001143e3f55c - se zobrazi 7 cisel, kde to posledni je to "virtualni" cislo, ktere se po prokliku pak otevre v prohlizecce s temi 15 strankami.

Tohle reseni doplnuje chybejici cast ve strukture periodikum -> rocnik -> cislo -> stranka. Pokud by se zobrazovaly stranky primo na urovni rocniku, tak by tam mohly byt stovky stranek (uvadeny casopis Powjdatel jich ma pres 200). Misto toho v rocniku pribude jen jedno 'virtualni" cislo a stranky jsou az na urovni prohlizecky, kam patri.

**Comment by honza-rychtar** [comment]
Chyba se tyka #42

**Comment by honza-rychtar** [comment]
Hotovo

**Comment by tumovam** [comment]
S novou verzí klienta se po rozkliknutí "virtuálního" čísla objeví chyba 404 s textem "Stránka nebyla nalezena. Přejděte na úvodní stránku."
Např. zde: https://kramerius.lib.cas.cz/uuid/uuid:ba203a22-530d-11e1-1418-001143e3f55c, stejný ročník v Digitálníknihovně: http://www.digitalniknihovna.cz/knav/uuid/uuid:ba203a22-530d-11e1-1418-001143e3f55c. 
Stránky ale v Krameriovi jsou, screen z jádra: 
![obrazek](https://user-images.githubusercontent.com/31240271/105992325-434e3000-60a5-11eb-8ad8-911464d22e30.png)

**Comment by filak** [comment]
To se nám děje taky, např.:

https://dev.medvik.cz/wck2/periodical/uuid:609a7d9b-3303-4847-a4c7-469e5cefab1a

Přitom ve starší verzi klienta se to zobrazuje dobře:

https://dev.medvik.cz/wck/view/uuid:609a7d9b-3303-4847-a4c7-469e5cefab1a

(ale je možné, že jsem si to tam nějak poupravil, už je to dlouho - nicméně to nad stejnými daty určitě lze zobrazovat korektně)

**Comment by honza-rychtar** [comment]
Opraveno.
http://www.digitalniknihovna.cz/knav/periodical/uuid:490185a2-b934-11e1-5015-001143e3f55c
http://www.digitalniknihovna.cz/nlk/periodical/uuid:609a7d9b-3303-4847-a4c7-469e5cefab1a
