### ISSUE TITLE
Špatné řazení periodik - pokud číslo nemá přesné datum vydání

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#350]
Pokud není u čísla periodika vyplněno přesné datum, čísla se špatně řadí. Bylo by vhodné dodělat podmínku pro řazení - pokud jsou čísla stejného data - vždy řadit podle hodnoty čísla.

Např. http://kramerius5.nkp.cz/periodical/uuid:b776c280-948d-11e3-8e84-005056827e51

**Comment by zabak** [comment]
To dává smysl a u leckterých novin by to vyřešilo i problém jak řadit několik vydání v rámci stejného dne (pokud jsou číslovaná). Ale zrovna v případě toho Zvonu tam jsou data uvedena na konci poslední strany každého čísla, takže by stálo za to je doplnit.

**Comment by honza-rychtar** [comment]
To se řešilo hodněkrát. Číslo periodika není zaindexované, resp. není zaindexované tak, aby se podle něj dalo řadit.
Nový indexer má pro řazení zaindexované číslo i vydání (ranní, polední, večerní) a řadí se pak nejdříve podle data, pak podle čísla a pak ještě podle vydání.

Ono se to u těchto případů dá dělat i na klientovi. Že když už ty čísla znám, tak je můžu zpracovat, tak abych to podle nich mohl i dodatečně seřadit. Ale cílem bylo mít v pořádku index, aby mi rovnou vracel výsledky v požadovaném pořadí.

**Comment by honza-rychtar** [comment]
Opraveno. S novým indexem se spraví řazení přímo. U starého se řazení po načtení upraví na straně klienta.
Takže by to mělo fungovat ve všech Krameriich.
http://www.digitalniknihovna.cz/nkp/periodical/uuid:b776c280-948d-11e3-8e84-005056827e51
