### ISSUE TITLE
mobilni rozhrani menu

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius-web-client#351]
Ahoj, je to feature, alebo bug? Pri testovani na mobile (napr prevrateni na lezato), sme prisli na to ze pri prevrateni zmizne menu na dalsich strankach

**Comment by zabak** [comment]
Můžeš sem dát nějaké screenshoty? Já nic takového nepozoruju, ale možná dělám něco jiného než ty.

**Comment by zabak** [comment]
@JanMeritus prosím otestuj to na DK. Je možné že je to vyřešené. Ovládací menu se objeví při tapnutí na obrázek stránky. Nesouviselo to nutně s rotací obrazovky, ale s tím, že se menu objevilo jen při použití myši, která jaksi na dotykáčích není častá.

**Comment by annie-cz** [comment]
Právě jsem si všimla tady toho chování na dnnt.mzk.cz. Ten bug tam asi pravděpodobně fakt bude. Když si rozkliknu nějaký dokument, tak se ztratí pravé menu - takže třeba i karta přihlášení, což je pak dost zásadní nedostatek. Chtěla jsem na to zrovna založit nové issue.

![image](https://user-images.githubusercontent.com/43028501/157483098-74f974ad-bf2a-4426-8ff5-24f1a7efee33.png)

@honza-rychtar ?

**Comment by honza-rychtar** [comment]
Pokud je zobrazené vyhledávací pole v navbaru (všude kom hlavní stránky), tak od určité šířky se schovají tlačítka v menu.
Je to chyba, resp. vážný nedostatek. Přidám schovácí menu pro mobilní zobrazení.

**Comment by honza-rychtar** [comment]
Opraveno v rámci #493 ve verzi **v2.3.5**

**Comment by zabak** [comment]
otestováno, zavírám. Díky.
