### ISSUE TITLE
Linkování na DNNT zvenčí

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#356]
Pokud zvenčí (z katalogu knihovny) linkuju na něco co je DNNT, chtěl bych, aby na uživatele rovnou vyskočilo že se má přihlásit. Teď se mu zobrazí kniha s hláškou že je nedostupná - např. https://ndk.cz/uuid/uuid:edde3fa0-984f-11e2-9a08-005056827e52 
Cílem eliminovat ten nezbytný klik na přihlášení. Můžeme použít https://ndk.cz/podminky-zpristupneni?target=https://ndk.cz/uuid/uuid:edde3fa0-984f-11e2-9a08-005056827e52 ale potřeboval bych potvrdit, že toto je správný způsob konstrukce toho linku. Nebyl by lepší nějaký parametr za URL?

**Comment by JanMeritus** [comment]
@jahhoo prosim o analyzu

**Comment by jahhoo** [comment]
@zabak ano, link na podminky-zpristupneni lze použít. Samozřejmě není problém dokonfigurovat libovolné přesměrování. Klidně navrhněte...

**Comment by zabak** [comment]
Zavírám, stávající řešení funguje dobře.
