### ISSUE TITLE
Tlačítko řazení: Nově přidané ve virtuálních sbírkách

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#357]
Tlačítko "řazení: Nově přidané" ve virtuálních sbírkách, tak jak je aktuálně nastavené, nedává příliš smysl z uživatelského hlediska. Když vlezu do virtuální sbírky a toto zadám, očekávám, že se mi výsledky seřadí podle toho, kdy se dokument nahrál do konkrétní virtuální sbírky - zejména u sbírek, které se mohou doplňovat a uživatel může být zvědavý, co se tam přidalo nové, co ještě třeba neviděl. V rámci sbírek mám pocit, že standardní řazení podle času nahrání do DK jako takové nedává smysl.

Navrhuji tedy buď:

a) tlačítko řadit podle "nově přidané" v rámci sbírek úplně zrušit

b) nebo lépe upravit "nově přidané" podle času nahrání do konkrétní sbírky

**Comment by honza-rychtar** [comment]
Řešeno tady #646. 

> a) tlačítko řadit podle "nově přidané" v rámci sbírek úplně zrušit

ok, schováme

> b) nebo lépe upravit "nově přidané" podle času nahrání do konkrétní sbírky

komplikované, nebude dělat

c) výchozí bude kurátorem určené pořadí 

Tady zavírám, dál řešme v #646
