### ISSUE TITLE
DNNT textace filtr

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius-web-client#358]
Textace filtru v anglictine "Documents not available on the market" neodpovida pravnimu terminu technicu, minimalne tak ako ho pouziva IFLA, Kluwers atd, prosim o opravu na "Out of Commerce Works"

<img width="269" alt="Screenshot 2020-10-26 at 10 28 17" src="https://user-images.githubusercontent.com/25201690/97156738-68b26180-1777-11eb-95e2-8d99dc02f858.png">

viz napr https://www.ifla.org/files/assets/hq/topics/exceptions-limitations/oocw_infographic_ver_2.1.pdf

**Comment by honza-rychtar** [comment]
V klientovi zatím nejsou DNNT hlášky přeloženy vůbec. **Documents not available on the market** jste si museli upravit sami.
U těchto textů 
- Dokument podléhá režimu děl nedostupných na trhu _(tooltip na zámečku)_
- Díla nedostupná na trhu _(filtr hledání)_
- Dílo nedostupné na trhu _(text u zámečku v podrobnostech)_

To všude změním na **Out of Commerce Works**
Pak je tam ještě ten dlouhý text v prohlížečce u nepřihlášeného uživatele u dnnt dokumentu.
Tam by se to pak asi mělo nastavovat na úrovni Krameria podobně jako text u neveřejného dokumentu.

**Comment by honza-rychtar** [comment]
Hotovo.
