### ISSUE TITLE
Citace - dotaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#36]
Měl by někdo něco proti tomu, že by se tlačítko pro vygenerování citace zobrazovalo vpravo u metadat? Stejně jako se tam bude zobrazovat trvalý odkaz? (viz. https://github.com/ceskaexpedice/kramerius-web-client/issues/13)

Jde o to, že takhle jak je to vlevo by tedy nešlo vygenerovat citaci pro celé periodikum. Citace pro celé periodikum by se dala vygenerovat na úrovni, kde jsou zobrazeny ročníky a pak také na úrovni, kde jsou zobrazena všechna čísla. Citace čísla a popř. článku by se dala vygenerovat až když rozkliknu číslo.

**Comment by vjirousek** [comment]
Pokud by vpravo byly citace, sdílení a tlačítko pro stažení kompletních metadat (viz #30) pak to myslím smysl dává..

**Comment by pavelkocourek** [comment]
#5 bude řešeno společně

**Comment by honza-rychtar** [comment]
Citace urcite vpravo v metadatech, jen zatim neni vyreseno, jak se bude citace generovat. Zvazovala se integace citacniho manageru citace PRO jako je to na knihovny.cz, ale nevim v jakem je to stadiu.

**Comment by honza-rychtar** [comment]
Přidal jsem generování citace podle ČSN ISO 690.
Citace se zobrazí po kliku na ikonu v panelu s metadaty:
<img width="301" alt="screenshot 2019-02-05 18 09 49" src="https://user-images.githubusercontent.com/1178142/52306636-c8138100-2998-11e9-9411-fd0b6a57dbc8.png">

<img width="1446" alt="screenshot 2019-02-05 22 45 14" src="https://user-images.githubusercontent.com/1178142/52306656-d3ff4300-2998-11e9-9a3a-52c10f680a77.png">

Citace se zobrazí také při výběru textu ze stránky (https://github.com/ceskaexpedice/kramerius-web-client/issues/112#issuecomment-460717720) a při textovém přepisu stránky.

Citace podporují i čísla periodika a články.

**Comment by honza-rychtar** [comment]
@krizovj Aha. No to teď nejde.
Napadají mě dvě možnosti.
1. V panelu s metadaty bude tlačítko _citace_ u každé úrovně (dokument, ročník, číslo, článek).
Tohle je ale dost nepřehledné.
2. V dialogu s citací by místo nadpisu **citace** byly přepínatelné _taby_ pro každou úroveň. 
Podobně jako dialog se zdrojovým MODS, kde se dá vybrat ze všech úrovní.
Takže výchozí chování by bylo jako teď. V případě článku se zobrazí dialog s citací článku, ale dalo by se přepnout na citaci čísla, citaci ročníku, citaci periodika.

Co vy na to?

**Comment by krizovj** [comment]
Mně se tedy víc líbí druhá možnost, jako je to u MODSu.

**Comment by honza-rychtar** [comment]
Ještě přidám možnost citovat přímo konkrétní stránku (jako další tab, nebude výchozí).
A citaci konkrétní stránky pak použijeme u výběru textu na stránce a textového přepisu stránky.

**Comment by LenkaKravecova** [comment]
Mně se taky líbí víc ta druhá možnost, ale záleží, jak to bude vypadat. Nějak si teď neumím představit ty přepínatelné taby.

**Comment by krizovj** [comment]
Já jsem to pochopila tak, že by to vypadalo vlastně úplně stejně jako teď, když si chci zobrazit MODS. Můžu se přepnout na záznam titulu, ročníku, čísla, článku, stránky,...

**Comment by honza-rychtar** [comment]
Tak změněno.

Vypadá to takto:
<img width="704" alt="screenshot 2019-02-06 21 57 39" src="https://user-images.githubusercontent.com/1178142/52375007-ed6ac280-2a5e-11e9-959d-2bad3efa76fd.png">

<img width="705" alt="screenshot 2019-02-06 21 57 55" src="https://user-images.githubusercontent.com/1178142/52375044-01aebf80-2a5f-11e9-9237-7152d994e04b.png">

Výchozí je vždy nejspecifičtější úroveň (ale ne stránka). Pak je možné přepínat v záhlaví.
U PDF dokumentů se nedá citovat přímo stránka. Jinde ano.
<img width="941" alt="screenshot 2019-02-06 22 23 48" src="https://user-images.githubusercontent.com/1178142/52375198-610ccf80-2a5f-11e9-9a2f-884498f29a1f.png">

U výběru textu a textového přepisu se cituje rovnou stránka.

**Comment by krizovj** [comment]
Citace fungují dobře, až na odkaz, který zůstává stejný, ať cituji číslo, titul, nebo stránku. Je to odkaz na konkrétní stránku.

**Comment by krizovj** [comment]
Ještě by se tam měla přidat informace, podle které normy je ta citace vytvořena.

**Comment by pavelkocourek** [comment]
29.4. KNAV - zobrazují se stejné odkazy

**Comment by honza-rychtar** [comment]
Problém se stejným odkazem u všech úrovní opraven. 
Přidáno info o použité normě,
