### ISSUE TITLE
chyba při zobrazení stránky v default rozlišení

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#361]
Nevím jestli to způsobuje specifická velikost stránky, ale u jedné konkrétní knihy ve více prohlížečích https://dnnt.mzk.cz/view/uuid:4d96ea0c-4051-11e1-ac09-0050569d679d?page=uuid:535cba68-4051-11e1-ac09-0050569d679d dělá toto:
![image](https://user-images.githubusercontent.com/811537/98088879-49f05100-1e82-11eb-94d0-e7a755d2d96b.png)

**Comment by honza-rychtar** [comment]
Zkoušel jsem na chvilku přepnout prohlížečku na Zoomify a tam to nezlobí. Jinou IIIF prohlížečku nemůžu zkusit, protože dokument není veřejný. Stejně tak to kvůli neveřejnosti nemůžu zkusit otevřít lokálně.

**Comment by zabak** [comment]
@honza-rychtar ten dokument je DNNTO, takže po přihlášení se na něj dostaneš. Můžeš na to mrknout?

**Comment by honza-rychtar** [comment]
@zabak to bude to samé jako tady #510
Není to public, takže nemůžu ověřit v Miradoru. 
Pokud by to byla chyba IIIF prohlížečky, tak jsou ty problému častější.

**Comment by zabak** [comment]
Máš pravdu. Mám podezření, že jde o velikost obrázku v pixelech. V tomhle dokumentu jsou všechny stránky stejně velké a všechny mají problém, až na přední desky, které mají jinou velikost a problém tam není. U knížky v #510 je problém jediná stránka, ostatní jsou jinak velké. Zkoušel jsem tu stránku i v universal vieweru, tam se vůbec nenačte.
