### ISSUE TITLE
DNNT u PDF dokumentů

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#362]
U PDF prohlížečky se teď nezobrazuje DNNT lišta.
Pokud ji přidáme stejně jako u obrázku, tak ji bude zakrývat horní ovládací panel integrované PDF prohlížečky.
Můžeme ji posunout pod ten panel. Na druhou stranu ten panel obsahuje stažení a tisk, což by u DNNT nemělo být možné, takže nakonec by asi dávalo smysl DNNT lištou překrýt ten ovládací panel. 
To sice bude lišta **nad** obsahem PDF a ne **přes** obsah, ale to je stejně jedno, protože si vždycky můžu odscrollovat. Podobně jako u obrázku si ho můžu stáhnout pod lištu.
Takže je to spíš o tom, jak moc musíme zabezpečit DNNT PDF dokument - lišta přes text, ovládací prvky, ...

**Comment by kerschfilip** [comment]
@honza-rychtar mohli bychom se k tomuhle problému vrátit? Licence pro AV ČR respektive jednotlivé ústavy, které teď připravujeme, se týkají hlavně PDF. Od založení issue došlo ke změně prohlížečky PDF, takže teď by přidání lišty už nemělo ovládacím prvkům vadit.
Díky!

**Comment by zabak** [comment]
Testoval jsem na https://kramerius.lib.cas.cz/view/uuid:dcc2307c-1551-4d3b-8ffa-6608e64ca992?article=uuid:ee7aaaac-90bc-44bf-85c9-48e4dbbc3ebe a pruh nevidím.

**Comment by honza-rychtar** [comment]
@zabak protože tohle přibylo ve verzi 2.5.0 a v KNAV (na které to zkoušíš) mají verzi 2.4.9
Zkus u vás třeba na https://www.digitalniknihovna.cz/mzk/view/uuid:373968db-1fb5-4c05-9f04-9763fc77d99c

@kerschfilip proč máte takto starou verzi klienta?

**Comment by kerschfilip** [comment]
@honza-rychtar podporuje aktuální verze možnost kombinovat příznaky policy:public/private a licence? U nás se nějak domluvilo, že upgradovat budeme až převedeme policy na licence, takže jsme zatím nechali 2.4.9

**Comment by zabak** [comment]
OK, každopádně to funguje, takže zavírám
