### ISSUE TITLE
V textu se nezvýrazňují slova s interpunkcí

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#365]
Dotaz "Tělesná výchova žen a dívek. Klemeňa Hanušová, první učitelka tělocviku. Lucie Swierczeková" nezvýrazní slova "dívek.", "Hanušová," a "tělocviku."

http://www.digitalniknihovna.cz/mzk/view/uuid:1ef27f20-3cfd-11e6-a5c5-005056827e51?page=uuid:5321edb0-5a1e-11e6-b155-001018b5eb5c&fulltext=%22T%C4%9Blesn%C3%A1%20v%C3%BDchova%20%C5%BEen%20a%20d%C3%ADvek.%20Kleme%C5%88a%20Hanu%C5%A1ov%C3%A1,%20prvn%C3%AD%20u%C4%8Ditelka%20t%C4%9Blocviku.%20Lucie%20Swierczekov%C3%A1%22

**Comment by honza-rychtar** [comment]
Opraveno. Slova v ALTO se osekávala o interpunkci, ale slova na vstupu ne. Sjednotil jsem to.
