### ISSUE TITLE
Vícedílná monografie - chybějící PartName a PartNumber

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#367]
Dobrý den,
po nasazení nového UNNK (nejspíše) verze 2.0.1 se nám v DKNAV nerobrazuje PartName, ani PartNumber. 
Např zde: https://kramerius.lib.cas.cz/uuid/uuid:dde64faf-cdc3-4226-a722-69b938ce01a5
Stejné to i tady: http://dk.kramerius.org/knav/periodical/uuid:dde64faf-cdc3-4226-a722-69b938ce01a5
Možná to souvisí s https://github.com/ceskaexpedice/kramerius-web-client/issues/280 
Děkuji, M. H.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.0.2
