### ISSUE TITLE
Chybí metadata k číslu / ročníku periodika

### ISSUE THREAD

**Issue by vjirousek** [ceskaexpedice/kramerius-web-client#37]
V panelu metadat se u periodik zobrazují vždy pouze metadata pro úroveň titulu.

**Comment by honza-rychtar** [comment]
Jsou doplneny informace: rocnik, rok, cislo, datum a navigace na predchozi/nasledujici cislo a na seznam vsech cisel - http://sluzby.incad.cz/kramerius/view/uuid:bfc85673-435d-11dd-b505-00145e5790ea?page=uuid:31df305f-435e-11dd-b505-00145e5790ea

**Comment by zabak** [comment]
Pokud jsem se pomocí fulltextového vyhledávání dostal na nějakou stránku nějakého čísla periodika, tak nevím, odkud ta stránka pochází - vidím jen informace o titulu. V Digitální knihovně je navíc informace o roku, ročníku, datu vydání a čísle a navigace na další/předchozí a seznam čísel.

**Comment by honza-rychtar** [comment]
@zabak to uz tam nejakou dobu je. Bez fulltextu i s fulltextem.
<img width="209" alt="screenshot 2018-03-25 12 05 54" src="https://user-images.githubusercontent.com/1178142/37873867-0d524cce-3025-11e8-9350-611561c6b76f.png">
