### ISSUE TITLE
Němčina (a slovenština) v klientovi

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#370]
Přidat do klienta další jazykové verze. Především němčinu.

**Comment by pavelkocourek** [comment]
Co Petře udělat tabulku na překlady .. a doplníme jazyky, které budou dávat smysl

**Comment by zabak** [comment]
Použil bych poeditor.com nebo crowdin.com. Oba mají nějakou formu free účtu a možnost požádat u open source projektu o plný účet zdarma. Oba mají github integraci. Oba mají podporu nějaké formu strojového překladu, což urychluje překlady do nových jazyků. Výhoda je, že překlady může dělat neomezené množství lidí (neprogramátorů). Crowdin má dokonce nějakou formu kooperativního schvalování, poeditor možná taky. @honza-rychtar máš nějakou zkušenost/preferenci? poeditor o sobě říká mj. toto: https://poeditor.com/kb/angular-xliff-editor ale něco podobného umí i crowdin, předpokládám. Existuje ještě transifex, ale ten by nám možná nepřiznal účet zdarma. Takže prosím vyberte něco vhodného.

**Comment by SPXcz** [comment]
Zkouším to teď dělat pomocí mz-dropdown, ale mám dost divný problém s funkcí onLanguageChanged(lang: string), konkrétně s [tímto řádkem](https://github.com/ceskaexpedice/kramerius-web-client/blob/b4a97baed40a1f17c1615515875462187e91e0b4/src/app/navbar/navbar.component.ts#L39). Z nějakého důvodu je proměná `lang` v pohodě, ale `this.translator.language` se nezmění. Není tam někde nějaký potenciální souběh, o kterém nevím? 

@honza-rychtar

**Comment by honza-rychtar** [comment]
@zabak Neřešme externí nástroje a crowd pro němčinu a slovenštinu.
Lokalizační soubor pro češtinu v novém klientovi
https://www.digitalniknihovna.cz/assets/i18n/cs.json
Lokalizační soubor pro češtinu v tmavém klientovi
https://www.difmoe.eu/i18n/cs.json
Lokalizační soubor pro němčinu v tmavém klientovi
https://www.difmoe.eu/i18n/de.json

Oba klienti jsou si dost podobní a němčina v tmavém prošla korekcí lidí z rakouských a německých knihoven, takže má smysl z toho vyjít a doplnit.
U toho překladu je nutné znát kontext - kde a jak se daný řetězec v klientovi použije.
Já ten německý překlad rozpracuju. Vyjdu z tmavého klienta a identifikuju chybějící řetězce. Tady by se hodilo někoho s dostatečnou znalosti němčiny, s kým bych zbytek doplnil. Ne tak, že bych poslal klíče, ale ukazoval bych to přímo v klientovi.
@zabak co Jirka Dufka? Umí německy, zná Krameria a klienta a rozumí knihovním pojmům.

@SPXcz Jakože u kliku na mz-navbar-item to funguje a u kliku na mz-dropdown-item to nefunguje? 
Nevidím důvod, proč by se to mělo chovat jinak. To bych musel vidět.
Jediné další místo, kde se nastavuje jazyk je start aplikace. Tak ledaže by změnou jazyka přes mz-dropdown došlo k hard reloadu aplikace.

**Comment by SPXcz** [comment]
Nahrál jsem tu verzi s chybou na můj [fork](https://github.com/SPXcz/kramerius-web-client/tree/lang-problematic).

Nakonec je to pravděpodobně nehotovým překladem, protože CS a EN to vezme, ale DE a SK ne.

Ale dívám se, že na více místech je ta implementace připravená jen na dva jazyky. Tak to budu muset nějak předělat.

@zabak Bude teda potřeba udělat pořádný překlad Slovenčtiny a Němčiny.

**Comment by SPXcz** [comment]
V Difmoe nemají nemají žádné FAQ, footer a About jazykové soubory. Ty taky musíme nějak zajistit.

**Comment by honza-rychtar** [comment]
Na https://k7-test.mzk.cz/mzk je nová verze s přepínáním do 4 jayků.
<img width="474" alt="Snímek obrazovky 2021-09-17 v 12 02 11" src="https://user-images.githubusercontent.com/1178142/133765278-854e3cc6-77a3-4880-8fb2-bfeb26a19d11.png">

Slovenština je kompletní https://github.com/ceskaexpedice/kramerius-web-client/blob/master/src/assets/i18n/sk.json
Němčina je částečně převzata z https://www.difmoe.eu, zbytek doplníme společně s MZK
https://github.com/ceskaexpedice/kramerius-web-client/blob/master/src/assets/i18n/de.json
Chybějící překlady mají českou verzi s prefixem **__**

Pak ještě potřebujete doplnit slovenské a německé texty u zdrojů týkajících se konkrétní instalace.
To se týká stránky s informacemi, faq stránky a patičky.
Do konfigurace přidat cesty a vytvoříte nové lokalizované html stránky.
```
...
  faqPage: {
    cs: '/assets/shared/faq.cs.html',
    en: '/assets/shared/faq.en.html',
    de: '/assets/shared/faq.de.html',
    sk: '/assets/shared/faq.sk.html'
  },
  aboutPage: {
    cs: '/assets/shared/about.cs.html',
    en: '/assets/shared/about.en.html',
    de: '/assets/shared/about.de.html',
    sk: '/assets/shared/about.sk.html'
  },
  footer: {
    cs: '/assets/shared/footer.cs.html',
    en: '/assets/shared/footer.en.html',
    de: '/assets/shared/footer.de.html',
    sk: '/assets/shared/footer.sk.html'
  },
...
```
Pokud slovenskou a německou verzi v konfiguraci neuvedete, použije se anglická verze. Pokud by i anglická chyběla, použije se česká.

Podobným způsobem pak přidáte jazykové verze do konfigurace pro licence
```
...
      licences: {
        dnnto: {
          label: {
            cs: 'Díla nedostupná na trhu',
            en: 'Out of Commerce Works',
            de: '???',
            sk: 'Diela nedostupná na trhu'
          },
          message: {
            cs: '/assets/shared/licences/dnnto.cs.html',
            en: '/assets/shared/licences/dnnto.en.html',
            de: '/assets/shared/licences/dnnto.de.html',
            sk: '/assets/shared/licences/dnnto.sk.html'
          },
...
```

U licencí se dá nastavit i klasická hláška o nedostupnosti a mít ji teda na klientovi a ne v jádře Krameria a přidat tak slovenskou a německou verzi hlášky o nedostupnosti v klientovi
```
...
      licences: {
       ....
        _private: {
          label: {
            cs: 'Dokument není veřejně dostupný',
            en: 'The document is not publicly accessible',
            de: '???',
            sk: 'Dokument nie je verejne prístupný',
          },
          message: {
            cs: '/assets/shared/licences/_private.cs.html',
            en: '/assets/shared/licences/_private.en.html',
            de: '/assets/shared/licences/_private.de.html',
            sk: '/assets/shared/licences/_private.sk.html'
          },
        },
...
```

Na https://k7-test.mzk.cz/mzk/ jsou u MZK nakonfigurované a vytvořené texty u dnnto licence a obecné hlášky o nedostupnosti i pro slovenštinu.

**Comment by SPXcz** [comment]
Můžeme zavřít, ne?
