### ISSUE TITLE
Zkrácený název na kartě v seznamu výsledků vyhledávání

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#371]
Pokud je za kartě zobrazena jen část názvu, dát na konec zkráceného názvu tři tečky a po najetí kurzoru myši nad název (nebo kliknutí na ty tři tečky u dotykových rozhraní) zobrazit celý název.

**Comment by annie-cz** [comment]
Tohle je už hodně staré issue a nikdo se tu zatím nevyjádřil. Já se ale musím zeptat: proč bys to tam chtěl? Kdyby se mi takhle jako kurátorovi i jako obyčejnému userovi zobrazovaly výsledky vyhledávání, tak mi z toho asi hrábne. Strávím mnohonásobně více času prohlížením a bude mi trvat mnohem déle, než najdu to, co skutečně chci.

**Comment by zabak** [comment]
Tohel už je vyřešené přes ti íčko v pravém horním rohu karty. V podstatě jde o to, že kdyby to tam nebylo, tak musíš každou tu kartu rozkliknout, abys viděla celý název. Když víc názvů začíná stejně, potřebuješ je nějak rozlišit.

**Comment by annie-cz** [comment]
Super. Tak jak jsi to napsal mi to znělo, že bys to tak chtěl u vyhledávání, tak mě to trošku vyděsilo. :)
