### ISSUE TITLE
Řazení podle nejstarších - nejnovějších nefunguje v některých instalacích K5.5

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#373]
Verze 2.0.2

Příklady - zjednodušeno na monografie:

https://www.digitalniknihovna.cz/nlk/search?doctypes=monograph&sort=earliest
https://www.digitalniknihovna.cz/nlk/search?doctypes=monograph&sort=latest

https://www.digitalniknihovna.cz/ntk/search?doctypes=monograph&sort=earliest
https://www.digitalniknihovna.cz/ntk/search?doctypes=monograph&sort=latest

https://www.digitalniknihovna.cz/svkhk/search?doctypes=monograph&sort=earliest
https://www.digitalniknihovna.cz/svkhk/search?doctypes=monograph&sort=latest

V našem případě používáme SOLR 7.7.2 - verze [schématu 1.4](https://github.com/ceskaexpedice/kramerius/blob/master/installation/solr-7.x/kramerius/conf/managed-schema) a dokumenty se nově komplet reindexovaly pomocí /search/api/v4.6/processes?def=reindex

Tuším že to souvisí s polem **datum** podle kterého se to řadí:

 `&sort=datum asc` 

Když ho vyměním za:

 `&sort=datum_begin asc`  

\- tak to funguje o poznání [lépe](https://kramerius.medvik.cz/search/api/v5.0/search?q=*:*&fq=(fedora.model%3Amonograph%20OR%20fedora.model%3Aperiodical%20OR%20fedora.model%3Amonographunit)%20AND%20datum_begin%3A%20%5B1%20TO%203000%5D&fl=PID,dostupnost,fedora.model,dc.creator,dc.title,datum_str,datum_begin,datum_end,datum&facet=true&facet.mincount=1&facet.field=keywords&facet.field=language&facet.field=facet_autor&facet.field=model_path&facet.field=dostupnost&sort=datum_begin%20asc&rows=60&start=0&wt=json)

Z nějakého neznámého důvodu v našich SOLR dokumentech u monografií to pole chybí:

https://kramerius.medvik.cz/search/api/v5.0/search?q=(fedora.model:monograph) AND datum:[* TO *] AND datum_begin:[1 TO 3000]&fl=PID,datum_str,datum,datum_begin,datum_end&rows=60&start=0&wt=json

- respektive je jich tam jen 10:

https://kramerius.medvik.cz/search/api/v5.0/search?q=(fedora.model:monograph) AND datum:[* TO *]&fl=PID,datum_str,datum,datum_begin,datum_end&rows=60&start=0&wt=json

A u periodik máme jen 1 dokument s polem datum:

https://kramerius.medvik.cz/search/api/v5.0/search?q=(fedora.model:periodical)%20AND%20datum:[*%20TO%20*]&fl=PID,datum_str,datum,datum_begin,datum_end&rows=60&start=0&wt=json

**Comment by honza-rychtar** [comment]
Je to chyba, kterou jsem tam zanesl s napojením klienta na nový index, resp. mapování nových polí na starý index.
Má to být `datum_begin` u _Od nejstarších_ a `datum_end` u _Od nejnovějších_.
Opravím to.

**Comment by honza-rychtar** [comment]
Opraveno.
