### ISSUE TITLE
Typ strany "normální" strana

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#374]
Dobrý den, 

v KNAV jsme narazili na problém se zobrazením typu strany "Normální strana" (resp. myslím, že klient dříve zobrazovat "Strana") u monografií, i periodik. Ani po "najetí kurzorem myši" se nic nezobrazí, ale v MODSu je _type="NormalPage"_. 
Problém je v Digitální knihovně (nevím současnou verzi), tak v klientova KNAV (v 2.0.2). Např.: [Monografie](http://www.digitalniknihovna.cz/mzk/uuid/uuid:c98078fc-a354-414c-96f8-9545396b8d91), [Periodikum](https://kramerius.lib.cas.cz/uuid/uuid:ba8d6a7c-aef2-11ea-a22d-005056a2b051). 

Zdá se, že u ostatních typů stran ([Titulní strana](http://www.digitalniknihovna.cz/mzk/uuid/uuid:db35a340-8644-4046-9917-42494d7c44a6), [Obálka](https://dnnt.mzk.cz/uuid/uuid:2ceaa715-6f26-4341-8a31-364e56b775b5), [Obsah](https://dnnt.mzk.cz/uuid/uuid:25471dec-a635-464c-9884-ff995d7d6c0a), atd.) je to v pořádku. 

Děkuji, M. H.

**Comment by honza-rychtar** [comment]
_NormalPage_ je výchozí typ strany, který klient nezobrazuje.
Je to ze dvou důvodů
1. zobrazení Strana u stany nemá pro uživatele žádnou informační hodnotu
2. pokud se u běžných stran nezobrazuje typ, tak je jednoduší najít ty speciální typy (obsah, titulka, ...)

Ale je to k diskuzi.
Myslíte si, že by se měl zobrazovat typ strany i pro _normalPage_?

**Comment by tumovam** [comment]
Mně šlo spíš o to, že např. tato str.  http://www.digitalniknihovna.cz/knav/uuid/uuid:a4278f89-6a7b-4a25-9ed7-231e27252192 v klientovi žádný typ strany nemá, i přes to, že v MODS je type "NormalPage".

Zatímco hned další sken typ strany má - http://www.digitalniknihovna.cz/knav/uuid/uuid:c425c8c9-ae24-4291-b7cc-75c9eb45a2e6 

<img width="454" alt="Typstrany" src="https://user-images.githubusercontent.com/31240271/104162963-dde81700-53f5-11eb-8ba8-d7e559e557f4.png">


Já na tom v zásadě nelpím, jen jsem měla dojem, jestli to není bug... Díky :)

**Comment by honza-rychtar** [comment]
U toho druhého dokumentu chybí typy stran přímo v MODS objektech stran.

7. strana
```
...
<part type="NormalPage">
...
```
8. strana
```
...
<part type="NormalPage">
...
```

Neznámý typ stran se zobrazuje jako _Strana_.
To jsme změnil, by se neznámý typ strany taky nezobrazoval.
