### ISSUE TITLE
Při kopírování fulltextu se pokusit zachovat konce řádků

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#377]
Pokud je to možné, zachovat ve vybraném textu konce řádků. Využít tagu Textline v ALTO souboru. Jak při použití výřezu, tak při použití OCR celé stránky.

**Comment by honza-rychtar** [comment]
Udělal jsem to a funguje to dobře, jen ne vždy to zrovna na přehlednosti přidá. 

**Původní**
<img width="1486" alt="Snímek obrazovky 2022-04-05 v 15 47 44" src="https://user-images.githubusercontent.com/1178142/161769904-9fe73de4-c7ee-4d8c-a5a1-f5c5e2e20339.png">

**Nově se zalamováním z originálu**
<img width="1486" alt="Snímek obrazovky 2022-04-05 v 15 46 36" src="https://user-images.githubusercontent.com/1178142/161769979-f58945a2-4cb4-48bc-bfb6-662057e964dc.png">

Příklad z #369
<img width="1050" alt="Snímek obrazovky 2022-04-05 v 15 52 02" src="https://user-images.githubusercontent.com/1178142/161770079-fc776c84-61cd-4691-b4ee-192c809c2656.png">

@zabak Může to být takto?

**Comment by zabak** [comment]
Hezké to moc není, ale čte se mi to líp. Jak se to chová při zobrazení stránky z novin?

**Comment by honza-rychtar** [comment]
> Jak se to chová při zobrazení stránky z novin?

Musíš dlouho scrollovat
<img width="1790" alt="Snímek obrazovky 2022-04-06 v 12 21 24" src="https://user-images.githubusercontent.com/1178142/161954267-ea925cd4-7777-4fe2-bb62-4f72ea7ce6e9.png">

Bez zalamování se to vejde na obrazovku, ale je to docela chaos.
<img width="1792" alt="Snímek obrazovky 2022-04-06 v 12 22 03" src="https://user-images.githubusercontent.com/1178142/161954410-853e4d98-94a7-4cc5-b774-127b440bd59d.png">

**Comment by honza-rychtar** [comment]
@zabak Já tam to zalamování teda nechám jo.
Jinak technicky. 
U přepisu vybrané části stránky se text rozbije na jednotlivé `Textline`, kdy na konci každé se vloží nový řádek (`\n`). U vykreslení v dialogu se pak `\n` nahradí za `<br/>` a celé se to vykreslí jako html.
U přepisu celé strany se použije TXT stream a ten v sobě nové řádky má, takže dál se postupuje stejně jako u té části strany.

**Comment by zabak** [comment]
@honza-rychtar souhlasím. Jestli je u těch rozsáhlejších textů scrollbar, tak je to ok.

**Comment by zabak** [comment]
funguje, zavírám
