### ISSUE TITLE
Přihlašování do jiného Krameria

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#378]
Pro účely dnnt je potřeba přihlášení. Dokud nebude vyřešené https://github.com/ceskaexpedice/kramerius/issues/783 by se hodilo mít možnost v situaci kdy mám dva Kramerie se stejným obsahem, z nichž jeden je dnnt a druhý ne, aby v tom co není dnnt byl link na přihlášení do toho druhého. Stačí upravit

Příklad:
Jsem na 
https://www.digitalniknihovna.cz/mzk/view/uuid:40cfdf50-37da-11e3-a5bb-005056827e52?page=uuid:01dbaae4-d866-4e26-a5dd-866bb7eb6e71 
Tam bude možné přihlášení, které ale povede na dnnt: https://dnnt.mzk.cz/podminky-zpristupneni?target=https://dnnt.mzk.cz/view/uuid:40cfdf50-37da-11e3-a5bb-005056827e52 což uživatele po přihlášení hodí na tu stránku na které byl předtím, jen na jiném serveru. Předpokládám že bude potřeba udělat tu změnu, že nastavení dnnt je potřeba v konfiguraci přesunout k jednotlivým knihovnám v krameriusList

**Comment by honza-rychtar** [comment]
Vyřešeno přes dynamický placeholder v textu o nedostupném dokumentu (rightMsg).
Klient pak při zobrazení textu nahradí všechny výskyty **${UUID}** za skutečné uuid právě otevřeného dokumentu (v prohlížečce se použije uuid otevřené stránky).
Takže konkrétně tady je upravený text u Krameria MZK:

`...
Pro zobrazení dokumentu přejděte na přihlášení do <a href="https://dnnt.mzk.cz/podminky-zpristupneni?target=https://dnnt.mzk.cz/uuid/${UUID}">Národní digitální knihovny - Covid</a>
...`

Je to link na dnnt.mzk.cz, ale s dynamicky vloženým uuid. To ma za následek, že když v Digitální knihovně otevřu neveřejný dokument z MZK Krameria, tak mám v textu o nedostupnosti link na přihlášení do dnnt.mzk.cz, ale s předaným parametrem návratové stránky - stejné stránky jako jsem měl otevřenou v DK, ale teď se otevře v dnnt po přihlášení.

**Comment by zabak** [comment]
funguje, zavírám
