### ISSUE TITLE
Číslo

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#38]
Šlo by, aby se u čísla zobrazovalo nejen číslo (partNumber), ale taky název (pokud existuje - partName)? 
Protože když není číslo čísla vyplněné, tak to vypadá dost divně - příklad: Jitřenka: časopis pro zábavu a poučení   -třeba ročník 1902 - jsou tam čísla, označená jako číslo (číslo: 1), ale mezi nimi jsou přílohy a ty nemají nic, jen datum vydání. 

Chápu, že ten název čísla může být dost dlouhý, dal by se tam dát třeba jen začátek, např. dva řádky a pak tři tečky a celé by to bylo vidět až po rozkliknutí čísla v metadatech. 
Měl by někdo něco proti tomu?

**Comment by honza-rychtar** [comment]
Tohle se tyka priloh. To uz je castecne vyreseno, jen se mi tam ted vloudila chyba #42

**Comment by honza-rychtar** [comment]
Chyba u priloh opravena. PartName se dal resi zde #45
