### ISSUE TITLE
Chyba v zobrazování vniřních částí (internalPart) - článků.

### ISSUE THREAD

**Issue by MarekFiser** [ceskaexpedice/kramerius-web-client#386]
Pokud má dokument také svou vnitřní část, realizuje se její zobrazení - alespoň tedy v případě článků (MODS_ARTICLE) - v novém klientovi jako přívazek v přehledu jednotlivých čísel periodika přičemž link zavede uživatele na první stránku čísla. U některých článků ale toto nefunguje - všiml jsem si toho u našich dokumentů, ke kterým jsou ještě přiřazeny jako vnitřní části obrázky (MODS_PICTURE). U všech dokumentů s takovýmito metadaty nelze článek zobrazit, klient na proklik nereaguje. Je to například v tomto ISSUE - http://www.digitalniknihovna.cz/dsmo/uuid/uuid:41f4171a-1b57-4bd6-99da-f8e926706cd2 , kde při zobrazení lišty články odkazy na proklik nefungují. Ze všech článků lze pouze zobrazit pouze ten s názvem "Hitlerovo krédo", kde se obrázky a tudíž jejich objektová metadata nevyskytují - http://www.digitalniknihovna.cz/dsmo/uuid/uuid:cdfa6049-7266-11ea-b677-001b63bd97ba

**Comment by MarekFiser** [comment]
V různých verzích standardů NDK METS.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.4.7**
Klient stále nepodporuje model picture, ale v tomhle případě se jen vlastně našel první podobjekt článku typu strana. Tím se přeskočily ty obrázky a načte se pak správně první strana šlánku.
Podporu obrázků řešme dál v #385

**Comment by zabak** [comment]
Funguje
