### ISSUE TITLE
Zvolené licence se nezobrazují v aktivních filtrech

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#389]
Pokud zvolím licenci např. Covid - zmizí z nabídky licencí, ale již se nezobrazí v aktivních filtrech (viz. screen)

![Snímek z 2021-03-17 15-16-37](https://user-images.githubusercontent.com/33415849/111482178-efbaa300-8733-11eb-808a-fe9a9f150201.png)

**Comment by jahhoo** [comment]
Omlouvám se, chyba při mergování.

**Comment by honza-rychtar** [comment]
@jahhoo je už někde dostupná nová verze jádra Krameria nad ostrými daty, že bych nad tím vyzkoušel ještě ty další změny kolem labelu na straně klienta.
