### ISSUE TITLE
Našeptávač - diakritika 

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#39]
Našeptávač by měl fungovat i když píšu bez diakritiky.  Když vyhledávám bez diakritiky, tak to ten dokument ve výsledku najde, ale neukáže v našeptávači. 
Je to určitě lepší i kvůli mobilům, kde asi nikdo nepíše háčky a čárky.

**Comment by honza-rychtar** [comment]
Hledani bez diakritiky je závislé v verzi indexu. Použití lemmatizace u našeptávače je teď součásti konfigurace. 
Na http://kramerius.rychtar.cloud/knav mají knihovny s novější verzi Krameria včetně KNAV zapnutou lemmatizaci u našeptávání, takže našeptávač pak funguje i bez diakritiky.
