### ISSUE TITLE
Custom textove hlasky - Pridat podporu pro licence - labels

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius-web-client#390]
Prosim o pridani podpory pro label s jadra. Pri jejich zobrazovani / nezobrazovani by melo byt mozno konfigurovat text a hlasky v zavislosti na druhu konkretni licence pomoci konfigurace.

**Comment by jahhoo** [comment]
Pro NK vyřešeno https://github.com/NLCR/kramerius-web-client/commit/c51bdbc951b129c739340a266e5bce5fe4dc6764

**Comment by zabak** [comment]
Navrhuji uzavřít, řeší verze 2.1.1

**Comment by zabak** [comment]
Považuji za vyřešené, @janmeritus pokud byste to potřebovali nějak upravit, založte prosím nové issue.
