### ISSUE TITLE
Nefunkční změna zdrojového Krameria

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#397]
Pokud ve výsledcích hledání otevřu nějaký dokument a pak se vrátím zpět do výsledků hledání, tak nefunguje změna zdrojového Krameria přes zobáček u počtu výsledků.
<img width="300" alt="Snímek obrazovky 2021-03-31 v 15 21 36" src="https://user-images.githubusercontent.com/1178142/113150935-e271de00-9234-11eb-985b-6854cc9dc1f1.png">

Seznam Krameriu se zobrazí, ale nefunguje klik na položku.
<img width="585" alt="Snímek obrazovky 2021-03-31 v 15 18 45" src="https://user-images.githubusercontent.com/1178142/113150943-e6056500-9234-11eb-8a6a-ca8fe962c241.png">

**Comment by honza-rychtar** [comment]
Opraveno.

**Comment by zabak** [comment]
Otestováno v 2.3.2, zavírám
