### ISSUE TITLE
Citování stránky

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#399]
Dobrý den,
uživatelé nás upozornili, že máme chybu v citaci stránky periodika, ale chybu máme i v citaci strany monografie.

Monografie nyní: JIRÁČEK, Pavel. Od slov k lyrickému vědomí. Brno: Středoevropské centrum slovanských studií, 2020. s. 8. ISBN 978-80-88296-12-6. Dostupné také z: http://www.digitalniknihovna.cz/knav/uuid/uuid:53c25eb9-5bb0-4c19-ae04-be612e50233a

Mělo by být: JIRÁČEK, Pavel. Od slov k lyrickému vědomí. Brno: Středoevropské centrum slovanských studií, 2020, (**ČÁRKA!**) s. 8. ISBN 978-80-88296-12-6. Dostupné také z: http://www.digitalniknihovna.cz/knav/uuid/uuid:53c25eb9-5bb0-4c19-ae04-be612e50233a

Citace stránky periodika nyní: Živa: časopis přírodnický. 1853-1914. Praha: Matice česká při Museu Království českého, 1972, 20(5). s. 161. ISSN 0044-4812. Dostupné také z: http://www.digitalniknihovna.cz/knav/uuid/uuid:e5044bc5-e6c5-47f5-896d-7997a5cf4f04

Správně by mělo být za ročníkem a čísle čárka: Živa: časopis přírodnický. 1853-1914. Praha: Matice česká při Museu Království českého, 1972, 20(5), (**ČÁRKA!**) s. 161. ISSN 0044-4812. Dostupné také z: http://www.digitalniknihovna.cz/knav/uuid/uuid:e5044bc5-e6c5-47f5-896d-7997a5cf4f04

Citace článku (PDF) je v pořádku: CERMAN, Ivo. Evropské osvícenství Jonathana Israele. Cornova: revue České společnosti pro výzkum 18. století. Praha: Česká společnost pro výzkum 18. století, 2011, 1(1), 27-50. DOI: https://doi.org/10.51305/cor.2011.01.02. ISSN 1804-6983. Dostupné také z: http://www.digitalniknihovna.cz/knav/uuid/uuid:08170dca-cbea-4b65-a195-9162896bc0ae

Děkujeme na opravu, 
KNAV

**Comment by honza-rychtar** [comment]
Opraveno. Mělo by fungovat hned ve všech klientech kromě NK.

**Comment by tumovam** [comment]
Otestováno. Funguje. Issue zavírám. Děkuji
