### ISSUE TITLE
Noviny a časopisy - navigace

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#4]
Z nejnižší úrovně časopisu (tj. úroveň kde už jsou skeny) se není možné dostat na vyšší úroveň. Tlačítko "zpět" nefunguje, ale až bude fungovat vrátí mě o stránku zpět nebo na seznam výsledků vyhledávání? Název periodika vpravo v metadatech by mohl být proklikávací na nejvyšší úroveň periodika. Tak by se uživatel jednoduše dostal zpět.

**Comment by honza-rychtar** [comment]
V pripade cisla periodika bude vpravo v metadatech navic moznost prechodu na predchozi/nasledujici cislo a na uroven vys, tj. seznam cisel.

Az bude tlacitko zpet funkcni, tak bude fungovat jako prechod o uroven vys. takze i kdyz uzivatel proklika v prohlizecce deset stran, tak zpet ho veme tam, odkud se do prohlizecky proklikl. To muzou byt vysledky hledani, rocnik periodika nebo hlavni stranka. 
Zpet bude fungovat i bez historie, takze pokud jsem do aplikace prisel primo do prohlizecky a nemam zadnou historii, tak v pripade cisla periodika me zpet dostane na rocnik periodika a vse ostatni na hlavni stranku.

**Comment by honza-rychtar** [comment]
Tlacitko zpet funguje, zbytek #10 a #26
