### ISSUE TITLE
Pridat podporu clanku

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#40]
Dva typy clanku
1) Na urovni **periodicalitem**, kde jsou **article**s, ktere pod sebou obsahuji **page**s, ktere jsou zopakovane taky primo pod **periodicalitem**
2) Na urovni **periodicalitem**, kde jsou jen **article**s, ktere obsahuji (jednostrankove i vicestrankove) PDF - toto bude potreba prochazet jinak - vlevo nebudou stranky, ale clanky,
Tohle ma (pouze??) KNAV

**Comment by filak** [comment]
co take u periodicalvolume? napr. sborniky, rocenky

**Comment by filak** [comment]
Ještě máme také úplně samostatné články:

http://kramerius.medvik.cz/client/handle/uuid:9e0876a9-1ad9-4115-8c53-449ae3560672

http://dev.medvik.cz/wck/view/uuid:9e0876a9-1ad9-4115-8c53-449ae3560672

Jinak články se ve web-client aktuálně neukazují:
http://dev.medvik.cz/wck/search?ordering=newest&doctypes=article

**Comment by krizovj** [comment]
Nám se také články nezobrazují

**Comment by honza-rychtar** [comment]
Pridana podpora clanku na urovni cisla periodika.
1) Stranky + clanky
http://mzk.kramerius.rychtar.cloud/uuid/uuid:5678e344-435f-11dd-b505-00145e5790ea
Taby **Stranky** a **Clanky**. Stranky funguji klasicky. Clanky pak filtruji jen stranky s clankem. Na clanky je mozne primo linkovat - http://mzk.kramerius.rychtar.cloud/uuid/uuid:cadd52a3-46c1-49e6-a4d0-47905f353efd
2) PDF clanky (bez stranek)
http://knav.kramerius.rychtar.cloud/uuid/uuid:089eaf3b-753e-44f6-adbc-32ea0f13fe10
Seznam clanku. Je mozne linkovat na konkretni clanek.

**Comment by krizovj** [comment]
Ještě bychom tam potřebovali přidat ta metadata k článku a taky by ten článek měl jít stáhnout.

**Comment by krizovj** [comment]
Tak články fungují, ale nějak divně. Zobrazí se jenom když se na to konkrétní číslo dostanu z "Doporučených", ale když tam chci vlézt třeba ze seznamu čísel v ročníku, tak se články neukážou.

**Comment by honza-rychtar** [comment]
@krizovj Aha, zanesl jsem tam nejakou chybu. Do pondelka to opravim.

**Comment by honza-rychtar** [comment]
Chybu jsem opravil a pridal metadata k clankum (#14)

**Comment by LenkaKravecova** [comment]
Mám k tomuto dotaz. Jde jen o podporu prohlížení článků? Vyhledávání článků se zatím neřešilo? Chci např. vyhledat článek "Šest století". Vím, že je v Lidových novinách, ale vůbec netuším rok vydání..
