### ISSUE TITLE
Nekonzistentní výsledky vyhledávání

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#400]
Dotaz:  Abecední sbírka zákonů říšských a zemských řezníček

https://www.digitalniknihovna.cz/mzk/search?q=Abecedn%C3%AD%20sb%C3%ADrka%20z%C3%A1kon%C5%AF%20%C5%99%C3%AD%C5%A1sk%C3%BDch%20a%20zemsk%C3%BDch%20%C5%99ezn%C3%AD%C4%8Dek
          
- kliknu na výsledek (kniha) => 

Upozornění! Nebyly nalezeny žádné výsledky. Prosím, zkuste jiný dotaz.

**Comment by filak** [comment]
V K7 se to chová pořád stejně:

https://k7-test.mzk.cz/mzkk7/search?q=Abecedn%C3%AD%20sb%C3%ADrka%20z%C3%A1kon%C5%AF%20%C5%99%C3%AD%C5%A1sk%C3%BDch%20a%20zemsk%C3%BDch%20%C5%99ezn%C3%AD%C4%8Dek

**Comment by filak** [comment]
Tak v K7 to už funguje, na digitalniknihovna.cz zatim ne.

**Comment by filak** [comment]
Na digitalniknihovna.cz uz to funguje.

Na k7-test.mzk.cz zda se taky, akorat v title tagu se objevuje *undefined*:

          1. undefined | Abecední sbírka zákonů říšských a zemských jakož i | MZK K7 | Digitální knihovna Kramerius

**Comment by zabak** [comment]
@honza-rychtar navíc se v tomto případě ani na kartě části se nezobrazuje název části, 
![image](https://user-images.githubusercontent.com/811537/133692436-909a9101-9422-4ea1-94d2-d58e2848ff86.png)

Možná je tam ale nějaká chyba v datech...?

**Comment by honza-rychtar** [comment]
@zabak Kde to zkoušíš? Ono to název části nemá, ale tobě to na tom sreenshotu neukazuje ani číslo části, autora a datum, což by se zobrazovat mělo.

MZK
https://k7-test.mzk.cz/mzk/periodical/uuid:9ab8db80-c5d9-11e6-bf97-005056825209

<img width="524" alt="Snímek obrazovky 2021-09-17 v 9 55 05" src="https://user-images.githubusercontent.com/1178142/133746222-7fdfe93a-1f57-4787-b93b-f3ac12cd4867.png">
MZK K7
https://k7-test.mzk.cz/mzkk7/periodical/uuid:9ab8db80-c5d9-11e6-bf97-005056825209

<img width="523" alt="Snímek obrazovky 2021-09-17 v 9 54 49" src="https://user-images.githubusercontent.com/1178142/133746257-4bf683cf-1cba-4ba7-b065-9eb9a6654c7d.png">

Tady opravím ten **undefined**.

**Comment by zabak** [comment]
@honza-rychtar to mi dělá https://k7-test.mzk.cz/mzkk7/periodical/uuid:9ab8db80-c5d9-11e6-bf97-005056825209?fulltext=Abecedn%C3%AD%20sb%C3%ADrka%20z%C3%A1kon%C5%AF%20%C5%99%C3%AD%C5%A1sk%C3%BDch%20a%20zemsk%C3%BDch%20%C5%99ezn%C3%AD%C4%8Dek

**Comment by filak** [comment]
Zdá se vyřešeno, zavírám.
