### ISSUE TITLE
K7 - Obzory - nezobrazují se čísla v ročníku 1945 - nad K5 se zobrazují v pořádku

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#401]
https://k7-test.mzk.cz/mzkk7/periodical/uuid:654819b0-f362-11ea-9c2e-005056827e51

https://www.digitalniknihovna.cz/mzk/periodical/uuid:654819b0-f362-11ea-9c2e-005056827e51

**Comment by honza-rychtar** [comment]
Ty stránky chybí v indexu. Zkusil jsem přeindexovat a v logu no hlásí I/O error při načtení. Takže chybí soubory, což nejspíš vzniklo migrací dat do Akubry. Prověříme to.

**Comment by rzeh4n** [comment]
Doplním Honzu: nejde o chybějící objekt, ale datastream TEXT_OCR. Bude to buď skutečně v datech, nebo v logice jádra při přístupu k soubor s textovým přepisem.

**Comment by rzeh4n** [comment]
Tak je to v datech, dále řešíme.

**Comment by rzeh4n** [comment]
Opraveno v datech, reindexováno. Problém nastal při replikaci repozitáře pro K7, přesnou příčinu se dohledat nepodařilo. Takže není vyloučeno, že na stejný problém nenarazíme někde jinde.
