### ISSUE TITLE
Nefunguje Vyhledavání sbírky

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#402]
Ve virtuálních sbírkách nefunguje pole "Vyhledat sbírku...". 

![obrazek](https://user-images.githubusercontent.com/31240271/115675840-42990300-a34f-11eb-9974-496930e9dffb.png)

Vyzkoušeno v klientovi KNAV, ale i v Digitalniknihovna.cz (KNAV, NDK, NTK, MLP, ne na datech MZK, ti mají jiné - hezčí :) virtuální sbírky).

Zároveň v KNAV nefunguje Abecední řazení, může to souviset se špatným zaindexováním?

Děkuji

**Comment by honza-rychtar** [comment]
U toho hledání je tam chyba. Názvy sbírek nejsou zaindexované, stejně tak názvy typů dokumentu, jazyků a míst uložení. U těchto 4 polí jsou zaindexovány jen kódy a zobrazení lokalizovaného názvu probíha až na klientovi.
Takže vyhledávací dotaz u těchto polí nemá jít do indexu, ale do v klientovi už namapovaných lokalizovaných názvů.
Tohle se v nějaké verzi pokazilo, protože to určitě fungovalo. Opravím.

> Zároveň v KNAV nefunguje Abecední řazení, může to souviset se špatným zaindexováním?

Ono funguje, ale 4 z těch sbírek mají v názvu mezeru na začátku, takže se vlastně seřadí nejdříve tyto 4 a pak za nimi zbytek.

```
...
"descs": {
  "cs": " Biologické centrum AV ČR",
  "en": "Biology Centre of the CAS"
},
...
```

Opravím to, aby se mezery na začátku ořezávaly ještě před řazením.

**Comment by zabak** [comment]
U sbírek MZK v K5 se nezobrazí  boční lišta, kde je to hledání, takže jakmile se přejde v K5 na hezké sbírky, tak funkce vyhledat sbírku není vůbec k dispozici. V K7 to funguje jinak a funguje i vyhledávání sbírek. Vzhledem k tomu, že v K5 je u sbírek problém v indexaci a v K7 to funguje, navrhuji toto issue zavřít.

**Comment by honza-rychtar** [comment]
Problém s vyhledáváním na straně klienta lokalizovaných názvů (sbírky, místa uložení, jazyky a typy dokumentů) jsem opravil.
Odstranil jsem mezery před a za názvy, což způsobovalo špatné řazení u sbírek KNAV.
Bude součásti příští verze koncem tohoto týdne.

**Comment by kerschfilip** [comment]
za KNAV zkontrolováno, vše funguje. Děkujeme a myslím, že issue lze uzavřít.
