### ISSUE TITLE
podpora pro oldprintsheetmusic

### ISSUE THREAD

**Issue by fstepanovsky** [ceskaexpedice/kramerius-web-client#404]
Potřeba přidat překlady pro oldprintsheetmusic:
![obrazek](https://user-images.githubusercontent.com/3747619/117775911-437cd080-b23b-11eb-8756-15eb6da91f21.png)

Nezobrazují se metadata pro root uuid:
![obrazek](https://user-images.githubusercontent.com/3747619/117776147-8343b800-b23b-11eb-947b-6ae3e564f646.png)

Ukázkový dokument: http://www.digitalniknihovna.cz/mzk/view/uuid:3a3c523e-c80b-4a44-9b12-1c2492c05de7

**Comment by honza-rychtar** [comment]
@fstepanovsky kde se vzal ten model? Staré tisky mají vlastní model v ProArcu, ale ne v Krameriovi.
A u konvolutu se v Krameriovi zavádí pouze model kořenového konvolutu oldprintomnibusvolume, ale vše pod konvolutem už mají být klasické modely. 
ProArc -> Kramerius
oldprintomnibusvolume -> oldprintomnibusvolume
oldprintmap -> map
oldprintsheetmusic -> sheetmusic
....

Takže oldprintsheetmusic není validní model pro Krameria.

**Comment by fstepanovsky** [comment]
@honza-rychtar vzal se tam přes k4 export

Dobře, takže je potřeba zjistit, proč se to exportuje, tak jak se to exportuje.
Nepřišlo mi to divné, protože jsem si myslel, že modely proarc - kramerius mají být 1:1

Tím pádem zavírám, díky za info.
