### ISSUE TITLE
K7 - nefunguje generování PDF - status 404

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#405]
Například:

https://k7-test.mzk.cz/uuid/uuid:e9d6c24b-ab27-4697-a881-51caa56179af

https://k7-test.mzk.cz/search/api/client/v7.0/pdf/selection?pids=uuid:e9d6c24b-ab27-4697-a881-51caa56179af,uuid:ed78e6c0-f9fe-4c9d-9dad-69271a7092c1&language=cs

**Comment by filak** [comment]
Příprava k tisku jinak funguje:

https://k7-test.mzk.cz/search/localPrintPDF?pids=uuid:e9d6c24b-ab27-4697-a881-51caa56179af,uuid:34065b25-6a95-46af-958e-6113a1fcd9ea&pagesize=A4&imgop=FULL

**Comment by honza-rychtar** [comment]
Tohle už bylo v K7 jádře opraveno.

**Comment by zabak** [comment]
Opraveno to bylo, ale pořád tam jsou letité problémy - negeneruje to textovou vrstvu (není zapnutá, nebo to K7 vůbec neumí) takže nemůžu posoudit jestli je pořád pounutá oproti obrázku, stránky pdf by měly mít stejnou velikost jako originál  a ne generickou A4 apod. Tady zavírám.
