### ISSUE TITLE
Našeptávač a dvojtečka

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#407]
Pokud je v názvu samostatně stojící dvojtečka a vybere se z našeptávače do vyhledávacího dotazu, nic se nenajde.
Testováno na https://k7-test.mzk.cz/knav

Zadat slovo právník a vybrat první výskyt:
Právník: časopis věnovaný vědě právní i státní, jejž vydává Právnická jednota v Praze : -1956

Nic to nenajde, když se odmaže ta dvojtečka před -1956 tak se najde.

**Comment by tumovam** [comment]
Stejný problém máme s **lomítkem**. Např. časopis "A / Věda a výzkum" nebo "Gender a výzkum / Gender and Research" . Když se odmaže "/", tak se periodikum najde. 

Obdobně klient nenajde časopis, v jehož názvu jsoou **pomlčky**. Př. "Korpus - gramatika - axiologie".

A vypadá to, že problém má i s **dvojtečkou**, případně s **rovnítkem** (rovná se). Např. " Geofysikální sborník = Geofizičeskij sbornik = Travaux géophysiques".

Vím,e že to je částečně způsobené i chybou v datech, ale bohužel, jsou to velká periodika a bojíme se oprav a úprav... 

Testováno také v https://k7-test.mzk.cz/knav

**Comment by zabak** [comment]
Otesstováno v 2.1.3, zavírám
