### ISSUE TITLE
API volání pro BIBLIO_MODS odesílá ve své adrese "undefined" místo uuid

### ISSUE THREAD

**Issue by SPXcz** [ceskaexpedice/kramerius-web-client#408]
Do svého Krameria jsem zatím  nahrál asi 30 knih a všechny se zobrazují jak mají, kromě [uuid:ecff4bf0-0135-11ea-a20e-005056827e51](https://ds-coil.uibk.ac.at/view/uuid:ecff4bf0-0135-11ea-a20e-005056827e51).

U této knihy selže volání BIBLIO_MODS XMLek, protože místo https://backend.ds-coil.uibk.ac.at/search/api/v5.0/item/uuid:ecff4bf0-0135-11ea-a20e-005056827e51/streams/BIBLIO_MODS se zavolá https://backend.ds-coil.uibk.ac.at/search/api/v5.0/item/undefined/streams/BIBLIO_MODS (tudíž to asi nemůže najít to uuid). Například, když se ale volá /search/api/v5.0/item/\<uuid>, tak se tam normálně vloží to uuid.

Nejsem si ale jistý, jestli se jedná o problém klienta nebo K5

Ve zdroji (DK) se ale kniha [zobrazuje správně](http://www.digitalniknihovna.cz/mzk/view/uuid:ecff4bf0-0135-11ea-a20e-005056827e51?page=uuid:ff3b9a51-0a9f-4e52-b0a3-22c89882128f).

Dole mám výpis HTTP dotazů zaznamenaných Firefoxem.
![Screenshot from 2021-06-04 16-18-20](https://user-images.githubusercontent.com/55412542/120815904-8edf8180-c550-11eb-9482-3b0050ef0e77.png)

Předem děkuji za pomoc.

**Comment by honza-rychtar** [comment]
Ten dokument není zaindexovaný - https://backend.ds-coil.uibk.ac.at/search/api/v5.0/search?q=PID:%22uuid:ecff4bf0-0135-11ea-a20e-005056827e51%22
V DK zaindexovaný je https://kramerius.mzk.cz/search/api/v5.0/search?q=PID:%22uuid:ecff4bf0-0135-11ea-a20e-005056827e51%22

Je to jeden svazek vícesvazkové monografie. Nevzniklo to pokusem o indexaci pouze toho svazku bez nadřazené monografie?

**Comment by SPXcz** [comment]
Dívám se na to a je to tak - asi je to opravdu tou indexací.
