### ISSUE TITLE
Dát tooltip na celý objekt

### ISSUE THREAD

**Issue by SykoraLukas** [ceskaexpedice/kramerius-web-client#409]
Pokud má vícesvazek pod sebou monografii s dlouhým názvem, zobrazí se jen část (zbytek zůstává skrytý). Dole na ikoně "část" se zobrazí celý název. Ideální by bylo, aby tooltip s celým název se zobrazil nad celým objektem.

![image](https://user-images.githubusercontent.com/27210823/122025821-f6f05c00-cdc9-11eb-9c8f-08d47c0a6e1b.png)

![image](https://user-images.githubusercontent.com/27210823/122025894-0a9bc280-cdca-11eb-85d4-6e282a210123.png)

**Comment by zabak** [comment]
otestováno na 2.1.3, zavírám
