### ISSUE TITLE
Špatné řazení svazků pojmenovaných kombinací čísla a písmena

### ISSUE THREAD

**Issue by marketakrutska** [ceskaexpedice/kramerius-web-client#410]
V MZK jsme narazili na vícesvazek, u kterého jsou některé svazky pojmenované kombinací čísla a písmena - např. 11a, 11b. Tyhle svazky se řadí až na konec, a tudíž to není seřazené správně: http://www.digitalniknihovna.cz/mzk/uuid/uuid:69776d40-ea29-11e3-8e46-5ef3fc9ae867 

V K7 to vypadá stejně: https://k7-test.mzk.cz/uuid/uuid:69776d40-ea29-11e3-8e46-5ef3fc9ae867

Šlo by tohle nějak ošetřit, abychom si nemuseli upravovat metadata?

**Comment by honza-rychtar** [comment]
Problém je v pořadí RELS-EXT vazeb jednotlivých svazků - takto je to v datech seřazeno.
Nejdříve se vše (ročníky, výtisky, vícesvazky) řadily přes RELS-EXT index a dalo se to manuálně upravit přes editor vazeb.
Pak se vše bralo z indexu a řadilo se automaticky přes nějaké pole (datum, výtisky, název).
A nakonec se to dělá tak, že ročníky a výtisky se řadí automaticky přes pole z indexu a vícesvazky se řadí přes RELS-EXT index - je to optimálnější, protože narozdíl od ročníku a výtisků často nemají data, pro automatické seřazení. Takže data jednotlivých svazků nemají na řazení vliv a řazení jde změnit v editoru částí.

V K7 toto chování zůstává a vícesvazky se řadí podle RELS-EXT indexu. Alternativu k editoru částí přidáme do nového admin rozhraní.

**Comment by marketakrutska** [comment]
Ještě než issue uzavřu - editor částí už v K7 je? Já ho tam nikde nevidím.

**Comment by honza-rychtar** [comment]
@marketakrutska Editor částí ještě není hotový, ale je naplánovaný. Ten budeme dále řešit v rámci adminu https://github.com/ceskaexpedice/kramerius-admin-client/issues/25
Tady to můžeme teda zavřít.

**Comment by marketakrutska** [comment]
Dobře, díky, tady uzavírám.
