### ISSUE TITLE
anonymizace IP adres v Google analytics

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#412]
Abychom eliminovali potenciální GDPR problém s Google Analytics, je nutné anonymizovat IP adresy v Google Analytics. Anonymizuje se poslední bajt adresy. Část nastavení se dělá v rozhraní GA (viz např. zde: https://www.martindomes.cz/jak-nastavit-google-analytics-vzhledem-k-narizeni-gdpr/ ) ale musí se změnit i nastavení sbírání na straně webu: https://support.google.com/analytics/answer/2763052?hl=cs 

Řeší tento pull request: https://github.com/ceskaexpedice/kramerius-web-client/pull/411

**Comment by honza-rychtar** [comment]
@zabak tohle už je dávno začleněné. Můžeme uzavřít.
