### ISSUE TITLE
Podpora Google Analytics 4

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#413]
Kramerius klient používá Universal Analytics (analytics.js).
V novém Google Analytics 4 už se přešlo primárně na gtag.js

Tady je návod na to, jak v Google Analytics 4 získat měřící kód Universal Analytics pro Krameria.
https://support.google.com/analytics/answer/10269537?hl=cs

Musí mít prefix **UA-** (ne **G-**)

Přidat do klienta podporu pro analytics.js i gtag.js
V konfiguraci by se potom uvedl měřící kód pro vybranou službu.

**Comment by honza-rychtar** [comment]
Přidáno ve verzi 2.4.9
V konfiguraci vyplňte měřící kód 
```
APP_GLOBAL.ga4: 'G-XXX'
```
Možno (a doporučeno) použít souběžně s Universal Analytics (`APP_GLOBAL.ga`).
Universal Analytics končí 1.7.2023. Ve verzi vydané po tomto datu už se bude v konfiguraci ignogorovat.

Fungování Google Analytics 4 v klientovi není finální a bude se postupně ladit a upravovat na základě zpětné zkušeností z provozu.

**Comment by mduda100871** [comment]
Ahoj,

možná mi něco uniká, ale nahoře se píše, že kód musí mít prefix `UA-`, ale dále se pak zase používá prefix `G-`.

Co je tedy správně?

Díky, MD

**Comment by honza-rychtar** [comment]
Ten původní komentář se týkal stavu v té době před 2 lety. Používal se Universal Analytics a prefix musel být UA-.
Teď s podporou Google Analytics 4 musí být prefix G-.
Doplnil jsem to do popisu konfigurace https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta
Ale pořád je možné mít Universal Analytics i Google Analytics 4.
V příští verzi klienta už bude možné použít pouze Google Analytics 4 a s tím taky vyhodím z dokumentace všechny zmínky o UA a tím se to zjedodužší.
