### ISSUE TITLE
Label DNNT-T před/po přihlášení - odlišení od DNNT-O

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#415]
Po dohodě s kurátory mezi NK a MZK bychom potřebovali přenastavit následující chování labelu DNNT-T:

**Nyní (dokud služba terminálů není funkční):**

Nepřihlášení uživatelé: klasický šedý zámeček
Přihlášení uživatelé: též klasický šedý zámeček do doby, než bude služba funkční. 

**Později (jakmile budou terminály funkční):**

Nepřihlášení uživatelé: klasický šedý zámeček
Přihlášení uživatelé: zámeček/přeškrtnutý foťáček nebo cokoli jiného, ale **odlišit barevně** od DNNT-O

Je třeba, aby se to vizuálně nepletlo a uživatele to nerozčilovalo, aktuálně uživatele spíše mystifikujeme, že se k něčemu dostane, ale následně mu odepřeme přístup. Viz např. https://dnnt.mzk.cz/search?licences=dnnto&from=2000&to=2007

**Comment by honza-rychtar** [comment]
Varianta **Nyní** 
Takto se to teď chová, protože můžu v konfiguraci licenci vypnout (resp. ji nekonfigurovat), čímž ji klient ignoruje a pokud je teda dokument private a dnntt, zachází s ním jako jen s private dokumentem.

Varianta **Později**
Ok, můžeme do konfigurace přidat obrázek licence. Ať už různě barevné zámečky nebo třeba creative commons piktogramy.
Je otázka, jestli by každá licence měla mít svůj obrázek pro přístupnou i nepřístupnou verzi (uživatel má/nemá přístup k licenci) jako je teď oranžový zámek a oranžový foťák.

**Comment by JanMeritus** [comment]
@honza-rychtar v jakom je to stavu premysleno do budoucna?

**Comment by annie-cz** [comment]
Jelikož začaly být v provozu terminály ve studovnách i na klientovi, tak bychom toto měli dořešit.

**Comment by honza-rychtar** [comment]
Vyřešeno přes #467
