### ISSUE TITLE
DNNT - změna ve fasetách dostupnosti před/po přihlášení

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#416]
V rámci dohod kurátorů NK x MZK bychom rádi navrhli změnu ve fasetách v rámci DNNT:

Faseta dostupnost:

Bez přihlášení - dostupnost: Pouze veřejné / Pouze neveřejné / Pouze po přihlášení; 
Po přihlášení - tak jak je to nyní, tj. 

![image](https://user-images.githubusercontent.com/43028501/129761763-edd20813-e25e-452c-84ef-450f835768de.png)

**Comment by honza-rychtar** [comment]
Ok, jen to trochu upravme. Licence nevyžadují přihlášeného uživatele. Klient ví, k jakým licencím ma aktuální uživatel přístup a podle nich dělá ten dotaz pro **Všechny dostupné dokumenty** a zobrazuje zámečky ve výsledcích hledání.
Takže Všechny dostupné dokumenty skryjme ne u nepřihlášeného uživatele, ale u uživatele, který nemá přiřazeny žádné licence.

**Comment by honza-rychtar** [comment]
Můžeme zavřít?
