### ISSUE TITLE
DNNT-O - změna hlášky "dokument není veřejně přístupný" na "... je dostupný po přihlášení"

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#417]
Dle dohody kurátorů NK x MZK: 

U dokumentů pod licencí dnnt-o je třeba změnit hlášku  “dokument není veřejně přístupný” na “dokument je dostupný po přihlášení” (aby klient postupoval podle toho, co je napsané v labelu, tj. aby neoperoval jen s příznakem private); později bude úplně stejně potřeba to vyladit u dnnt-t. Změna je nutná, aby si v podstatě neodporovaly na venek informace, které uživateli dáváme a je třeba ho co nejvíce navést k tomu, aby se přihlásil a tu službu využil.

**Comment by honza-rychtar** [comment]
Myslíš tyto dva výskyty?
<img width="1436" alt="Snímek obrazovky 2021-08-17 v 19 10 24" src="https://user-images.githubusercontent.com/1178142/129770679-2a393134-ba7b-460d-9f11-143688a0d06b.png">

Tady zase narážíme na obecnost licencí. 
**Dokument není veřejně přístupný** je obecný fakt. Jednotlivé licence a obecný text u neveřejného dokumentu pak vysvětlují jednotlivé možnosti přístupu k dokumentu.
**Dokument je dostupný po přihlášení** nemusí být pravda, protože to není dostatečná podmínka, pokud se přihlásím účtem s nedostatečným oprávněním, ale ona to ani není nutná podmínka, pokud má dokument více licencí a některá mi dokument zpřístupní i bez přihlášení, např. na vyhrazených terminálech.

**Comment by zabak** [comment]
Jinými slovy jako nadpis dát něco jako "Přístup k dokumentu omezen" a místo podnadpisu Dílo nedostupné na trhu dát "Dokument přístupný po přihlášení" kde už to "po přihlášení" by byl link?

**Comment by honza-rychtar** [comment]
Takže? Je možné vyřešit tlačítkem v konfigurovatelném popisu licence?

**Comment by honza-rychtar** [comment]
Už neaktuální, řeší se v rámci #629
