### ISSUE TITLE
DNNT - zobrazení labelu ve svazcích vícesvazku

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#418]
U vícesvazku má kořenové uuid label dnnt-o, jednotlivé svazky se ale navenek tváří jako public, nicméně jakmile je člověk otevře, dozví se, že jsou pod dnnt-o a musí se přihlásit, pokud se k nim chce dostat. Logika je takto stejná jak před/po přihlášení. Bylo by skvělé, kdyby se i na úrovni vícesvazku objevoval oranžový zámeček/přeškrtnutý foťáček, aby bylo na první pohled jasné, že jednotlivé svazky jsou skutečně přístupné/nepřístupné v nějakém režimu. Navíc se může teoreticky stát, že jeden svazek bude dnnt-o a další ne a pak to bude velice chaotické.

Viz: https://dnnt.mzk.cz/periodical/uuid:9a5e0e22-67af-11eb-ae93-0242ac130002

![image](https://user-images.githubusercontent.com/43028501/129764008-43ba74e9-e54a-45b3-8370-e5d6e4de9177.png)

![image](https://user-images.githubusercontent.com/43028501/129764127-2034d499-9cd1-4387-b3f2-46eb7de360a5.png)

**Comment by honza-rychtar** [comment]
O tom jsem se bavili. Už je to opraveno, jen to není vydané.

**Comment by honza-rychtar** [comment]
Tak ještě to upřesním. U vícesvazku byla chyba v klientovi se zámečkama a je opravena, ale jen u private zámečku.
Problém u zámečků licenci u vícesvazku je ještě ten, že narozdíl od výsledku hledání nebo seznamu ročníků a čísel, k čemuž se berou data ze solru, kde licence jsou, se vícesvazky berou přes api `children`, kde licence nejsou. Důvod byl nemožnost seřazení podle indexu ze solru. 
Upravím to, aby se to jednak správně řadilo a zároveň se načetly licence.

**Comment by zabak** [comment]
Otestováno na 2.1.3, zavírám
