### ISSUE TITLE
Chyba u zobrazeni priloh v periodiku

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#42]
Tyka se i "virtualnich" cisel

**Comment by vjirousek** [comment]
Týká se tohle issue i zcela chybějících příloh u čísel? 

http://sluzby.incad.cz/kramerius/view/uuid:71b3e850-8ba5-11e7-927c-001018b5eb5c?page=uuid:77fd30f0-8bdb-11e7-927c-001018b5eb5c

vs 

http://www.digitalniknihovna.cz/mzk/view/uuid:71b3e850-8ba5-11e7-927c-001018b5eb5c?page=uuid:77fd30f0-8bdb-11e7-927c-001018b5eb5c

(chybí 2 strany přílohy Neděle)

**Comment by honza-rychtar** [comment]
@vjirousek Ne, zalozil jsem k tomu zvlast issue #65 
Prilohy u rocniku se zobrazuji uz spravne. Zaviram.
