### ISSUE TITLE
Klient verze 2.1.2 - připomínky

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#422]
Zdravím,

nasadil jsme poslední verzi klienta na testovací server a zatím jsem narazil na dva problémy:

1. přestože mám v konfiguraci licence nastavený parametr `bar: true`, tak se po přihlášení u dnnto dokumentů nezobrazuje modrý panel s příslušným identifikátorem uživatele, aktuální konfigurace viz screenshot

![dnnto-00](https://user-images.githubusercontent.com/8750622/132045184-1e0cea05-ae35-4f3e-9c42-7698e694caac.png)

2. při odhlašování se musí kliknout 2x na tlačítko [Odhlásit] aby došlo k odhlášení z aktivní session, stejně se to chová i v MZK, kde je verze klienta 2.1.1 - předchozí DNNT verze klienta 2.0.5 se takto nechovala.

MD

**Comment by honza-rychtar** [comment]
> přestože mám v konfiguraci licence nastavený parametr bar: true, tak se po přihlášení u dnnto dokumentů nezobrazuje modrý panel s příslušným identifikátorem uživatele, aktuální konfigurace viz screenshot

@mduda100871 děje se to pořád? Panel by se měl zobrazit pokud jsou splněny následující podmínky.
a) v konfiguraci klienta je nakonfigurovaná požadovaná licence, řekněme **dnnto**
b) v konfiguraci klienta je licences.dnnto.bar: true
c) prohlížená strana obsahuje licenci dnnto
d) uživatel má dostupnou licenci dnnto
e) uživateli byla zpřístupněna prohlížená strana právě na základě licence dnnto (ne přes IP, admin roli, ...) 

a) a b) jsou splněny, c) podle popisu taky. Jsou splněny i podmínky d) a e)?

> při odhlašování se musí kliknout 2x na tlačítko [Odhlásit] aby došlo k odhlášení z aktivní session, stejně se to chová i v MZK, kde je verze klienta 2.1.1 - předchozí DNNT verze klienta 2.0.5 se takto nechovala.

Workflow klienta je
1) zavolat logout na Krameria (kramerius logout)
2) otevře stránku definovanou v konfiguraci auth.logoutUrl (shibboleth logout) a předá ji návratové url s aktuální stránkou
3) shibboleth logout pak provede přesměrování zpět
4) zavolá se Kramerius user info, kde by už původně přihlášený uživatel neměl být

Problém je v kombinaci shibboleth logout a kramerius logout
**kramerius logout**
Kramerius ignoruje `GET https://dnnt.mzk.cz/search/api/v5.0/user/logout` v případě přihlášení přes shibboleth. Resp. on ten logout možná provede, ale přebije to současně zaslaná shibsession cookie, která ho zase přihlásí při tomto nebo jakémkoli dalším requestu.
@pavel-stastny je to tak?
**shibboleth logout**
Pokud používaný shibboleth logout endpoint https://dnnt.mzk.cz/Shibboleth.sso/Logout bez return url zadám přímo do address baru a odpálím, tak mi to vrátí.
<img width="936" alt="Snímek obrazovky 2022-02-21 v 14 06 12" src="https://user-images.githubusercontent.com/1178142/154961183-12689dbd-8750-4160-8887-9066da1706c6.png">
Pokud to odpálím ještě jednou, tak dostanu
<img width="476" alt="Snímek obrazovky 2022-02-21 v 14 05 47" src="https://user-images.githubusercontent.com/1178142/154961433-339a3943-5568-4695-8463-098871b391fc.png">
Takže ono to i po logoutu ještě drží session v prohlížeči. A až druhé zavolání je dostatečné.

Nevím jestli to ještě má smysl v K5 opravovat, každopádně tohle na úrovni klienta neopravím. To by musel Kramerius při logoutu ještě sám invalidovat to shibsession.

**Comment by mduda100871** [comment]
> > přestože mám v konfiguraci licence nastavený parametr bar: true, tak se po přihlášení u dnnto dokumentů nezobrazuje modrý panel s příslušným identifikátorem uživatele, aktuální konfigurace viz screenshot
> 
> @mduda100871 děje se to pořád? Panel by se měl zobrazit pokud jsou splněny následující podmínky. a) v konfiguraci 
klienta je nakonfigurovaná požadovaná licence, řekněme **dnnto** b) v konfiguraci klienta je licences.dnnto.bar: true c) prohlížená strana obsahuje licenci dnnto d) uživatel má dostupnou licenci dnnto e) uživateli byla zpřístupněna prohlížená strana právě na základě licence dnnto (ne přes IP, admin roli, ...)

Aktuálně už s tím není problém, zřejmě mezitím byla nějaká verze, kde se to opravilo "samo". Alespoň si nikdo z našich kurátorů nestěžuje, že by to nefungovalo.

> 
> a) a b) jsou splněny, c) podle popisu taky. Jsou splněny i podmínky d) a e)?
> 
> > při odhlašování se musí kliknout 2x na tlačítko [Odhlásit] aby došlo k odhlášení z aktivní session, stejně se to chová i v MZK, kde je verze klienta 2.1.1 - předchozí DNNT verze klienta 2.0.5 se takto nechovala.
> 
> Workflow klienta je
> 
> 1. zavolat logout na Krameria (kramerius logout)
> 2. otevře stránku definovanou v konfiguraci auth.logoutUrl (shibboleth logout) a předá ji návratové url s aktuální stránkou
> 3. shibboleth logout pak provede přesměrování zpět
> 4. zavolá se Kramerius user info, kde by už původně přihlášený uživatel neměl být
> 
> Problém je v kombinaci shibboleth logout a kramerius logout **kramerius logout** Kramerius ignoruje `GET https://dnnt.mzk.cz/search/api/v5.0/user/logout` v případě přihlášení přes shibboleth. Resp. on ten logout možná provede, ale přebije to současně zaslaná shibsession cookie, která ho zase přihlásí při tomto nebo jakémkoli dalším requestu. @pavel-stastny je to tak? **shibboleth logout** Pokud používaný shibboleth logout endpoint https://dnnt.mzk.cz/Shibboleth.sso/Logout bez return url zadám přímo do address baru a odpálím, tak mi to vrátí. <img alt="Snímek obrazovky 2022-02-21 v 14 06 12" width="936" src="https://user-images.githubusercontent.com/1178142/154961183-12689dbd-8750-4160-8887-9066da1706c6.png"> Pokud to odpálím ještě jednou, tak dostanu <img alt="Snímek obrazovky 2022-02-21 v 14 05 47" width="476" src="https://user-images.githubusercontent.com/1178142/154961433-339a3943-5568-4695-8463-098871b391fc.png"> Takže ono to i po logoutu ještě drží session v prohlížeči. A až druhé zavolání je dostatečné.
> 
> Nevím jestli to ještě má smysl v K5 opravovat, každopádně tohle na úrovni klienta neopravím. To by musel Kramerius při logoutu ještě sám invalidovat to shibsession.

No já v konfiguraci klienta volám právě přímo odhlašovací endpoint SP a žádný return parametr tam nemám, takže to musí doplňovat asi klient sám.

Znevalidnění session by dle mého názoru bylo asi nejlepší v jádře Krameria - je to vlastně SP, takže by ten odhlašovací endpoint pod tlačítkem přihlášení měl jednak zavolat endpoint odhlášení SP pod apachem, a pak se vrátit do jádra Krameria a tam to pak také znevalidnit, a změnit tlačítko. Pokud to tak půjde implementovat.

Jinak ale aktuálně řeším opačný problém u té úplně poslední verze klienta, kde naopak po jeho nasazení se nejde vůbec přihlásit, přestože konfigurace jádra pod tím, ani konfigurace SP pod apachem se neměnila.

V logu tomcatu vidím, že atributy do jádra po přihlášení doputují, ale následné autorizační rozhodnutí jádra zpátky do klienta nedojde, takže nedojde k přihlášení. Je ta poslední verze klienta ještě kompatibilní s jádrem K5?

MD

**Comment by pavel-stastny** [comment]
> Problém je v kombinaci shibboleth logout a kramerius logout kramerius logout Kramerius ignoruje GET https://dnnt.mzk.cz/search/api/v5.0/user/logout v případě přihlášení přes shibboleth. Resp. on ten logout možná provede, ale přebije to současně zaslaná shibsession cookie, která ho zase přihlásí při tomto nebo jakémkoli dalším requestu. @pavel-stastny je to tak? shibboleth logout 

No vše je o tom, jestli SP podává tomcatu shibboleth hlavičky.  Pokud je při nebo po stále ještě podává, dojde k automatickému přihlášení.  O shibboleth cookie se stará pouze SP.  Samotný kramerius to neřeší. 

> Nevím jestli to ještě má smysl v K5 opravovat, každopádně tohle na úrovni klienta neopravím. To by musel Kramerius při logoutu ještě sám invalidovat to shibsession.

To ne. Shib session Kramerius neřeší. 

> Jinak ale aktuálně řeším opačný problém u té úplně poslední verze klienta, kde naopak po jeho nasazení se nejde vůbec přihlásit, přestože konfigurace jádra pod tím, ani konfigurace SP pod apachem se neměnila.

>V logu tomcatu vidím, že atributy do jádra po přihlášení doputují, ale následné autorizační rozhodnutí jádra zpátky do klienta nedojde, takže nedojde k přihlášení. Je ta poslední verze klienta ještě kompatibilní s jádrem K5?

A co vrací po přihlášení endpoint `~/user` ?  Vrací přihlášeného uživatele?

**Comment by mduda100871** [comment]
> A co vrací po přihlášení endpoint `~/user` ? Vrací přihlášeného uživatele?

Vrací json (nechci to tady dávat veřejně, můžu to případně poslat separátně mailem), kde jsou řádně vyplněné hodnoty autorizačních atributů z IdP, přidělené role jádrem a dostupné licence, takže evidentně má jádro všechno k dispozici, jen se to zpátky klient nedoví...

**Comment by honza-rychtar** [comment]
> Jinak ale aktuálně řeším opačný problém u té úplně poslední verze klienta, kde naopak po jeho nasazení se nejde vůbec přihlásit, přestože konfigurace jádra pod tím, ani konfigurace SP pod apachem se neměnila.

@mduda100871 zkus prosím novou verzi 2.3.2. Opravoval jsem tam několik věcí kolem dnnt a kompletně to otestoval na instalaci dnnt.mzk.cz a funguje to. 
https://github.com/ceskaexpedice/kramerius-web-client/releases/tag/v2.3.2

**Comment by mduda100871** [comment]
> > Jinak ale aktuálně řeším opačný problém u té úplně poslední verze klienta, kde naopak po jeho nasazení se nejde vůbec přihlásit, přestože konfigurace jádra pod tím, ani konfigurace SP pod apachem se neměnila.
> 
> @mduda100871 zkus prosím novou verzi 2.3.2. Opravoval jsem tam několik věcí kolem dnnt a kompletně to otestoval na instalaci dnnt.mzk.cz a funguje to. https://github.com/ceskaexpedice/kramerius-web-client/releases/tag/v2.3.2

No tak přihlášení sice už funguje, ale zase je tam pro změnu zpátky problém s tím modrým pruhem u dnnto dokumentů - nezobrazuje se. U verze 2.1.2 se zobrazuje korektně...

**Comment by mduda100871** [comment]
> No tak přihlášení sice už funguje, ale zase je tam pro změnu zpátky problém s tím modrým pruhem u dnnto dokumentů - nezobrazuje se. U verze 2.1.2 se zobrazuje korektně...

Nezobrazující se modrý pruh byla nakonec zavlečená chyba v konfiguraci přidělování rolí v `shibrules.txt`. Takže můj předchozí příspěvek neplatí.

MD

**Comment by honza-rychtar** [comment]
Můžeme zavřít?
