### ISSUE TITLE
Klient zobrazuje staré fasety dokud se nestáhnou nová data

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#426]
Dokud se nestáhnou nová data faset, zobrazuje klient data která načetl naposledy - i když jsou z jiné knihovny. Nejvíc je to vidět, když se nedaří dotáhnout data - třeba na pomalé lince:

![image](https://user-images.githubusercontent.com/811537/133643985-0ae7c3f5-dce6-406f-a78a-832994dbcdb5.png)

**Comment by annie-cz** [comment]
Je to stále aktuální?

**Comment by zabak** [comment]
Už se to neprojevuje, asi vyřešeno, zavírám.
