### ISSUE TITLE
V Pardubicích se zobrazují na prvním místě hřbety

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#427]
Jsou označené <mods:part type="Spine">, ale zobrazují se na prvním místě a jako reprezentativní stránka. Např. https://kramerius.knihovna-pardubice.cz/uuid/uuid:ddc18aa8-5344-4536-8fd8-8b9b41a56c39

**Comment by honza-rychtar** [comment]
Už jsou na konci. Asi už to přeindexovali.
Tohle zavírám.
