### ISSUE TITLE
Zámečky na záložce Doporučené na hlavní stránce ignorují DNNT labely

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#430]
...u DNNT věcí jsou šedé zámečky i když jde o DNNT věci.

**Comment by annie-cz** [comment]
Toto už není platné o ohledem na nové zobrazování zámečků apod. 

<img width="741" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/39650e3b-dde0-4d8c-bf11-1b8fa14518fd">
