### ISSUE TITLE
Cient neignoruje COVID lablu.

### ISSUE THREAD

**Issue by Romx98** [ceskaexpedice/kramerius-web-client#431]
Zdravim,

dnes sme narazili na problem, kde jedna monografia mala nastavene len covid label, avsak v klientovi sa zobrazovala ako dnnt dokument (zlty zamocek).  Po odstraneni dnnt-lablu (covid), sa dany dokument zobrazil bez zlteho zamocku.
Z informacii, ktore som dostal by covid lable mal byt ignorovany. 

R.K (mzk)

**Comment by zabak** [comment]
@Romx98 protože zde nemáme konkrétní příklad na kterém by se to dalo otestovat, tak do zavírám, kdybychom na nějaký narazili, tak založíme nové issue.
