### ISSUE TITLE
Zvukové nahrávky nezobrazují zámeček

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#433]
Pokud je zkuková nahrávka private, tak se přehrávač tváří, jako by nic nebránilo přehrání, jen se nic nestane. Bylo by dobré podobně jako u stránek zobrazit nějaké info o licenci.

**Comment by honza-rychtar** [comment]
Od verze 2.3.1 je přehrávač upravený včetně varování o nedostupnosti nahrávky.

<img width="1287" alt="Snímek obrazovky 2022-02-07 v 11 18 38" src="https://user-images.githubusercontent.com/1178142/152770000-4e9397bf-723b-4352-a4f5-bee681f08d95.png">


Plánují se používat licence i u zvukových dokumentů?
Další informace o nedostupnosti včetně licencí je pak pod íčkem v podrobnostech vpravo stejně jako u jiných typů dokumentů.

**Comment by zabak** [comment]
@honza-rychtar pokud vím tak zatím žádné zvláštní licence nikdo nemá. Do budoucna je to možnost, ale pravděpodobně skončíme jen u variací na public nebo private. Funguje, zavírám.
