### ISSUE TITLE
kalendář - špatné zobrazení v dubnu 1916

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius-web-client#434]
U dubna 1916 se špatně zobrazuje "zdvojeně" 1. den, znovu na konci měsíce na správně zašedlém místě pro 1.5.
Ať už tam nějaká čísla jsou:
Pressburger Zeitung: https://www.digitalniknihovna.cz/d/periodical/uuid:df5b9687-74fd-4409-a02a-f6cc62058745
Westungarischer Grenzbote: http://www.digitalniknihovna.cz/d/uuid/uuid:75195984-bd75-4bc0-8a5b-64e46f11f0c6
Lidové noviny: https://dnnt.mzk.cz/periodical/uuid:2607f3e0-61e6-11dc-9c6f-000d606f5dc6
<img width="274" alt="w_548" src="https://user-images.githubusercontent.com/4635032/139061721-56ae3070-3352-473b-b906-9f9ad0c9a599.png">
Anebo nejsou:
Volksfreund: https://dnnt.mzk.cz/periodical/uuid:8bc846c4-5cb4-4eaf-9d56-4e52c7d8d5f8

**Comment by honza-rychtar** [comment]
Opraveno. Např. http://dk.kramerius.org/mzk/periodical/uuid:2607f3e0-61e6-11dc-9c6f-000d606f5dc6

**Comment by zabak** [comment]
otestováno, zavírám
