### ISSUE TITLE
Deformace obrázku stránky při otevírání nebo zavírání bočních lišt

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#44]
Pokud schovám nebo zobrazím boční lištu, tak při jejím vyjetí nebo zajetí se neproporcionálně roztáhne nebo smrští zobrazená stránka. Potom poskočí aby se proporcionálně srovnala do nové velikosti okna - zároveň dojde ke strátě zoom levelu stránky. Bylo by dobré s velikostí a pozicí stránky manipulovat minimálně - např podobně jako v případě, že měním velikost celého okna browseru.

**Comment by honza-rychtar** [comment]
Deformace vyřešeny novou prohlížečkou.

Pokud jde o zoom level a pozici, tak u otevření/zavření bočních lišt nebo při přechodu z/do fullscreen režimu se (někdy výrazně) změní plocha pro obrázek a při této změně dává smysl obrázek vycentrovat.

**Comment by mtravnicek** [comment]
Chapu to spravne, ze se Vam nechce vymyslet, jak prizpusobit obrazek obrazovce a date proste reset na jeho zoom/polohu - cimz se vyresi 2 roky stary bug? Tim jste totiz problem nevyresil, jen zamaskoval, ten obrazek se ted sice neroztahuje a nesmrstuje, ale zase popojizdi a poskakuje, coz je dane celkove spatne provedenym  konceptem "plovouciho obrazku", tedy ze s obrazkem jde vsemozne posouvat a zvetsovat ho... ale toto by mel delat jen uzivatel, ne ta aplikace... pokud totiz vysunu a zasunu bocni panel, tak se to animuje a obrazek "jede" spolecne s tim panelem, coz mozna vypada cool, ale nedava to smysl, obrazek by (dle meho) mel zustat pevne pribity uprosted obrazovky, pripadne tam, kde si ho uzivatel posunul (a jak si ho zvetsil). Pokud si obrazek zvetsim, tak ze bude presahovat aktualne zobrazitelnou plochu a bude treba zleva prekryt bocnim panelem, pokud ten panel oddelam, tak by mel proste odhalit prekrytou cast obrazku za nim, ne aby za nim obrazek jezdil tam a zpatky a nakonec se vyresetoval jeho zoom i poloha ("vycentroval"). Pocitam ze to souvisi s tim, ze si obrazek drzi nejakou relativni vzdalenost od leveho praveho okraje atd. a je tak vycentrovan a nedrzi se nejake sve vlastni plochy, coz take souvisi s tim, jakym zpusobem se zaviraji bocni panely (na to bude issue za chvili). Dokazete se od toho centrovani oprostit?

**Comment by zabak** [comment]
@honza-rychtar: Co píše @mtravnicek o tom ponechání obrázku tak jak je dává smysl, ale nevím, jestli to jde snadno udělat (vlastně by se jen rozšířilo okno prohlížečky tu na jednu, tu na druhou stranu, nebo v případě fullscreenu na všechny strany). Vedlo by to ale ještě k jednomu funkčnímu tlačítku. Současné tlačítko Přizpůsobit obrazovce totiž u obvyklé kombinace obrazovky a stránky ve skutečnosti přizpůsobuje stránku na výšku. Chtělo by to ještě jedno tlačítko, které ji přizpůsobí aktuálnímu oknu prohlížečky na šířku. S tím, že stávající tlačítko by se přejmenovalo na přizpůsobit na výšku. Nebo by to stávající cyklovalo mezi režimem na šířku a na výšku, ale to myslím není z hlediska UX dobrý nápad.

**Comment by zabak** [comment]
Zde zavírám, původní issue bylo vyřešeno.
