### ISSUE TITLE
Konvoluty - přidat zobrazení názvu/čísla části v seznamu přívazků vlevo

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#440]
Zobrazovat <mods:partName> a <mods:partNumber>

http://www.digitalniknihovna.cz/mzk/uuid/uuid:2be20185-5537-43b4-a2ff-7b72196e567f

v levé části okna:

![image](https://user-images.githubusercontent.com/811537/143003595-6acc2efa-8e65-4af6-8458-2b118ce738ff.png)

v pravé čísti se to zobrazuje:

![image](https://user-images.githubusercontent.com/811537/143003676-8616e4c1-4173-4140-9153-52954df73c95.png)

**Comment by honza-rychtar** [comment]
@zabak Tohle jsme řešili. Číslo části se nepropsalo do pole `title` v indexu.
Část konvolutu ma v MODS
```
<mods:titleInfo>
   <mods:title>Super sexto Decretalium</mods:title>
   <mods:partNumber>P. 2</mods:partNumber>
</mods:titleInfo>
```
by měl indexer zpracovat jako
```
"title": "Super sexto Decretalium. P. 2",
```
místo toho je v indexu
```
  "title": "Super sexto Decretalium",
```

Těch chyb tam bylo víc, tohle jsou staré záznamy, Nepoznáme, co bylo opraveno.
Každopádně, jakmile se to zaindexuje správně, pak klient ty části zobrazí včetně čísel. 

Konvoluty teď testujeme v K7. Ale budeme potřebovat nějaké správně zpracované dokumenty. @zabak Ozvu se ti k tomu.

Tohle se teda netýká klienta, je možné zavřít.
