### ISSUE TITLE
Problém se zobrazováním oranžového zámečku/foťáčku u fulltextového vyhledávání v dokumentech

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#441]
Narazila jsem na chybu u zobrazování oranžového zámečku/foťáčku, když vyhledávám fulltextově v dokumentech. Když si rozkliknu např. periodikum a klient mi ukazuje vyhledávaný dotaz v náhledech na jednotlivých stránkách v jednotlivých číslech, tak je zámeček šedý. Když se doklikám dovnitř čísla, pak je vše už v pořádku a zámečky/foťáčky jsou správně oranžové.

Viz:

http://www.digitalniknihovna.cz/mzk/periodical/uuid:1c869c00-535b-11e3-9ea2-5ef3fc9ae867?fulltext=fr%C3%A1%C5%88a%20zem%C3%ADnov%C3%A1

http://www.digitalniknihovna.cz/mzk/periodical/uuid:408ed78a-0355-4e8c-a71a-94755bb427d4?fulltext=fr%C3%A1%C5%88a%20zem%C3%ADnov%C3%A1

http://www.digitalniknihovna.cz/mzk/periodical/uuid:1db01f60-7130-11e7-b92d-005056827e51?fulltext=fr%C3%A1%C5%88a%20zem%C3%ADnov%C3%A1

**Comment by annie-cz** [comment]
Teď ke mně došla informace, že to bude součástí příští verze klienta. @honza-rychtar je to tak pls? Pokud ano, můžeme zavřít.

**Comment by annie-cz** [comment]
Mohl by mi prosím někdo odpovědět, jak to tedy je nebo není? Ten problém stále trvá.

![image](https://user-images.githubusercontent.com/43028501/146191947-b2f7621f-f360-4f32-83c7-eaea6558d37e.png)

**Comment by annie-cz** [comment]
@honza-rychtar ?

**Comment by zabak** [comment]
Funguje, testováno na verzi 2.3.1
