### ISSUE TITLE
Překlep v admin části klienta K7

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#445]
Vybrných objektů -> Vybraných objektů
https://github.com/ceskaexpedice/kramerius-web-client/blob/69185f4fcc4bcdada2f0c73bf07061214019a3a1/src/app/dialog/dialog-admin/dialog-admin.component.html

Akorát by ten text správně měl být v jazykovém souboru.

**Comment by honza-rychtar** [comment]
@zabak překlep jsem opravil. Lokalizaci admin části klienta řešme pak tady #463 až bude funkcionalita finální.
