### ISSUE TITLE
Nezobrazovat neplatné ISBN

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#446]
Dobrý den,

narazil jsem na problém se zobrazováním ISBN v klientovi: Pokud má monografie dvě ISBN, jedno platné a jedno neplatné, pak se v postranním panelu zobrazuje pouze jedno, a to bez ohledu na to, zda je, nebo není platné. Bylo by možné nezobrazovat ISBN, které má atribut `invalid="yes"`?

Děkuji!
FK

**Comment by honza-rychtar** [comment]
Příklad
https://www.digitalniknihovna.cz/knav/view/uuid:e3f2be82-fc40-438f-a067-d2b16530e44f?page=uuid:8fd3c1ab-ba19-4bc9-bec8-fe6b3f7719c4

**Comment by kerschfilip** [comment]
funguje, díky
