### ISSUE TITLE
Název čísla (partNumber) - tooltip

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#45]
Při rozkliknutí ročníku, kde je seznam jednotlivých čísel, by se po najetí myší na náhled čísla zobrazil název čísla (pokud je v metadatech). Jde o údaj v poli "partNumber" z úrovně čísla.

**Comment by honza-rychtar** [comment]
Ted je logika takova, ze se zobrazi issueNumber pokud existuje. Pokud ne, tak se zobrazi partNumber.

Obe pole obsahuji cislo vydani - jen zalezi na typu digitalizace. Ted uz se pouziva vzdy partNumber.
 
Zkuste mi poslat ukazku cisla periodika, ktere obsahuje issueNumber i partNumber. Ale myslim, ze neexistuje. Alespon ne v solru, je mozne, ze nekde v MODS bude, ale do solru se takova situace nepropaguje.

**Comment by krizovj** [comment]
Taková situace může být například u mimořádných čísel časopisů, třeba tady u Filosofického časopisu:

https://kramerius.lib.cas.cz/search/handle/uuid:7a9f3afc-4e8d-4fbe-874e-76de161fb91d 

Nechci to dát do popisu místo partNumber, ale jen do tooltipu, pokud by nebyl partName, tak by se tootip vůbec nezobrazil. Teď třeba zpracovávám hodně staré periodikum (takže ještě není v Krameriovi), kde je prostě svazek=ročník a v tom svazku jsou jednotlivá čísla a ta mají zvláštní název (partName) i autora. Číslo čísla nemají, takže ho tam musím uměle dopočítat, aby to bylo podle standardu. Protože oficiálně nemají číslo čísla (partNumber), tak uživatel ta čísla zná spíš podle názvu. A když v tom ročníku je těch čísel třeba dvacet a nejsou u nich názvy, tak je musí uživatel jedno po druhém otevřít, aby zjistil, jestli je to to, co hledá.

**Comment by honza-rychtar** [comment]
Aha, bavime se tady o _partName_ a ne o _partNumber_ (ktere jste uvadela).
_partName_ neni indexovane.
Je sice v MODS - https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:7a9f3afc-4e8d-4fbe-874e-76de161fb91d/streams/BIBLIO_MODS
ale neni v solr:
https://kramerius.lib.cas.cz/search/api/v5.0/search?q=PID:%22uuid:7a9f3afc-4e8d-4fbe-874e-76de161fb91d%22
ani v API Krameria
https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:7a9f3afc-4e8d-4fbe-874e-76de161fb91d

Na urovni seznamu cisel nemuzu davat dotazy na MODS kazdeho cisla (teoreticky ano, ale bylo by to pomale a u vetsich periodik nepouzitelne).
Informace o seznamu cisel lze ziskat bud dotazem do solru nebo pres API /item/UUID/children
a ani jeden zpusob neobsahuje _partName_.

Resenim by bylo pridat _partName_ do solr a API (details) stejnym zpusobem jako je tam _partNumber_. V pripade solr by se pridala dalsi pozice do _details_, tj.
title##issueNumber##date##partNumber **##partName**

Tohle se uz ale netyka klienta.

**Comment by krizovj** [comment]
No jo, to se omlouvám, psala jsem to špatně,,. místo partName jsem psala partNumber

Takže to je potřeba vyřešit v jádru? Přidat do Solr a API element partName. 
A potom by to šlo?

**Comment by honza-rychtar** [comment]
@krizovj Ano

**Comment by honza-rychtar** [comment]
V K7 je partName indexováno a zobrazuje se v tooltipu.
https://k7-test.mzk.cz/mzkk7/periodical/uuid:31f91f46-2de5-4b69-9cd5-ff0827377ba5

<img width="660" alt="Snímek obrazovky 2022-08-02 v 10 46 34" src="https://user-images.githubusercontent.com/1178142/182333113-55dbe840-42cd-4f06-8647-39dea9b5cc8c.png">

**Comment by zabak** [comment]
funguje, zavírám
