### ISSUE TITLE
Implementovat podporu (ne)udělení (ne)souhlasu uživatele se zpracováním cookies

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#453]
V souvislosti s novelou zákona o el. komunikacích 
https://www.zakonyprolidi.cz/cs/2005-127

https://www.uoou.cz/cookies-od-zacatku-roku-2022-pouze-se-souhlasem/d-53646

https://www.uoou.cz/casto-kladene-otazky-ohledne-souhlasu-s-cookies-udeleneho-prostrednictvim-tzv-cookie-listy/ds-6912/archiv=1&p1=2619

https://www.peytonlegal.cz/novela-elektronicke-komunikace-cookies/

Dle litery zákona je GA script v klientovi možno aktivovat až po udělení souhlasu.

**Comment by filak** [comment]
Osobně si ale myslím, že obecně sledování návštěvnosti je klíčový ukazatel pro hodnocení efektivity poskytovaných web služeb, takže zrovna tohle by mělo být spíše defaultně zapnuté... Stejně tak z hlediska vývoje je nezbytné sledovat jaké technologie klienti služby používají. Zásadní je samozřejmě také sledování výkonnostních ukazatelů webu i konkrétních stránek... Což všechno nám umožňuje používání Google Analytics.

**Comment by filak** [comment]
Zřejmě by šlo použít toto:

https://github.com/orestbida/cookieconsent

**Comment by filak** [comment]
> Zřejmě by šlo použít toto:
> 
> https://github.com/orestbida/cookieconsent

Nasadili jsme to např. na nlk.cz a funguje to dobře - navíc je to super konfigurovatelné/flexibilní, takže si to každý může nastavit podle svých potřeb...

**Comment by honza-rychtar** [comment]
Na schůzce 4.3. se dohodlo, že v klientovi bude vlastní implementaci cookie lišty. 
Bude to vycházet z UI aplikace a použití se bude dát nastavit v konfiguraci klienta - možnost vypnout a použít vlastní řešení.

Uživatel si bude moct zapnout zvlášť analytické cookies - Google Analytics a preferenční cookies (local storage) - volby pouze veřejné, jazyk, nejnovější/doporučené/navštívené, seznam navštívených, dvoustránkový režim, periodika řazení, periodika typ - kalendář, mřížka, metadata typ

Později můžeme tu lištu více graficky a textově přiblížit čtenáři (cílové skupině na míru produktu - digitální knihovně), což zvedá poměr udělení souhlasu.

**Comment by honza-rychtar** [comment]
Hotovo ve verzi  [2.3.4](https://github.com/ceskaexpedice/kramerius-web-client/releases/tag/v2.3.4)
Popis konfigurace tady.
https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta#cookie-li%C5%A1ta

Možnost vyzkoušet na instalaci tady http://dk.kramerius.org/

**Comment by zabak** [comment]
Funguje, uzavírám. Případné další úpravy budeme zakládat jako nové požadavky.
