### ISSUE TITLE
Dopočítávání nezdigitalizovaných ročníků

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#46]
Dát pryč funkci dopočítávání nezdigitalizovaných ročníků.

**Comment by krizovj** [comment]
![dopocetroc](https://user-images.githubusercontent.com/21309201/36465340-dd38db66-16d4-11e8-8e7c-e24931ca6160.jpg)

**Comment by honza-rychtar** [comment]
No dobre. A chcete tam vubec to zobrazeni roku, kdyz se z toho stane vlastne jen zobrazeni mrizky bez nahledu?
A taky by me zajimalo, proc to chcete zrusit.

**Comment by krizovj** [comment]
Klidně to tam bez těch náhledů může zůstat, aspoň se tam vejde víc ročníků. Ale pokud by to chtěl někdo dát úplně pryč, tak se prosím ozvěte. 

Chtěli bychom to zrušit, ptž to je uživateli vlastně k ničemu. Asi by to bylo i trochu frustrující, když jenom zjistí, že tam je ještě nějaký ročník, ale nemůže se k němu dostat. 
Navíc existuje dost případů, kdy se to dopočítá špatně. 
Třeba tady:
https://kramerius.lib.cas.cz/client/handle/uuid:481895ae-b934-11e1-bc5d-005056a60003

první ročník vyšel 1804 a další až 1814 a mezi nimi nic nevyšlo, ale tady by se to dopočítalo, že tam něco chybí.

**Comment by honza-rychtar** [comment]
> Klidně to tam bez těch náhledů může zůstat, aspoň se tam vejde víc ročníků. Ale pokud by to chtěl někdo dát úplně pryč, tak se prosím ozvěte.

Tohle zobrazeni funguje jinak, nebyla by to uprava tohoto, ale vytvoreni noveho zobrazeni.

> Chtěli bychom to zrušit, ptž to je uživateli vlastně k ničemu. Asi by to bylo i trochu frustrující, když jenom zjistí, že tam je ještě nějaký ročník, ale nemůže se k němu dostat.

No myslim, ze frustrujici je to spis pro knihovnu nez pro uzivatele :) 
Je to vlastne podobne jako s kalendarem, taky nezahodim brezen, pokud v nem nemam nic zdigitalizovane.

> Navíc existuje dost případů, kdy se to dopočítá špatně.
> Třeba tady:
> https://kramerius.lib.cas.cz/client/handle/uuid:481895ae-b934-11e1-bc5d-005056a60003
> 
> první ročník vyšel 1804 a další až 1814 a mezi nimi nic nevyšlo, ale tady by se to dopočítalo, že tam něco chybí.

To ano, ale to z dat ani nejde zjistit - dalo by se to zjistit z nakladatelskych udaju, ale tento dokument je nema vyplnene.
Navic tem mezeram ve vydani se nevyhneme ani u hledani. V indexu je pouze pocatecni a koncovy rok, takze pokud budu hledat rok 1809, tak mi to toto periodikum najde, i kdyz se ten rok nevydavalo.
Nakonec i kdyz je ta mezera kvuli pauze ve vydavani, tak se porad snaze vizualne hleda v neprerusovane ose.

Pokud ho chcete zrusit, pak teda _dobre_, ale reknete, jestli ho zrusit uplne (otazka par minut), nebo ho nahradit novym zobrazeni, ktere bude stejne jako mrizka jen bez nahledu a cisla rocniku.

**Comment by krizovj** [comment]
Myslím, že by se to mělo zrušit úplně. Pokud by měl někdo něco proti, tak se, prosím, ozvěte.

**Comment by zabak** [comment]
Myslím si, že tam ty prázdné roky smysl dávají - právě proto, že si tak uživatel uvědomí, že je to nekompletní. Jinak si bude myslet, že je to souvislé, ty díry neuvidí a pak se bude divit. Podobně funguje například ANNO: http://anno.onb.ac.at/cgi-content/anno?aid=mbz

**Comment by krizovj** [comment]
Ano, ale jak by tedy měla vypadat metadata v případě, že tam prostě byla pauza ve vydávání?

**Comment by zabak** [comment]
Zatím nedokážeme rozlišit rozdíl mezi pauzou ve vydávání, čísly chybějícími v knihovně a čísly která jsou v knihovně, ale nejsou naskenovaná. Pro uživatele je to ale jedno, výsledek je, že to v digitální knihovně není.

**Comment by krizovj** [comment]
Právě, uživateli je to jedno, prostě to tam není. Takže k čemu je mu informace, že tam něco chybí, když se stejně nedozví, jak se k tomu dostat. A u těch pauz se to navíc dozví špatně, že něco chybí. Myslím, že to není tak úplně výjimečný případ, že je pauza ve vydávání.
U nás je to třeba u časopisů: 
Biologické listy - Ročník 31 (datum vydání 1951) a Ročník 32 (datum vydání 1968)
Časopis pro moderní filologii - Ročník 28 (datum vydání 1942) a Ročník 29 (datum vydání 1946)
Právník - Ročník 1 (datum vydání 1861) a Ročník 2 (datum vydání 1863)
Český lid - Ročník 32 (datum vydání 1932) a Ročník 33 (datum vydání 1946)

A u dalších.

**Comment by zabak** [comment]
To ovšem vede spíše k požadavku zobrazovat spolu s rokem i číslo ročníku. Ale uživatel vidí, že ty dva navazující ročníky mají mezi sebou větší časovou pauzu, když tam ty šedé roky jsou. Ale náš spor ukazuje, že toto je vhodný adept na uživatelské testování.

**Comment by krizovj** [comment]
Aby v tom nebyl zmatek, jako číslo ročníku může být totiž někde uvedený taky rok. 
Třeba tady (Přehled výzkumů):
https://kramerius.lib.cas.cz/client/handle/uuid:f91c3df3-7190-11e1-84d7-005056a60003

A má to sloužit primárně jako co? Aby uživatel viděl co není zdigitalizováno nebo aby viděl, že v některých letech nic nevyšlo? Problém prostě je, že to nejde poznat.

**Comment by zabak** [comment]
Ne, ale nezatajujeme uživateli informaci, že pro daný rok v digitální knihovně nic nemáme. To je to co je pro uživatele důležité.

**Comment by krizovj** [comment]
Já myslím, že uživatele zajímá spíš co máme, než co nemáme. A asi by to bylo užitečně, kdyby se dalo rozeznat, jestli tam je díra proto, že prostě nic nevyšlo nebo proto, že to není zdigitalizované. Ptž to pak uživatel neví, jestli to má teda hledat jinde nebo napsat do knihovny, že by to chtěl zdigitalizovat. 
Asi by to chtělo se zeptat nějakých uživatelů.

**Comment by zabak** [comment]
Ano, v tomto případě by posloužil i pětivteřinový test, nebo jiná podobná metoda. Nemám práva přidělit tomuto issue  žádný label, ale pokud se s tímto má něco dělat, tak by bylo vhodné to označit labelem typu "user testing".

**Comment by vjirousek** [comment]
Jenom drobný příspěvek k diskusi že s takto vizualizovanou informací uživatelé pracovali (zároveň ale není reálné očekávat že by kvůli ní chodili do Registru digitalizace). Zachyceno přede dvěma dny na FB.. 

Jinak by mi přišlo docela důležité říct kolika procent periodické produkce celkově se zhruba týká situace, kdy platí, že bylo vydávání titulu přerušeno a zároveň není uvedeno řádné číslo ročníku ale rok. Nemyslím že by to bylo více než nízké jednotky procent. Pokud jsme se dostali do bodu kdy měl být seznam ročníků bez náhrady zrušen, pak se vracím k tomu, že nastavení defaultního zobrazení na mřížku s náhledy a pro uživatele možnost zobrazit si seznam ročníků včetně vizualizace v jakém rozsahu je titul zpracován mi přijde vhodnější řešení. I kdyby to v 5-10% případů poskytovalo trochu zkreslenou informaci.
![obrazek](https://user-images.githubusercontent.com/22765973/37084363-91d40f5a-21f2-11e8-9c32-b9dc3de7f528.png)

**Comment by honza-rychtar** [comment]
@krizovj Třeba u těch Biologických listů máte v datech vydání 1912-2005. Což je přece taky zavádějící a pokud bych měl pouze zobrazení mřížkou, tak není téměř možné odhalit, že se časopis v letech 1952 až 1967 nevydával. Musel bych jet ročník po ročníku, všimnout si skoku v roku a zároveň nepřerušení římsky číslovaného názvu ročníku. 

Zobrazení přes roky je to nejjednodušši a zároveň nejpřirozenější vizuální zobrazení ročníků. 
Nepřidávejme název ročníku - kvůli jednotkám procent divností negativně ovlivníme 90 % standardně zpracovaných periodik.  
Použití náhledu zase nemá žádnou informační hodnotu. Použití bílých obálek z prvího ledna pro každý rok, kde všechny vypadají stejně je zbytečné a naopak znemožňuje rychlou orientaci v ročnících.
Jediný případ, kdy má smysl použít náhledu, je seznam čísel u nových měsíčníků s pěknou reprezentativní obálkou, např. http://www.digitalniknihovna.cz/mkct/periodical/uuid:d7de3d0a-3dcf-489f-b325-4fed0eae2fea, kde obálky pěkně reprezentují měsíce - květen hudební festival, říjen začátek hokejové ligy apod. Ale to se týká čísel, kde tento přípád preferuje zobrazení mřížky před kalendářem. Ale u seznamu ročníku ani v tomto případě nemá zobrazení obálky smysl - zobrazit deset obálek se zasněženou krajinou a přáním do nového roku je zbytečné - všechny reprezentují měsíc leden, ne daný rok.

Příklad, který uvedl @vjirousek, pěkně ukazuje, že zobrazení chybějících ročníků v uživatelích vzbuzuje přesně opačnou emoci než frustraci, které se obáváte.

Z téměř deseti tisíc návštěv Digitální knihovny týdně se dá docela dobře vypozorovat, jak uživatelé fungují, odkud přícházejí, co hledají a kdo vlastně jsou.
A právě zmíněný příspěvek z Facebooku je ukázkou klasických uživatelů - skupina lidí zajímající se o vodní mlýny. Těchto skupin je spousta, např. genealogie, včelařství, vojenství, historie měst apod.
Nejsou to profesionálové, kteří používají pět logických operátorů v každém dotazu, výsledky porovnávají s registrem digitalizace a pro rok vydání marně hledají pole 260$c.

Problém u lidí z knihoven je ten (a nemyslím to špatně), že se dlouho učili jak pracovat s daty, jak je zpracovat, uložit, vyhledat. Potom je pro ně složité navrhovat rozhraní pro běžného uživatele, který se tohle nikdy neučil, nezná interní formáty, funguje vizuálně, intuitivně a vyžaduje hlavně jednoduchost.

**Comment by krizovj** [comment]
Já si prostě myslím, že když uživatel uvidí jen ty roky a mezi nimi ty neaktivní, tak si bude myslet, že tam něco chybí, i když tam nich nechybí a bude to matoucí. A i když se bude těšit, až se zdigitalizuje to co chybí, tak tam pak třeba stejně zůstane mezera, kdy nic nevyšlo a bude se těšit dál, ale zbytečně. Myslím, že s vyhledávacími operátory to nemá nic společného. 

U ročníku by asi náhled obálky být nemusel, ale u čísla to ničemu nevadí, i když nejsou všechny obálky čísel reprezentativní. A zas by to vypadalo divně, když by někde ty náhledy byly a někde ne.

Ale možnost zobrazení ročníků přes mřížku doufám zůstává (ať už s náhledem obálky nebo bez něj)? Ne každý hledá jen přes roky vydání, číslo ročníku by u té mřížky prostě mělo být (teď tam je). Můžete znát jen číslo ročníku a rokem vydání si nemusíte být jist. 



Na testovacím serveru se ty ročníky teď dopočítávají nějak divně. Vypadá to, že se ty roky zobrazují podle toho, jak vycházel časopis, který jsem prohlížela předtím. 
Třeba: u časopisu Deutsche post se zobrazil jako první rok 1905, ale v datu vydání je jako první rok 1919. Po F5 se to srovná. Pak jsem otevřela časopis Ženská rada a ten měl jako první rok 1919 (jako Deutsche post), i když podle data vydání to mělo být 1925. Zase po F5 ok.

**Comment by vjirousek** [comment]
> Navíc existuje dost případů, kdy se to dopočítá špatně.
> Třeba tady:
> https://kramerius.lib.cas.cz/client/handle/uuid:481895ae-b934-11e1-bc5d-005056a60003
> 
> první ročník vyšel 1804 a další až 1814 a mezi nimi nic nevyšlo, ale tady by se to dopočítalo, že tam něco chybí.

Není primárně chyba v samotných (meta)datech než ve způsobu jejich zobrazení? V katalogu jsou k titulu informace, které v metadatech chybí:

> 310   	|a Vychází nepravidelně
> 3620   	|a Bd. 1(1802/1804)-Bd. 8(1822/1823); N.F. Bd. 1(1824/1826)-Bd. 5(1836); 5.F. Bd. 1(1837/1840)-Bd. 14(1865/1866), Bd. 15; 6.F. Bd. 1(1867)-Bd. 12(1883/1884)

Bez těchto údajů nikdy nebude mít čtenář úplnou informaci, protože i když mu nezobazíme prázdné roky, stejně bude mít jedinou informaci o vycházení z pole mods:dateIssued (které tady vlastně ale taky vůbec nenacházím), kde by zase byla z pohledu neknihovnického světa zavádějící informace "1804-1885".

**Comment by krizovj** [comment]
Tohle konkrétní periodikum je zrovna celé špatně zpracované, takže ho teď předěláváme, aby se v něm dalo trochu vyznat. Ale nevím, jestli zrovna z té poznámky 362 jde něco pochopit.

Takže myslíte, že úplně ve všech časopisech, kde třeba třeba jen jeden rok nic nevyšlo (protože byla prostě pauza), tak by to mělo být rozepsané v poznámce a že když tam uživatel uvidí tu díru, tak první co ho napadne bude, že se podívá do poznámky, aby zjistil proč tam je? To bohužel u všech časopisů rozhodně nemáme. Což je nejspíš špatně, ale tak to prostě je.

Klidně se ta funkce může zachovat, když už to teď nikdo další nechce zrušit, nicméně si pořád myslím, že to bude matoucí.

**Comment by LenkaDamborska** [comment]
Já myslím, že jsme se na schůzce shodli, že zobrazovat neaktivní roky je matoucí. Měli jsme tam třeba příklad, kdy periodikum vycházelo 50 let a byly zdigitalizovány pouze 2 ročníky. Všichni jsme se shodli na tom, že to vypadá špatně. A já si to osobně myslím pořád. 

Nestačí prostě, že informace o vydávání je v popisu dokumentu hned vpravo? Proč uživateli ještě nastrkovat, že jsme ještě nezdigitalizovali další ročníky. Taky si myslím, že je lepší mu ukázat, co máme, než co nemáme, a pokud bude trochu sečtělý a bude mít o periodikum zájem, tak se podívá do pravé strany obrazovky, kde v popisu dokumentu uvidí, že roků vydávání je víc. Pak se může zeptat, proč to ještě nebylo zdigitalizováno a kdy to bude - tuto informaci z těch neaktivních ročníků stejně nevyčte a stejně se na to bude muset zeptat. 

Myslím, že ve výsledku to bude matoucí a bude to pro uživatele zbytečná informace, takže já osobně jsem pro to neaktivní roky nezobrazovat. Navíc uživatelé jsou na to zvyklí ze starého Krameria, kde byly vždy jen ty digitalizované ročníky.

**Comment by indrakm** [comment]
Ano jak píše Lenka D., nemá smysl čtenáři promovat nezdigitalizované roky. V eshopu se taky neprodává zboží, které není k mání. 
Byl bych ale všemi deseti pro v tom případě, kdyby existovala jednoduchá cesta, jak by mohl čtenář navrhnout dané neaktivní roky adresně dodigitalizovat a celé se to dalo lehce zprocesovat, ale taková lehká cesta bohužel není (zatím není). Kdyby to tak ale bylo, bylo by to ideální.

**Comment by indrakm** [comment]
@honza-rychtar 
off topic _"Z téměř deseti tisíc návštěv Digitální knihovny týdně se dá docela dobře vypozorovat, jak uživatelé fungují, odkud přícházejí, co hledají a kdo vlastně jsou..."_  - na druhou stranu k předešlému , analytika návštěvníků digit. knihovny a její promítnutí zpětně až do vlastní digitalizace, vývoje knihovny a celého procesu rozhodování. Tímto bysme se měli seriózně začít zabývat.

**Comment by zabak** [comment]
Nejde o to je promovat, ale dát mu přehled co je k dispozici. Kalendář jako souvislou řadu má v hlavě každý. Pokud jsou v té řadě díry, tak tím zašednutím rovnou vidím, že něco chybí (buď to není zdigitalizované zatím, nebo to nemáme, nebo to nemá nikdo, nebo to nevycházelo) - ale rovnou to vidím. Jinak musím hledat, kde je číslování roků přerušené apod. Pokud ale přicházím z nějakého vyhledávacího dotazu, tak na stránku s roky vůbec nepřijdu. V každém případě si myslím, jak už bylo několikrát řečeno, že tohle je vhodný případ na uživatelské testování.

**Comment by honza-rychtar** [comment]
No dobře, tak na základne této diskuze se ptám, jestli mám zrušit i zobrazení výtisků přes kalendáře. Argumenty pro to jsou stejné. Uživatel nepozná jestli chybějící den je z důvodu, že v ten den nic nevyšlo nebo knihova nemá výtisk zdigitalizovaný. Ty prázdné soboty vypadaji špatně, tak je raději zahodíme, ať je víc místa, ale to už to můžeme zahodit celé a zobrazit jen mřižku s náhledy všech zdigitalizovaných čisel.

@indrakm Srovnávat digitální knihovnu s eshopem je sice dost vedle, ale i tak ... jasně že v eshopech ukazují zboží, které namají k dispozici. A hlavně to není o promování ale o vizuálním zobrazení obsahu periodik, stejně jako kalendář je vizuálním zobrazení obsahu ročníku.

**Comment by indrakm** [comment]
@honza-rychtar 
já myslím, že každému je obsah periodika úplně ukradený (zase, myslím si to já jedinec, nemáme žádná zpracovaná data o chování uživatelů) zvláště v digi světě, kde to chci mít prostě hned, proto tam taky jdu, ergo není důvod tam mít, co tam zrovna není. Komu ukradený obsah periodika není, tak ten si to dopátrá ať to tam je nebo ne. To jsou ti, co potom volají. Ale to je jedno, to není na hádání, prostě měli bychom rozhodovat nad daty zanalizovaného uživatelským chováním. To je pointa.

**Comment by pavluska** [comment]
Z meho osobniho pohledu praktickeho testovace: kdyz Honza funkci zavedl, tak jsem si rikala, ze to vypada divne, hlavne, kdyz je zdigitalizovany jeden rocnik z dvaceti, ze jo (mozek knihovnika zaplakal)... Ale ted kdyz vyhledavam (realne neco hledam, ne ze neco testuju), tak jsem za tu funkci sakra rada, protoze mi to setri cas a nervy. Proste mrknu a vidim! Jednim rychlym pohledem zjistim, zda rocnik neco obsahuje nebo ne. Obvykle me ani nezajima, zda byl vydany nebo ne. Proste nemusim resit, jestli nahodou neni zarazeny na konci nebo prehozeny s jinym rokem. Vidim, ze ciselna rada je neprerusena.

Kazdopadne v ramci pouzitelnosti dk a nespolehlivosti metadat je lepsi tam mit vsechny roky. Apeluji  (stejne jako jsem to delala vzdycky) na to, abyste nepremysleli o tom, co si uzivatel asi tak muze myslet, ale zacnete sami dk vyuzivat. Ve volnem case si hledejte informace o historickych udalostech a osobnostech, co maji vyroci nebo proste to, co vas zajima a bavi a uvidite, jaka funkce je realne pouzitelna a jaka ne. Tahle je :)

Souhlasim s tim, ze zobrazeni cisla rocniku by se hodilo, ale kdyz si predstavim tech milion ruznorodych typu zapisu a opet casto nespolehlivost metadat, tak se mi dela fyzicky spatne ;)

**Comment by filak** [comment]
Koukam prave sem http://mzk.kramerius.rychtar.cloud/periodical/uuid:91f1b240-16e8-11e8-8485-5ef3fc9ae867 - a to zobrazeni je prece prepinatelne. Takze se spis muzeme bavit o tom, zda se ma dat pro konkretni objekt/titul periodika nastavit defaultni zobrazeni.

**Comment by krizovj** [comment]
Myslím, že je to tak, že pokud mají všechny ročníky jako datum vydání rok, tak se defaultně zobrazí ty roky (a jde to přepnout na tu mřížku) a když je tam i jen u jednoho ročníku nějaký jiný formát data (třeba rozsah let), tak se zobrazí mřížka a nejde to přepnout na ty roky.

**Comment by BrozekAles** [comment]
Řada uživatelů hledá v Krameriovi i v ANNO a kritizuje, že se v lecčems odlišují. Nechme tam všechny roky...

**Comment by krizovj** [comment]
Promiňte, ale co je ANNO?

**Comment by filak** [comment]
Jinak jsem pro zachování, pokud si to bude uživatel moci přepínat.

**Comment by krizovj** [comment]
Jsem pro zachování, pouze pokud by to šlo nastavit tak, že defaultně se bude vždy zobrazovat mřížka a pokud to bude možné, tak si to uživatel bude moci přepnout  na roky.

**Comment by zabak** [comment]
http://anno.onb.ac.at/

**Comment by indrakm** [comment]
@krizovj 
@filak
souhlasím, máte pravdu.

**Comment by vjirousek** [comment]
Také jsem pro zachování ale pro defaultní zobrazení na mřížku.

**Comment by krizovj** [comment]
Děkuji za ANNO, našla jsem to, ale nebyla jsem si jistá, že je to skutečně ono.

**Comment by filipsir** [comment]
prosim ponechat moznost volby - zobrazovani (dle nejakeho klice asi ze strany MZK - asi z urciteho pole kde je napsano vychazelo od do - a uz vubec v tom zaznamu nenaleznu informaci se kterou by stejne Kramerius mel problemy pracovat) neni mozne (tak jak to tady ctu a vidim na jinych datech nez MZK), aby se zobrazovalo vse viz vyse. 

Pokud se vychazi z rocniku, nekdy mezi rocniky je treba 2/5/n let rozdil. Tedy nemuzu dat zavadejici informaci ze rocniky - chapejme roky, byly ci budou zdigitalizovany. Na datech to tak neni videt, na ostatnich datech ano. 

Tedy prosim moznost volby, resp. dodelat moznost (protoze nedokazeme vycist tyto informace z pole poznamek apod.) zaskrnuti ktere roky tam jeste budou napr. - tedy daleko uzivatelsky prehlednejsi (at uz admin ci ctenar)

**Comment by zabak** [comment]
Nezapomínej ale, jak se uživatel k té informaci (na tu stránku) dostane.  Pokud uživatel hledá primárně fulltext, tak jde přímo na stránku s výsledky. Pokud jde přes titul, tak se mu (alespoň teď) zobrazí přehled digitalizovaných ročníků s náhledy. Teprve při přepnutí na kalendář se mu zobrazí kalendář - a ten logicky obsahuje všechny roky - ne jen některé.

**Comment by filipsir** [comment]
Co je smyslem teto tabulky? Ukazat ctenari spravne hodnoty, tedy ze rocnik byl svazan s timto rokem nebo tam nechat emental, ktery svadi k tomu aby psali ze to chteji mit. Ja nerikam ze A nebo B je spravne, ja rikam, mejme moznost vyberu a trochu i toho nastaveni co chceme

**Comment by krizovj** [comment]
Zase je prostě problém v tom, že nemám možnost uživateli říct, že tady v tom roce sice nic nemáme, ale je to proto, že to nevyšlo a ne proto, že bychom to ještě nezdigitalizovali. Kdyby tam byla tato možnost, tak to určitě má smysl.
A hlavně, teď se roky zobrazují v případech že jsou na to data (roky vydání u všech ročníků jsou ve formě yyyy), defaultně. Takže bych prostě teď jen změnila tohle. Vždycky se to bude zobrazovat jako mřížka. A až pokud uživatel bude chtít a bude to podle dat možné tak si to zobrazí jako roky.

**Comment by zabak** [comment]
Je to zobrazení dle kalendáře. Roky jak jdou za sebou. Podobně jako po rozkliknutí roku měsíce a dny jak jdou za sebou. K některým z nich se váže nějaké číslo, k jiným ne. Protože vím, že tam jsou roky všechny, tak mám na první pohled představu o tom, co mám k dispozici. Ale to už psala Pavla.

**Comment by filipsir** [comment]
Ale to stale nedava smysl Petre. To je jako ze tam dame kalendar celeho roku a ke kazdemu datu v roce budeme vazat nejaky dokument... a vetsina z nich nebude zaplnena, nicmene uzivatelum jsme ukazali kalendar. Ztraci smysl - ma to byt pouzitelne pro dodavatele dat. Kalendar hezky, ale neni to uzivatelsky... 

stejne si ale myslim ze by smyslem melo byt - ne rozptyl roku dle kalendare, resp. ze to v sobe dokument ma, ale pohrat si s tim, aby uzivatel dostal spravnou/presnou/pravdivou informaci o tech rocnicich/cislech. Takto to je funkce co spise pridelava praci vsem

**Comment by zabak** [comment]
Je to přesně tak jak píšeš. Ke každému datu je přiřazen nějaký dokument, nebo taky ne. Prostě zobrazení periodika ve formě kalendáře. Ale webový klient slouží uživatelům, ne dodavatelům dat, to je nedorozumnění. Tohle je opravdu zobrazení kalendáře, tedy časové osy, s vazbou na dostupná čísla. A jak jsem psal, nikdo ten kalendář není povinen používat - primární zobrazení je teď přes seznam digitalizovaných ročníků. Nejsme schopni dát informaci o nezdigitalizovaných ročnících, protože často sami nevíme, jestli daný titul v dané době vyšel nebo ne, jestli kdekoli existuje alespoň jedna kopie apod.

**Comment by krizovj** [comment]
Primární zobrazení je teď podle toho, jak je zapsané datum vydání nebo ne?

**Comment by zabak** [comment]
pravda, to je důvod proč se bavíme o konfigurovatelnsoti.

**Comment by honza-rychtar** [comment]
Takze zaver je takovy, ze zustanou obe zobrazeni a vychozi zobrazeni bude nastavitelne pres konfiguracni soubor. Ok?

**Comment by filipsir** [comment]
Pokud to tak muze byt, bylo by to daleko jednodussi a kazdy pouzije jak potrebuje

**Comment by honza-rychtar** [comment]
V konfiguraci je mozne nastavit:
a) Povolit/zakazat zobrazeni pres roky u seznamu rocniku
b) Vychozi zobrazeni u seznamu rocniku (roky, mrizka)
c) Povolit/zakazat zobrazeni pres kalendar u seznamu cisel
d) Vychozi zobrazeni u seznamu cisel (roky, kalendar)

Nicmene myslete na to, ze uzivatele nepouzivaji jen jednoho - toho vaseho - Krameria. Ruzne chovani stejneho klienta je pak pro ne dost neprijemne.

**Comment by pavelkocourek** [comment]
Kopiruju komentář z mailu od JR : volba zobrazení čísel periodika je následující:
A) Pokud ročník nemá rok ve tvaru yyyy, pak se použije gridové zobrazení a není možné se přepnout na zobrazení kalendáře.
B) Pokud ročník má rok ve tvaru yyyy a zároveň obsahuje alespoň jedno číslo, ktere nemá datum ve tvaru dd.mm.yyyy, pak se použije gridové zobrazení a je možné se přepnout na zobrazení kalendáře.
C) Pokud ročník má rok ve tvaru yyyy a zároveň všechna čísla mají datum ve tvaru dd.mm.yyyy, pak se použije zobrazení kalendáře.

Tohle je výchozí chování. V konfiguraci aplikace je možné změnit výchozí zobrazení na grid a také je možné zobrazení kalendáře kompletně zakázat.

Výchozí nastavení se také změní, pokud uživatel ručně přepne volbu zobrazení. Pak se u něj dál používá toto jím zvolené zobrazení jako výchozí.
