### ISSUE TITLE
Poslední verze klienta - konfigurace jazykových mutací

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#462]
Zdravím,

lze v poslední verzi klienta nějakým způsobem deaktivovat/měnit obsah nabídky podporovaných jazykových mutací?
Např. deaktivovat němčinu?

Díky, MD

**Comment by honza-rychtar** [comment]
V této verzi ne.
Přidal jsem možnost nastavit přes konfiguraci seznam dostupných jazyků (jakoukoli podmnožinu z těch 4 dostupných) a volbu výchozího jazyka. 
Pokud je jazyk jen jeden, tak se výběr jazyka ani vlajka nezobrazuje.
Bude součástí příští verze plánované na konec tohoto týdne.

**Comment by mduda100871** [comment]
> Tak pokud bude nová verze tento týden a bude tam možnost to měnit/deaktivovat, tak je to fajn, dost nám to usnadní život v rychlejším nasazení u nás v KNAV...
> 
> Díky, MD

A poprosím to nastavení pak stručně zdokumentovat na wi-ki.
