### ISSUE TITLE
v2.3.1 - problémy s eČlánky

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#464]
Dobrý den,
narazili jsme na dva drobné problémy při prohlížení eČlánků (těch, kde je u každého článku samostatné PDF) v novém klientovi:

**1) Když dojedu na konec PDF jednoho článku a překliknu na další, tak je PDF dalšího článku zarolováno úplně nakonec** (nestává se ale vždy)

**2) Levý boční panel neukazuje, který článek si zrovna čtenář prohlíží** (chybí podbarvení v menu): 
Staré rozhraní:
![image](https://user-images.githubusercontent.com/57805328/152781522-eff1b0c7-2561-4e7d-baff-6d7318b6a022.png)

Nové verze:
![image](https://user-images.githubusercontent.com/57805328/152781676-fe22fd0e-5ac2-4414-bda3-96f7a0194679.png)  

Díky, FK

**Comment by honza-rychtar** [comment]
Opraveno
http://dk.kramerius.org/knav/view/uuid:883795fb-5d63-4247-a71e-fb6d4dc631c8?article=uuid:e65e7307-67b1-4c01-b1d2-19519d0a9798

**Comment by kerschfilip** [comment]
u eČlánků je to opraveno, dokonce to podle mě vypadá líp než předtím, takže moc díky!

Všiml jsem si, že obdobně jako před opravou se to chová u eMonografií - například tady: http://dk.kramerius.org/knav/view/uuid:a003e056-94a2-4560-a7d4-932e1bd23c10  
je možné nastavit podbarvování i tady, nebo je to složitější tím, že se ten obsah vytahuje přímo z PDF?

**Comment by honza-rychtar** [comment]
Je to složitější, ale udělám jsem to. Bude to v příští verzi.

**Comment by honza-rychtar** [comment]
Hotovo ve verzi 2.3.3
Např. http://dk.kramerius.org/knav/view/uuid:a003e056-94a2-4560-a7d4-932e1bd23c10
Pokud pdf obsahuje kapitoly, tak se synchronizuje aktuálně zobrazená kapitola v pdf s navigací, kde se podbarví tato kapitola. I když scrolluju v pdf, tak se postupně podbarvují kapitoly v  navigaci.

Funguje to i pro podkapitoly, které se rozbalí šipkou v navigaci. 
<img width="549" alt="Snímek obrazovky 2022-03-10 v 17 56 52" src="https://user-images.githubusercontent.com/1178142/157715351-3e60e4c8-7bfa-4a74-b09e-219cf6030145.png">

<img width="550" alt="Snímek obrazovky 2022-03-10 v 17 57 51" src="https://user-images.githubusercontent.com/1178142/157715364-09011590-640b-4d82-9ed5-de4735f60a35.png">

**Comment by kerschfilip** [comment]
otestováno, vypadá to dobře, mockrát děkuji!
