### ISSUE TITLE
v2.3.1 - tlačítko "zavřít" v okně "informace o autorech" je jinde a jiné

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#465]
ve verzi v2.3.1 je tlačítko "zavřít" v okně "informace o autorech" vlevo a vypadá trochu jinak než v ostatních modálních oknech, která se zobrazují při prohlížení metadata, generování citace a sdílení. Šlo by to, prosím, upravit tak, aby to bylo všude stejné?

Informace o autorech:
![image](https://user-images.githubusercontent.com/57805328/152783337-07ff1914-2731-49c1-a4ab-2d0967f80fc6.png)
ostatní:
![image](https://user-images.githubusercontent.com/57805328/152783532-0554431f-d2a9-489a-859f-eb5afcba0d18.png)

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.3.2

**Comment by kerschfilip** [comment]
opraveno, děkuji.
