### ISSUE TITLE
v2.3.1 - Mobilní zobrazení - okna pro metadata/citace atd. nejsou dobře vidět

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#468]
Dobrý den,

v nové verzi klienta se při zobrazení na mobilu řadí okna zobrazující metadata/citaci/odkaz atd. až pod panel s informacemi, takže nejsou vidět, viz screenshot:

![image](https://user-images.githubusercontent.com/57805328/153370529-d9ff5dc1-e02b-485e-b80a-7e8fcdef83ad.png)

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.3.2

**Comment by kerschfilip** [comment]
opraveno, děkuji!
