### ISSUE TITLE
v2.3.1 - změna stylu písma a horší kontrast 

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#469]
V nové verzi došlo ke změnám ve stylu/tloušťky písma, což způsobuje, že některé údaje v pravém postranním panelu nemusí být pro všechny dobře čitelné: konkrétně myslím texty jako "ISBN", "Autor", "Nakladatelské údaje",... 
Problém je hlavně kontrast mezi barvou písma a pozadím, který je příliš malý, přikládám ještě screen z contrast checkeru: 

Šlo by to, prosím, lehce upravit? Děkuji, FK

![image](https://user-images.githubusercontent.com/57805328/153372413-f8ef3ab5-e14d-41d0-9d84-e06470a05cf3.png)
  
![image](https://user-images.githubusercontent.com/57805328/153373246-1112a82c-8133-4c50-b5d8-dd615a96ee29.png)

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.3.2**

Původně
<img width="299" alt="Snímek obrazovky 2022-02-13 v 15 30 32" src="https://user-images.githubusercontent.com/1178142/154980264-821f3c6d-3d80-4eb9-96d6-dae4c60bc326.png">
Teď
<img width="301" alt="Snímek obrazovky 2022-02-13 v 15 30 46" src="https://user-images.githubusercontent.com/1178142/154980259-f983d7a2-76ed-4a8f-bd61-d4d8c883e039.png">

**Comment by kerschfilip** [comment]
super, děkuji!
