### ISSUE TITLE
nefunkcni prehravani na zarizenich iphone s iOS 

### ISSUE THREAD

**Issue by filipsir** [ceskaexpedice/kramerius-web-client#47]
nefunguje na safari, chrome, ani google apkach.

**Comment by filipsir** [comment]
prosim, udalo se neco v tomto kroku? ted mi na testovacim krameriovi data mzk jdou z ios prehrat. ale nas zkusebni instalace na nasich datech je neprehraje - zvukace. Muzete mi napsat @honza-rychtar zda se v tom neco neudelalo? nez to bude @MartinRumanek u nas kontrolovat. dekuji

**Comment by honza-rychtar** [comment]
Predpokladam, ze myslis tuto zkusebni instalaci - http://k.nm.cz/
Problem bude v konfiguraci audioserveru, protoze pri pozadavku na MP3 (nebo jiny zvukovy) stream vraci Kramerius "audioserver.nm.cz: Name or service not known", napr.
http://k.nm.cz/search/api/v5.0/item/uuid:762b9f1d-11f2-44db-ad19-c32bf1ceee20/streams/MP3
Stejny dotaz na server zvuk.nm.cz funguje
http://zvuk.nm.cz/search/api/v5.0/item/uuid:762b9f1d-11f2-44db-ad19-c32bf1ceee20/streams/MP3

Tohle se netyka klienta.

**Comment by filipsir** [comment]
jo, presne. ano, na zvuku to funguje, to vime. ale ten bude vypnut do mesice... ted se jedna o novou instalaci ktera nam spojila dve digi knihovny. tak snad to @MartinRumanek uvidi a bude vedet. Dekuji za identifikaci a pomoc

**Comment by MartinRumanek** [comment]
k.nm.cz je moje chyba. Opravim to.

**Comment by filipsir** [comment]
to nebyla tvoje chyba... klient to neumel v dobe kdy jsem to psal - neslo na ios prehravat v zadnem prohlizeci. ted to jde, tak jsem se ptal co s tim

**Comment by honza-rychtar** [comment]
Opraveno
