### ISSUE TITLE
Vypnuté filtry nezobrazovat jako link 

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#473]
Pokud nemám v konfiguraci aktivní filtry **Typ dokumentu**, **Klíčová slova**, **Jazyk**, tak se přesto zobrazují v podrobnostech jako link, který vede do vyhledávání s tímto (vypnutým) filtrem, který pak nefunguje.

**Comment by zabak** [comment]
Tohle je asi jiný problém, ale trochu asi souvisí: Když jdu do MZK: https://k7-test.mzk.cz/mzk/search tak máme nastavenou licenci DNNTO ve fasetě licence. Pak přepnu šipečkou vedle počtu výsledků na jinou knihovnu, kde licence nejsou nastavené. Licence zůstanou ve fasetách v této podobě: 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/811537/155219594-7b042ebc-6e68-439e-befd-08de0ce76c5c.png">

**Comment by honza-rychtar** [comment]
@zabak To s tím vůbec nesouvisí. Ale problém to jo, přepsal jsem sem #485 a opravím.
Tohle issue považuju za dokončené.
