### ISSUE TITLE
Zobrazení identifikátoru urn:nbn v popisu dokumentu

### ISSUE THREAD

**Issue by vjirousek** [ceskaexpedice/kramerius-web-client#476]
Prosím o rozšíření zobrazovaných metadat o identifikátor urn:nbn.

Viz pravidla pro registrátory v systému CZIDLO: "5. V digitální knihovně musí registrátor vystavit identifikovaný dokument tak, aby byl identifikátor URN:NBN viditelný pro čtenáře a uvedený v sekci s bibliografickými metadaty (např. názvem) popisujícími tento dokument."

https://resolver.nkp.cz/web/#tab1

**Comment by luckajirku** [comment]
A není tahle podmínka splněná tím, že to lze dohledat v xml přes "Metadata"? Viditelné to je, v sekci s popisnými metadaty to je. Přijde mi zbytečné tím zabírat místo - normální uživatel ocení jiné údaje o dokumentu, ne?

**Comment by vjirousek** [comment]
> A není tahle podmínka splněná tím, že to lze dohledat v xml přes "Metadata"? Viditelné to je, v sekci s popisnými metadaty to je. Přijde mi zbytečné tím zabírat místo - normální uživatel ocení jiné údaje o dokumentu, ne?

Dohledatelný a viditelný není totéž.

Navíc si nemyslím že by uživatel nemohl ocenit v popisu nějaký jednoznačný identifikátor zobrazeného dokumentu, aktuálně může sáhnout leda po url adrese pokud nemá dokument ISBN.

**Comment by stanislavteplik** [comment]
Dobrý den, rád bych se k problematice vrátil. U monografií se URN:NBN zobrazuje validně, ale v případě periodik se očekává URN:NBN na úrovni titulu a nikoli čísla, se kterým je URN:NBN svázáno. Šlo by prosím do budoucna opravit? Díky.

**Comment by rzeh4n** [comment]
> Dobrý den, rád bych se k problematice vrátil. U monografií se URN:NBN zobrazuje validně, ale v případě periodik se očekává URN:NBN na úrovni titulu a nikoli čísla, se kterým je URN:NBN svázáno. Šlo by prosím do budoucna opravit? Díky.

Je dobré uvádět příklady (odkaz, uuid, urn:nbn, ...). V nějakém kontextu to může vypadat, že něco je obecným pravidlem, ale může to tak být jen pro určitou instituci, sbirku, fond, ...
Třeba urn:nbn může být obecně přiřazeno jak číslu, tak ročníku/svazku, tak samotnému periodiku. A nebo nějaká kombinace.

**Comment by stanislavteplik** [comment]
Zasílám doplňující iniformace.
Zde příklad: https://www.digitalniknihovna.cz/nkp/uuid/uuid:7e0f66d0-8c7f-11e2-b269-5ef3fc9ae867
Na titulu je urn:nbn:cz:mzk-0005qh.
Na čísle je urn:nbn:cz:mzk-0003nh.
Klient ukazuje urn:nbn titulu. Což by urn:nbn přiděleno ani mít nemělo dle metodiky https://standardy.ndk.cz/ndk/archivace/Certifik_metodika_urnnbn_2018.pdf

Pak je zde například: https://www.digitalniknihovna.cz/nkp/uuid/uuid:34886f50-f5bf-11ef-bd9e-5ef3fc9bb22f
Které má urn:nbn pouze na čísle a to se v klientovi neukáže.

Nebylo by tedy vhodné, aby se v klientovi u periodik ukazovalo urn:nbn čísla, případně ročníku (ale pouze pokud koukám na stránku s výpisem ročníků)?

**Comment by vjirousek** [comment]
> Zasílám doplňující iniformace. Zde příklad: https://www.digitalniknihovna.cz/nkp/uuid/uuid:7e0f66d0-8c7f-11e2-b269-5ef3fc9ae867 Na titulu je urn:nbn:cz:mzk-0005qh. Na čísle je urn:nbn:cz:mzk-0003nh. Klient ukazuje urn:nbn titulu. Což by urn:nbn přiděleno ani mít nemělo dle metodiky https://standardy.ndk.cz/ndk/archivace/Certifik_metodika_urnnbn_2018.pdf
> 
> Pak je zde například: https://www.digitalniknihovna.cz/nkp/uuid/uuid:34886f50-f5bf-11ef-bd9e-5ef3fc9bb22f Které má urn:nbn pouze na čísle a to se v klientovi neukáže.
> 
> Nebylo by tedy vhodné, aby se v klientovi u periodik ukazovalo urn:nbn čísla, případně ročníku (ale pouze pokud koukám na stránku s výpisem ročníků)?

U prvního příkladu je to zamotanější a část problému je v datech – při NDK digitalizaci se urn:nbn přidělené číslu propisovalo minimálně po určitou dobu z čísla chybně i na úroveň titulu. Do Krameria pak proniklo "titulové" urn:nbn z prvního importovaného čísla jehož identifikátoru pak odpovídá. V každém případě v metodice rovněž čtu že pro titul periodika se urn:nbn nevyužívá, takže řešením by u periodik mělo být zobrazování identifikátoru pro úroveň čísla (zda se reálně přiděluje ročníkům si nejsem jistý).

**Comment by FilipPavcik** [comment]
Dobrý deň, ja iba doplním, že ročníkom periodika je síce možné prideliť URN, ale v praxi sa reálne ročníkom URN neprideľuje... 

Čiže v Krameriovi by sa na úrovni titulu ani ročníku periodika nemalo zobrazovať žiadne URN, keďže týmto úrovniam nebolo pridelené. URN by sa malo zobraziť len u daného čísla periodika.
