### ISSUE TITLE
Navigace, pracovni protredi pri detailu

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius-web-client#477]
Zde uverujniji zpetnu vazbu ctenare ke klientovi, zejmena k rozvrzeni pracovniho prostredi:

>Navigace zobrazených stran je velmi nepraktická, rolování při zvětšování obsahu nevydrží na další stránky, ale musí se po načtení další vždy opakovat. Při jakékoli manipulaci s oknem si aplikace nepamatuje předchozí uložené kroky, navíc při detailním zvětšení stránky se nezobrazí celá stránka, ale jen její část. Okno rovněž považuji za malé a celá internetová stránka je zbytečně obohacena o další nepodstatné informace vpravo, které při detailní práci s dokumentem nepotřebuji a můžu si je najít zvlášť, včetně zbytečně velkých oken s ostatními naskenovanými stránkami vlevo.

**Comment by zabak** [comment]
@honza-rychtar vzhledem k tomu že zámek zoomu řeší #31 a okno se stránkou je možné zvětšit na celou obrazovku nebo jen skrýt pravé menu, navrhuji zde uzavřít.
