### ISSUE TITLE
Ohýbání slov při plnotextovém hledání

### ISSUE THREAD

**Issue by KarolinaKostalova** [ceskaexpedice/kramerius-web-client#48]
Na http://sluzby.incad.cz/kramerius/ jsem zadala dotaz: chytla kořalka

Mezi výsledky je i Čech. 1908, roč. 33, č. 97 (7. 4. 1908), s. 5 - http://sluzby.incad.cz/kramerius/periodical/uuid:5c259210-2182-11e6-918e-5ef3fc9ae867?fulltext=chytla%20ko%C5%99alka&accessibility=all, http://sluzby.incad.cz/uuid/uuid:c95f2980-771e-11e6-bb23-005056827e51 

Na stránce je zvýrazněno slovo Kořalka. Slovo chytla je na stránkce podle textového přepisu ve tvaru chytnout. 

Znamená to, že K6 automaticky hledaná slova ohýbá? To se určitě hodí. 

Někdy zároveň hledám slovo v konkrétním tvaru, tj. potřebuju, aby v textu bylo slovo "chytla", nikoliv jiný tvar tohoto slova. Zkoušela jsem dát obě slova do uvozovek, ale nezdá se, že by to mělo na výsledky vliv. I tak se našel Čech z 7. 4. 1908.

**Comment by pavel-stastny** [comment]
Dobrý den, 

> Na stránce je zvýrazněno slovo Kořalka. Slovo chytla je na stránkce podle textového přepisu ve tvaru chytnout.
> 
> Znamená to, že K6 automaticky hledaná slova ohýbá? To se určitě hodí.
> 
nezáleží to na klientovi ale na verzi indexu. Ohýbání je přítomno od přechodu na novější verzi solru .  Probíralo se to i u issue  #24. 

> Někdy zároveň hledám slovo v konkrétním tvaru, tj. potřebuju, aby v textu bylo slovo "chytla", nikoliv jiný tvar tohoto slova. Zkoušela jsem dát obě slova do uvozovek, ale nezdá se, že by to mělo na výsledky vliv. I tak se našel Čech z 7. 4. 1908.

Toto se rovněž týká předchozího.     Pole `text_ocr ` je nyní pouze v lemmatizovaném tvaru. Byla vydána verze 
[5.4.1](https://github.com/ceskaexpedice/kramerius/releases/tag/v5.4.1_patch) se změnami ve schématu, kde jsou přítomny obě varianty nicméně je nutná reindexace dat a to nějakou dobu potrvá.

**Comment by honza-rychtar** [comment]
Nakonec jsem v klientovi vubec nepouzil **text_ocr** a misto toho pouzil **text**, ale i tak se aktualni verze solru a stav indexu v MZK Krameriovi chova podivne. 
V Digitalni knihovne je pouzito pole **text_ocr** a ve vysledku se chovani v tomto klientovi a v Digtialni knihovne prohazuje (jakoby cast dat fungovala na puvodnim solr schematu a cast na novem). 
Tohle ted nema smysl resit - MZK bude schema aktualizovat a data reindexovat.

**Comment by honza-rychtar** [comment]
Problem solru, vyresi nove verze, pripadne reindexace.
