### ISSUE TITLE
U PDF dokumentů nefungují tlačítka pro stažení a tisk

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#484]
Zdravím,

ve verzi 2.3.2 (a pravděpodobně i té minulé) nefungují tlačítka pro stažení a tisk u eborn dokumentů. Po kliknutí na příslušné ikonky se nic nestane. U naskenovaných titulů to funguje normálně.

Příklad emonografie, kde to nefunguje: http://dk.kramerius.org/knav/view/uuid:ed65c75e-7e2b-4737-b4c3-eaca34a994e0

**Comment by honza-rychtar** [comment]
U pdf dokumentů bude tlačítko pro stažení.
<img width="825" alt="Snímek obrazovky 2022-03-04 v 11 36 00" src="https://user-images.githubusercontent.com/1178142/156747998-52b709ea-1d85-4586-ae27-d1da829f4019.png">
Bude v příští verzi.

**Comment by honza-rychtar** [comment]
Hotovo ve verzi 2.3.3

**Comment by kerschfilip** [comment]
ověřeno, funguje, mockrát děkuji!
