### ISSUE TITLE
Přepnutí knihovny u hledání neaktualizuje fasetu licence

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#485]
Od @zabak 
https://github.com/ceskaexpedice/kramerius-web-client/issues/473#issuecomment-1048212669

> Tohle je asi jiný problém, ale trochu asi souvisí: Když jdu do MZK: https://k7-test.mzk.cz/mzk/search tak máme nastavenou licenci DNNTO ve fasetě licence. Pak přepnu šipečkou vedle počtu výsledků na jinou knihovnu, kde licence nejsou nastavené. Licence zůstanou ve fasetách v této podobě:

**Comment by honza-rychtar** [comment]
Opraveno.

**Comment by zabak** [comment]
Funguje
