### ISSUE TITLE
Přihlašování v DK

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#486]
@honza-rychtar rád bych se zbavil těch duplicitních ikon DNNT knihoven v horním řádku rozcestníku a napadlo mě, že teď když funguje proklik na přihlašování z údaje o licenci, tak by se to dalo stejně udělat i pro přihlašovací link v horním menu. 

Tj. pokud zapnu link na přihlášení na digitalniknihovna.cz/mzk, tak ten link povede na https://dnnt.mzk.cz/podminky-zpristupneni?target=https://dnnt.mzk.cz/ + případné uuid kam se má po přihlášení skočit. Totéž by se analogicky udělalo pro další DNNT Kramerie. Šlo by to? Muselo by se to nastavit v configu pro každý kramerius samostatně, což nevím jestli je teď možné.

**Comment by honza-rychtar** [comment]
@zabak Ano, v K7 už to přihlašování pro každou knihovnu zvlášť je. 
Tady se ty dnnt přihlašování řeší globálně, protože dnnt instalace jsou vždy _jednokrameriové_.
V DK by se to hodilo mít na úrovni knihovny a řešení, které navrhuješ je možné. Tím že target url půjde vždy mimo DK, tak se vlastně přihlášený uživatel a odhlašování v této instalaci stejně nebude řešit a půjde jen o url tlačítka Přihlásit.

**Comment by zabak** [comment]
@honza-rychtar viz dnešní diskuse + pull request #459

**Comment by honza-rychtar** [comment]
Konfigurace přihlášení `auth` se přesunula z globální úrovně do úrovně jednotlivého Krameria, takže je teď možné definovat `auth.loginUrl` pro každého Krameria zvlášť.
Na http://dk.kramerius.org jsem vyhodil z rozcestníku ty dnnt instalace a u MZK, KNAV a NKP jsem nakonfiguroval `auth.loginUrl` na ty jednotlivé dnnt instalace, takže u těchto 3 Krameriů je v navbaru tlačítko Přihlsit, které vede na přihlášení do dané dnnt instalace.

**Comment by luckajirku** [comment]
>  u MZK, KNAV a NKP jsem nakonfiguroval `auth.loginUrl` na ty jednotlivé dnnt instalace, takže u těchto 3 Krameriů je v navbaru tlačítko Přihlsit, které vede na přihlášení do dané dnnt instalace.
> 
Bylo by možné to udělat stejně i u SVK HK?

**Comment by honza-rychtar** [comment]
@luckajirku jo jo, to je čistě na konfiguraci klienta. A MZK už to do DK přidala.
Ještě je tam jedem problém https://github.com/ceskaexpedice/kramerius-web-client/issues/436#issuecomment-1129761960, kvůli kterého se s DK přes přihlášení do jiného klienta nenačte stejná stránka, odkud z toho původního klienta uživatel odešel. To vyřešíme ještě během tohoto týdně.

**Comment by honza-rychtar** [comment]
Oprava předání cesty do jiné instalace klienta https://github.com/ceskaexpedice/kramerius-web-client/issues/436#issuecomment-1198240254

**Comment by zabak** [comment]
Fukguje, zavírám
