### ISSUE TITLE
Tlačítko "kopírovat" u citací

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#489]
Šlo by prosím doplnit kopírovací tlačítko u citací, stejně jako je tomu u sdílení? Nedává smysl to mít jen u jednoho a u druhého ne. Kromě toho je to dost problém na telefonu, kde se pak dá hodně obtížně ta citace kopírovat. :)

![image](https://user-images.githubusercontent.com/43028501/157483617-bd41f8e2-3a0b-4dbc-9c23-1b66bdb3fa04.png)

vs

![image](https://user-images.githubusercontent.com/43028501/157483700-cd5e9d6f-f9ff-48d1-aa19-7f5bdcd4b495.png)

**Comment by honza-rychtar** [comment]
Hotovo ve verzi 2.3.3
Např. tady
http://www.digitalniknihovna.cz/mzk/uuid/uuid:ea8e5950-2161-11e5-bcc5-5ef3fc9bb22f
<img width="786" alt="Snímek obrazovky 2022-03-10 v 17 49 33" src="https://user-images.githubusercontent.com/1178142/157713466-9d2d2aae-5ce8-4943-9437-f5221e826ac3.png">

**Comment by zabak** [comment]
otestováno, zavírám

**Comment by honza-rychtar** [comment]
@annie-cz Založil jsem k tomu nové issue #492. Ono se to potom blbě trackuje, když se rozšiřují už uzavřená issue a původní problém už je vyřešený.

**Comment by annie-cz** [comment]
Pardon, pravda, moje chyba. Já jsem si toho bohužel všimla až později, jinak bych to zahrnula rovnou u tohoto issue.
