### ISSUE TITLE
Plnotextové hledání - v rámci jednoho čísla periodika

### ISSUE THREAD

**Issue by KarolinaKostalova** [ceskaexpedice/kramerius-web-client#49]
Na stránce http://sluzby.incad.cz/uuid/uuid:25ad77d0-61e6-11dc-9ffc-000d606f5dc6 (LN z 19. 2. 1920, ráno, s. 1) se  v článcích vyskytují mimo jiné tyto věty: ...Byla avisována vojenská pohotovost. Zatím hrnuli se se všech stran němečtí venkované do Pohořelic... 

Pokud chci na http://sluzby.incad.cz/uuid/uuid:25ad77d0-61e6-11dc-9ffc-000d606f5dc6 hledat v zobrazeném čísle a zadám slovo pohotovost:
* pohotovost - nenajde se nic (přitom na straně 1 toto slovo průkazně je, hraje roli, že je za ním tečka? Slovo je v OCR přečteno správně.)
* pohotovost - pokud zaškrtnu možnost "všechny stránky", na první stránce vydání se slovo pohotovost označí

Stejně se v LN z 19. 2. 1920 chová např. slovo vesnic, které se na stránce také vyskytuje. Nebo slovo Obrana (je na straně 2). 

Nebo Venkov z  1. 1. 1916, s. 1 - http://sluzby.incad.cz/uuid/uuid:c74755e0-c66f-11e7-80e7-5ef3fc9bb22f.
Na první stránce se vyskytují např. slova ruské dumy nebo pravice dumy. Při hledání v rámci čísla jsem musela zaškrtnout "všechny stránky", aby se slova našla. Jinak byl výsledek 0. Zkoušela jsem hledat jedno slovo: dumy (slovo se označilo správně v textu článku, ale v nadpisu článku už ne - tam to bude souviset se špatně přečteným ocr) i kombinace ruské dumy a pravice dumy. 
Pokud zadám dotaz pravice dumy do celého Krameria, stránku z Venkova z 1. 1. 1916  ve výsledcích nevidím.

**Comment by honza-rychtar** [comment]
Viz #48 
Tohle zrovna v Digitalni knihovne funguje, protoze se pouziva **text_ocr**. Nicmene slovo _pohotovost_ by melo byt nalezeno i pres pole **text**
Kdyz zkusite hledat nejake jine slovo, ktere vidite na strance, tak ho to najde.
Tohle nesouvisi s klientem. Bohuzel je MZK index v takovemto stavu.
V digitalni knihovne se pouziva **text_ocr**, coz kvuli lemmatizaci casto vraci spoustu (nerelevantnich) vysledku a nekdy zase funguje i vlozeni fraze do uvozovek, coz by v nasazene verzi solru prave kvuli lemmatiazaci vubec fungovat nemelo. 
V novem klientovi se zase s pouzitim **text** obsac nenajdou zadne vysledky, nebo jsou vysledky omezeny.

Bude se resit az s novou verzi solru. Klient pak bude pouzivat kombinaci **text** a **text_lemmatized**.

**Comment by honza-rychtar** [comment]
Problem solru, vyresi nove verze, pripadne reindexace.
