### ISSUE TITLE
Tlačítko kopírovat u textového přepisu.

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#492]
Viz https://github.com/ceskaexpedice/kramerius-web-client/issues/489#issuecomment-1070753869
Možnost kopírovat text i citaci.

**Comment by zabak** [comment]
@honza-rychtar když už to budeš řešit, zohledni prosím i #377 a #369. Ne nutně je rovnou vyřešit, ale zkopírovat ten text včetně konců řádků.

**Comment by honza-rychtar** [comment]
Doplněno ve verzi **2.3.5**
<img width="1212" alt="Snímek obrazovky 2022-05-10 v 16 17 06" src="https://user-images.githubusercontent.com/1178142/167650583-7c4ae5a6-4c89-4680-8f45-d5cff91a3a92.png">

**Comment by zabak** [comment]
Ověřeno. Prosím o zvážení jestli by alt text neměl místo generického "zkopírovat do schránky" být "zkopírovat text do schránky" a "zkopírovat citaci do schránky"

**Comment by zabak** [comment]
@honza-rychtar prosím o vyjádření

**Comment by honza-rychtar** [comment]
@zabak No nevím, myslím že je  text od citace dostatečně oddělený, aby bylo jasné co k čemu patří.
Ony tyhle zpřesňování s sebou nesou potřebu udržovat texty na více místech, máme to ve 4 jazycích, tlačítko je ještě na dalších 2 místech, takže pak by se mělo zvážit i zkopírovat ODKAZ do schránky.

**Comment by zabak** [comment]
OK, zavírám
