### ISSUE TITLE
Na mobilu není vidět horní menu

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#493]
Ve verzi 2.1.2 to ještě fungovalo, ale v 2.3.2 už ne. Menu při zmenšování šířky stánky zmizí a není jak ho zobrazit, přežije jen vlaječka. Prosím zachovat např. v podobě hamburger ikony, hlavně chybějící link na přihlášení je problém, nedá se ale dostat ani na seznam sbírek a další.

**Comment by honza-rychtar** [comment]
<img width="500" alt="Snímek obrazovky 2022-05-10 v 16 07 06" src="https://user-images.githubusercontent.com/1178142/167648565-9cf100e7-2dd7-4738-8fd3-753ac199c81d.png">

Dostupné ve verzi 2.3.5

**Comment by zabak** [comment]
otestováno, díky!
