### ISSUE TITLE
Doplnit popis konfigurace pro mapové zobrazení výsledků

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#494]
Doplnit do release notes 2.3.1 popis konfigurace a postupu získání API klíče podkladové mapy pro zobrazení výsledků hledání na mapě

**Comment by honza-rychtar** [comment]
Doplnil jsem to do releasu https://github.com/ceskaexpedice/kramerius-web-client/releases/tag/v2.3.1 a do wiki k nasazení klienta https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta#hled%C3%A1n%C3%AD-p%C5%99es-pozici-na-podkladov%C3%A9-map%C4%9B

**Comment by zabak** [comment]
Díky, API key podle toho návodu jsem vytvořil, zavírám.
