### ISSUE TITLE
nameIdentifier se zobrazuje ve fasetě autorů

### ISSUE THREAD

**Issue by kvetjo** [ceskaexpedice/kramerius-web-client#498]
V našem Krameriu jsme narazili na záležitost, která nám nepřipadá správně/užitečně. Všiml jsem si, že se nejedná pouze o našeho Krameria, ale že stejný problém se vyskytuje i v dalších digitálních knihovnách. 
Jde o to, že ve fasetě autorů se vyskytují mimo samotných jmén také ID autorů z metadatového pole "nameIdentifier". Tato věc je viditelná i v případě procházení podle autorů. 
Určitě je dobře, že Kramerius umí vyhledávat i podle identifikátoru autora, na to to ale podle mě nemusí být ve fasetě, kde pak je současně jméno autora i jeho ID, což je zbytečné a matoucí.
![Výstřižek](https://user-images.githubusercontent.com/71756310/160395517-8035db8f-01d3-4c64-85a1-df2a938aa12b.PNG)

Možná se však za touto skutečností skrývá úmysl a má to svůj opodstatněný důvod, v takovém případě se omlouvám a budu rád za objasnění důvodu, 

Díky moc, 

Jonáš Květ
ÚK UK

**Comment by honza-rychtar** [comment]
Tohle je určitě špatně. Ale není to standardní chování. Ty identifikátory se vám propisují do indexu do polí `facet_autor`, `search_autor` a tam nepatří. Starý indexer bere tuším autory z DC a ne MODS a právě v DC máte ty identifikátory, kam nepatří. V MODS to rozlišit jde, ale v DC už je identifikátor od jména autora nerozlišitelný (z pohledu struktury). Pokud se to pak zaindexuje, tak je to nerozlišitelné i v indexu a ani v klientovi potom.
Ono by to šlo odfiltrovat na úrovni indexace i na úrovni klienta, ale prvotní problém je to, že to máte špatně v podkladových datech.
V K7 se DC nepoužívá, tam tento problém nebude.
Srovnejte MODS, DC, SOLR u dokumentu v UK a MZK.

### UK
http://kramerius.cuni.cz/uuid/uuid:6ded0ee8-8daf-45ae-baa4-6d75ead0eaae
MODS
http://kramerius.cuni.cz/search/api/v5.0/item/uuid:6ded0ee8-8daf-45ae-baa4-6d75ead0eaae/streams/BIBLIO_MODS
```
<mods:name type="personal" usage="primary">
  <mods:namePart type="family">Kapras</mods:namePart>
  <mods:namePart type="given">Jan</mods:namePart>
  <mods:namePart type="date">1880-1947</mods:namePart>
  <mods:role>
    <mods:roleTerm authority="marcrelator" type="code">aut</mods:roleTerm>
  </mods:role>
  <mods:nameIdentifier>jk01052930</mods:nameIdentifier>
</mods:name>
```
DC
http://kramerius.cuni.cz/search/api/v5.0/item/uuid:6ded0ee8-8daf-45ae-baa4-6d75ead0eaae/streams/DC
```
<dc:creator>Kapras, Jan, 1880-1947</dc:creator>
<dc:creator>jk01052930</dc:creator>
```
SOLR 
http://kramerius.cuni.cz/search/api/v5.0/search?q=PID:%22uuid:6ded0ee8-8daf-45ae-baa4-6d75ead0eaae%22
```
"facet_autor": [
  "Kapras, Jan, 1880-1947",
  "jk01052930"
],
"search_autor": [
  "Kapras, Jan, 1880-1947",
  "jk01052930"
],
```

### MZK
http://www.digitalniknihovna.cz/mzk/uuid/uuid:7d253610-8338-11eb-b9bf-005056827e52
MODS
https://kramerius.mzk.cz/search/api/v5.0/item/uuid:7d253610-8338-11eb-b9bf-005056827e52/streams/BIBLIO_MODS
```
<mods:name type="personal" usage="primary">
  <mods:namePart>Jirásek, Alois</mods:namePart>
  <mods:namePart type="date">1851-1930</mods:namePart>
  <mods:role>
    <mods:roleTerm authority="marcrelator" type="code">aut</mods:roleTerm>
  </mods:role>
  <mods:nameIdentifier>jk01051816</mods:nameIdentifier>
</mods:name>
```
DC
https://kramerius.mzk.cz/search/api/v5.0/item/uuid:7d253610-8338-11eb-b9bf-005056827e52/streams/DC
```
<dc:creator>Jirásek, Alois</dc:creator>
```
SOLR
https://kramerius.mzk.cz/search/api/v5.0/search?q=PID:%22uuid:7d253610-8338-11eb-b9bf-005056827e52%22
```
"search_autor": [
  "Jirásek, Alois"
],
"facet_autor": [
  "Jirásek, Alois"
],
```

**Comment by kvetjo** [comment]
Díky za rychlou reakci. Mám k tomu ještě poznámku. Nejsem si jistý, do jaké míry to může být našimi podkladovými daty - jde o to, že nám to takto leze z Proarcu, nicméně když prohlížím metadata v Proarcu, tak ID autora je správně rozpoznané a zařazené v poli "nameIdentifier". viz obrázek:
![image](https://user-images.githubusercontent.com/71756310/161013068-d201d858-539b-41ec-8750-26a412795a6f.png)

Další věc je ta, jak už jsem zmínil v původním příspěvku, že jsem si všiml, že náš Kramerius není jediný, u kterého se tento problém vyskytuje. Například v KNAV také mají v některých případech ve fasetě autorů i jejich ID:
![image](https://user-images.githubusercontent.com/71756310/161013690-5a368c56-122f-421c-8504-353e8d0140d1.png)

Pokud i přesto bude řešením přejít na K7, je otázka do jaké míry je potřeba řešit problémy ve starší verzi. 
Díky,
Jonáš Květ

**Comment by honza-rychtar** [comment]
Takže odpověď stále stejná. I KNAV má ty identifikátory v DC a K5 indexuje autora z DC. Indexer ani potom klient takto není schopný odlišit jméno autora od jeho identifikátoru, protože jsou obě hodnoty ve stejném poli.

Přechod na K7 to vyřeší, protože K7 indexer nepoužívá DC ale MODS, odkud se berou pouze jména autorů.

Další řešení je úprava DC a reindexace. Pokud se to děje i u nových dat, pak opravou šablony pro generování DC.

Každopádně klienta se to netýká a tady to můžeme zavřít.
