### ISSUE TITLE
Nefunguje tlačítko "zobrazit citaci" 

### ISSUE THREAD

**Issue by JanaHrzinova** [ceskaexpedice/kramerius-web-client#5]
Nefunguje tlačítko "zobrazit citaci"

**Comment by honza-rychtar** [comment]
Neni implementovane. Je to v reseni a nejspis se pouzije napojeni na Citace PRO, podobne jako je to na knihovny.cz

**Comment by pavelkocourek** [comment]
Je třeba specifikovat, na co bude tlačítko napojeno - projdeme na schůzce.

**Comment by honza-rychtar** [comment]
Tlacitko odstraneno, dokud nebude vyresena implementace, dal viz #36
