### ISSUE TITLE
Výběr stran dokumentu pro tisk/generování PDF

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#50]
Ponechat aktuální možnost vybrat strany "od do". Měla by přibýt závorka o maximálním počtu stran. Například pokud je aktuálně označena strana 6, do závorky za výběr by se mělo vypsat kolik maximálně stran může uživatel vybrat (resp. poslední možná strana). Příklad:
![pocet stran](https://user-images.githubusercontent.com/21309201/36657962-e868f536-1ace-11e8-88ce-352feaff993d.jpg)

U možnosti "od do" přidat tlačítko "Vybrat strany pro tisk" nebo "Vybrat strany pro PDF". Po kliknutí se zobrazí okno se záhlavím a thumbnaily celého dokumentu, které bude možné označit/odznačit. V záhlaví by měly být volby "vybrat vše", "vybrat maximální počet stran" a "zrušit výběr". Pro výběr by měla fungovat taky klávesa Shift.
Označení jednotlivých thumbnailů by mělo respektovat předchozí výběr stran (od do). Takže pokud vyberu v nastavení "od do" třeba 20 stran, a pak si chci vybrat jednotlivé strany, thumbnaily těch stran, které jsem vybrala v předchozím kroku by měly být taky označené.

Někde v liště záhlaví (s výše uvedenými funkcemi) thumbnailů by mělo být vidět, kolik stran je označeno + info o tom, kolik jich může být vytištěno.
Pokud je označeno více stran než je limit a uživatel zkusí potvrdit tisk nebo vygenerování PDF, objeví se upozornění, že bylo vybráno více stran než je povolený limit a že se vytiskne/vygeneruje PDF prvních např. 50 stran z výběru.

![tiskpdf](https://user-images.githubusercontent.com/21309201/36658719-2440455c-1ad2-11e8-8444-f37ed146534b.jpg)

**Comment by filak** [comment]
OK. Akorát ten údaj "Maximání počet stran: 150" je nějaký zavádějící.

**Comment by krizovj** [comment]
Těch 150 stran je nastaveno v tom testovacím klientovi a já jsem to zapomněla z toho obrázku vymazat. Měl by tam být limit podle toho, jak to bude nastavené v tom konkrétním Krameriovi.

**Comment by pavelkocourek** [comment]
Z.Vozar - návrh zpracování v rámci fronty a odeslání informace na zadaný email. Případně možnost delegování na samostatný server.

**Comment by jahhoo** [comment]
Proč je maxPageCount definováno ve zdrojovém kódu..? Mělo by to jít nastavit v globals.js

**Comment by honza-rychtar** [comment]
https://github.com/ceskaexpedice/kramerius-web-client/issues/12#issuecomment-480787080
