### ISSUE TITLE
Od verze 2.3.3. chybí 'Pokročilé hledání'

### ISSUE THREAD

**Issue by eskrdlant** [ceskaexpedice/kramerius-web-client#501]
Ve verzi 2.3.3 a 2.3.4 se mi přestal pod horní lištou zobrazovat odkaz na 'Pokročilé hledání'

**Comment by zabak** [comment]
@honza-rychtar ty jsi to v kódu natvrdo vypnul?

**Comment by eskrdlant** [comment]
Pěkný den, je chyba potvrzena? bude v další verzi opravena? 
děkujeme

**Comment by honza-rychtar** [comment]
Pokročilé hledání jsem obnovil a je dostupné ve verzi **2.3.5**
Ale je to dočasné řešení, pokročilé hledání bude upraveno, aby se v něm daly kombinovat libovolné výrazy jako je to např. na knihovny.cz
<img width="889" alt="Snímek obrazovky 2022-05-10 v 16 20 52" src="https://user-images.githubusercontent.com/1178142/167651243-638084f6-91a9-4d9f-a305-4e8dc0f8da41.png">

**Comment by zabak** [comment]
díky, zde zavírám a těším se na dodělání #193 a #259.
