### ISSUE TITLE
Možnosť - v advanced search nefunguje

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius-web-client#502]
Možnosť - v advanced search, napr. Mácha -Máj, nefunguje.

Róbert Randiak MZK

**Comment by r2it-git** [comment]
Keď som to skúšal, tak som sa držal toho čo je napísané na [wiki](https://github.com/ceskaexpedice/kramerius-web-client/wiki/Pokro%C4%8Dil%C3%A9-dotazov%C3%A1n%C3%AD). Tak stačí asi updatovať vo wiki, že takáto možnosť nie je.

**Comment by zabak** [comment]
@honza-rychtar byl by problém tam to - doplnit?

**Comment by honza-rychtar** [comment]
@zabak přepsal jsem to sem.
https://github.com/ceskaexpedice/kramerius-web-client/wiki/Pokro%C4%8Dil%C3%A9-dotazov%C3%A1n%C3%AD

Potom to nahradíme skutečným pokročilým vyhledáváním - tohle jsou jen zástupné znaky a operátory, které je možné použít v **jednom textovém** vyhledávacím poli.

**Comment by zabak** [comment]
Tohle issue je teď vyřešené, v advanced search funguje "-". Jenže v normálním hledání teď nefunguje a v popisu na wiki tahle informace též není.
