### ISSUE TITLE
Zobrazení georeferencovaných map

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#503]
S využitím dat z georeferenceru ( https://staremapy.cz/data/uuid/ ) umožnit zobrazení georeferencované mapy na mapovém podkladu mapy světa.

**Comment by honza-rychtar** [comment]
Přidáno ve verzi 2.4.8

Týká se MZK

<img width="1792" alt="Snímek obrazovky 2023-05-26 v 9 14 47" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/87460cce-9a96-48c3-9db5-ea30d957ee3b">


<img width="1792" alt="Snímek obrazovky 2023-05-26 v 9 15 47" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/4c73f783-0cb2-418f-a49c-24b5a1f594f7">

V konfiguraci je potřeba zapnout:
```
krameriusList.georef: true,
```

K testu:
http://dk.kramerius.org/mzkk7/view/uuid:f50dab1b-cfba-4615-bf04-ae1d5596d5e0?page=uuid:7c2d85b1-f339-4fa4-9252-9a841b1b9606
