### ISSUE TITLE
Načtení mapového hledání nepřebírá souřadnice z parametrů

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#504]
Pokud se přepnu do mapového hledání a přesunu mapu třeba na Itálii, tak se mi patřičně změní parametry v url
https://www.digitalniknihovna.cz/mzk/search?accessibility=public&doctypes=graphic&north=44.57565770645229&south=37.1787654925934&west=8.84807004069937&east=21.724046603199373
Pokud si ale otevřu tento link, tak se otevře mapa nad Českem a i parametry se přepíšou.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.4.7**

**Comment by zabak** [comment]
funguje
