### ISSUE TITLE
Zobrazení více než jedné <relatedItem>

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#506]
Narazil jsem na případ, kdy je článek recenzí na 2 jiná díla: https://kramerius.lib.cas.cz/uuid/uuid:d099c425-55b9-478f-9f9a-c8a77b9f3517

v modsu jsou správně zapsána obě recenzovaná díla, každé do svého elementu `<relatedItem>`, klient ale v pravém panelu zobrazuje pouze informaci o jednom z nich:
```xml
<mods:relatedItem>
      <mods:name type="personal">
        <mods:namePart type="family">Charypar</mods:namePart>
        <mods:namePart type="given">Michal</mods:namePart>
      </mods:name>
      <mods:originInfo>
        <mods:publisher>Praha : Ústav pro českou literaturu AV ČR, 2018</mods:publisher>
      </mods:originInfo>
      <mods:titleInfo>
        <mods:title>Prameny Máchova Máje : fakta a hypotézy</mods:title>
      </mods:titleInfo>
</mods:relatedItem>
<mods:relatedItem>
      <mods:name type="personal">
        <mods:namePart type="family">Mácha</mods:namePart>
        <mods:namePart type="given">Karel Hynek</mods:namePart>
      </mods:name>
      <mods:originInfo>
        <mods:publisher>Praha : Ústav pro českou literaturu AV ČR, [2019]</mods:publisher>
      </mods:originInfo>
      <mods:titleInfo>
        <mods:title>Máj</mods:title>
      </mods:titleInfo>
</mods:relatedItem>
```

![image](https://user-images.githubusercontent.com/57805328/161733417-ab537fb3-61c0-43de-9892-149f0697c977.png)

Bylo by, prosím, možné zobrazovat v podobných případech všechna recenzovaná díla?

**Comment by honza-rychtar** [comment]
Doplněno ve verzi **2.3.5**
http://dk.kramerius.org/knav/view/uuid:c5312c0c-62e9-486d-b6b8-d41f1864fb0e?article=uuid:d099c425-55b9-478f-9f9a-c8a77b9f3517
**
<img width="286" alt="Snímek obrazovky 2022-05-10 v 16 14 44" src="https://user-images.githubusercontent.com/1178142/167649877-162cc9e9-b3c9-4c3b-aae2-e946ae73f51c.png">
**
