### ISSUE TITLE
Cookie lišta způsobí vyskočení z webview

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#507]
Při použití mobilní aplikace způsobí cookie lišta vyskočení z aplikace na web.

**Comment by honza-rychtar** [comment]
@zabak Už asi vím, co se děje. V mobilní aplikaci cookie lištu nezapínej. Tam jsou jiná pravidla.

**Comment by zabak** [comment]
OK, vypneme
