### ISSUE TITLE
Export citace

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#508]
Ze zpětné vazby od čtenáře ... :)

_

> Dobrý den,
> 
> nejdříve mi dovolte poznamenat, že digitální knihovna je skvělá a moc děkuji, že ji poskytujete a staráte se o její chod.
> 
> Měl bych jen drobnou připomínku, návrh na zlepšení, a totiž přidat funkci exportu citace ve formátu RIS, či jiném formátu pro import do citačních managerů jako je např. Zotero.
> 
> S pozdravem

_

Připadá mi to celkem podnětné, proto přidávám sem.

**Comment by zabak** [comment]
Navrhuji jako variantu v konfiguraci přidat možnost volání citační služby citace.com, která by toto měla mít hotové. Prosím o diskusi, pro a proti takového řešení.

**Comment by annie-cz** [comment]
Jako že by tam zůstala ta stará služba a k tomu by se přidala jen možnost volání citace.com?

**Comment by zabak** [comment]
Ano. Ne každá knihovna si platí Citace Pro, takže stávající citace by byly default a kdo má tu možnost, nastavil by si v konfiguraci citece.com.

**Comment by vanniewelt** [comment]
Tohle bych taky potřeboval!

@zabak @honza-rychtar  Není mi jasné, jakou roli by v tom hrála služba třetí strany jako citace.com. Pokud tomu správně rozumím, jde jen o to vyexportovat data o publikaci do nějakého standardizovaného formátu, které citační manažery umí importovat (RIS, BibTeX a další). Jediný problém je tedy zakódování dat do jiného formátu, nikoliv "vykreslování" citace podle některé konkrétní citační normy – o to se stará až citační manažer, který si uživatel vybere.

V tomto případě mi dává smysl, aby to bylo součástí jádra, jako nějaký endpoint REST API pro export publikace např. v RISu (nevím přesně, jak je aplikace strukturovaná, jen házím nápady). Otázka je, jaké formáty podporovat. RIS a BibTeX mi přijdou nejběžněji používané.

Např. na [stránkách sociologického časopisu](https://sreview.soc.cas.cz/) lze pro každý článek stáhnout jako `.ris` nebo `.bib`.

**Comment by honza-rychtar** [comment]
@vanniewelt ne každý používá citační manažery, Kramerius musí být schopný vygenerovat uživateli citaci v plain textu v nějaké normě a on si to jen zkopíruje do schránky.
Teď umíme jen normu ČSN ISO 690. Další normy buď uděláme rozšířením citační služby Krameria, nebo použitím služby třetí strany.
Podobně je to pak u formátů. Tady by to možná i bylo jednodušší udělat rovnou na straně té citační služby.

Citační služba je teď vyjmuta z Krameria právě přes REST API ji používají až klienti Krameria. Všichni tedy používají stejnou poslední verzi bez ohledu na to, jakou mají verzi Krameria nebo klienta.
Nejdůležitější je tady vlastně vytěžení dat potřebných pro citaci.
- identifikace zdrojového Krameria (base url)
- identifikace citovaného objektu (uuid)
- určení potřebných souvisejících objektů: článek, výtisk, ročník, periodikum, ... (solr)
- popisná metadata všech relevantních objektů (mods)

Z tohoto se pak dá vygenerovat buď přímo citace (text, html) v určité normě nebo soubor v určitém formátu (.ris, .bib, ..)
I pokud použijeme službu třetí strany, tak musíme provést to vytěžení my a jí potom odeslat už strukturovaná data, protože data v Krameriovi jsou hodně specifická.

Z mého pohledu je použití služby třetí strany výhodné v tom, že umožní zobrazení v různých normách, aniž bychom to museli řešit.
Na druhou stranu, jakmile máme ta data pro konkrétní objekt v konkrétním Krameriovi vytěžena, pak už je to vlastně jen o jejich seskládání a jestli je to iso690, harvard, nebo ris jde vlastně dělat přímo v té citační službě pro Krameria.

**Comment by vanniewelt** [comment]
@honza-rychtar Vycházel jsem z toho, že původní požadavek v tomhle vláknu byl "export citace do citačního manažeru", nikoliv "vygenerování citace v některé citační normě X", což mi přijde jako jiný úkol, který je do jisté míry nezávislý na tomto.

Ale rozumím tomu, že pro obojí je potřeba nějaká služba (ať už vlastní nebo cizí, knihovna nebo API), která strukturovaná data vydolovaná z Krameria buď převede do jiného formátu, nebo vygeneruje citaci.

Možná by se dalo inspirovat u [zotero/bib](https://github.com/zotero/bib). Na převádění mezi formáty to využívá [translation server](https://github.com/zotero/translation-server) a na generování knihovnu [citeproc.js](https://github.com/Juris-M/citeproc-js)

**Comment by honza-rychtar** [comment]
@zabak na knihovny.cz máte CitacePRO a jen generujete text podle vybrané normy. Stažení ve vybraném formátu tam není.
Pokud bychom měli řešit jednu externí službu pro generování citace v zadané normě a druhou externí službu pro konverzi do zadaného formátu, tak už mi přijde skoro jednodušší to začlenit do té citační služby Krameria - místo převádění dat do formátu pro ty služby se převedou rovnou do těch požadovaných formátů. A jestli to bude znamenat export do 2 jasně specifikovaných formátů a možnost generování v dalších 3 normách, tak to zase takový problém nebude.

Pokud by ty externí služby byly dostupné pro všechny, pak by to bylo jednodušší řešení, ale pokud je to ještě závisle na licenci, tak klient bude dělat jen kopu režie, kde nakonec někdo bude mít vše a někdo nic.
