### ISSUE TITLE
Volání citační služby za kódem jazyka je ještě znak }

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#509]
Např. https://citace.kramerius.cloud/v1/kramerius?url=https://kramerius.mzk.cz&uuid=uuid:d8985830-379e-11e3-bd38-5ef3fc9ae867&format=html&lang=en%7D&k7=false

Předpokládám, že tam ta závorka je omylem.

**Comment by honza-rychtar** [comment]
Ano, opravím.
