### ISSUE TITLE
Našeptávač - filtry

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#51]
Našeptávač by měl reflektovat aktivní filtry. Pokud tedy například zvolím filtr "veřejné" a "knihy", tak by měl našeptávač radit podle toho a ne všechno.

**Comment by pavelkocourek** [comment]
Prodiskutujme na schůzce, zdali nebude našeptávání pro uživatele matoucí. Nemáme jednoznačný názor.
Může být na první pohled nejasná nekonzistence Home page a Result page.

**Comment by zabak** [comment]
Problém vidím v tom, že jedním z filtrů je i předcházející vyhledávací dotaz. I když se "přepíše" novým dotazem, tak by to mohlo být zavádějící. Proběhla o tomhle nakonec nějaká diskuse?

**Comment by honza-rychtar** [comment]
Našeptávač filtruje výsledky podle aktuálně nastavených filtrů a reflektuje placeholder ve vyhledávacím poli #171.

Mezi filtry se nepočítá hledaný řetězec, který se neuplatňuje při dalším hledání, protože je novým řetězcem nahrazen.
