### ISSUE TITLE
Externí reference na fonty

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#511]
Zdravím,

řešíme problém s externí referencí na fonty z klienta:

![font-00](https://user-images.githubusercontent.com/8750622/165906877-313344b3-9f4f-4d85-a02f-ae53aa734869.png)

V normálním případě, kdy má uživatel přístup na internet bez omezení, tak všechno funguje bez problému. Komplikace nastávají v situaci, kdy je uživatel u počítače/kiosku, kde je přístup na internet omezen, resp. úplně zakázaný - celkem běžná situace v počítačových studovnách.

Šlo by toto ošetřit např. prostřednictvím nějakého lokálního bundlu sady fontů u klienta?

Díky, MD

**Comment by luckajirku** [comment]
Jen doplním - na stanicích s omezeným přístupem na internet se nám teď nezobrazují ikony (viz obr.) - resp. nejen nám, chová se to tak ve všech DK, které mají mají nového klienta (a mají správně omezený přístup). Pokud bychom to chtěli obejít a povolit, tak s tím zároveň umožníme uživateli přístup na Google Disk - čili by si mohl udělat el. kopii (to chceme?). 
Můžeš se na to prosím podívat @honza-rychtar ? Díky.
![IMG_20220503_092730837](https://user-images.githubusercontent.com/6359479/166419635-5aef16c5-1316-4ca2-83d0-f14c2059ba87.jpg)

**Comment by honza-rychtar** [comment]
Dobře, stáhnul jsem fonty a balík s ikonami lokálně a bude se distribuovat společně s klientem a odkazy tedy nepovedou mimo doménu, kde je hostovaný klient.

Jinak přístupy na internet se dají omezovat/povolovat cíleně. Konkrétně pro povolení Google fontů by se povolil přístup na doménu fonts.gstatic.com. Podobně pokud byste chtěli zachovat funkcionalitu měření návštěvnosti a chování uživatelů přes Google Analytics i na terminálech, tak by se musela povolit doména www.google-analytics.com
Určitě to neznamená, že by se zároveň musel uživatelům povolit přístup na online úložiště.

**Comment by mduda100871** [comment]
To ano, ale dovedu si představit, že ne každý firewall na perimetru privátní sítě umožní například dávat do filtrovacích pravidel DNS jména, automaticky hlídat, zda-li IP se pod jménem nezměnila atd.

Sice z toho nadšený také nejsem, ale "paranoidní" nastavení/omezení přístupu na internet v těch knihovních studovnách je prostě častý případ.

Díky, MD

**Comment by honza-rychtar** [comment]
Hotovo, dostupné od verze **2.3.5**

**Comment by mduda100871** [comment]
Fajn, vyzkouším
