### ISSUE TITLE
Zobrazení nedostupných akcí

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#515]
Pokud není akce (pdf, txt, citace, tisk, ...) dostupná, tak ji neschovávat, ale jen udělat neaktivní a zašednout.

**Comment by honza-rychtar** [comment]
<img width="465" alt="Snímek obrazovky 2022-07-28 v 16 26 15" src="https://user-images.githubusercontent.com/1178142/181545980-72cb0275-fc0c-4847-b966-2e84cbaf9567.png">


Nedostupné akce jen zešednou a nejedou použít. Ale vizuálně zůstávají na místě a jen se aktivují v případě dostupnosti.
Výjimkou je nastavení akce jako `never`, kdy se opravdu ikona akce vůbec nevykreslí.

**Comment by zabak** [comment]
ověřeno, zavírám
