### ISSUE TITLE
Funkce výřez stránky

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#52]
Přidat funkci výřez stránky jako je to v Digitální knihovně
![image](https://user-images.githubusercontent.com/21309201/36671575-5a1f4892-1afc-11e8-9f90-5822cdebdf43.png)

**Comment by honza-rychtar** [comment]
Tohle funguje jen s Image serverem s podporou IIIF.

**Comment by zabak** [comment]
Ano. Tak zatím konfigurovatelně?

**Comment by zabak** [comment]
A prosím pokud možno tak, aby při dvoustránkovém zobrazení ten rámeček respektoval rozhraní mezi stránkami - v digitální knihovně teď můžu rámečkem sice přejet a vybrat výřez dvojstránky, ale stejně se mi pak (zcela logicky) ukáže jen výřez levé stránky.

**Comment by honza-rychtar** [comment]
Hotovo. Je to stejně jako v Digitální knihovně.

Výřez obrázku se aktivuje tlačítkem v ovládacích prvcích:
<img width="563" alt="screenshot 2019-02-05 18 03 04" src="https://user-images.githubusercontent.com/1178142/52290675-df3e7880-2970-11e9-8050-de2bfe501c79.png">

Potom se vybere oblast a v novém tabu se otevře výřez obrázku.

**Comment by mduda100871** [comment]
Zdravím,
prosím o bližší upřesnění.
1) V novém balíku klienta přibyla properta `iiif=true|false`. Ta má zajistit podporu výřezů?
2) Používáme balík imageserveru od MZK, takže tam podpora IIIF předpokládám je?
3) Nainstaloval jsem poslední release klienta, nastavil `iiif=true`, ale ikona pro výřez se stále nezobrazuje...
Díky, MD

**Comment by mduda100871** [comment]
Zdravím,
drobný posun - podařilo se mi "přesvědčit" klienta aby zobrazil ikonu výřezu, nicméně po výběru oblasti se objeví prázdné černé okno a v konzoli prohlížeče vypadne chybová hláška:

![konzole](https://user-images.githubusercontent.com/8750622/56725219-be561a00-674c-11e9-849b-f71647cbf73c.png)

V logu webserveru, kde imageserver beží jako fcgi modul je zalogován request:

![log](https://user-images.githubusercontent.com/8750622/56725367-09702d00-674d-11e9-8b42-c0f48a7b799d.png)

který ale odkazuje na něco co neexistuje. Předpokládám, že jde o nějaké parametry pro imageserver...

MD

**Comment by MartinRumanek** [comment]
@mduda100871 Mohl bych prosím vidět co je v logu například po tomto requestu?

[http:://kramerius.lib.cas.cz/search/iiif/uuid:8ebf04ea-b732-4b77-946c-d4ddadc16d28/info.json](url)

+ ještě prosím jak vypadá snippet relst-ext z Fedory.

**Comment by zabak** [comment]
@honza-rychtar any thoughts? Na čem to z tvého pohledu selže, třeba v NK?

**Comment by luckajirku** [comment]
Bylo by prosím možné tomu dát vyšší prioritu? Je to funkce, která uživatelům (hlavně při práci s novinami) citelně chybí.

**Comment by zafan** [comment]
Nejdříve by chtělo zjistit, jak máte nakonfigurovaný webový server. V MZK to máme takto: https://github.com/moravianlibrary/osdd-docker-images/blob/master/imageserver/mzk/openresty/nginx.conf
Poté je potřeba se ujistit, že vám běží krameriusiiif: https://github.com/MartinRumanek/krameriusiiif

To je zatím vše, co mě napadá.

**Comment by mduda100871** [comment]
Zdravím,

podařilo se mi to trochu posunout kupředu a zprovoznit. U instancí, kde není použit Docker a místo NGINXe Apache, je potřeba nakonfigurovat následující (příklad v příslušném virtuálu):

```
...
    ScriptAlias "/cgi-bin/" "/usr/lib/cgi-bin/"
    ScriptAlias "/fcgi-bin/" "/usr/lib/cgi-bin/"

    <Directory "/usr/lib/cgi-bin">
        AllowOverride None
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
        <RequireAll>
            <RequireAny>
                Require ip 127.0.0.0/8
                Require host localhost
            </RequireAny>
        </RequireAll>
    </Directory>
        
    <IfModule mod_fcgid.c>
        <IfModule mod_mime.c>
            AddHandler fcgid-script .fcgi
        </IfModule>
        FcgidInitialEnv LOGFILE "/var/log/iipsrv/iipsrv.log"
        FcgidInitialEnv VERBOSITY "2"
        FcgidInitialEnv JPEG_QUALITY "80"
        FcgidInitialEnv MAX_IMAGE_CACHE_SIZE "16"
        FcgidInitialEnv MAX_LAYERS "-1"
        FcgidInitialEnv MAX_CVT "4000"
#       FcgidInitialEnv ALLOW_UPSCALING 0
#       FcgidInitialEnv KAKADU_READMODE 2
#       FcgidInitialEnv INTERPOLATION 1
#       FcgidInitialEnv MEMCACHED_SERVERS=127.0.0.1:11211
#       FcgidInitialEnv MEMCACHED_TIMEOUT=1800
        FcgidIdleTimeout 0
        FcgidMaxProcessesPerClass 4
    </IfModule>
...

    <IfModule mod_rewrite.c>
        RewriteEngine On
        LogLevel alert rewrite:trace1
    
        RewriteCond %{QUERY_STRING} ^Zoomify=([a-zA-Z0-9_\/\.\-]+)\/([a-zA-Z0-9\.\,\:]+)/([a-zA-Z0-9\.\,\:\!]+)/([0-9\.\!]+)/([a-zA-Z0-9]+).jpg$
        RewriteRule ^/cgi-bin/iipsrv.fcgi http://%{HTTP_HOST}/cgi-bin/iipsrv.fcgi?IIIF=%1/%2/%3/%4/native.jpg [L]
        
    </IfModule>

...
```
Klíčová jsou přepisovací pravidla v konfiguraci `mod_rewrite`.

V okamžiku, kdy uživatel provede výřez, přijde na server request z klienta, například:
```
"GET /search/iiif/uuid:d7d7cae6-4eed-11e9-8962-005056a2b051/1865,4099,736,418/full/0/default.jpg HTTP/1.1"
```
Ten je jádrem Krameria přepsán na:
```
"GET /cgi-bin/iipsrv.fcgi?Zoomify=/home/kramerius/image-server-root/2019/03/25/klg001-0000mj/UC_klg001-0000mj_0001.jp2/1602,3139,1531,1103/full/0/default.jpg HTTP/1.1"
```
Ten je dále přepsán pomocí výše uvedených pravidel na:
```
"GET /cgi-bin/iipsrv.fcgi?IIIF=/home/kramerius/image-server-root/2019/03/25/klg001-0000mj/UC_klg001-0000mj_0001.jp2/1602,3139,1531,1103/full/0/native.jpg HTTP/1.1"
```
a výřez to úspěšně vrátí.

Při ladění jsem také zjistil, že verze imageserveru, kterou máme nasazenou, nerozumí nastavení parametru kvality `default.jpg`, ale vyžaduje to přepsat na `native.jpg`. Jinak imageserver vrací status `400`:

![img-400-01](https://user-images.githubusercontent.com/8750622/67214337-df5ba700-f41f-11e9-9eaf-0c5fc06a2667.png)

![img-200-01](https://user-images.githubusercontent.com/8750622/67215146-429a0900-f421-11e9-9144-464f9a55aeb6.png)

Výše uvedená konfigurace vypadá zatím stabilně s imageserverem (balíček od MZK) verze `1.1`.

Starší verze `0.9.9`, kterou mám na testovací instanci, vykazuje značnou nestabilitu - při větším výřezu to "upadne" a vrátí status `500`.

MD

**Comment by pavelkocourek** [comment]
bude převedeno na wiki jako návod

**Comment by vlahoda** [comment]
na wiki Krameria pridana stranka Konfigurace-imageserveru-pro-podporu-IIIF

**Comment by zabak** [comment]
https://github.com/ceskaexpedice/kramerius/wiki/Konfigurace-imageserveru-pro-podporu-IIIF
