### ISSUE TITLE
Přidat dialog s nápovědou k hledání

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#520]
Přidat do vyhledávacího vpravo ikonu íčka, které zobrazí dialog s použitím zástupných znaků a operátorů.
Jako příklady možno uvést tyto
https://github.com/ceskaexpedice/kramerius-web-client/issues/502#issuecomment-1122629315

**Comment by honza-rychtar** [comment]
Přidáno ve verzi 2.3.6
Je to na hlavní obrazovce i v navbaru. Je  češtině a angličtině. V němčině se použije anguličtina.
<img width="1223" alt="Snímek obrazovky 2022-07-28 v 16 28 53" src="https://user-images.githubusercontent.com/1178142/181548490-cfaa246a-d3a4-46be-a125-01b4d3c5fe19.png">

<img width="823" alt="Snímek obrazovky 2022-07-28 v 16 29 19" src="https://user-images.githubusercontent.com/1178142/181548610-be741a07-f3ee-4348-8dbd-099a7432aa96.png">

<img width="792" alt="Snímek obrazovky 2022-07-28 v 16 29 33" src="https://user-images.githubusercontent.com/1178142/181548704-9fd84b2a-6553-48a1-8507-dd024319631b.png">

Test:
http://dk.kramerius.org/

**Comment by zabak** [comment]
díky, ověřeno, zavírám
