### ISSUE TITLE
Pridať tlačítko návratu na rozcestník do dnnt kraméria

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius-web-client#523]
Zdravím,
v podstate by sme cheli aby sa dalo nastaviť url návratu na rozcestník aj pre jednokramériove instancie, ktoré sa nachádzajú mimo rozcestník. Konkrétne v tomto prípade pre dnnt kraméria.
Viem si to predstaviť tak, že pokiaľ sú kraméria súčasťou rozcestníku, nič by sa nemenilo.
Pokiaľ by šlo o jednokramériovu instanciu bez nastavenej url, taktiež by sa nič nemenilo.
Pokiaľ by šlo o jednokramériovú instanciu s nastaveným URL návratu, zobrazila by sa na home page tá kytička návratu na rozcestník, ktorá by presmerovala na zadanú URL.
![kyticka_cropped](https://user-images.githubusercontent.com/65346739/172559845-ffc1de13-8ea5-4437-8eba-324d3a2d0a99.png)

RR MZK

**Comment by annie-cz** [comment]
Po pravdě si myslím, že to budeme používat jenom my kvůli rozcestníku. A zbytek má tu možnost si to tam dát taky, pokud by chtěl nějak s rozcestníkem spolupracovat. Jiné použití mě nenapadá.

**Comment by zabak** [comment]
Přejdeme na K7 a tím tohle issue nebude potřeba, zavírám.
