### ISSUE TITLE
Průhlednost watermarku

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#525]
Pro jeden konkrétní use case bychom potřebovali zprovoznit watermarky. V dokumentaci ale je jen příklad konfigurace, není vysvětleno, co jednotlivé parametry znamenají. Potřebovali bychom, aby watermark nebyl text definované barvy, ale něco průsvitného, co jen ztmaví nebo zesvětlí podklad.

**Comment by honza-rychtar** [comment]
> V dokumentaci ale je jen příklad konfigurace, není vysvětleno, co jednotlivé parametry znamenají.

V dokumentaci je příklad se všemi možnými parametry. Parametry jsou popsané svými názvy, ale přeložím je teda do češtiny a doplním do dokumentace k licencím ... (popíšu to teda nejdřív tady)
```
watermark: {
  defaultText: 'DNNT',
  color: 'rgba(0, 0, 0, 0.3)',
  fontSize: 16,
  rowCount: 3,
  colCount: 5,
  probability: 75
}
```
**defaultText**: Výchozí text, který se použije, pokud není dostupný jmenný identifikátor uživatele.
**color**: Barva textu
**fontSize**: Velikost fontu
**rowCount**: Počet výskytů v řádku
**colCount**: Počet výskytů v sloupci
**probability**: Pravděpodobnost se kterou se watermark zobrazí - aplikuje se na každý zvlášť (v matici rowCount  * colCount). Rozsah 0 - 100, kde 0 = watermark se nezobrazí,  50 = watermark se zobrazí s 50% pravděpodobností, 100 = watermark se zobrazí.

Takže příklad konfigurace výše říká, že watermark se zobrazí černou poloprůhlednou barvou fontem o velikosti 16px. Maximálně se zobrazí 15 watermarků (3*5) v mřížce 3 (řádek) * 5 (sloupec). Každý z těch 15 watermarků se zobrazí se 75% pravděpodobností. Text watermarku bude jméno/id uživatele a pokud chybí, pak bude text DNNT.


> Potřebovali bychom, aby watermark nebyl text definované barvy, ale něco průsvitného, co jen ztmaví nebo zesvětlí podklad.

Co to znamená?

Připomínám, že watermark na klientovi je krajní řešení, které nezaručuje ochranu podkladového obrázku. Ten si pak stejně můžu stáhnout přes IIIF bez watermarků.

**Comment by zabak** [comment]
@honza-rychtar té průhlednosti v zadání barvy jsem si nevšiml a plně to řeší můj požadavek. Jen prosím doplň tu dokumentaci výše na vhodné místo, aby se to nemuselo hledat v issues a zde je to možné zavřít.

**Comment by honza-rychtar** [comment]
@zabak jo, hned jsem to překopíroval do wiki ke konfiguraci licencí https://github.com/ceskaexpedice/kramerius-web-client/wiki/Konfigurace-licenc%C3%AD
