### ISSUE TITLE
Watermark jako obrázek

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#526]
Je možné místo textu zadat coby watermark nějaký obrázek - třeba URL jednobarevné průhledné bitmapy?

**Comment by honza-rychtar** [comment]
Je to možné, ale připomínám, že watermark na klientovi je krajní řešení, které nezaručuje ochranu podkladového obrázku. Ten si pak stejně můžu stáhnout přes IIIF bez watermarků.

**Comment by honza-rychtar** [comment]
@filak Pokud si pamatuju, tak Imageserver neuměl ty watermarky generovat dynamicky - např. jméno uživatele.

To řešení na straně klienta se potom udělalo jakože ve smyslu _"dostatečného vyvinutí úsilí ..."_ - což mělo stačit pro DNNT. Ale proto právě připomínám, že to nezaručuje ochranu, tak aby někoho nenapadlo to použít k účelům, kde už toto _úsilí_ dostatečné nebude.

Pak by se znova měly zvážit další možnosti ochrany, jako se to tenkrát řešilo pro DNNT.

**Comment by zabak** [comment]
Prosím o implementaci na straně klienta, řešení na straně imageserveru by znamenalo úpravy imageserveru a asi i jádra Krameria.

**Comment by honza-rychtar** [comment]
Přidáno ve verzi **2.4.0**

**Comment by zabak** [comment]
funguje, zavírám
