### ISSUE TITLE
K7 + Solr - problém s managed-schema

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#527]
Zdravím,

připravuji testovací instanci K7 a narazil jsem na problém s indexovacím schématem pro jádro `search`. 

Schéma `managed-schema`, resp. celou konfiguraci Solru, jsem převzal z oficiálního instalačního balíčku K7:

https://github.com/ceskaexpedice/kramerius/releases/tag/v7.0

Nainstaloval jsem Solr 8 a založil dle dokumentace příslušná jádra `search` a `processing`. Prostřednictvím admin klienta jsem naimportoval příslušný balíček našich testovacích dat - všechno proběhlo bez problému, včetně indexace.

Problém nastal až v okamžiku, kdy jsem se k naimportovaným datům pokusil přistoupit z uživatelského rozhraní/webklienta.

Webklient není schopen zobrazit žádná data. V konzoli prohlížeče jsem dohledal, že kolabuje dotaz do Solru prostřednictvím API rozhraní jádra K7. V logu Solru jsem dohledal, že dotaz obsahuje pole `created_date`, které se ovšem v indexovacím schématu nevyskytuje.

Ve zdrojovém kódu webklienta, v  `solr.service.ts`, jsem dohledal, že zřejmě došlo ke změnám názvů některých polí v indexovacím schématu:

![src-00](https://user-images.githubusercontent.com/8750622/173528041-118237a9-cbde-48d4-8acd-b3a481852890.png)

Ze zdrojového kódu jsem vydedukoval, že z důvodu kompatibility směrem ke staré K5, dochází v kódu webklienta k větvení a sestavování různých dotazů dle toho, zda-li webklient komunikuje s jádrem K5 nebo K7 - alespoň se tak domnívám.

Nejprve jsem předpokládal, že webklient je schopen sám detekovat automaticky s jakou verzí jádra komunikuje a dle toho sestavit příslušný dotaz do Solru s odpovídajícími názvy polí. Nicméně to se neděje a webklient stále tvrdošíjně posílal dotaz do Solru, konstruovaný pro jádro K5.

Šel jsem tedy hledat do wiki, zda-li neexistuje nějaká properta, jejímž prostřednictvím bych mohl explicitně webklientovi sdělit, že komunikuje s jádrem K7 a tomu přizpůsobit konstrukci dotazu do Solru. Nic jsem nenašel.

Takže jsem se vrátil ke zdrojovým kódům webklienta a analýzou kódu jsem nakonec zjistil, že v `app-settings.ts` existuje, na wiki nezdokumentovaná (alespoň já to nenašel), properta `kramerius.version`:

![src-01](https://user-images.githubusercontent.com/8750622/173530930-41f0e8b6-f48c-4d72-846a-11caf00af92a.png)

Přenastavením konfigurace `globals.js` webklienta:

![cfg-00](https://user-images.githubusercontent.com/8750622/173531941-62b23195-e160-479c-a34e-c58d12b2ced2.png)

jsem nakonec dosáhl toho, že webklient začal konstruovat dotaz do Solru pro jádro K7.

Z výše uvedeného plyne, že properta `version` je poměrně klíčová a zásadní, a měla by být uvedena explicitně na wiki, dle mého názoru, protože detekcí problému jsem strávil neproduktivně několik hodin.

Nicméně ani přenastavením verze jsem nedospěl k funkčnímu stavu. Dotaz sice přestal kolabovat na neexistenci pole `created_date`, ale začal kolabovat pro změnu na neexistenci pole `collection`:

![error-00](https://user-images.githubusercontent.com/8750622/173533515-9585a2b9-d2b7-49d6-8d10-5beb07612292.png)

a log Solru:

![error-01](https://user-images.githubusercontent.com/8750622/173533575-12f0c726-adfc-484b-a009-32c95d3a794b.png)

Napadlo mě, že možná poslední oficiální build webklienta obsahuje směrem k jádru K7 nějaký bug, takže jsem zkusil stáhnout z gitu poslední zdrojové kódy a přeložit vlastní balíček. Nicméně po instalaci chyba zůstala.

V této fázi tedy nejsem schopen dál pokračovat a nejsem schopen zprovoznit K7 do použitelného stavu.

Ještě doplním, že jsem si rovněž musel vyžádat neoficiální build samotného jádra K7, protože poslední oficiální build z konce roku 2021 je už nefunkční.

Chtěl bych tímto poprosit vývojáře, aby co nejdříve, jak jen to bude možné, aktualizovali na gitu všechny oficiální instalační balíčky (+ doplnění wiki), aby "standardní" admin byl schopen nainstalovat funkční K7 bez potřeby průzkumu bojem, co jsem teď absolvoval já.

Čas opravdu již hodně tlačí a potřebujeme K7 už začít zavádět do provozu, aktuálně alespoň testovacího a po prázdninách už do produkčního!

Díky, MD

**Comment by vlahoda** [comment]
@rzeh4n @pavel-stastny Muzete prosim zkontrolovat schemata SOLR v modulu installation, odstranit pozustatky po K5 a pripadne doplnit, co chybi pro K7. Myslim ze treba solr 6 uz podporovat nebude potreba.
Otaguju a pripravim pak novy "oficialni" build.

**Comment by rzeh4n** [comment]
Ten poslední problém se solr polem "collection" bude ve špatně konstruovaném dotazu, který je ale určený pro K7, což jde poznat z endpointu a z dalších polí, co v schématu K5 neexistovaly (např. model, own_model_path). Naopak pole "collection" je z K5, v K7 takové pole neexistuje.

Takže za jádro problém nevidím, je to v tom dotazu, co konstruuje klient.
@honza-rychtar Ta verze by na [wiki](https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta#globalsjs) být měla.

**Comment by honza-rychtar** [comment]
@mduda100871 Dokumentaci pro K7 doplním. Specifické věci pro K7 se hodně měnily a nedával jsem je průběžně do dokumentace.
Teď už by to rozlišení mělo být finální přes `krameriusList.version: 7`

Pokud jde o tu chybu s collection, tak prosím odeber v konfiguraci z pole `krameriusList.filters` hodnotu **collections**.
V K7 už není sbírka filtr ale typ dokumentu. Klient nedělá kontrolu na validní filtry podle verze a do dotazu takto přidal i facetu sbírek, které je dostupná v K5, ale ne v K7.

Dostupné filtry v K5:
['accessibility', 'licences', 'doctypes', 'authors', 'keywords', 'geonames', 'collections', 'locations', 'languages'],

Dostupné filtry v K7:
['accessibility', 'licences', 'doctypes', 'authors', 'keywords', 'geonames', 'publishers', 'places', 'locations', 'genres', 'languages'],

Tohle taky doplním do dokumentace, ale už nám to strašně bobtná. Původně měla konfigurace 5 položek, teď jich je přes 40 a komu ještě komplexní konfigurace licencí.
Mohli bychom se domluvit na nějakém lepší způsobu popisu.

**Comment by honza-rychtar** [comment]
> A hlavně jasně oddělit na wiki konfiguraci specifickou pro K5 a pro K7 - teď je to hrozně matoucí, a to platí i pro jádro.

V případě klienta to není úplně možné. V jednom klientovi můžu míchat K5 i K7 Kramerie. To bude i dlouhou dobu příklad klienta www.digitalniknihovna.cz, kde budou knihovny postupně přecházet na K7, ale klient pořád bude zobrazovat i zbylé K5.
Naopak klient ten rozdíl v jádře co nejvíc skrývá a navenek to vypadá skoro stejně.
V rámci konfigurace konkrétního Krameria v krameriusList bychom pak už mohli jasně říct, co je jen v K5 a co jen v K7.
A udělat i samostatné příklady pro K5 a K7.

**Comment by mduda100871** [comment]
Já vím, v tom případě to může mít podobu tří základních konfigurací, čistě pro K5, čistě pro K7 a pak hybrid.

Na druhou stranu, to hybridní nasazení je celkem exotická věc a přijde mi, že to asi málokterá z knihoven bude takto provozovat.

MD

**Comment by zabak** [comment]
@honza-rychtar @mduda100871 v nějaké verzi web klienta odstraníme podporu K5. Dá se tohle issue uzavřít?

**Comment by honza-rychtar** [comment]
Tohle se týká dokumentace, ne funkčnosti.
Dokumentace se bude muset upravovat tak či tak, ale asi není dobré požadavky na úpravy držet v jednotlivých issues.
Takže tohle bych zavřel.
