### ISSUE TITLE
Generování PDF - neveřejné dokumenty

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#53]
U neveřejných dokumentů by mělo být zakázáno generovat PDF, ptž i když jsou dostupné na místě samém, tak by nemělo být možné je ukládat, ale pouze tisknout.

**Comment by honza-rychtar** [comment]
U neverejnych dokumentu se po kliku na generovani pdf zobrazi dialog s vysvetlenim.

**Comment by krizovj** [comment]
U neveřejných dokumentů by nemělo být možné generovat PDF, ale ne, pokud je nastaven IP filtr pro přístup. Například pokud je nastaven přístup pro určité IP adresy. Když vidí plný text, mělo by být možné generovat PDF.

**Comment by krizovj** [comment]
Stejné je to s OCR. Pokud má uživatel přístup k neveřejnému dokumentu na základě IP adresy, měl by OCR vidět, i přesto, že je dokument neveřejný.

**Comment by SykoraLukas** [comment]
Jak to vypadá s řešením tohoto issue? IP filtr používají i v knihovně ČRo a byla by potřeba, aby povolené IP adresy měli možnost generování PDF a OCR.

**Comment by zabak** [comment]
@SykoraLukas My to řešíme tak, že na studovně je přístup ne přímo do krameria ale na remote desktop běžící na serveru a odtud teprve do Krameria. Tisk je pak možný normálně přes printserver rovnou z toho virtuálu, ale je z něj zamezeno přístupu jinam do internetu a nedají se přenášet soubory mezi virtuálem a fyzickým počítačem u kterého uživatel sedí. Obdobné řešení je i pro DNNTT, jen bez možnosti tisku.

**Comment by honza-rychtar** [comment]
U akcí Příprava k tisku, Stáhnout PDF, JPEG stránky, Textový přepis stránky, Vybrat text a Výřez obrázky je možné v konfiguraci zadat novou volbu available (navíc k stávajícím always, public, never).
V případě nastavení akce jako **available** se akce zobrazí pokud je aktuální obrázek uživateli zpřístupněn (z jakéhokiliv důvodu).
Např.  v této instalaci
http://dk.kramerius.org
je v konfiguraci 
```
actions: {
  pdf: 'available',
  print: 'public',
  jpeg: 'public',
  text: 'available',
  citation: 'always',
  metadata: 'always',
  share: 'always',
  selection: 'public',
  crop: 'public'
},
```
Takže akce Stáhnout PDF a Textový přepis stránky se zobrazí pokud je aktuální stránka zpřístupněná, ale Příprava k tisku a JPEG stránky se zobrazí jen u veřejných dokumentů.
Např. tady http://dk.kramerius.org/mzk/view/uuid:fa663370-fa6c-11e2-9923-005056827e52?page=uuid:b8aeb1a0-fc53-4478-bf7d-33610f6873f7 je při listování stránkami vidět, že se ty dvě available akce zobrazují u zveřejněných stran - tady se zveřejňují některé stránky podle typu strany (obálka, titulka, obsah), ale u zbylých jsou akce skryté. 
U zveřejněné strany díky IP filtru se to chová stejně.

Jeden problém tady ale je. Právě to zpřístupnění některých typů strany vede k tomu, že se akce Stáhnout PDF zobrazí, ale PDF nepůjde vygenerovat, pokud si uživatel vybere i strany, které zpřístupněny nejsou.
Tohle klient nemůže vědět dopředu - ví že aktuální strana je zpřístupněna, ale neví to o zbylých stranách.
Tohle je v pořádku pro zobrazování JPEG a OCR strany, ale u toho generování PDF aktuální stránka vlastně neurčuje dostupnost celého dokumentu, což je u generování PDF umožněno.

**Comment by SykoraLukas** [comment]
Váže se to na novou verzi klienta? Nebo je možné to zprovoznit na současné?

**Comment by honza-rychtar** [comment]
@SykoraLukas Je to až od verze 2.3.3

**Comment by SykoraLukas** [comment]
Super, díky

**Comment by zabak** [comment]
@honza-rychtar popisuješ tam problém "available" versus zpřístupnění obsahů a obálek. Pomohlo by, kdyby byly obsahy a obálky zpřístupněny na základě labelu u kterého by byl zákaz tisku?

**Comment by honza-rychtar** [comment]
@zabak akce tisk a pdf nikdy nebude fungovat úplně dobře pro volbu public a available, protože tyto volby se vážou k vybrané straně, kdežto tisk/pdf vyvolá dialog s volným výběrem stran.

Navrhuju používat volbu always - tlačítko bude vždy dostupné - a detekci dostupných stran delegovat až na ten dialog, který bude (#516) nabízet výběr jen dostupných stran. Pokud nebude dostupná žádná, tak se vypíše nějaká hláška.
Pokud bude dostupná jen obálka a obsah, pak se povolí výběr jen těchto stran a nebude záležet na tom, kterou stranu jsem měl zrovna v prohlížečce vybranou.

**Comment by zabak** [comment]
OK, nikdo nemá připomínky, takže zavírám. V případě potřeby otevřeme nové issue.
