### ISSUE TITLE
K7 dostupnost obrázků po přihlášení

### ISSUE THREAD

**Issue by stanislavteplik** [ceskaexpedice/kramerius-web-client#531]
Dobrý den, mám zde následující situaci:
- poslední build jádra Krameria
- admin klient 1.2.0
- uživatelský klient 2.3.5 / `iiif: true`
- externí imageserver s podporou IIIF
- read pouze, pokud jste k4_admins nebo kramerius_admin
- účet ve skupině k4_admin a kramerius_admin

Když se přihlásím do klienta a jdu na náhled nějakého obrázku (importovaného z PSP balíku), tak zpátky dostanu prázdný náhled a v konzoli 403 na `https://kramerius.svkpk.cz/search/iiif/uuid:23b7b4f8-7f6c-11ec-8e49-001b63bd97ba/full/147,221/0/default.jpg` , že nemám práva na prohlížení. 
Při pokusu zobrazit obrázek, který byl importován přes foxml, dostanu také 403 na `https://kramerius.svkpk.cz/search/api/client/v7.0/items/uuid:f0519cb0-d40c-11de-bc50-000d606f5dc6/image` , ale místo obrázku je zde aspoň text _Chyba! Obrázek se nepodařilo načíst._
Zvláštní je, že i přes to mám přístup k administrátorským funkcím a mohu například editovat viditelnost dané stránky. Při dotazu na API s bearer tokenem se obrázek ukáže.

Při testování funkčnosti jsem přidal pohyblivou zeď pro common_users, pravidlo funguje a stránky se zobrazují.

Dále jsem vypnul IIIF v klientovi `iiif: false`. V ten okamžik se mi začaly ukazovat obrázky importované z PSP balíku, avšak v konzoli se při prvotním načtení stránky ukáže také 403 při dotazování na: `https://kramerius.svkpk.cz/search/api/client/v7.0/items/uuid:23b766d7-7f6c-11ec-8e49-001b63bd97ba/image/zoomify/TileGroup0/0-0-0.jpg` . Obrázky importované z foxml, stále hlásí 403 a _Chyba! Obrázek se nepodařilo načíst._

Log imageserveru pouze informuje o splněném požadavku na obrázek.
V logu Tomcatu se zobrazuje: 
`26-Jul-2022 08:18:11.239 SEVERE [ajp-nio-127.0.0.1-8009-exec-6] cz.incad.kramerius.utils.solr.SolrUpdateUtils.sendToDest`
a
`.DNNTStatisticsAccessLogImpl.log` záznam ,kde vidím `..."solrDate":"1970","preffered_user_name":"admin_teplik","remoteAddr":"172.16.4.6","username":"admin_teplik","dnnt":false,"policy":"public"}`

Nějaký nápad proč nemám z klienta autorizované requesty na obrázky?

Děkuji.

**Comment by stanislavteplik** [comment]
Update: jdou vidět 2 requesty na adresu:
`https://kramerius.svkpk.cz/search/api/client/v7.0/items/uuid:bd819c10-502a-11de-90a6-000d606f5dc6/image` 
První je typu xhr a obsahuje v hlavičce Authorization attribut, ten má response 200.
Druhý je typu json a bez Auth atributu, ten dostane 403.

Neměl by mít i ten druhý auth v hlavičce? Zatím hledám v apachy, jestli se někde neztrácí...

**Comment by honza-rychtar** [comment]
Dobrý den, zítra budu dělat nový release klienta. Dělaly se tam změny, které by měly Váš problém vyřešit.

**Comment by honza-rychtar** [comment]
@stanislavteplik Můžete to prosím zkusit s novou verzi klienta https://github.com/ceskaexpedice/kramerius-web-client/releases/tag/v2.3.6

**Comment by stanislavteplik** [comment]
Hlásím, že pro dokumenty importované z psp balíku je chyba opravena. Stále přetrvává pro staré foxml importy z djvu/jp, které se dotazují na /image.

**Comment by honza-rychtar** [comment]
Prohlížečka v klientovi v případě Full image streamu (plné JPEGy a ne Zoomify nebo IIIF) nepředávala Keycloak token při requestu na obrázek.

Tohle je ve verzi **2.3.8** opraveno.

**Comment by zabak** [comment]
@stanislavteplik prosím o potvrzení že je to vyřešeno

**Comment by stanislavteplik** [comment]
Potvrzuji, že náhledy image streamů od verze 2.3.8 fungují
