### ISSUE TITLE
Drobná oprava dokumentace

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#534]
Zdravím,

bylo by asi dobré opravit v dokumentaci název property pro sekundární GA ID - viz screenshot:

![ga-00](https://user-images.githubusercontent.com/8750622/182342844-4ccf510f-3fb0-4b56-bb89-3e19b572b568.png)

Správně by se měla jmenovat `APP_GLOBAL.gaCookieless`, alespoň dle zdrojového kódu:

![ga-01](https://user-images.githubusercontent.com/8750622/182343603-ee8115d4-ffe6-4220-a7d5-d45c229fca4c.png)

Teď je to matoucí.

Díky, MD

**Comment by honza-rychtar** [comment]
Díky, opraveno.
