### ISSUE TITLE
Respektování licencí z podřazených a nadřazených objektů

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#538]
K7 má v indexu 3 pole k licenci (má licenci, je rodičem něčeho s licencí, je předkem něčeho s licencí)
K5 má v indexu 2 pole k licenci (má licenci, je rodičem něčeho s licencí)

Respektovat všechna tato pole při zobrazení zámečků na všech úrovních a taky pro filtraci a počty ve fasetách.

**Comment by honza-rychtar** [comment]
V K7 se zobrazují zámečky a aplikují filtry pro všechny dokumenty, které mají licenci přímo, dědí ji z nadřazeného objektu, neb obsahují objekt s licencí.
Menší problém je u počtů dokumentů ve fasetě licence, protože ty počty se sčítají a pokud má dokument explicitně přiřazenou (nezděděnou) licenci a zároveň má nadřazený objekt explicitně přiřazenou licenci (dokument ji dědí), pak je dokument započítaný dvakrát. 
Řešíme teď možnost dalšího pole v indexu, které by sjednocovalo všechny 3 druhy licence, protože uživatelský klient nerozlišuje typ licence.

V K5 je potřeba v konfiguraci klienta přidat na úrovni Krameria `containsLicences: true`
Ono to potřebuje určitou verzi jádra a zatím to je určeno k testu.

**Comment by zabak** [comment]
Funguje. @honza-rychtar mám to nechat otevřené kvůli tomu novému poli v indexu?

**Comment by zabak** [comment]
@honza-rychtar jak to dopadlo s tím novým polem v indexu?

**Comment by honza-rychtar** [comment]
@honza-rychtar je potřeba to přidat v jádře https://github.com/ceskaexpedice/kramerius/issues/971

**Comment by zabak** [comment]
@honza-rychtar to issue 971 už je vyřešené. Ale problém je u sbírek, viz https://github.com/ceskaexpedice/kramerius/issues/1015 - podle mě ale to není věc klienta, ale jádra...?

> @honza-rychtar je potřeba to přidat v jádře https://github.com/ceskaexpedice/kramerius/issues/971
