### ISSUE TITLE
Přidat geografické vyhledávání

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#54]
V indexu je už podporováno, nutno přidat i do klienta. Funkcionalita obdobná jako např. http://mapy.mzk.cz/hledat/ nebo https://vufind.mzk.cz/Search/Results?filter[]=bbox_geo%3A%22Intersects(11.5%2048.3%2019.1%2051.1)%22

**Comment by zabak** [comment]
Souřadnice máme zaindexované v Solru, takže už je na čem testovat.

**Comment by zabak** [comment]
Zoomovací tlačítka u vyhledávací mapy se zobrazí níž než je okraj okna, takže tlačítko na zoom out není vidět. Testováno v Chrome, Safari a Firefoxu.

![image](https://user-images.githubusercontent.com/811537/75100627-7bfda380-55d0-11ea-856f-d940607c5e91.png)

**Comment by honza-rychtar** [comment]
@zabak Není to jen překryté dockem na Macu?
Každopádně jsem tlačítka přesunul nahoru.
A tohle issue zavírám, protože Geografické vyhledávání už je docela dlouho hotové.
