### ISSUE TITLE
K7 - nelze zobrazit Dublin Core

### ISSUE THREAD

**Issue by marketakrutska** [ceskaexpedice/kramerius-web-client#542]
Všimli jsme si, že v klientu K7 si nelze zobrazit metadata v Dublin Core. Při migraci se to určitě nezahazovalo, někde by to tam mělo být, jen se to asi nezobrazuje. 
viz K5 vs. K7
![image](https://user-images.githubusercontent.com/43740512/186171083-ac7c673c-49f2-4dc3-bbec-1d580dd762f5.png)
![image](https://user-images.githubusercontent.com/43740512/186171098-9401091c-5bfb-481d-9b41-bc59fcfbaedc.png)

**Comment by rzeh4n** [comment]
Problém je na straně klienta, který pro K7 vyrábí špatně url na backend.
Namísto
https://k7-test.mzk.cz/search/api/client/v7.0/items/uuid:6f7587d0-171c-11ed-986f-005056827e52/streams/DC
má být
https://k7-test.mzk.cz/search/api/client/v7.0/items/uuid:6f7587d0-171c-11ed-986f-005056827e52/metadata/dc

**Comment by marketakrutska** [comment]
Jj vím, že DC už není v K7 potřeba. Pak mě napadá otázka, proč je tam vůbec to tlačítko na zobrazení DC, když nemá ani fungovat.

**Comment by zabak** [comment]
@honza-rychtar jediné použití pro DC je v případě nasazení OAI-PMH data provideru nad K7. Tam je Dublin Core záznam povinné předávat jako default formát. Ale nemusí to být DC z metadat, klidně to může být DC poskládaný z metadat v Solru. Pokud už DC nemá v Krameriu využití, měl by zmizet i z metadat, ale pokud v těch metadatech je, měl by se zobrazovat.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.3.9
Např. http://dk.kramerius.org/mzkk7/view/uuid:5867f7d0-4f75-11ed-8291-5ef3fc9bb22f?page=uuid:f0749cfe-9fa2-4bae-8b96-e9757e27559f
