### ISSUE TITLE
Neviditelná jména autorů a roku v document-cart ve Firefoxu

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#546]
Ve Firefoxu dochází k odřádkování textu v document-cart u material icon. Jméno autora nebo rok se tedy posune na další řádek, který se nezobrazí (díky overflow:hidden)

![Snímek obrazovky z 2022-08-30 16-59-02](https://user-images.githubusercontent.com/33415849/187471352-75fdd3dc-a24c-4f4c-9577-282af6fb8dc4.png)

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.3.8**
Ty ikony jsem úplně odebral. Pro pochopení textu nejsou potřeba a je to takto čistší.
<img width="1116" alt="Snímek obrazovky 2022-09-16 v 17 44 43" src="https://user-images.githubusercontent.com/1178142/190680582-7a3f325c-7258-42d2-ba6b-d3a4e907e08b.png">

**Comment by zabak** [comment]
Esteticky se tam ty ikonky hodily, nezbytné ale nejsou a ve firefoxu se teď vše zobrazuje, takže zavírám
