### ISSUE TITLE
Mezera mezi ikonami v sekci kolekcí

### ISSUE THREAD

**Issue by SPXcz** [ceskaexpedice/kramerius-web-client#547]
Zdravím,

na EOD OPEN instanci klienta mám už delší dobu problém se zobrazováním kolekcí. Dělá se tam nevysvěltitelná mezera mezi řádky ikon, kterou nikdo v MZK nikdy jinde neviděl. Mám tam aktuální verzi (2.3.7), ale problém jsem měl už dřív. V mobilním rozlišení problém není. @zabak

https://diglib.eodopen.eu/collections

![Screenshot from 2022-08-31 12-45-29](https://user-images.githubusercontent.com/55412542/187661412-a5911aa4-f32c-466b-9372-fa1aa7a21442.png)

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.3.8**
Sbírky se teď zobrazují v jednom sloupci. Ono je to přehlednější než to bylo ve dvou. Hlavně když jsou popisy různě dlouhé.
https://k7-test.mzk.cz/eod/collections
<img width="1492" alt="Snímek obrazovky 2022-09-16 v 17 53 40" src="https://user-images.githubusercontent.com/1178142/190680135-9420dff4-1b8f-45d5-baec-f4db6e215027.png">

**Comment by zabak** [comment]
@SPXcz prosím potvrď že je to ok

**Comment by SPXcz** [comment]
Jede to v pohodě
