### ISSUE TITLE
xx "titulů" v sekckci sbírek se nepřekládá do angličtiny

### ISSUE THREAD

**Issue by SPXcz** [ceskaexpedice/kramerius-web-client#549]
Bylo by dobrý vytvořit překlad v i18n lokalizačních souborech. Minimálně "titles" do EN a DE. Chtěl by to tak i Petr.
![Screenshot from 2022-09-07 11-46-28](https://user-images.githubusercontent.com/55412542/188848984-c77da2b2-bb1e-43d4-9cb3-354fc6840e66.png)

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.3.8**
https://k7-test.mzk.cz/mzk/collections

**Comment by zabak** [comment]
Funguje, zavírám
