### ISSUE TITLE
Přidat možnost odebrat "pouze veřejné" checkbox z úvodní stránky klienta.

### ISSUE THREAD

**Issue by SPXcz** [ceskaexpedice/kramerius-web-client#550]
V EOD OPEN krameriovi nebudou veřejná díla, takže by bylo dobré přidat možnost odebrání checkboxu do konfiguráku nebo to nějak svázat s nastavením facet (žádná kategorie "Dostupnost" -> smaže se checkbox).

![Screenshot from 2022-09-07 12-00-12](https://user-images.githubusercontent.com/55412542/188850885-8b3cfa35-8fac-4bae-b1ca-768c7c977d6f.png)

**Comment by honza-rychtar** [comment]
Ale ono to je svázané s nastavením facet.
Pokud v poli `filters` není `accessibility`, tak se nejen nepoužije faceta **Dostupnost**, ale taky se skryje to **Pouze veřejné** zaškrtávátko na hlavní straně.

**Comment by zabak** [comment]
funguje, zavírám
