### ISSUE TITLE
K7 sbírky - jak opustím sbírku?

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#563]
Pokud vstoupím do nějaké K7 sbírky, začne se daná sbírka chovat jako filtr. Není ale jasné, jak sbírku opustit. Jde to šipkou v levém horním rohu, ale uvažujeme o jejím odstranění. Chtělo by to přidat do drobečkové navigace něco jako "root" a o řádek výš k názvu sbírky červený křížek jako u filtrů.

**Comment by pavluska** [comment]
<img width="593" alt="Snímek obrazovky 2023-11-22 v 10 55 59" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/3939120/8a761c4d-78bb-422e-8334-9f23aec505cc">
v navigaci sbírek přibyl domeček, který navede na vyhledávací stránku (jakoby zruší filtr sbírky), ale zachová queryParams, pokud byly zadané
