### ISSUE TITLE
Zobrazení většího počtu údajů o obsahu

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#565]
Tento svazek: https://www.digitalniknihovna.cz/mzk/view/uuid:a10c991b-f488-4c1d-9b70-5c69f4fedf9b?page=uuid:b7953d8f-009f-4157-8b3e-1539f16c0503 obsahuje sedm grafik, z nichž každá měla v původním bibliografickém záznamu odpovídající pole 505.  Záznam v MARCu je zde: https://muo.kpsys.cz/records/d8e13ce3-4a9b-4896-8419-4dacf2fbc5ea
Ta se v pravém panelu zobrazí pod záhlavím Obsah. Vzhledem k tomu, že probíhá digitalizace svazků o několika stech grafikách, je potřeba:

- [ ] upravit zobrazení tak, aby se zobrazilo jen prvních několik údajů a další se daly rozbalit
- [ ] jednotlivé údaje o obsahu vertikálně oddělit, podobně jako jsou oddělené poznámky u stejného dokumentu
- [ ] poznámky by mohly v případě většího počtu být taky rozklikávací

**Comment by honza-rychtar** [comment]
Teď se dívám, že u poznámek je chybně popisek _Obsah_ místo _Poznámky_. Opravím.
