### ISSUE TITLE
Bug: zobrazení fulltextového dotazu při zobrazení dokumentu

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#568]
Postup: zadám vyhledávací dotaz, např niveau: https://www.digitalniknihovna.cz/mzk/search?q=niveau&accessibility=public
Klinku na dokument, kde jsou výsledky ve fulltextu, např https://www.digitalniknihovna.cz/mzk/view/uuid:92612320-7da8-11ec-bc36-005056827e51?page=uuid:ca09173c-f2b3-4a7b-a745-0e437c919049&fulltext=niveau
Hledaný výraz se přenese do vyhledávacího políčka na hledání uvnitř dokumentu:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/811537/197731905-24095bc6-5b94-4960-aeee-12b2d1529374.png">
V hlavním vyhledávacím poli zadám stejný dotaz: https://www.digitalniknihovna.cz/mzk/view/uuid:92612320-7da8-11ec-bc36-005056827e51?page=uuid:ca09173c-f2b3-4a7b-a745-0e437c919049&fulltext=niveau
a vyberu stejný dokument.
Hledaný výraz se nepřenese do fulltextového pole, ale klient se chová jako by to tam bylo:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/811537/197732781-229a1ba7-2ca8-495a-965d-962e829dce61.png">
Pokud zatrhnu "všechny stránky", tak se hledané slovo v políčku zase objeví.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.3.9.
http://dk.kramerius.org/mzk/view/uuid:92612320-7da8-11ec-bc36-005056827e51?page=uuid:ca09173c-f2b3-4a7b-a745-0e437c919049&fulltext=niveau
