### ISSUE TITLE
Podivné chování při vyhledávání - našeptávač vrátí název ale výsledek je nulový

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#57]
Máme v Krameriovi dokument s názvem "Nemocnice a útulek Čsl. ochrany matek a dětí v Praze-Krči"

https://dev.medvik.cz/wck/view/uuid:MED00182845-d6fb415b-fd8a-42fc-a907-c538c38bdf06

Když začnu tento název zadávat do vyhledávácího boxu (bez úvozovek), tak mi našeptávač nabídne celý název, takže ho vyberu, ale nic se nenajde. 

https://dev.medvik.cz/wck/search?q=Nemocnice%20a%20%C3%BAtulek%20%C4%8Csl.%20ochrany%20matek%20a%20d%C4%9Bt%C3%AD%20v%20Praze-Kr%C4%8Di%20:%20porodnice%20na%20%C5%A0tvanici&ordering=relevance

Chování je stejné nad starým Solr i nad novým (v7.2).

V obou starých klientech se tento řetězec bez úvozovek najde, ve web-client pouze v úvozovkách.

**Comment by honza-rychtar** [comment]
Opraveno, chyba byla odstranovani pomlcky v dotazu. Misto Praze-Krči se vyhledavalo PrazeKrči.
