### ISSUE TITLE
Zobrazení variantních názvů dokumentu

### ISSUE THREAD

**Issue by kvetjo** [ceskaexpedice/kramerius-web-client#570]
Zdravím, 

mám návrh k diskuzi, který vyplynul z konzultací s jednou z naších paní knihovnic.  

V Krameriu (na liště metadat) je uveden název z MARC pole 245, ale nejsou tam viditelné variantní názvy z polí 246. Dozvěděl jsem se, že v K7 by tyto názvy měly již být dohledatelné při vyhledávání, ale stále však nebudou viditelné. Nestálo by proto zato tyto variantní názvy také zviditelnit?

Chápu, že některé dokumenty mohou mít takovýchto názvu mnoho a že by nebylo vhodné je všechny vypisovat na lištu, proto si myslím, že určité řešení by mohlo být přidat tři tečky (tak jako to je u autorů a dalších tvůrců), které vyvolají tabulku. V této tabulce by pak mohly být všechny názvy přehledně vypsané bez toho, aby na liště zabíraly místo. Tři tečky by se mohly zobrazovat jen tehdy, když jsou variantní názvy k dispozici (protože většina dokumentu má jen jeden název).

Jedná se sice o detail, ale myslím, že má svůj význam. Prosíme tedy o zvážení.

Děkuji,

Jonáš Květ
Ústřední knihovna UK

**Comment by honza-rychtar** [comment]
Ano, to můžeme udělat. 
Zobrazit variantní názvy na liště metadat je možné i v K5. Ono se to tady bere z MODS. 
V K7 se variantní názvy začaly indexovat (což se v K5 nedělo), takže hledání ve variantních názvech je dostupné pouze v K7.

**Comment by honza-rychtar** [comment]
Přidáno ve verzi 2.3.9
K testu tady http://dk.kramerius.org
Např. http://dk.kramerius.org/mzk/periodical/uuid:eb3adc60-dd58-11e2-9923-005056827e52

<img width="153" alt="Snímek obrazovky 2022-11-02 v 9 20 18" src="https://user-images.githubusercontent.com/1178142/199437310-99ca3abf-75ab-4619-ab48-b4276f0711d7.png">

<img width="152" alt="Snímek obrazovky 2022-11-02 v 9 21 30" src="https://user-images.githubusercontent.com/1178142/199437331-97728fe5-c793-4212-9020-8e4ad81cc0cf.png">

**Comment by kvetjo** [comment]
Skvělé, děkujeme Vám
