### ISSUE TITLE
K7 - nefunguje prepinani kapitol v monografiich

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius-web-client#574]
Proti backendu K7 nefunguje prepinani kapitol v ramci monografie (v levem panelu) - zustava stale zobrazena prvni strana. Priklad: https://k7-test.mzk.cz/mzkk7/view/uuid:0174f891-62d3-11e1-8115-0050569d679d?page=uuid:0175bbe2-62d3-11e1-8115-0050569d679d 

Obdobne prepinani clanku v periodiku pritom funguje. Chyba je zrejme v tom, ze dotaz na SOLR, ktery vyhledava stranky v kapitole, hleda v poli own_parent.pid namisto foster_parents.pids.

Pro ilustraci:
- Nefunkcni dotaz na kapitoly:
http://kramerius.snk.sk/search/api/client/v7.0/search?fl=pid,accessibility,model,title.search,licenses,contains_licenses,licenses_of_ancestors,page.type,page.number,page.placement,track.length&q=own_parent.pid:%22uuid:92e7ade5-e0bb-4a18-9e58-8f70862ebc69%22&sort=rels_ext_index.sort%20asc&rows=2000&start=0

- Funkcni dotaz na clanky:
http://kramerius.snk.sk/search/api/client/v7.0/search?fl=pid,accessibility,model,title.search,licenses,contains_licenses,licenses_of_ancestors,page.type,page.number,page.placement,track.length&q=foster_parents.pids:%22uuid:92e7ade5-e0bb-4a18-9e58-8f70862ebc69%22&sort=rels_ext_index.sort%20asc&rows=2000&start=0

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.4.0**

**Comment by zabak** [comment]
funguje
