### ISSUE TITLE
Pristupnost podle norem WCAG 2.1

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius-web-client#576]
* Bolo by mozne, aby elementy ktore su oznacene ako “focus” (pri ovladanie z klavesnice) boli viacej graficky viditelne, napr. nejakym farebnym borderom, tak aby to graficky ladilo?
* Dalej pri zmene jazyka je potrebne aby  tag <html lang="cs”> sa zmenil na lang=“SK”, rovnako pre anglicky lang EN, atd.
* Portal osbsahuje vela kontrastnych chyb, su dobre zdokumentovane ked si zapnete kontrolu napr. cez WAVE plugin v Google Chrome (https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) , cez tento nastroj je viditelnych aj viacero dalsich chyb.
* Ovladanie z klavesnice, niektore elementy pri prechadzani s pouzitim iba klavesnice, su preskocene, napr. zobrazenie metadat, priprava na tlac, stiahnutie PDF, alebo v detaile nahladu sa z klavesnice neda ovladat zvacsenie/zmensenie nahladu. Dalej nie je mozne uplne ovladanie filtra vlavo v sidebare, neda cez klavesnicu vybrat napr. typ dokumentu.
* Cez nastroj Lighthouse v Google Chrome sa da analyzovat taktiez pristupnost, napr. na odkaze http://kramerius.snk.sk/search tak accessibility ma iba 83%. Su tam vypisane aj chyby, skuste sa na to prosim pozriet.

**Comment by neridev** [comment]
Zdravim, dakujem za zalozenie issue.

**Comment by neridev** [comment]
@zabak Ano.
