### ISSUE TITLE
Toolbar - facet.field - model_path vs fedora.model

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#58]
Proč se nepoužívá pro app-search-toolbar fedora.model namísto model_path ?

Potřebovali bychom zahrnout i model article. Pro srovnání:

model_path:
https://dev.medvik.cz/search/api/v5.0/search?q=(fedora.model:monograph%5E5%20OR%20fedora.model:periodical%5E5%20OR%20fedora.model:article)&fl=PID&facet=true&facet.mincount=1&facet.field=model_path&rows=0&start=0

`<lst name="facet_fields">
<lst name="model_path">
<int name="periodical/periodicalvolume/periodicalitem/article">12635</int>
<int name="monograph">6044</int>
<int name="monograph/article">4918</int>
<int name="periodical/periodicalvolume/article">2604</int>
<int name="periodical">270</int>
<int name="monograph/internalpart/article">204</int>
<int name="periodical/periodicalvolume/supplement/article">184</int>
<int name="article">154</int>
<int name="monograph/monographunit/internalpart/article">6</int>
</lst>
</lst>`

fedora.model:
https://dev.medvik.cz/search/api/v5.0/search?q=(fedora.model:monograph%5E5%20OR%20fedora.model:periodical%5E5%20OR%20fedora.model:article)&fl=PID&facet=true&facet.mincount=1&facet.field=fedora.model&rows=0&start=0

- dotaz s fedora.model vrací konzistentní odpověď:

`<lst name="facet_fields">
<lst name="fedora.model">
<int name="article">20705</int>
<int name="monograph">6044</int>
<int name="periodical">270</int>
</lst>
</lst>`

**Comment by honza-rychtar** [comment]
Protoze @filak Protoze tohle vam bude fungovat jen pro vysledky bez fulltextu. Nalezy ve fulltextu maji vzdy fedora.model=page. 
Proto se pouzva model_path, aby se ze stranky odvodil i typ root dokumentu, ktery stranku obsahuje.

Model article neni (nebo alespon nebyl a vetsina knihoven ho tak pouziva) top level dokument. Takze ve vysledcich hledani (v metadatech i ve fulltextu) je zbaleny pod nadrazeny dokument podobne jako vytisky nebo stranky.

Clanky se pouzivaji ruznym zpusobem a nejde nejak rozumne pouzit stejnou logiku pro hledani a zobrazeni/cteni clanku pro vsechny zpusoby.
Treba Lidove noviny v MZK maji 50 tisic clanku. pokud bych zobrazoval clanky v hladani a vyhledal "Lidove noviny", tak se mi ve vysledcich zobrazi cele periodikum a potom 50 tisic samostatnych clanku.
Muzu ve vysledcich zobrazit jen ty clanky, ktere jsou samostatne, coz je zase trochu matouci. Nebo to pridam do konfigurace, kde bude mozne nastavit clanky, aby se chovaly jako top level dokumenty.

Ruzne zpracovani clanku bude problem i u prohlizeni.
1) Zminene Lidove noviny jsou zpracovany tak, ze clanek je pod vytiskem a tento clanek obsahuje stranky, ktere jsou zaroven obsazeny pod tim vytiskem. (Vytisk je mozne prohlizet bez clanku).
2) Napr. KNAV ma clanky reseny tak, ze pod vytiskem jsou pouze clanky a zadne stranky.  (Vytisk neni mozne prohlizet bez clanku). Clanky pak obsahuji nasekana pdf.

**Comment by filak** [comment]
OK. Ale jak tedy zajistime legitimni potrebu filtrovat vysledky/omezit vyhledavani pouze na clanky?

**Comment by filak** [comment]
Ten filtr/faseta by mohl vypadat napriklad takto:

https://dev.medvik.cz/search/api/v5.0/search?q=(model_path:*article*)

**Comment by filak** [comment]
Tak jsem si to zkusil nejak poladit a docela to funguje: 

https://dev.medvik.cz/wck/search?ordering=newest&doctypes=article

Takze zaviram.
