### ISSUE TITLE
Klient nerespektuje kurátorem zadané pořadí dokumentů po nahrání do sbírky

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#584]
Když v K7 po přihlášení admin účtem seřadím dokumenty podle abecedy a v tomto pořadí je zkusím zařadit do sbírky (aby byly dokumenty i v řazení “nově přidané” podle abecedy hned), tak se to nepodaří. Dokumenty se do sbírky nahrají v random pořadí.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/43028501/207438485-516864da-27c3-4ee8-abff-4e1ed5df38b6.png">

Zajímavé je, že přímo v adminu se pořadí zobrazuje zas úplně jinak a netuším, podle jakého klíče.

<img width="931" alt="image" src="https://user-images.githubusercontent.com/43028501/207438747-fa6edce9-76fa-404e-89c2-ae7fdc98f3d7.png">

**Comment by annie-cz** [comment]
Po dohodě s Honzou Rychtářem přesouvám do Kramerius admin klienta, zde zavírám.

**Comment by rzeh4n** [comment]
https://github.com/ceskaexpedice/kramerius-admin-client/issues/48
