### ISSUE TITLE
Nefunguje zobrazovani volnych casti (typ monographunit jako top level )

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius-web-client#585]
V krajske knihovne Pardubice jsou nove naimportovane samostatne dokumenty typu monographunit. Spravne se zobrazuji ve vysledcich vyhledavani, ale pak nejdou otevrit. Ve vysledcich vyhledavani je na ne URL takto:
https://www.digitalniknihovna.cz/kkp/view/uuid:a16371eb-92cc-4cf5-b27f-ebddca1a8be3
to je ale presmerovano na podivne (proc je tam periodical?):
https://www.digitalniknihovna.cz/kkp/periodical/uuid:a16371eb-92cc-4cf5-b27f-ebddca1a8be3

Krome toho v levem panelu je videt podivne oriznuty text:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/1308698/207842595-95358308-ffad-46ce-b2be-56875db3b01b.png">

Dokument je pritom nejspis v poradku, ve starem administartorskem klientu se zobrazuje spravne:
https://kramerius.knihovna-pardubice.cz/search/i.jsp?pid=uuid:a16371eb-92cc-4cf5-b27f-ebddca1a8be3&q=&fq=model_path:monographunit*

**Comment by honza-rychtar** [comment]
U monographunit se vyžaduje nadřazený objekt monograph. Podobně jako u periodicalvolume se vyžaduje nadřazený objekt periodical.

Proč mají samostatné objekty monographunit?
