### ISSUE TITLE
"Pokročilé vyhledávání" podle signatury (apod.)

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#587]
V K5 i K7 lze už vyhledávat podle signatury, což podle mě hodně lidí vůbec nevím. Šlo by vyhledávání podle signatury (a cokoli, podle čeho lze ještě hledat) přidat i do “pokročilého vyhledávání”? Takto to uživatel (i knihovník) musí vědět, aby to mohl používat. Napsané to nikde není.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/43028501/208515319-769e0dcc-7114-4720-ae3f-35d07707cf1e.png">

**Comment by honza-rychtar** [comment]
Přidána Signatura a ISBN ve verzi **2.4.7**

**Comment by zabak** [comment]
Funguje, isbn se musí hledat s pomlčkami.
