### ISSUE TITLE
Doporučené dokumenty - názvy

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#59]
Šlo by udělat, aby se u doporučených dokumentů (vybrané) zobrazoval název nejvyšší úrovně toho dokumentu? Takže když tam mám třeba obálku časopisu, tak by název nebyl "Obálka" nebo "(1a)", ale název toho časopisu, ze kterého ta strana je? Jako je to v jádru? 
![vybrane](https://user-images.githubusercontent.com/21309201/37515914-bb36f166-290c-11e8-826f-a10484627d94.jpg)
![vybrane2](https://user-images.githubusercontent.com/21309201/37515918-be5e4dda-290c-11e8-97e0-7aca55c4210b.jpg)

**Comment by honza-rychtar** [comment]
Ano, udelam.

**Comment by krizovj** [comment]
Děkuji

**Comment by honza-rychtar** [comment]
Opraveno
