### ISSUE TITLE
Navigace při fullscreen zobrazení

### ISSUE THREAD

**Issue by vjirousek** [ceskaexpedice/kramerius-web-client#6]
Při fullscreen zobrazení velmi postrádám navigační prvky pro listování na levém a pravém okraji obrazovky. Digitální knihovna toto má, Kramerius 5 neměl. Budou? :)

**Comment by vjirousek** [comment]
Vlastně mi chybí i při běžném zobrazení.

**Comment by honza-rychtar** [comment]
Tlacitka pro listovani na predchozi a nasledujici stranku jsou tady v ovladacich prvcich dole. 
Tohle muzeme podle zpetne vazby predelat a mit je samostatne po stranach jako v Digitalni knihovne.

**Comment by krizovj** [comment]
Taky by mi ta navigace přišla lepší po stranách.

**Comment by honza-rychtar** [comment]
Navigace funguje. Diskuzi o moznem presunu tlacitek resme v issue #29
