### ISSUE TITLE
Vícedílné monografie

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#60]
Mám dotaz ohledně vícedílných monografií. Nezobrazují se tak, jak mají. Například monografie s názvem Památky východočeské. Má to vypadat tak, že je jeden zastřešující záznam pro celou tu vícedílnou monografii a pod ní jsou ty jednotlivé díly. Zde je odkaz jak to vypadá v jádru:
https://kramerius.lib.cas.cz/search/i.jsp?pid=uuid:562d4075-7b0a-4bc2-9160-02e243875a68&q=pam%C3%A1tky%20v%C3%BDchodo%C4%8Desk%C3%A9

A tady do našeho současného klienta:
https://kramerius.lib.cas.cz/client/handle/uuid:562d4075-7b0a-4bc2-9160-02e243875a68

Ale teď je vlastně ten zastřešující záznam prázdný (nejsou v něm žádné skeny) a ty jednotlivé svazky jsou 
vyházeny mimo ten záznam a jsou zvlášť. U těch Památek východočeských je ani nenajdu, i když mi je našeptávač radí:
![vyhledviced](https://user-images.githubusercontent.com/21309201/37520433-4130d7cc-291d-11e8-93d8-eb604938964d.jpg)

Ale přitom jsem u MZK našla taky jednu vícedílnou monografii, která se zobrazuje zhruba tak, jak bychom potřebovali. Jmenuje se Praktická hospodyňka. Nevíte, prosím, co je tam za problém? Nevím, jak se to liší od těch našich vícedílných monografií, ptž se nemůžu podívat do metadat. 
Akorát u té praktické hospodyňky jsem si všimla, že se to nejdřív tváří jako kniha a pak jako časopis, a pak zas jako kniha:
Výsledky vyhledávání:
![viced](https://user-images.githubusercontent.com/21309201/37520230-88bfec00-291c-11e8-8de8-78567765d868.jpg)

Seznam všech částí:
![viced2](https://user-images.githubusercontent.com/21309201/37520242-9698aab0-291c-11e8-94b7-ccd25de56934.jpg)

Jedna z částí:
![viced3](https://user-images.githubusercontent.com/21309201/37520252-9c546a84-291c-11e8-948a-5d2b22c657f4.jpg)

**Comment by honza-rychtar** [comment]
@krizovj U vicedilnych monografii se pro jednotlive dily pouziva model monographunit, u toho vaseho pripadu se pouziva monograph. 

K te druhe casti. Spatne pouziti typu dokumentu u vicedilnych monografii opravim.

**Comment by krizovj** [comment]
Takže z "originInfo/issuance"? Nebo odjinud se to bere?

**Comment by honza-rychtar** [comment]
Tohle neni v popisnych metadatech (resp. je to v DC, ale z toho to Kramerius nebere).
Je to v **rels-ext** jako vazba **hasModel**, podobne jako treba prirazeni stranky k dokumentu je pres vazbu **hasPage**.

Podle modelu se klient rozhoduje jak s dokumentem pracovat. Pokud byste omylem priradili model _soundrecording_ pro periodikum, tak se toto periodikum otevre v hudebnim prehravaci.

**Comment by honza-rychtar** [comment]
Typ dokumentu opraven. Zbyle se tyka chyby v datech. Zaviram.
