### ISSUE TITLE
Nastaveni actions u licenci je aplikovano az po prihlaseni

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius-web-client#603]
V SNK mame nastavene u license paying_users  blok actions: {
            pdf: false,
            print: false,
            jpeg: false,
            text: true,
            citation: true,
            metadata: true,
            share: true,
            selection: true,
            crop: true
          }
Tedy nepristupna tlacitka pdf, print a jpeg. 
Treba tento titul:
https://dikda.snk.sk/view/uuid:5b2f9dc6-b3e6-4ab7-9a6f-c23f583b8810?page=uuid:c64bf8e6-0509-4cff-aa51-897d29082e7c

Tlacitka jsou ale pri otevreni titulu pristupna a deaktivuji se az po prihlaseni uzivatele. Podobne u licence only_in_library, kde je access:'terminal' a prihlaseni neni vubec potreba (pristup je omezen pres IP filtr), zustavaji tlacitka pristupna. 

JPEG a PDF sice akci nasledne nedovoli spustit (s varovanim o autorske ochrane), ale v priprave tisku jde pokracovat a nakonec skonci matouci hlaskou "stranka nebyla nalezena".

Obecne by asi bylo lepsi i dostupnost akci definovat a vyhodnocovat na backendu a ne v globals.js. Bylo by to logictejsi a konzistentni. (Dostali jsme i navrh/pozadavek, aby pristupnost tlacitka Tisk byla zavisla na IP adrese - to jinak nez na backendu vyresit nelze.)

**Comment by zabak** [comment]
Totéž platí pro vodoznak: když máme licenci vyžadující vodoznak, tak bych potřeboval, aby ho aplikoval jakýkoli klient na základě informace ze serveru. Obecně asi všechny vlastnosti licencí by měl předávat server, včetně toho, že si ČDK tyto vlastnosti z jednotlivých Krameriů bude přebírat a poskytovat je klientovi ČDK.

**Comment by honza-rychtar** [comment]
K serveru. Ano, to je cíl, aby se vše konfigurovalo na serveru. S @pavel-stastny jsme domluveni, že to uděláme. Ale nemá to teď prioritu a ty já neurčuju.

Pokud jde o konfiguraci akcí na klientovi, tak akce se konfigurují globálně https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta#akce-v-prohl%C3%AD%C5%BEe%C4%8Dce
A pak je možnost je přetížit pro každou licenci zvlášť.
Důležité je rozlišovat 1) licenci dokumentu, 2) licenci uživatele a 3) licenci přes kterou je dokument skutečně zpřístupněný.
Ty přetížené akce se uplatňují pro možnost 3), tj. až na základě toho, že je dokument uživateli poskytnut opravdu na základě této licence.
Takže řešením bude nastavit akce jako `available` globálně. A pak je pro každou licenci povolit podle potřeby.
To je specifický use case SNK, kdy má každý dokument právě jednu licenci a každá licence odpovídá jednomu ze tří typů dostupnosti a zároveň ta právě jedna licence je jediný způsob zpřístupnění dokumentu.

**Comment by vlahoda** [comment]
Diky, to globalni nastaveni 'available' tenhle problem vyresilo. Nastavovani vsech prav na serveru je na samostatne issue, myslim ale, ze to prioritu brzo bude muset dostat.
