### ISSUE TITLE
Periodika – přechod z úrovně čísla na ročník

### ISSUE THREAD

**Issue by kvetjo** [ceskaexpedice/kramerius-web-client#604]
Zdravím,
zasílám zpětnou vazbu, kterou jsem na Krameria získal:

Některá periodika mají v ročníku pouze jedno číslo, úrovně ročník a číslo jsou stejné. Pokud je uživatel na úrovni čísla, klikne na možnost „Přejít na ročník“, načte se znovu to stejné, což může být pro něj matoucí. Šlo by tuto možnost „**Přejít na ročník**“ v těchto případech odstranit a ponechat jen „**Přejít na periodikum**“?
Jako příklad mohu uvést: [https://kramerius.cuni.cz/uuid/uuid:60597310-f75d-468b-9b6e-aa735a4f3984](https://kramerius.cuni.cz/uuid/uuid:60597310-f75d-468b-9b6e-aa735a4f3984)

Myslím si, že se jedná o relevantní připomínku, každopádně rozumím, že to může být z nějakého hlediska problematické, proto prosím o váš názor, 

Jonáš Květ
Ústřední knihovna UK

**Comment by honza-rychtar** [comment]
Přidáno ve verzi 2.4.4

**Comment by zabak** [comment]
funguje
