### ISSUE TITLE
Drobná oprava dokumentace

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#606]
Zdravím,
na wiki, v sekci týkající se konfigurace licencí:

https://github.com/ceskaexpedice/kramerius-web-client/wiki/Konfigurace-licenc%C3%AD

je drobná chyba, viz screenshot:

![wiki-00](https://user-images.githubusercontent.com/8750622/220375134-5077ca15-cb3e-473f-a6a2-e4e5396e6189.png)

Pokud to není nějaký speciální záměr, tak ta direktiva `access: 'login'` by měla být posunuta až do konkrétní licence, v tomto případě tedy `dnnto`.

Toto umístění naopak evokuje, že jde o globální/výchozí nastavení pro všechny licence, které pak lze případně u nějaké licence dle potřeby přetížit.

Celkem mě to potrápilo, nastavil jsem to v konfiguraci klienta a ono to pořád nefungovalo, až mi pak došlo, že je to asi tedy chyba v dokumentaci...

Díky, MD

**Comment by honza-rychtar** [comment]
Jej, moje chyba, omlouvám se. opravil jsem to na wiki. Díky.
