### ISSUE TITLE
Zdvojená hláška o nedostupnosti u private dokumentů 

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#607]
U dokumentů, které mají `policy=private`, ale nemají přidanou žádnou licenci (stále velká část dokumentů alespoň v DK KNAV) je u konkrétní strany zdvojená hláška o nedostupnosti. Nejdřív se text vypíše pod hlavičkou "Tento dokument spadá pod následující licence" a potom se ten stejný text opakuje pod nadpisem "Pokud se k dokumentu nemůžete dostat v rámci licencí..."

Problém se objevuje např. tady: https://www.digitalniknihovna.cz/knav/uuid/uuid:7fb6e9a5-87ee-4dcb-8f66-1674b93510d1

Šlo by to nějak vyřešit? Může to působit trochu matoucím dojmem a opuštění příznaku `private` bude asi ještě chvíli trvat... 

Díky

**Comment by kerschfilip** [comment]
Chyba se projevuje i u dokumentů, které licenci přidělenou mají - pod textem o konkrétní licenci je vždy obecný text patřící private dokumentům 2x:

![image](https://user-images.githubusercontent.com/57805328/220585671-c8bd392c-0ff1-4f67-a1a9-3f118d35b274.png)

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.4.4**

**Comment by kerschfilip** [comment]
opraveno, díky!
