### ISSUE TITLE
Po vyhledání fráze se nezobrazí dokument

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#609]
Tento odkaz https://kramerius.k7-test.mzk.cz/mzk/view/uuid:2e52f130-4743-11ea-9ac7-005056827e51?fulltext=%C3%BAvod%20do%20geografick%C3%BDch%20informa%C4%8Dn%C3%ADch%20syst%C3%A9m%C5%AF%20kone%C4%8Dn%C3%BD zobrazí jen matadata, jinak nic. Pokud odmažu poslední slovo, začne to fungovat. Problém je v tom, že se ta fráze nenachází na jedné stránce, ale i tak by se mělo zobrazit menu vlevo a info že nebyla nalezena žádná stránka.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.4.8
https://dk.kramerius.org/mzk/view/uuid:2e52f130-4743-11ea-9ac7-005056827e51?fulltext=%C3%BAvod%20do%20geografick%C3%BDch%20informa%C4%8Dn%C3%ADch%20syst%C3%A9m%C5%AF%20kone%C4%8Dn%C3%BD

**Comment by zabak** [comment]
funguje, zavírám
