### ISSUE TITLE
Nespravne udaje ve facete Typ dokumentu ve strance vyhledavani

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius-web-client#610]
Faceta Typ dokumentu v zalozce Prochazet ukazuje spravne pocty polozek:
![image](https://user-images.githubusercontent.com/1308698/221139676-7609c726-92b0-47b5-a2c4-65d780d32b3a.png)

ale odpovidajici faceta Typ dokumentu na strance s vysledky vyhledavani (bez aktivnich filtru) nespravne nebo nulove hodnoty:
![image](https://user-images.githubusercontent.com/1308698/221140204-53c01bb0-f666-4120-a4d3-dc082d5df755.png)

**Comment by honza-rychtar** [comment]
U těch typů dokumentu se počítá jen s top level modely. Možnost konfigurace slouží k omezení, ne k přidávání dalších.
Proč by tam měly být kapitoly? To bez kontextu nedává smysl.
Články v určitých případech ano, ale muselo by se to upravit. 

Ta chybná čísla jsou pak způsobena připočtením kapitol ke knihám a článků k novinám.

**Comment by vlahoda** [comment]
Proc to knihovnici chteji, to nevim. Meli to tak ve sve puvodni verzi digitalni knihovny. 
V kazdem pripade myslim, ze neni dobre, ze na strance Prochazet se obsahy facet zobrazuji spravne, i pro ty clanky a kapitoly a u vysledku vyhledavani ne - pritom by to mela byt stejna faceta  a kdyz nejsou aplikovany zadne filtry, tak i stejny dotaz do indexu.

**Comment by lgloncak** [comment]
Pozdravuje Ľuboš Glončák zo Slovenskej národnej knižnice.

Dôvod je jednoduchý, články z monografií (kapitoly) boli totiž vykázané ako digitálny objekt, ktorý je zobraziteľný v digitálnej knižnici. 

Pokiaľ ide o to, prečo by tam mali byť kapitoly - je potrebné vysvetliť, že ide o špecifický typ kapitoly, keďže ide o články / príspevky z monografických zborníkov. Nejde teda o kapitoly z nejakej beletrie, kde by to skutočne zmysel nemalo.

Ide o analógiu článku z periodika, ale v monografii (resp. monografickom zborníku), preto je tam aj chapter a nie article.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.4.4

**Comment by zabak** [comment]
@lgloncak můžeme zavřít?

**Comment by lgloncak** [comment]
@zabak áno, môžete zavrieť, ďakujeme.
