### ISSUE TITLE
Nesprávne zobrazenie informácie o dostupnosti pre dokumenty s public licenciou

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius-web-client#613]
Pri dokumentoch, ktoré sú private a majú licenciu, ktorá dovoľuje ich zobrazenie bez prihlásenia sa nesprávne vykresľuje informácia o dostupnosti, viď obrázky.

<img width="557" alt="image (1)" src="https://user-images.githubusercontent.com/65346739/222412933-5550c4d8-f3ee-4f2d-9e25-e6964f0c3d28.png">![Screenshot 2023-03-02 at 12-18-11 Hledání Moravská zemská knihovna Digitální knihovna Kramerius](https://user-images.githubusercontent.com/65346739/222414070-0d40d14f-ec34-4369-8de6-04bc9dc6ee7f.png)

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.4.4

**Comment by zabak** [comment]
funguje, zavírám
