### ISSUE TITLE
U filtru "Typ dokumentu" se zobrazuji sbirky i kdyz nejsou definovane v konfiguraci

### ISSUE THREAD

**Issue by pkudela** [ceskaexpedice/kramerius-web-client#619]
Priklad - SNK -> https://dikda.snk.sk/search
V konfiguraci -> https://dikda.snk.sk/assets/shared/globals.js jsou definovane pouze 3 polozky:

doctypes: ['periodical', 'monograph', 'manuscript'],

Presto se zobrazuji 4 polozky, konkretne "Sbirky" tam byt nemaji.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.4.4
