### ISSUE TITLE
Poslední verze 2.4.4 - problém s otáčením obrázku

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-web-client#624]
Zdravím,

po nasazení verze 2.4.4. jsem zjistil, že nelze otáčet obrázek (tlačítko [Otočit doprava] na nástrojové liště). Obrázek se sice otočí, ale hned se vrátí do původní/výchozí polohy.

Vyzkoušeno na několika nezávislých instancích Krameria.

U PDF otočení ale funguje, problém se týká podle všeho jen obrázků (klasický jpg i dlaždice z imageserveru).

Příklad zde:
https://kramerius.nulk.cz/uuid/uuid:aae92e0b-5996-44f7-9bde-3f0abde5346d

MD

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.4.7**

**Comment by kerschfilip** [comment]
Funguje, díky!
