### ISSUE TITLE
Úpravy v terms pages

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius-web-client#626]
Zdravím,
v MZK by sme si chceli viacej prispôsobiť vykresľovanie terms pages.
Konkrétne by sme chceli aby sa dal checkbox "Souhlasím s podmínkami použití" parametrizovať linkom na stránku s podmienkami použitia.
A celkovo by sme chceli aby sa dal celý komponent, checkbox a tlačítko Prihlásiť, umiestniť hocikde v rámci html. Momentálne sa táto dvojica vykresľuje pod html stránku terms a chceli by sme dosiahnúť aby sa dala zakomponovať niekde v rámci terms stránky. Dalo by sa to dosiahnúť nejakým placeholderom?
V každom prípade momentálne vyzerá takto https://kramerius.k7-test.mzk.cz/mzk/terms a chceli by sme týmto dosiahnúť aby sa viacej podobala na  https://dnnt.mzk.cz/podminky-zpristupneni?target=https://dnnt.mzk.cz , kde je celý ten komponent, checkbox a tlačítko Prihlásiť, v texte a nachádza sa vyžšie na stránke.

Ďakujem,
Róbert Randiak MZK

**Comment by honza-rychtar** [comment]
Volitelně je možné zadat `termsPage2`, které se zobrazí pod odsouhlasení podmínek a tlačítko přihlášení.

Pokud je uvedeno `termsUrl`, tak se u souhlasu s podmínkami v textu "Souhlasím s podmínkami použití" změní text "podmínkami použití" na odkaz vedoucí na uvedené url.
```
...
termsPage: {
  cs: '/assets/shared/terms/terms.cs.html',
  en: '/assets/shared/terms/terms.en.html'
},
termsPage2: {
  cs: '/assets/shared/terms/terms2.cs.html',
  en: '/assets/shared/terms/terms2.en.html'
},
termsUrl: {
  cs: 'https://kramerius.k7-test.mzk.cz/assets/shared/terms/terms_of_use.html',
  en: 'https://kramerius.k7-test.mzk.cz/assets/shared/terms/terms_of_use.html?lang=en'
},
...
```


Ukázka
http://k7.kramerius.org/terms

**Comment by r2it-git** [comment]
Funguje ako má. Zatváram.
