### ISSUE TITLE
Hlášky u nedostupných dokumentů - změna na základě UX analýzy

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#629]
Zdravím, 

z UX analýzy Proof & Reason vzešel návrh zjednodušit hlášky u neveřejných dokumentů tak, že se čtenáři nejdříve důrazně a jednou větou řekne, co má udělat, aby se k dokumentu dostal místo toho, aby se vypisovaly všechny licence. Podrobnější popisy jednotlivých licencí by měly být schované pod odkazem "Více o licenci".

Původní návrh P&R:
![image](https://user-images.githubusercontent.com/57805328/231126900-0f28650b-1e6a-4d7f-9c30-718c199c83c2.png)

Podle domluvy ze schůzky jsem připravil dokument s návrhem toho, jak by to mohlo vypadat s DNNT a dalšími licencemi. Prosím o komentáře a připomínky, abychom se mohli dohodnout na tom, jak to realizovat: https://docs.google.com/document/d/1nNMG2b36UHunj-O3vnRcxrLbFSVW5RXiqjyF1pstLeQ/edit

Text vychází z dohodnuté a v současnosti používané hlášky pro veřejně nedostupné dokumenty, jde hlavně o tu první část a o to, aby to dávalo smysl jako celek...

Děkuji!

**Comment by honza-rychtar** [comment]
Upraveno ve verzi 2.5.0
<img width="814" alt="Snímek obrazovky 2023-08-11 v 10 49 57" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/dcbd90d7-7694-4aad-bb25-c8adb6cf1954">

Je nutná změna konfigurace. Minimálně přidat pro každou licenci `instruction`.
https://github.com/ceskaexpedice/kramerius-web-client/wiki/Konfigurace-licenc%C3%AD
