### ISSUE TITLE
Nefunkční top level stránka při použití více Krameriů

### ISSUE THREAD

**Issue by mjtecka** [ceskaexpedice/kramerius-web-client#630]
Ahoj,

po upgradu z klienta 2.3.8 na 2.4.4 nám přestalo fungovat přesměrování z https://kramerius.cuni.cz na prvního Krameria v konfiguraci tzn. https://kramerius.cuni.cz/uk  Místo toho dostáváme 404 stránku (nedaří se mi vystopovat příčina). 

Nevidím žádnou relevantní změnu v konfiguraci, rollback na 2.3.8 zase přesměrování opravil. Konfigurační soubor global.js máme v obou případech stejný, všechno ostatní co vidím v Chrome vrací poctivě 200. Přímé otevření https://kramerius.cuni.cz/uk funguje v pohodě i v 2.4.4. 

Rozbil jsem někde něco v klientovi, nebo se mohlo mezi těmi verzemi měnit něco co by mohlo hrát nějakou roli?

[kvůli tomu rollbacku tam máme zpátky předchozí verzi klienta, takže https://kramerius.cuni.cz teď funguje]

Dík,
MJ.

**Comment by mjtecka** [comment]
Zároveň nám taky v 2.4.4 přestaly fungovat linky z https://kramerius.cuni.cz/uuid/uuid:1e7ff482-d2bf-11ed-b923-fa163e4ea95f (které jsou teda samy o sobě problematické, protože nám je generuje v téhle formě i "uk" Kramerius i "lf1" kramerius.. ale to je asi trošku jiná story)

**Comment by honza-rychtar** [comment]
Chyba projevující se u klienta napojeného na více Krameriů bez rozcestníku.
Opravím.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.4.7**
