### ISSUE TITLE
Searchbar na hlavní stránce je posunutý doleva, když se odebere 'accessibility' z facet.

### ISSUE THREAD

**Issue by SPXcz** [ceskaexpedice/kramerius-web-client#632]
Zapnuté 'accessibility' (ok):

![Screenshot from 2023-04-19 16-47-36](https://user-images.githubusercontent.com/55412542/233113185-28e8d915-e7ef-4b95-9b73-61e3aac1c9f3.png)

Vypnuté 'accessibility' (problém):

![Screenshot from 2023-04-19 16-42-20](https://user-images.githubusercontent.com/55412542/233112651-bd176c7a-bad5-4f6b-8298-876dcb95dd6c.png)

Edit: Spíš bych řekl, že se ten searchbar "protáhne".

**Comment by honza-rychtar** [comment]
Opraveno ve verzi **2.4.7**
