### ISSUE TITLE
Podpora image serveru s protokolem IIIF v2 - alternativa k IIP+Zoomify

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#64]
Lokálně jsem zprovoznil Java image server [Cantaloupe v3.4.1](https://github.com/medusa-project/cantaloupe) s **OpenJPEG** v2.3.0. 

Testoval jsem ho zatím s prohlížečkou [OpenSeadragon](https://openseadragon.github.io/examples/tilesource-iiif/) v2.3.1 přes Kramerius search/iiif/ endpoint, což funguje bez problému a subjektivně server odpovídá rychle.

Thumbnaily se v Kram. klientech také načítají svižně.

Problém je ale s implementací prohlížečky v Kram. klientech, kde se počítá pouze se zdrojem dlaždic Zoomify nebo DZI.

Bylo by možné do web-clienta integrovat alternativně nějakou čtečku podporující IIIF protokol ?

**Comment by zabak** [comment]
S postupným přechodem na IIIF se počítá v rámci projektu RightLib. Klokan nad OpenLayers postavil https://github.com/klokantech/iiifviewer

**Comment by filak** [comment]
Tak to je fajn, ale ptám se na K6 web-klienta ... Nevím, jaké jsou šance, že se to dostane do kódu klienta, a kdy by k tomu mohlo třeba dojít.

**Comment by filak** [comment]
Aktivní projekt IIIF prohlížečky pro Angular: 
https://github.com/NationalLibraryOfNorway/ngx-mime

Demo: 
https://nationallibraryofnorway.github.io/ngx-mime-site/

**Comment by filak** [comment]
Nakonec jsem vystačil pouze s https://www.npmjs.com/package/openseadragon

https://github.com/filak/wck/blob/f83df8b11326786eed99ffe963d362550a5e7f1e/src/app/book/iiif-viewer/iiif-viewer.component.ts

Použití příslušné prohlížečky se řídí globální property: imageViewer: 'iiif' / 'zoomify'

TODO: 
- doladit 2-stránkové zobrazení
- podpora ALTO/overlay při vyhledávání

(Živou online instalaci zatím bohužel nemám.)

**Comment by filak** [comment]
Znovu otevírám, protože v oficiální verzi podpora IIIF stále chybí.

**Comment by JanMeritus** [comment]
taky nas to celkom zaujima. Aky mate na to nazor u vas? @zabak

**Comment by zabak** [comment]
Na straně klienta to není problém změnit, on už reálně IIIF Image API využívá pro výřezy obrázků (podmínkou je ale že obrázek je poskytovaný přes IIPImage, který IIIF umí) - viz MZK. Ale je potřeba odpracovat si konverzi všech obrázků do jp2.

**Comment by zabak** [comment]
OpenLayers zamergovali tento pull request https://github.com/openlayers/openlayers/pull/9430 takže podpora IIIF Image API v je v OpenLayers od verze 6, která je teď v betě.

**Comment by honza-rychtar** [comment]
Nová prohlížečka má podporu IIIF.
Pokud má klient v konfiguraci zapnuto IIIF a obrázek má dlaždice, pak se použije IIIF
Pokud nemá klient v konfiguraci zapnuto IIIF a obrázek má dlaždice, pak se použije Zoomify
Jinak se použije JPEG


IIIF http://dk.kramerius.org/mzk/uuid/uuid:288862c6-4e2e-4b5f-8e57-290035032b0e
Zoomify: http://dk.kramerius.org/nkp/uuid/uuid:5591ee80-cb78-11e6-ac1c-001018b5eb5c
JPEG: http://dk.kramerius.org/knav/uuid/uuid:e8bad9cc-39e9-41f9-8da7-d2ed823c4856
