### ISSUE TITLE
Při zařazování dokumentů do sbírky z klienta je třeba vylepšit a zabezpečit proces přidávání

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#640]
Vypadá to, že pokud člověk v klientovi odejde úmyslně / omylem (a že je to jednoduché) z nabídky (pod tužtičkou) na zařazení dokumentů do sbírky, část dokumentů se nezařadí. Záleží v jaké části nahrávání to dropne. Je vždy nutné čekat až se dotočí kolečko a kurátor dostane hlášku, že proces byl spuštěn. Není to ideální, chtělo by to, aby se to poslalo automaticky na pozadí tak či onak jako sadu (a hlavně jako jeden proces, ne jako sadu 60 samostatných procesů, pokud tam člověk nacpe např. celou stránku výsledků vyhledávání). Takto hrozí vznik zbytečných chyb, kterých si kurátor nemusí všimnout a zasekává to frontu.

Issue přestěhováno z https://github.com/ceskaexpedice/kramerius-admin-client/issues/50.

**Comment by honza-rychtar** [comment]
@annie-cz hromadné přidávání přes jeden dotaz by už mělo být dávno hotové.

**Comment by annie-cz** [comment]
Otestováno, aktuálně tam vyskočí potvrzující dotaz a následně dialog s hláškou, že se proces zařadil do naplánovaných procesů. Zavírám. 🙂 

<img width="709" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/2784f74a-00ea-4658-a88d-181d063891e3">

<img width="511" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/a4c40468-c5b1-4659-81e5-99f9908119db">
