### ISSUE TITLE
Možnost přidávání licencí a donátora z klienta

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#645]
Prosím o přidání možnosti přidávání licencí a donátora rovnou z klienta v rámci admin módu. Byl by to pak další řádek v této nabídce:

![image](https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/792652ce-e44e-434f-a736-6278494ba050)

Žádosti původně z issues:
https://github.com/ceskaexpedice/kramerius-admin-client/issues/3
https://github.com/ceskaexpedice/kramerius-admin-client/issues/27

**Comment by annie-cz** [comment]
Ještě by možná stálo za to přidat podobným způsobem i možnost označit z klienta rovnou některý dokument jako doporučený pro hlavní stránku. Částečně se tomu věnuje issue: https://github.com/ceskaexpedice/kramerius-admin-client/issues/11

**Comment by annie-cz** [comment]
Licence jsou v pořádku, u donátora ještě čekám na test. Pokud to bude v pořádku, zavřu issue. Na poslední koment ohledně podobného chování vzhledem k doporučeným dokumentům založím nové issue.

**Comment by honza-rychtar** [comment]
Donátoři ještě nejsou. Na to založme nové issues. Bude potřeba i API a admin klient. 
Tohle issues nechme na správu licencí v klientovi, který byla přímočařejší a samostatná - teď je možné to dělat přes API, admina i uživatelského klienta.
