### ISSUE TITLE
Podkladová mapa je jen v angličtině

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#651]
Pokud přepnu jazyk, podkladová mapa  (jak pro hledání, tak pro mapová díla) zůstane v angličtině.  Jednak tlačítka na přepnutí mezi mapou a satelitním snímkem a jednak místní názvy.

**Comment by pavluska** [comment]
@zabak Můžeš mi udělat printscreen, co přesně myslíš? Já mám zas všechno pořád v češtině, tak to bude asi brát lokalizaci z browseru. Viz https://developers.google.com/maps/documentation/javascript/localization

**Comment by zabak** [comment]
<img width="843" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/811537/9f237865-a0d2-496d-8428-d0fc8a90bdc2">
<img width="220" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/811537/0d61a824-6ebf-4e9e-8d07-d84aa9525805">
V tom druhém případě tam nejsou otextovaná tlačítka, takže je to asi jedno, všiml jsem ale přitom, že jsou tam anglicky i názvy českých měst.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.5.0
