### ISSUE TITLE
Na home stránce tab "Navštívené" nezobrazuje žádné položky

### ISSUE THREAD

**Issue by pkudela** [ceskaexpedice/kramerius-web-client#653]
V klientovi v MLP, ktery bez nove bezi pod k7 nefunguje zalozka "Navštívené", respektive nezobrazuji se zadne navstivene dokumenty, po nasem telefonickem rozhovoru zakladam toto issue.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.4.8

**Comment by zabak** [comment]
funguje, zavírám
