### ISSUE TITLE
epub - nefunguje zobrazení externě linkovaného dokumentu

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#656]
Příklad: https://diglib.eodopen.eu/view/uuid:0ef727bb-edf3-435b-9639-8697218bdf6b
Ve FOXML je link na epub
http://www.dlib.si/stream/URN:NBN:SI:doc-KZFI959V/3836a715-4096-41c5-a926-4b1f7e43901b/EPUB
link je funkční, ale klient daný epub nezobrazí. Co je špatně?

**Comment by honza-rychtar** [comment]
Ve FOXML má mimetype **application/pdf**, takže Kramerius ho pak takto i vrací v 
https://backend.ds-coil.uibk.ac.at/search/img?pid=uuid:0ef727bb-edf3-435b-9639-8697218bdf6b&stream=IMG_FULL&action=GETRAW
a snaží se ho otevřít/uložit jako pdf.

Pro test epubu v klientovi můžeš tady https://diglib.eodopen.eu/view/epub zkusit načíst libovolný epub. Ten z FOXML funguje.
<img width="1659" alt="Snímek obrazovky 2023-05-29 v 17 05 03" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/d639430a-71a3-4af1-a2d3-8eaeb8dfb760">

Je potřeba poladit cestu od importu po API, aby se epub vracel jako epub. V prvé řadě je potřeba nastavit správný mimetype 
**application/epub+zip**

S @pavel-stastny máme v plánu udělat přístup k epubu přímo přes tu strukturu uvnitř archivu - nebude se stahovat celý epub, ale jen požadované části.

**Comment by SPXcz** [comment]
Tady je to normálně jako application/epub+zip:
https://backend.ds-coil.uibk.ac.at/search/api/v5.0/item/uuid:2ebee875-0319-4caf-b46d-ec444942634f/foxml

Ale nic se nezobrazuje:
https://diglib.eodopen.eu/view/uuid:2ebee875-0319-4caf-b46d-ec444942634f

Podle analýzy HTTP provozu to vypadá, že se ten klient ani na ten EPUB neptá.

**Comment by honza-rychtar** [comment]
Od verze 2.5.0 fungují epuby nad daty z K7. 
http://dk.kramerius.org/k7/view/uuid:c9b6c867-6d60-4a64-9519-95f5e66ea910

V K5 je tam chyba. Bude opravena v příští verzi.

**Comment by SPXcz** [comment]
Pokud je chyba jen v K5, tak to asi není potřebovat opravovat @zabak, ne?

**Comment by zabak** [comment]
Ano, v k5 není potřeba opravovat

**Comment by honza-rychtar** [comment]
Není to chyba přímo v K5, ale v komunikaci klienta s K5. Už je to opraveno, bude v příští verzi.

**Comment by annie-cz** [comment]
@zabak můžeme zavřít?

**Comment by zabak** [comment]
Ano, ten epub uvedený na začátku issue funguje, zde zavírám
