### ISSUE TITLE
Text licence podle toho jestli je uživatel přihlášený nebo ne

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#658]
Na schůzce 28.4.2023 se dohodlo, že bude možné nastavit různé text licence podle toho jestli je uživatel přihlášený nebo ne.
Takže pokud jsem přihlášeny a zároveň nemám přístup k licenci X a snažím se zobrazit dokument s licenci X, pak se zobrazí text určený pro přihlášeného uživatele.
Ten může být např. rozšířený o následující text na začátku.

> „Váš účet nesplňuje podmínky pro přístup k dokumentu. Problém může být v údajích, které systému předává poskytovatel Vaší identity (instituce, jejíž účet používáte pro přihlášení). V takovém případě svého poskytovatele kontaktujte.“

Důvodů proč nemám i po přihlášení přístup k licencí může být hodně. 
- nedostatečné atributy u poskytovatele identity (už jsem jen absolvent u univerzity, dlužím knihy v knihovně, ...)
- jsem na black listu u Krameria (banování uživatelů)
- jsem přihlášený účtem, který je vyžadovaný pro jinou licenci
- jsem přihlášený běžným účtem (Google, Facebook, ...) pouze kvůli možnosti tvorby uživatelských seznamů.

Tomuto pak bude potřeba ty texty přizpůsobit - to že je někdo přihlášený a zároveň nemá licenci DNNT ještě neznamená, že je někde chyba nebo dochází k blokování - třeba jsem se přihlásil jen proto, abych měl funkcionalitu pro personalizaci a persistenci

**Comment by pavel-stastny** [comment]
@honza-rychtar Nebylo by dobré toto sjednotit s plánovaným přechodem konfigurace licencí do jádra ?

**Comment by honza-rychtar** [comment]
@pavel-stastny bylo, ale ten přechod pořád nikdo neschválil.

**Comment by pavel-stastny** [comment]
@honza-rychtar Ok  :-)

**Comment by honza-rychtar** [comment]
U licence je možné nastavit 3 typy textu
* `message` - odkazy na text licence v html pro případ, že uživatel není přihlášený a nemá přístup k licenci
* `message2` - odkazy na text licence v html pro případ, že uživatel je přihlášený a nemá přístup k licenci
* `message3` - odkazy na text licence v html pro případ, že uživatel má přístup k licenci

Více zde
https://github.com/ceskaexpedice/kramerius-web-client/wiki/Konfigurace-licenc%C3%AD
