### ISSUE TITLE
Divné chování při hledání

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#66]
tak jsme to zkoumali a nevíme kde je problém - viz.
https://github.com/ceskaexpedice/kramerius-web-client/issues/61
https://github.com/moravianlibrary/kramerius/issues/249

Pokud zadám slovo novézvolení, novézvolení poslanci, "novézvolení poslanci" tak se jinak chová nový klient a digitální knihovna. Liší se to i v rámci vyhledávání ve stránce a zobrazení vyhledaného termínu na stránce.

**Comment by honza-rychtar** [comment]
Dokud neupgradujete solr, tak tohle vubec nereste. DK pouziva pro fulltext _text_ocr_ - ktere je ted lemmatizovane a nemelo by. V dalsi verzi solru uz zase lemmatizovane nebude (lemmatizovane bude _text_ocr_lemmatized_). Takze _text_ocr_ bude fungovat jako pred upgradem a tak jako funguje u knihoven, ktere neupgradovaly. 
Novy klient pouziva _text_, ktere neni lemmatizovane - tohle je jeden z duvodu ruznych vysledku. Druhy je divny stav mzk indexu. Vse se vyresi upgradem.
