### ISSUE TITLE
Problém s collection.desc

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius-web-client#668]
Po commitu e5465ca máme problém s vyhledáváním - dotazuje se na API: https://kramerius5.nkp.cz/search/api/v5.0/search?q=*:*&fq=(fedora.model:monograph%20OR%20fedora.model:periodical%20OR%20fedora.model:map%20OR%20fedora.model:sheetmusic%20OR%20fedora.model:monographunit)&fl=PID,dostupnost,fedora.model,dc.creator,dc.title,dc.title,root_title,datum_str,dnnt-labels&facet=true&facet.mincount=1&facet.field=keywords&facet.field=language&facet.field=dnnt-labels&facet.field=facet_autor&facet.field=collection.desc&facet.field=model_path&facet.field=dostupnost&sort=created_date%20desc&rows=60&start=0

Pokud zaměním collection.desc za collection vše funguje. V NK odstraněnou změnou řádku 1344 v solr.service.ts na return 'collection';

**Comment by honza-rychtar** [comment]
Bylo zaneseno i opraveno mezi releasy. Ve verzi 2.4.9 to bylo v pořádku, ve verzi 2.5.0 taky.

**Comment by zabak** [comment]
@jahhoo prosím o kontrolu a zavření
