### ISSUE TITLE
Sdílet - v Mozille nejde zkopírovat odkaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#67]
V Mozille mi nejde označit odkaz pro sdílení, abych ho mohla zkopírovat. Mám verzi 59.0.2 a měla by být aktuální. Jiný prohlížeč mi to nedělá (Chrome, IE, Opera). 
Jde s tím něco dělat nebo ne?

**Comment by pavelkocourek** [comment]
opraveno, bude v buildu
