### ISSUE TITLE
neexistující uuid v K7 zacyklí klienta

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#670]
Když v K7 zadám neexistující uuid, tak se klient zacyklí (např. https://kramerius.k7-test.mzk.cz/mzk/view/uuid:2b17ae14-6952-476a-9d0d-74e31aaf34 ) zatímco v K5 vrátí 404

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.5.0
https://k7.kramerius.org/view/uuid:2b17ae14-6952-476a-9d0d-74e31aaf34
