### ISSUE TITLE
Matomo analytics siteId nastavení

### ISSUE THREAD

**Issue by svetlikr** [ceskaexpedice/kramerius-web-client#671]
SiteId v případě použití Matomo je zapečeno natvrdo. https://github.com/ceskaexpedice/kramerius-web-client/blob/e5465ca3a2efce902d6ea3faec551be0f3963d18/src/app/app.component.ts#L73
Bylo by vhodné přidat možnost nastavení v `/assets/shared/globals.js` podobně jako je `APP_GLOBAL.matomo`.

**Comment by honza-rychtar** [comment]
Přidáno ve verzi 2.5.0
V konfiguraci přes `APP_GLOBAL.matomoSiteId`
Výchozí hodnota je 5 pro zachování předchozí funkcionality bez nutnosti měnit konfiguraci.

**Comment by zabak** [comment]
@honza-rychtar prosím o doplnění do wiki a zavření

**Comment by honza-rychtar** [comment]
@zabak doplněno https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta
