### ISSUE TITLE
Nesprávne zaradené číslo periodika s hodnotou v hranatej zátvorke

### ISSUE THREAD

**Issue by lgloncak** [ceskaexpedice/kramerius-web-client#674]
Nesprávne zaradené číslo s hodnotou v hranatej zátvorke
====================================================
- číslo 13, rok 1922 v titule Tatry nie je zaradené do poradia - predpokladám, že kvôli hranatej zátvorke:
https://dikda.snk.sk/periodical/uuid:d04e5c54-625d-4c49-b475-f271562c1f1d

![image](https://github.com/ceskaexpedice/kramerius-web-client/assets/126249299/60a36830-67c8-44eb-92cc-4bff8a00e501)

> _zápis v hranatých zátvorkách sa používa vtedy, keď informácia na výtlačku chýba, alebo je chybná, hodnota v hranatej zátvorke je fakticky oprava - korektná hodnota_

Dokážete implementovať pravidlo, podľa ktorého, keď bude prítomná **hranatá zátvorka**, bude sa brať do úvahy (pre účely triednia/radenia) len **hodnota, ktorá je v nej uložená?**

Ďakujem za odpoveď.

S pozdravom

Ľuboš Glončák

**Comment by rzeh4n** [comment]
Vyřešeno na úrovni jádra od Indexeru [verze 17](https://github.com/ceskaexpedice/kramerius/wiki/Vyhled%C3%A1vac%C3%AD-index#verze-17).
Takže řešením je přeindexovat, jakmile nasadíte některý nový build jádra.

**Comment by lgloncak** [comment]
Ďakujeme,

len taká drobnosť - otázka:

Daná implementácia rieši len izolovaný typ formátu **DD.MM.RRRR** alebo všetky možné prípady zápisu v hranatej zátvorke? 

Ak nie je, tak **pravidlo má byť také** ako bolo uvedené už vyššie: ak bude v zápise uvedená hranatá zátvorka, bude sa brať do úvahy (pre účely triednia/radenia) len **hodnota, ktorá je v nej uložená**, bez ohľadu na to, čo je v nej napísane - bez ohľadu na formát (mimo DD.MM.RRRR, môže byť aj MM.RRRR; DD.-DD.MM.RRRR; MM.-MM.RRRR; atď.) alebo existenciu ďalších hodnôt, ktoré sa v predmetnej hranatej zátvorke nenachádzajú (napr. DD.MM.RRRR[DD.MM.RRRR].

S pozdravom

Ľuboš Glončák

**Comment by rzeh4n** [comment]
@lgloncak 
Ano, doplnil jsem jen **[DD.MM.RRRR]**
Takže pro další zmiňované případy to fungovat vždy nemusí.

Některé formáty s hranatými závorkami už podporované jsou, ale jsou tam i jiné zápisy, třeba jen s jednou závorkou. Např.:
- 1920]
- 1920?]
- [ca 1690
- asi 1690]
- [18--?]
- 183-?]
- [1897 nebo 1898] 
-...

Je to dost dané existujícími daty. A je to kompromis mezi zaindexováním pro řazení a odhalením chyb v datech. Takto se kromě explicitně uvedených patternů ostatní věci neparsují a chybná data pak jdou poznat - jsou v řazení až na konci.

Rozširoval bych to proto dál, až uvidíme problém v datech. Protože vůbec bych se nedivil, kdyby se ukázalo, že namísto  `[MM.-MM.RRRR]` bývají úplně jiné zápisy, třeba `MM.-[MM].RRRR` nebo `MM.-MM.[RRRR]`

**Comment by lgloncak** [comment]
Ok, to je rozumný prístup.

V každom prípade môže poprosiť rozšíriť aspoň o nasledovné prípady:

[DD.-DD.MM.RRRR]
[MM.RRRR]
[MM.-MM.RRRR]
[RRRR]
[RRRR-RRRR]

DD.MM.RRRR[DD.MM.RRRR]
MM.RRRR[MM.RRRR]
RRRR[RRRR]

[DD.MM.RRRR]DD.MM.RRRR
[MM.RRRR]MM.RRRR
[RRRR]RRRR

**Comment by rzeh4n** [comment]
Ještě jsem to doplnil:

> [DD.-DD.MM.RRRR]
> [MM.RRRR]
> [MM.-MM.RRRR]
> 
Rozšířil jsem, bude fungovat od Indexeru verze 17.


> [RRRR]
> [RRRR-RRRR]
> 
Už fungovalo teď, minimálně od verze 15.


> DD.MM.RRRR[DD.MM.RRRR]
> MM.RRRR[MM.RRRR]
> RRRR[RRRR]
> 
> [DD.MM.RRRR]DD.MM.RRRR
> [MM.RRRR]MM.RRRR
> [RRRR]RRRR

Tady si nejsem jistý významem. Nechybí vám tam pomlčky?

**Comment by lgloncak** [comment]
Pozdravujem,

nie nechýbajú.

Ide o štandardizovaný zápis v prípade, že na výtlačku je uvedený nesprávny dátum. Vtedy sa zapíše nesprávny aj správny dátum natesno vedľa seba, pričom správny sa zapíše do hranatej zátvorky.

Inverznú verziu zápisu (keď sú hranaté zátvorky na prvom mieste) som dal len pre každý prípad, štandardne je zápis najskôr bez hranatej zátvorky a potom s ňou.

**Comment by honza-rychtar** [comment]
@lgloncak koukal jsem na vaše data a z celkem z celkového množství 407 060 výtisků obsahuje v datu vydání otevřenou hranatou závorku 238 výtisků. Z toho 137 jich má tu závorku na začátku a 101 uvnitř.
Všechny tyto případy obsahují i zavřenou hranatou závorku a to vždy na konci.

Pokud jde o formáty, tak z vašich případů se tam nikde nevyskytují
```
[DD.MM.RRRR]DD.MM.RRRR
[MM.RRRR]MM.RRRR
[RRRR]RRRR
```
A naopak se tam vyskytují případy, které neuvádíte
```
MM.-MM.RRRR[MM.-MM.RRRR]
DD.MM.-DD.MM.YYYY[DD.MM.-DD.MM.YYYY]
DD.-DD.MM.YYYY[DD.-DD.MM.YYYY]
```

Celkově těch výskytů je u vás minimálně a v případě českých knihoven se prakticky nevyskytují.
Podle [pravidel pro popis periodik](https://old.ndk.cz/standardy-digitalizace/copy_of_pppperio8.5_final_15_05_23.pdf) jsou formáty pro datum vydání následující

● DD.MM.RRRR - pokud známe den (např. 27.01.1998)
● MM.RRRR - pokud známe pouze měsíc (např. 01.1998)
● RRRR - pokud známe pouze rok (např. 1998)
● RRRR-RRRR – vydání pro více roků (např. 1998-1999)
● MM.-MM.RRRR - vydání pro více měsíců (např. 01.-02.1998)
● MM.RRRR-MM.RRRR – vydání pro více měsíců (např. 12.1998-01.1999)
● DD.MM.-DD.MM.RRRR - vydání pro více dní (např. 31.01.-01.02.1998)
● DD.MM.RRRR-DD.MM.RRRR – vydání pro více dní (např. 31.12.1998-01.01.1999)
● DD.-DD.MM.RRRR – vydání pro více dní (např. 02.-03.02.1998)

S dodatkem že
**Žádný z těchto údajů se nezapisuje do závorky**

Případy, které uvádíte, se týkají katalogizačních pravidel pro popisná metadata - ta se uplatňují u titulů ale ne nutně u výtisků, které v katalogu nejsou a vznikají při digitalizaci podle výše zmíněných pravidel.

Prosím taky o vyjádření @luckajirku @zabak @kerschfilip @vjirousek

@lgloncak pokud by to na vaší straně šlo, tak prosím o úpravu vašich pravidel, aby to bylo jednotné a nerozjíždělo se nám to.

V každém případě se budeme snažit přidat podporu pro co nejvíce formátu, protože správná interpretace je pak nutná pro řazení a filtrování.

**Comment by lgloncak** [comment]
@honza-rychtar: ďakujem za feedback.

ad 1:
v zásade každý z uvedených zavedených formátov (ktorý máte podľa pravidiel pre popis periodík) môže mať verziu s hranatou zátvorkou a to v 2 možných variáciách:
- 1 formát v hranatej zátvorke - záznam na výtlačku absentuje - nebol vytlačený, ale je odvoditeľný na základe predchádzajúceho / nasledujúceho výtlačku
- 2 formáty - prvý (štandardne) mimo zátvorky, druhý (štandardne) v zátvorke - mimo zátvorky (nesprávna informácia vytlačená na zdrojovom dokumente), v zátvorke (operátorom doplnená správna / korigovaná informácia)

ad 2:
viem, že som neuviedol všetky prípady, vzhľadom na to, že kolega @rzeh4n, navhrol pridávať pravidlá postupne a vychádzal som z predpokladu, že najčastnejšie sa predmetný "problémový" zápis vyskytuje pri formátoch dátumu: DD.MM.RRRR[DD.MM.RRRR], MM.RRRR[MM.RRRR], RRRR[RRRR]

ad 3:
rozumiem Vašej požiadavke na zjednotenie formátov podľa už existujúcich pravidiel. Podľa Vašich možností Vás chcem poprosiť o doplnenie predmetných formátov na základe spomínaného predpisu, ktorý toleruje existenciu hranatých zátvoriek. Ak predpokladám správne, tak nejde o narušenie pravidel stávajúceho zápisu, ale skôr jeho doplnenie / rozšírenie.

U nás predmetný "zátvorkový" zápis je určený dodržiavaním pravidiel definovaného predpisu (štandardu), ktorého výstupom je mimo záznamov v dmd sekcii METS-u aj vytvorenie MARC záznamu, ktorý sa následne vkladá do knižničného katalógu. Úprava záznamov bude znamenať potrebu dodatočných korekcií vo výstupných dátach.


V každom prípade, dajte mi prosím vedieť aké su možnosti, príp. Vaše finálne rozhodnutie, aby som v prípade zamietavého stanoviska, vedel oboznámiť kolegov a následne nastaviť príslušné korekčné mechanizmy.

Prajem všetko (aspoň) dobré a ďakujem.

**Comment by zabak** [comment]
@honza-rychtar změň tomuhle prosím stav, předpokládám, že to ještě není domluvené

**Comment by honza-rychtar** [comment]
@zabak ono se to netýká klienta. Přepsal jsem to sem https://github.com/ceskaexpedice/kramerius/issues/1045
Tady bych to zavřel.
