### ISSUE TITLE
Zobrazovat více ISSN

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-web-client#676]
Bylo by, prosím, možné v případech, kdy má časopis/noviny více ISSN, zobrazovat je v pravém panelu všechny? Máme v Krameriovi periodika, která v průběhu své existence nasbírala více ISSN (třeba protože přešla z tištěné formy jen na elektronickou), ale i když máme všechna zapsaná v metadatech, tak klient zobrazuje jen to, které je zapsané jako poslední.

Například: https://kramerius.lib.cas.cz/uuid/uuid:109a956b-0c99-499c-a2e3-443d82482448

Díky!

**Comment by honza-rychtar** [comment]
Přidáno ve verzi **2.5.0**

<img width="399" alt="Snímek obrazovky 2023-08-11 v 8 58 05" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/aae19845-8f52-4a2a-afa3-390c2b6f6b0d">

http://dk.kramerius.org/knav/periodical/uuid:109a956b-0c99-499c-a2e3-443d82482448

**Comment by kerschfilip** [comment]
Děkuju!
