### ISSUE TITLE
ve funkcni sdileni neni klikatko kopirovat

### ISSUE THREAD

**Issue by filipsir** [ceskaexpedice/kramerius-web-client#68]
clovek nevi zda ma zkopirovano nebo ne, prosim o moznost kliknuti na KOPIROVAT odkaz

**Comment by honza-rychtar** [comment]
Přidal jsem vedle odkazu tlačítko pro zkopírování do schránky. 

<img width="604" alt="screenshot 2018-10-09 09 58 29" src="https://user-images.githubusercontent.com/1178142/46654755-f8ddd800-cba9-11e8-8570-dde8640a3eb0.png">

Po kliku a úspěšném zkopírování se zobrazí notifikace, že byl odkaz zkopírován do schránky.
