### ISSUE TITLE
klient 2.5.0 - u  nepřístupných dokumentů se donekonečna točí kolečko

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#681]
Testováno mj. na http://dk.kramerius.org/mzk/view/uuid:ffbf2470-d9dd-11ed-b3f4-005056827e51?page=uuid:05c7ae4c-5c64-4745-9fe3-bd66fe77dd9d

<img width="794" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/811537/f5d1b193-12b7-487d-b156-a5723b3c21f5">

**Comment by honza-rychtar** [comment]
Chybí konfigurace krátkých textů pro licence - text, který říká, co po třeba udělat pro zobrazení dokumentu.
https://github.com/ceskaexpedice/kramerius-web-client/wiki/Konfigurace-licenc%C3%AD
```
dnnto: {
  ....
  instruction: {
    cs: '/assets/shared/licences/dnnto.instruction.cs.html',
    en: '/assets/shared/licences/dnnto.instruction.en.html',
  },
....
```

Teď je tam vlastně chyba, kdy se u chybějícího pole `instruction` v konfiguraci licence načítá špatná stránka, místo textu se zobrazí text Digitální knihovna Kramerius a točí se kolečko.
To jsem teď opravil, ale v tomto releasu tu chybu nechme - pole `instruction` je od této verze povinné - tímto je na toto chybějící pole alespoň víc upozorněno, než pokud by jen nebyl zobrazený ten text.

Na http://dk.kramerius.org/ jsem neměnil konfiguraci. Je tam spousta Krameriů se spoustou licencí a u všech by se musely vytvářet texty a upravovat konfigurace.
To uděláme později.

U této instalace jsou texty i konfigurace upraveny podle změn ve verzi 2.5.0
http://k7.kramerius.org/view/uuid:ffbf2470-d9dd-11ed-b3f4-005056827e51?page=uuid:05c7ae4c-5c64-4745-9fe3-bd66fe77dd9d

**Comment by zabak** [comment]
problém odstraněn, zavírám
