### ISSUE TITLE
Pridani noveho donatora pro Narodni muzeum do lokalizace a upload noveho obrazku

### ISSUE THREAD

**Issue by pkudela** [ceskaexpedice/kramerius-web-client#682]

**Comment by pkudela** [comment]
@honza-rychtar je to hotove.

**Comment by annie-cz** [comment]
Můžeme zavřít?

**Comment by zabak** [comment]
tohle by měl v obecné rovině řešit admin klient, viz https://github.com/ceskaexpedice/kramerius-admin-client/issues/12 , zde můžeme určitě zavřít.
