### ISSUE TITLE
Dlouhé názvy typů dokumentů se bijí se štítkem dostupnosti

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#684]
Všimla jsem si, že v FKBZ se bijí štítky na dokumentech ve výsledcích vyhledávání, viz:

https://kramerius.kfbz.cz/search

![image](https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/b2abfa12-7d6a-482a-bd5e-a20586a9c684)

Stejný problém je i u MZK (jak v K7, tak v K5)

https://www.digitalniknihovna.cz/mzk/search?doctypes=soundrecording
https://dnnt.mzk.cz/search?doctypes=soundrecording

![image](https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/fd8c3e2d-f2ce-43eb-bddc-2826d70a9157)

![image](https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/393d5e3c-9b96-49cf-8538-70f8618666e8)

Stejný problém bude mít do budoucna jakýkoliv dvouslovný název. Neplatí to aktuálně pouze u "noviny a časopisy", protože se takto zobrazuje pouze ve filtru, ale přímo na dokumentu je štítek "noviny".

Je možné, že tento problém je i u starších verzí klienta, ale nemám to aktuálně na čem ověřit. 

Za mě osobně byl systém zámečků, co byl v minulosti, lepší a přehlednější. Ale to jen tak off the record. :)

**Comment by zabak** [comment]
Zkrátit ten štítek na "Audio" nebo "Zvuk"? Nebo by se musela nadefinovat větší minimální šířka karet.  
PS. dnnt je už přesměrované na DK, takže už tam K5 nenajdeš, chytla jsi to na poslední chvíli.

**Comment by annie-cz** [comment]
To by asi šlo, akorát se to pak bude lišit od těch filtrů a to je trošku zvláštní (podobně jako u těch novin a časopisů). Co spíš dát ten název nad sebe, tj. místo:

zvukové nahrávky

zvukové
nahrávky

... ?

O DNNT a K5 vím, že s tím končíte, ale jde o verzi klienta a knihoven, kteří jedou zároveň na novém klientovi. Jestli je to nad K5 nebo K7 může, ale taky nemusí mít souvislosti a je dobrý myslet stále na obojí. K5 u jiných knihoven zdaleka ještě nekončí, ne všichni jsou na přechod na K7 připravení.

**Comment by annie-cz** [comment]
@zabak ten problém je stále i u MZK, nejen u Zlína, takže K5kou z minulosti to nebude ... 

<img width="946" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/380ffbed-e3ca-41a7-8dc6-a3050b7a50d8">

**Comment by honza-rychtar** [comment]
Tá šířka karet je ještě závislá na šířce prohlížeče.
Na mém 14" macBooku se to zrovna dostane na limit, že se ještě vlezou 4 sloupce, ale karty už jsou dost malé, že se nevejdou ani **Periodikum** v kombinaci s **Po přihlášení**

<img width="760" alt="Snímek obrazovky 2024-02-08 v 15 09 43" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/603566f9-16ca-4307-b40a-194910e0885b">

Tohle jsou ty věci, které vypadají pěkně ve statickém návrhu ve Figmě, ale v realitě je to peklo. 

Obecně jsem pro výrazný redesign těch karet. Teď bychom mohli alespoň předefinovat ty zlomy. Takže ten můj screen by byl na 3 sloupce a ten od @annie-cz na 2 sloupce, což je ale zase strašné mrhání místem, protože to pro zbytek obsahu (a toho hlavního obsahu) není vůbec potřeba.

**Comment by zabak** [comment]
Jo, to už spíš si říká o přidání jednoho řádku do karty - dát ty dva údaje nad sebe, nebo na jeden řádek ale přes celou kartu, tj i pod thumbnail.

**Comment by annie-cz** [comment]
A nebo se teoreticky vrátit k původnímu konceptu ikonek, protože tam tohle fungovalo dost dobře a vizálně se to (dle mého názoru) tolik nepralo. Teď je tam strašně moc krátkých textíků a vizuálně se blbě rozlišuje, do čeho se člověk dostane a do čeho ne. Teď to vypadá spíš jako takový velký lákadlo a pak přijde zklamání, když to člověk rozklikne moc rychle.

**Comment by honza-rychtar** [comment]
Jo no. Vrátit zámek přes náhled - jen pokud nemá uživatel přístup - buď ikonu domečku, nebo klíče.
Pokud přístup má, tak tam nedávat nic a nijak nerozlišovat.

**Comment by zabak** [comment]
Vzhledem k tomu, že ty ikony jsou i ve fasetách, tak v tom nevidím problém. Jen ty texty musí být v tooltipu, i kvůli screen readerům.

**Comment by honza-rychtar** [comment]
Karty jsou teď trochu kompaktnější, takže se většina kombinací teď vleze

Periodikum, Po přihlášení
Před:
<img width="1211" alt="Snímek obrazovky 2024-12-09 v 17 49 41" src="https://github.com/user-attachments/assets/c9e68087-a1f5-4546-94bb-37b07b5845f9">
Po:
<img width="1211" alt="Snímek obrazovky 2024-12-09 v 17 49 56" src="https://github.com/user-attachments/assets/3f7e32e4-f071-4926-82e5-a50fdf320a4f">

Zvukové nahrávky, Veřejné
Před:
<img width="1209" alt="Snímek obrazovky 2024-12-09 v 17 50 56" src="https://github.com/user-attachments/assets/3f3558fb-e2c8-408c-9393-8b0835255f35">
Po:
<img width="1209" alt="Snímek obrazovky 2024-12-09 v 17 51 22" src="https://github.com/user-attachments/assets/cb6924c9-10a1-4976-9092-f59e69a3c458">

Pokud se tam nějaká kombinace nevleze, pak se typ dokument usekne a přidají tři tečky
Zvukové nahrávky, V knihovně
Před:
<img width="1208" alt="Snímek obrazovky 2024-12-09 v 17 52 31" src="https://github.com/user-attachments/assets/1e86afd8-54bb-4b36-a25e-e46fd75baa48">
Po:
<img width="1208" alt="Snímek obrazovky 2024-12-09 v 17 52 54" src="https://github.com/user-attachments/assets/0d408703-d29f-41a4-a002-5e71d5fbd32b">

**Comment by kerschfilip** [comment]
> Pokud se tam nějaká kombinace nevleze, pak se typ dokument usekne a přidají tři tečky

@honza-rychtar bylo by prosím možné tohle udělat i pro karty v kurátorských seznamech? My nechceme/nemůžeme používat ty seznamy s většími obrázky, protože se nám kvůli malým náhledům rozmažou, ale na těch menších kartách se popisky právě překrývají: 
![obrazek](https://github.com/user-attachments/assets/e1de0c15-fed2-43af-beb2-587216372cd7)

**Comment by honza-rychtar** [comment]
Je to stejná komponenta, takže se to upraví automaticky taky.

<img width="1322" alt="Snímek obrazovky 2024-12-10 v 15 47 22" src="https://github.com/user-attachments/assets/ce4e6731-c5cc-4cae-a130-e43cd7fb1c37">
