### ISSUE TITLE
Přejmenovat Twitter na X, změnit ikonu

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#688]
ve sdílení přejmenovat Twitter na X, [změnit ikonu na X](https://about.twitter.com/en/who-we-are/brand-toolkit)

**Comment by annie-cz** [comment]
Toto je vyřešeno v 2.6.0., @zabak jediné místo, kde stará ikonka ještě visí, je u vás dole na rozcestníku.

**Comment by zabak** [comment]
OK, to si dořešíme, zde zavírám

**Comment by zabak** [comment]
Váhal jsem jestli to otevírat když se to obecně řeší v #496, ale raději to udělám. Ta hlavička rozcestníku je natvrdo v kódu, nemůžeme to sami změnit.

**Comment by honza-rychtar** [comment]
@zabak ty ikony ale součástí distribuce nejsou. Je to v té **shared** složce.
Tady je odkaz na ikonu, která velikostně a barevně sedí s ostatníma 
https://www.dropbox.com/scl/fi/29scwyg3uzp17noov46b1/footer_twitter.png?rlkey=88yzbp98xuz7nj4x2h7gdlhl0&dl=0
tímto nahraďte stávající
/assets/shared/sp/footer_twitter.png

Název souboru neměňte.

**Comment by zabak** [comment]
@honza-rychtar díky, ikonu jsme si opravili, ale vytáhnout tu patičku ven bude potřeba.
