### ISSUE TITLE
sdileni na konretni stranky nefunguje

### ISSUE THREAD

**Issue by filipsir** [ceskaexpedice/kramerius-web-client#69]
jak je to s moznosti sdileni? nechapeme logiku jak funguje. vypada to ze je to pouze na jedno persistentni url - nicmene u stareho K5 slo sdilet pouze jednu stranku. Nefunguje to tak.

prosim o moznost sdileni po strance, po cisle, rocniku, titulu - tedy pokazde jina persistentni url adresa

**Comment by filak** [comment]
Mně se tedy zdá, že to pro konkrétní stránku funguje, např. https://dev.medvik.cz/wck/view/uuid:MED00149086-da23af57-b12a-4a4e-bd42-3a43baa8fe69?page=uuid:84cfa5be-b5fd-4ccc-b447-4c24a9438954
