### ISSUE TITLE
Možnost lokalizace title a subtitle u Krameria

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#690]
<img width="1261" alt="Snímek obrazovky 2023-11-08 v 10 08 06" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/f6745f39-b548-4618-9406-0c31512e7809">

**Comment by pavluska** [comment]
opraveno
https://github.com/ceskaexpedice/kramerius-web-client/commit/962dce59dd61f6a41b0fcbe345f6f828331119a2

**Comment by zabak** [comment]
funguje, zavírám
