### ISSUE TITLE
Příslušnost dokumentu ve sbírkách v panelu s metadaty - bug

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius-web-client#691]
Ahoj, 
"Příslušnost dokumentu ve sbírkách v panelu s metadaty" sa momentálne nespráva konzistentne. Na dokumentoch vyššej úrovne sa táto informácia nezobrazuje.
[V náhľade konvolutu](https://www.digitalniknihovna.cz/mzk/periodical/uuid:d13a076f-a07e-42f9-bd4b-e6744fff265d) sa informácie o zaradení do zbierky nezobrazia, ale [vnútri v dokumente](https://www.digitalniknihovna.cz/mzk/view/uuid:d13a076f-a07e-42f9-bd4b-e6744fff265d?page=uuid:b7d16c18-0bd7-48fd-a4ac-52eadafa9345) už áno. 
Rovnako je to aj pri periodikách, kde sa táto informácia zobrazí len v [čísle](https://www.digitalniknihovna.cz/mzk/view/uuid:431bda50-c281-11ea-b03f-5ef3fc9bb22f?page=uuid:d0846f34-7bee-41c3-8e09-6c14a8b58519), ale nezobrazí sa v [ročníku](https://www.digitalniknihovna.cz/mzk/periodical/uuid:217b54a0-c27e-11ea-b03f-5ef3fc9bb22f) a v [periodiku](https://www.digitalniknihovna.cz/mzk/periodical/uuid:19b2fd90-c27e-11ea-9a89-005056825209).
A aj pri zväzkoch monografií, v [monografií](https://www.digitalniknihovna.cz/mzk/view/uuid:318a8340-7ebd-11e8-87bd-005056827e52?page=uuid:d47c6d50-9ac1-11e8-8b19-005056825209) sa zobrazí ale vo [zväzku](https://www.digitalniknihovna.cz/mzk/periodical/uuid:62525e70-942b-11e8-be68-5ef3fc9bb22f) už nie.
Ďakujem,

Róbert Randiak, MZK - OSDD

**Comment by annie-cz** [comment]
Otestováno, vypadá to v pořádku. Prosím však @r2it-git o kontrolu.

**Comment by r2it-git** [comment]
Jop, funguje.
