### ISSUE TITLE
ČDK a popisky zdrojových knihoven. 

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius-web-client#695]
Potřeboval bych vyřešit následující issue:  https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/52.  Bylo by možné, aby klient popisky automaticky přebíral z registru krameriů ?

**Comment by zabak** [comment]
Bylo by možné aby měly ty knihovny anglickou verzi svého názvu?

**Comment by honza-rychtar** [comment]
@zabak Ano, je to právě v těch lokalizačních souborech, takže mohou mít verzi pro každý jazyk.

**Comment by honza-rychtar** [comment]
@pavluska Doplň prosím do https://github.com/ceskaexpedice/kramerius-web-client/blob/140e9eee603e2dc4a71bdfb4bc6ff16dd42a43fe/src/assets/i18n/cs.json#L785
další zdroje, hlavně nkp. A taky doplň další jayzkové mutace. V cs a sk nech češtinu, do zbytku angličtinu.

**Comment by annie-cz** [comment]
Doplněno do verze 2.7.0. @pavel-stastny, koukni na to prosím.
