### ISSUE TITLE
V K7 nefunguje "našeptávač"

### ISSUE THREAD

**Issue by AlesBrozek** [ceskaexpedice/kramerius-web-client#698]
V K7 nefunguje "našeptávač" (nebo není zapnutý?). Přikládám printscreen obrazovky z prohledávání slov ve stejném čísle Čtenáře v DK NK (K5) a DK MZK (K7) - problém je vidět v levém horním rohu v panelu s lupičkou
![Snímek obrazovky 2024-01-12 v 16 07 48](https://github.com/ceskaexpedice/kramerius-web-client/assets/141346237/f761defb-68e8-4375-bfc5-38abfabc9bb6)
![Snímek obrazovky 2024-01-12 v 16 11 03](https://github.com/ceskaexpedice/kramerius-web-client/assets/141346237/d62fddf0-4ae1-4137-a3bd-676dae94dbc0)

**Comment by zabak** [comment]
@honza-rychtar tohle je problém klienta nebo api?

**Comment by honza-rychtar** [comment]
Klientem to není. V rámci klienta digitalniknihovna.cz to nefunguje pro MZK (K7), ale funguje pro KNAV (K5) i pro SVK PK (K7).
Tam kde to nefunguje Solr nevrací ty fragmenty s nalezeným textem.
U K7 to funguje u SVK PK a CVTI, kde je starší verze K7 a tedy i indexeru.
Ale naše testovací verze Krameria má novou verzi K7 i Indexeru a našeptávání funguje, takže podezřívám přímo verzi Solru.
Prověřím verze Solru u různých instalací a dám vědět.

Na druhou stranu, dotaz na samotné zobrazení fulltextu funguje na podobném principu a ten se zobrazuje. Takže to možná půjde vyřešit jen úpravou dotazu v klientovi tak, aby fungoval napříč verzemi.

Tohle bude souviset i s #699

**Comment by AlesBrozek** [comment]
Doufám, že věta "Takže to možná půjde vyřešit jen úpravou dotazu v klientovi tak, aby fungoval napříč verzemi" neznamená, že uživatel má upravovat dotaz tak, aby zadával jen smysluplná  slova. Všimněte si, že našeptávač u NDK (K5) nabídl i slovo "knihov", protože v textu je slovo knihovníkem na konci řádku a rozděleno na "knihov-níkem". Pokud výraz knihovníkem nenapíši v uvozovkách a s rozdělovníkem, nenajde ho. Podobně se využívá našeptávač, aby mi prozradil chybné OCR v textu a já hledaný výraz napíši podle té chyby v OCR...

**Comment by honza-rychtar** [comment]
@AlesBrozek ne ne, tohle se týká klientské aplikace, pro uživatelé se nic nezmění.

**Comment by annie-cz** [comment]
Bude se to týkat nejspíš nějakých novějších verzích. Protože např. v Plzni K7 mají, aktuálně používají verzi klienta v2.4.7 a tam to funguje správně.

![image](https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/45ac7e04-a749-4c83-85c0-3099893624fb)

**Comment by honza-rychtar** [comment]
Tohle je způsobeno novou verzí Solru. Není to závislé na verzi Krameria, indexeru, ani klienta.
Mělo by to jít spravit i na straně klienta.

**Comment by annie-cz** [comment]
Našeptávač opět funguje, opraveno v rámci v 2.9.0 @AlesBrozek. Můžeme zavřít?

![image](https://github.com/user-attachments/assets/86475099-2750-4160-bca0-aec65121f11c)
