### ISSUE TITLE
Vyhledávání

### ISSUE THREAD

**Issue by BrozekAles** [ceskaexpedice/kramerius-web-client#7]
Zdá se, že vyhledává jen výrazy v názvu dokumentu a ne v textu dokumentu. Nenašel jsem ani možnost hledat v textu periodik. Např. slovo Archipenko se najde v časopise Host. Takže dotaz Archipenko v K5 vede k výsledku stránky: 60/381, zatímco v K6 k hlášce  Upozornění Nebyly nalezeny žádné výsledky. Prosím, zkuste jiný dotaz

**Comment by krizovj** [comment]
Souhlasím, taky mi to nefunguje

**Comment by honza-rychtar** [comment]
Fulltextove vyhledavani jeste neni hotove. Bude pridano behem tohoto mesice.

**Comment by BrozekAles** [comment]
Mám pocit, že fulltextové vyhledávání dosud nebylo přidáno a 20.2. bychom měli klienta hodnotit...

**Comment by pavelkocourek** [comment]
dobré dopoledne, do 20tého je plánováno vydání ... na vývojovém serveru se postupně  přidávají změny.

**Comment by honza-rychtar** [comment]
Doplneno

**Comment by BrozekAles** [comment]
No ještě bych to nechtěl uzavírat. Ve veřejně přístupné publikaci Průvodce hudební a divadelní  je na s. 57 pro mne důležitý údaj o výrobci praporů Trenkwaldovi: "Prápory zpěv. spolků zhotovuje: Jan Tippmann v Ovocné u. 766—П. a H. Trenkvald ve Ferdinan- dově tř. 118—II"
Pokud dám hledat v celé bázi: prápory zhotovuje, nalezne to 13 veřejných dokumentů (nenajde to však onu publikaci Průvodce hudební a divadelní), v nichž je na jedné straně dokumentu současně slovo prapor v různých pádech a výraz zhotovovat, ale nic se netýká zhotovování praporů!
Pokud hledám přímo v publikaci Průvodce hudební a divadelní slovo prápory – najde s. 5, 6, 12 a 43, ale ne s. 57. Proč nenajde tu s. 57?

**Comment by honza-rychtar** [comment]
@BrozekAles Fulltextove hledani jsem dodelal dneska. Problemy tykajici se hledani bych pak resil v samostatnych issues.
Nicmene, hledani ted neni ani otazkou klienta, ale verzi solru v MZK. Jednak je tam chyba ve schematu, ktera vede k "podivnostem" a taky v te verzi probehla zmena, ktera se bude zase odstranovat. MZK prave pracuje na upgradu Krameria, solru, schematu a reindexaci.
