### ISSUE TITLE
funkce DOMU

### ISSUE THREAD

**Issue by filipsir** [ceskaexpedice/kramerius-web-client#70]
chapeme, ze lze kliknout na LOGO instituce a dostaneme na uvodni stranku, nicmene toto nebude chapat uzivatel - prosime o ikonku DOMECKU vedle loga, ktera by hodila uzivatele NE na uvodni obrazovku, ale na vyhledavaci (tu obrazovku ktera je po VSTUPTE)

**Comment by honza-rychtar** [comment]
@filipsir Proc si myslis, ze to nebude uzivatel chapat? Logo/nazev sluzby umisteny vlevo nahore fungujici jako link na domovskou stranku je uz standard. Uzivatele to ocekavaji.

I tady na GitHubu se na homepage dostanu (pouze) pres logo vlevo nahore. 

A pokud pripustime sekundarni prvek pro navigaci ikonou **DOMECKU**, tak proc by ikona **DOMU** nemela vest na homepage, tj. **DOMU**, ale na uplne jinou stranku? Na vyhledavaci obrazovku vede ikona lupy ve vyhledavacim poli.

**Comment by filipsir** [comment]
Protoze ja neuvazuji jako ty :) ale uvazujeme s lidma (cca 10) kteri kramerius pouzivaji, znaji uzivatele kteri kramerius pouzivaji a jasne se vyjadrili, ze nikdo z nich nebude mit tucha ze ma kliknout na ikonku loga instituce. V kombinaci s nulovou napovedou je to proste spatny. 

Je jedno kam to pujde. To uz je vec pohledu. Zda do vyhledavaciho po vstupu nebo na uplne uvodni obrazovku. To by si teoreticky mel kazdy nastavit dle sebe

Takze otazka je, zda to zustane tak jak je nebo ne.

**Comment by honza-rychtar** [comment]
Ja to nenavrhuju podle toho, jak uvazuju pri pouzivani webu ja, ale podle obecnych UI/UX pravidel.
Jsou prakticky 2 zpusoby. Bud se jde na homepage jen pres logo/nazev nebo pres logo/nazev + dalsi link - ikona domecku nebo text domu/domovska stranka/hlavni stranka (takto to ma napr. Facebook).

Takze ok, muzeme pridat tu ikonu domecku, ale at vede na homepage, nikam jinam. A at to ve vsech klientech a vsech instalaci klienta vede na stejnou stranku - homepage! 
Sice si stale spousta uzivatelu mysli, ze existuje jen jeden Kramerius (Praha/Brno/Olomouc), ale jinak pouzivaji vice Krameriu - a hlavne pouzivaji vice webu, a ikona domecku vede vzdy domu.

No a abychom to meli podlozene velkym vzorkem uzivatelu, tak jsem do Digitalni knihovny pridal sledovani kliku na "Digitalni knihovna" (ktery vede na hlavni stranku). 
Za 14 dni pridam i ikonu domecku a tu budu taky sledovat. Za mesic pak budeme mit realna data o tom, jak se pouziva odkazovani na homepage pres nazev sluzby a jak to ovlivni pridani ikonu domecku - co se bude pouzivat vic a hlavne o kolik bude vyssi soucet kliku na nazev + ikonu oproti puvodnimu poctu kliknuti pouze na nazev.

Takze odpoved je: ano, muzeme pridat ikonu domecku, ale at je ve vsech instalacich a at vede vzdy na domonskou stranku.
 
@pkudela Zakomponuj ji tam nekam prosim :)

**Comment by pkudela** [comment]
Ahoj a dobry den. Celkovy vzhled aplikace byl schvalen a takto byl i realizovan. Naprosto souhlasim s Honzou, co se tyce vyznamu a funkcionality home odkazu/ikony + odkazu z loga/nazvu na home page. Pokud by jsme se rozhodli nekam tento podpurny odkaz na home page umistit, tak rozhodne ne vedle loga, coz by suplovalo ten samy ucel, navic by to rozhodilo layout prvku v navigacni liste vcetne responsivniho chovani. Odkaz na home page vcetne ikony, pokud tomu tak bude, by se mel nachazet v hlavni navigaci vpravo. Nicmene toto musi byt schvaleno vyvojovou skupinou.

**Comment by filipsir** [comment]
Zdravim. Je uplne jedno kde to bude. Ale at to tam je ;) neni treba salodlouhe vysvetleni, chapu ze to tak bylo odsouhlaseno a respektuji to, je pisi ze to ve spojeni se vsim ostatnim co chybi to proste neni plne funkcni. 

Takze budu rad za ikonku kamkoliv vy uznate ze je to nejlepsi. 

Diky moc. Predavam info do Narodniho muzea

**Comment by pavelkocourek** [comment]
Chceš-li Filipe změnu v rozhranní, musíš přes vývojovou skupinu. 
Ale můžeš si dokreslit domeček do img loga ;)

**Comment by filipsir** [comment]
Ja myslim ze je vyreseno viz odpoved @honza-rychtar
