### ISSUE TITLE
Přidat tooltip k přepnutí Krameria ve vyhleávání

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#700]
K tomu zobáčku dát lokalizovaný tooltip **Vyhledat v jiné knihovně**

<img width="860" alt="Snímek obrazovky 2024-01-16 v 15 41 51" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/784582cc-e784-424c-b3dd-b20d304cf94c">

**Comment by honza-rychtar** [comment]
Hotovo ve verzi 2.7.1
http://dk.kramerius.org/mzk/search

**Comment by zabak** [comment]
Proč vlastně ten zobáček není vedle loga knihovny?

**Comment by honza-rychtar** [comment]
Teoreticky by to šlo, ale pak by to evokovalo, že celé logo je dropdown pro změnu. Ale ono se to chová jako home button. Pokud by to v hledání bylo dropdown celé, pak by se to chovalo na každé obrazovce jinak. Pokud by to na všech obrazovkách bylo dropdown pro změnu knihovny, pak bychom ztratili home button.
Navíc by se ty názvy musely zkrátit, protože třeba s NK už se tam zobáček nevejde.

Takže je to teď vlastně funkce specifická pouze pro vyhledávací obrazovku podle toho je to i umístěné.

**Comment by zabak** [comment]
OK, zavírám
