### ISSUE TITLE
Stažení uživatelského seznamu jako CSV

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#703]

**Comment by annie-cz** [comment]
Otestováno. Chová se, jak má.

**Comment by annie-cz** [comment]
Popsáno na WIki.

https://github.com/ceskaexpedice/kramerius-web-client/wiki/U%C5%BEivatelsk%C3%A9-seznamy#sta%C5%BEen%C3%AD-csv

![image](https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/c9760469-5599-4af4-9a2b-e4384ed01e3f)

![image](https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/cd18a0cc-ee1c-485a-aaa0-b8b203ec81b1)
