### ISSUE TITLE
Přepracovaný systém výběru oblasti

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#704]

**Comment by annie-cz** [comment]
Otestováno, funguje.

**Comment by annie-cz** [comment]
Výběr oblasti se nyní nově zobrazuje po najetí kurzoru myši na tlačítko s hvězdičkami vpravo přímo ve skenu. Po přejetí kurzoru myši přes tlačítko se automaticky rozbalí nabídka, která navede uživatele k výběru oblasti a dalším akcím, konkrétně vytvoření výstřižku, jeho sdílení nebo využití AI nástrojů (zatím v testovacím režimu).

<img width="946" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/c5614b10-527e-4643-86e6-a81115d8081d">


Bez vybrané oblasti se zvolené akce na tlačítcích budou vždy vztahovat na celou stranu dokumentu, po výběru oblasti je možné zvolit pro vybranou akci jen konkrétní část.

<img width="941" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/d0b7867d-65da-4b9b-9002-dc6d3fee429d">

<img width="946" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/0d6dd40d-2421-420c-9d2d-47856320dc8f">

<img width="946" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/09e6a1bc-7c95-4c17-9a49-2fb975b0d299">

Pro využívání AI funkcí je třeba být přihlášen. Nepřihlášený uživatel má k dispozici pouze sdílení výstřižku, stažení jpegu výstřižku a textový přepis vybrané oblasti.

<img width="960" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/914af36d-003c-4890-9bea-7088b8273cd6">

**Comment by zabak** [comment]
Zavírám, připomínky budeme dávat do nových issue
