### ISSUE TITLE
Výstřižky ve sbírkách

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#705]

**Comment by annie-cz** [comment]
Ze strany klienta otestováno, funguje. Aktuálně lze přidat jakýkoliv výstřižek (výřez obrázku) z Krameria do sbírky, ale i zvenčí. Bylo by dobré, aby to někdo v knihovnách ještě otestoval a vyjádřil se k tomu.

**Comment by zabak** [comment]
> Aktuálně lze přidat jakýkoliv výstřižek (výřez obrázku) z Krameria do sbírky, ale i zvenčí. Bylo by dobré, aby to někdo v knihovnách ještě otestoval a vyjádřil se k tomu.

Zadává to admin, takže by měl vědět co dělá. Bylo by samozřejmě dobře, aby vložení chybného (nefunkčního nebo jakkoli rozbitého nebo vracejícího jinou věc než obrázek) linku to nerozbilo Krameria.

**Comment by honza-rychtar** [comment]
@zabak @annie-cz @pavel-stastny tak udělejme kompromis, že se primárně předpokládá, že výstřižek je opravdu sdílený výběr oblasti v cílovém Krameriovi. Admin klient bude teda hlídat formát url, aby byl
`<KRAMERIUS_KLIENT>/uuid/<UUID>?bb=<X>,<Y>,<WIDTH>,<HEIGHT>`

Pokud zadané url nebude mít tento formát, tak admin klient vyhodí varovný dialog s infem o pokusu vložit nepodporované url, kde si uživatel ale může zvolit **Přesto uložit**.
Takto by se hlídalo nechtěné vkládání jiného url a zároveň by zůstala možnost vytvářet i jiné odkazy.

**Comment by zabak** [comment]
Předpokládám, že to mělo být spíš KRAMERIUS_API, nikoli KRAMERIUS_KLIENT. Budeme v okamžiku vlkládání testovat existenci daného uuid nebo obecně to, že dané url vrací obrázek (zvlášť u externích odkazů? Aby klient ustál to, že se mu místo obrázku nečekaně vrátí třeba html.

**Comment by honza-rychtar** [comment]
Je to odkaz generovaný v klientovi a směřující zpět do klienta, takže ne API.
Klient dělá taky kontrolu url a pokud má správný tvar, tak vygeneruje náhled přes IIIF Image API. Pokud nemá ten tvar, tak prostě nezobrazí nic.

**Comment by pavel-stastny** [comment]
@honza-rychtar Ok. Přidáme varovný dialog.

**Comment by zabak** [comment]
@annie-cz mohla bys ten návod přenést i na vhodné místo do wiki?

**Comment by annie-cz** [comment]
@zabak https://github.com/ceskaexpedice/kramerius-web-client/wiki/V%C3%BDst%C5%99i%C5%BEky zde ;)

**Comment by zabak** [comment]
Perfektní!
