### ISSUE TITLE
Hledání v uživatelských seznamech

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#706]

**Comment by annie-cz** [comment]
Otestováno, funkcionalita v pořádku, vyhledávání je pohodlné a srozumitelné. Bude třeba jen zkontrolovat chování jiných dokumentů než monografií.

**Comment by zabak** [comment]
Neprohledává ani metadata ze sbírek obsažených v seznamu ani fulltext z čísel periodik.

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.7.1

Možno vyzkoušet tady
http://dk.kramerius.org

**Comment by zabak** [comment]
funguje, zavírám
