### ISSUE TITLE
chybi NAPOVEDA

### ISSUE THREAD

**Issue by filipsir** [ceskaexpedice/kramerius-web-client#71]
neni nikde mozne se dostat jak k ceskemu, tak k anglickemu textu napovedy. prosime na uvodni stranku

prosime stranku s moznosti editace ala- http://kramerius.nm.cz/search/help/cs.jsp

**Comment by zabak** [comment]
Nápověda by měla být jednotná (součástí distribuce) tam, kde popisuje chování klienta. Jedině tak zůstane aktuální při přechodu na nové verze. Každý klient by měl mít tuto nápovědu vlastní, protože vypadá a chová se trochu jinak. Mimo to, by měla být specifická informace popisující obsah digitální knihovny, ta by ale zase měla být napsaná tak, aby mohla být použita v libovolném klientovi.

**Comment by JanMeritus** [comment]
Reakcie od nas: 

> Rozhraní K6 je uživatelsky velmi přívětivé a intuitivní, ale uživatelé by měli mít k dispozici alespoň stručnou nápovědu pro práci se systémem.

> Nicméně nějaká textová rychlá nápověda v klientovi jako základ chybí.

V akom je to ted stave?

**Comment by annie-cz** [comment]
V MZK máme k dispozici tento "obecný návod" i se screeny, ještě obecnější nebo kratší variantu nemáme. Pokud by se líbil, lze použít.

Viz https://docs.google.com/document/d/13EIE-Qv4a_flKOSP2508xgtfM4y577-qaSFVXUSAl1g/edit?usp=sharing

**Comment by JanMeritus** [comment]
@honza-rychtar @filipsir neviem, ci nepritomnost "pevnej" napovedy nevnimat skor ako bug, nez navrh na rozsirenie. Navrhom na rozsirenie by mala byt pripadne editovatelna napoveda a  #103

**Comment by tumovam** [comment]
@honza-rychtar jak to prosím vypadá s tímto issue? Nějak to usnulo... Nemohla by se Nápověda přidat do klienta vpravo nahoru vedle: 
![obrazek](https://user-images.githubusercontent.com/31240271/116524121-4db3dc00-a8d7-11eb-9d52-9f595649a63a.png) ?
Jménem KNAV děkuji za odpověď :)

**Comment by honza-rychtar** [comment]
@tumovam V konfiguraci klienta se dá nastavit kromě stránky Informace i stránka FAQ
https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta#str%C3%A1nka-s-faq

Můžeme přidat i přímo Nápovědu, aby se to nemuselo jmenovat FAQ.
Jako obsah té stránky pak můžete použít třeba to, co má MZK tady http://www.digitalniknihovna.cz/help

**Comment by zabak** [comment]
Zavírám, v případě potřeby je možné znovu otevřít.
