### ISSUE TITLE
jedna uvozovka v dotazu na solr

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#710]
Přehazuju sem kus diskuse ze slacku. Prosím o kontrolu, jestli není někde v klientovi zatoulaná uvozovka navíc:

Vladimir Lahoda
...  
a druhy problem, ze v dotazu na SOLR se v fulltext query objevil neplatny znak, konkretne jedna uvozovka

http://solr.k7-solr.svc.cluster.local:8983/solr/search/select?q=pid%3A%22uuid%3Ae41600d0-4dcb-11dd-9df0-000d606f5dc6&q"=&rows=1&hl.fragsize=20&wt=json

na pozici 118, v parametru q: [&q](http://solr.k7-solr.svc.cluster.local:8983/solr/search/select?q=pid%3A%22uuid%3Ae41600d0-4dcb-11dd-9df0-000d606f5dc6&q)"=&rows=1

thread_ts=1706716523.789419&cid=G01E22QV92M)
to je asi na @honza-rychtar

**Comment by honza-rychtar** [comment]
Tohle klient negeneruje.
