### ISSUE TITLE
Přesun (částí) konfigurace klienta do jádra

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#711]
Vytvářím toto issue jako sběrné pro všechna ostatní issues kde vznikla potřeba přenést nějakou část konfigurace do jádra.

**Comment by annie-cz** [comment]
Z požadavků NPO (7k, nové funkce administrace v prostředí uživatelského klienta):

- customizace obrázků, log, názvů, textů, faset, hlášek, vyskakovacích oken apod. + možnost vkládat html tagy do jsonu - souvisí s #707
