### ISSUE TITLE
Funkce "Otočit doprava" nefunguje

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius-web-client#712]
Ahoj,
po prechode na 2.7.0 z v2.6.2 nefunguje funkcia "Otočit doprava", ktorá by mala otáčať image o 90° doprava.
Predpokladám, že to súvisí s implementáciou #704 .

Róbert, MZK

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 2.7.1
http://dk.kramerius.org/mzk/search

**Comment by r2it-git** [comment]
Funguje, zatváram.
