### ISSUE TITLE
Pokud je popis sbírky příliš dlouhý, text se bije se štítkem sbírka

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-web-client#714]
<img width="245" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/51bf9a78-9c9e-4d84-8b0a-3e5b7c723280">

(platí pro zobrazení jak na pc, tak na mobilu)

**Comment by annie-cz** [comment]
Podobný problém je i u seznamů.

<img width="253" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/8e2b05d5-8726-4178-a1a9-dd965a0e6a95">

Souvisí částečně asi i s #684

**Comment by honza-rychtar** [comment]
První problém se vyřešil omezením popisku sbírky na 3 řádky. Druhý problém řešený tady #684
