### ISSUE TITLE
AI funkce - motivovat k přihlášení

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#717]
Rozšíření #704 - pokud Kramerius podporuje AI funkce, měl by tuto nabídku zobrazit i nepřihlášeným uživatelům - například tak, že ta tlačítka tam budou, ale nepřihlášeného uživatele navedou na přihlášení.

**Comment by honza-rychtar** [comment]
Ano, a to samé se srdíčkem pro přidávání do seznamu.

**Comment by honza-rychtar** [comment]
Přidáno ve verzi 2.7.2
Možno vyzkoušet zde http://dk.kramerius.org/mzk
Pokud jsou v klientovi u Krameria povoleny AI akce, tak se zobrazí i nepřihlášenému uživateli. Po kliku na akci se mu pak zobrazí vysvětlující dialog s možnosti přihlásit se.


<img width="818" alt="Snímek obrazovky 2024-03-25 v 17 23 18" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/1b12be4c-d3b3-4f1a-9c7c-af6fbde3b3b4">   

---

<img width="778" alt="Snímek obrazovky 2024-03-25 v 17 23 38" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/7dede929-7f7f-4e53-ac07-a32cefcb7c5c">

**Comment by zabak** [comment]
funguje, zavírám
