### ISSUE TITLE
kolize cookie lišty a ovládacích prvků výstřižku

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#720]
Když jsem chtěl otestoval link http://dk.kramerius.org/t/collection/uuid:8c95c934-8c00-4f98-9b06-28fc2677d01e a šel na první výstřižek ( inzerát Kartáče ), tak se mi ovládací prvky překryly s cookie lištou:

![image](https://github.com/ceskaexpedice/kramerius-web-client/assets/811537/db5c7d7c-5e3b-454d-9a50-beea3e72ff5a)

Když jsem pak kliknul na povolit všechny, tak jsem se dostal na stránku kde se donekonečna točilo kolečko.

**Comment by honza-rychtar** [comment]
To s těmi tlačítky opravíme.

Pokud jde o odpálení cookie lišty, tak tam vždy dojde ke kompletnímu reloadu stránky. Což by určitě nemělo způsobit nekonečný loading - použije se aktuální url a web se načte znovu, to url by mělo být vždy validní, když funguje před reloadem.
@zabak zkus to prosím ještě jednou, třeba v anonymním režimu, ať máš fresh cookie lištu.

Co ale problém může být, je že odkaz na vybraná oblast nezachovává po načtení tu oblast v url. Což je kvůli mnoha jiným důvodům chtěné. Sdílení oblasti je přes tlačítko sdílet a sdílená oblast se přes odkaz správně načte.
Ale nefunguje sdílení oblasti přes vykopírování url z address baru. A tedy se nezachová vybraná oblast po odpálení cookie lišty, kdy dochází k tomu reloadu url (už bez informaci o oblasti).
Otázka je, jestli tohle vůbec řešit. Obecně odpálení cookie lišty mi nějakým způsobem zruší stav práce na stránce.

**Comment by zabak** [comment]
To donekonečna se točící kolečko už se mi neopakovalo, takže to ignorujme, stačí jen vyřešit ten překryv prvků.

U toho kopírování URL by se teoreticky dalo využít toho, že by se při ctrl-c v URL řádku podhodilo javascriptem jiné URL i s potřebnými parametry, jestli to jde. Ale neřešil bych to.

**Comment by honza-rychtar** [comment]
> U toho kopírování URL by se teoreticky dalo využít toho, že by se při ctrl-c v URL řádku podhodilo javascriptem jiné URL i s potřebnými parametry, jestli to jde. Ale neřešil bych to.

Jako uživatel doufám, že to není možné :) Rád bych měl jistotu, že kopíruju text, který mám vybraný.

**Comment by annie-cz** [comment]
Opraveno ve verzi 2.9.0 @zabak. Cookie lišta je už stranou, ovládcí prvky se už s ničím nebijí.

![image](https://github.com/user-attachments/assets/6bb5dfb8-d48f-4f55-b33b-49896ecb8c92)
