### ISSUE TITLE
AI funkce - čtení se nevypne když ze stránky odejdu

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#727]
Když se pak na nějakou stránku vrátím, tak se dá vypnout, takže to není velký problém a možná je to pro některé účely vlastně dobře, ale v takovém případě by mělo být možné to čtení nějak stopnout i odjinut než ze zobrazení stránky.

**Comment by annie-cz** [comment]
A teď jsem zjistila ještě jako bonus, že se nevypne ani když přejdu z předčítání celé strany na výřez. :)

<img width="514" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/43028501/5e18255b-11d3-4e5c-8f1c-e1f947144c27">

ERBEN, Karel Jaromír, Karel ČAPEK a Božena NĚMCOVÁ. Pohádky Erbenovy, B. Němcové a K. Čapka. V Brně: Nová brána jazyků, 1940, s. 3. Dostupné také z: http://dk.kramerius.org/mzk/uuid/uuid:9d7b52ab-7025-45a8-b6c1-38813422ad41

Myslím si, že když člověk dokument opustí, mělo by se přestat číst a zároveň, když kliknu na jakoukoliv jinou akci, tak by se měl proces přerušit taky a přejít na ten jiný.

**Comment by honza-rychtar** [comment]
Ale to je dobře ne. U toho výřezu nechceš nutně číst. Co když si chci nechat číst stránku nahlas a zároveň vybrat vybrat text z výřezu, udělat náhledový obrázek, sdílet atd.

K tomu je tam ten společný panel čtení, kde je možné čtení zastavit ručně.

**Comment by annie-cz** [comment]
Jasný, chápu, co tím myslím. Ale ... nejsem si tím i tak po pravdě jistá, resp. ne v této konkrétní podobě Přijde mi to v této podobě trochu nepředvídatelný. U výřezu to totiž zabere i to modré pole, takže to vypadá jako by sis dělal výřez právě s tím modrým polem (jako když děláš výřez / printscreen obrazovky), takže tě to úplně nemotivuje si dělat např. výřez proto, aby sis uložil ten výřez nebo abys používal ty další funkce, protože to může vizuálně evokovat, že to bude zabírat tu vymodřenou část a nebo že to je nějaké zaseklé. Přijde mi to díky tomu jako potenciálně matoucí. Možná, kdyby se to nezobrazovalo s tím modrým polem, tak by mi to dávalo větší smysl a tenhle problém by se odstranil. 🙂  Co myslíš?

**Comment by honza-rychtar** [comment]
No vypnout zobrazování té čtené plochy by byl dobrý kompromis.

U vypínání, resp. nevypínání čtení bychom potom mohli jít jít ještě dál a tu současnou chybu, kdy se čtení nezastaví při odchodu z prohlížečky, překlopit v požadovanou funkcionalitu. V rámci přehrávání zvukových nahrávek je navrženo, že se bude dát přehrávat na pozadí a k ovládání bude sloužit k tomu speciální schovávací panel, přes který bude možné přehrávané nahrávky ovládat včetně pozastavení a zrušení přehrávání.
Něco podobného bychom mohli použít i pro to čtení - četlo by se dál na pozadí a uživatel by přitom mohl procházet aplikaci bez omezeni s možnostmi čtení pozastavit a zrušit.

Tohle by ale bylo složitější. Zatím to přehrávání vypnu při odchodu z prohlížečky (což je titulek tohoto issues) a zbytek přepíšu do nových issues.

**Comment by annie-cz** [comment]
Od v2.9.0 se čtení chová tak, že když čtenář dokument opustí, čtení se ihned vypne. 

Pokud ale začne v rámci dokumentu listovat dalšími stránkami a nebo používat další prvky (třeba textový režim nebo výstřižky), čtení pokračuje. Uživatel tak může s dokumentem pracovat a zároveň poslouchat čtený text.

**Comment by annie-cz** [comment]
Pardon, zavřeno omylem předčasně, prosím o kontrolu @zabak.

**Comment by zabak** [comment]
Funguje zavírám. Bylo by dobré aby to někdo otestoval na čtení více stran na mobilu, třeba cestou v autě, jestli tam nejsou nějaká nečekaná překvapení, to by ale bylo nové issue.
