### ISSUE TITLE
nelze zobrazit obrazek gramodesky

### ISSUE THREAD

**Issue by filipsir** [ceskaexpedice/kramerius-web-client#73]
toto je dosti problemove. nutno vyresit. jinak je to nepouzitelne...

**Comment by filipsir** [comment]
Mas zlateho bludistaka. Zatim pouze na mobilu, ale vypada to moc pekne. Cisty a logicky. Zkouknu na ntb a napisu.

**Comment by zabak** [comment]
Hodilo by se mít možnost ty obrázky zoomovat. Třeba střed té druhé gramodesky na notebooku nepřečtu (teda většinou to nějak odhadnu, ale jsou to blechy).
