### ISSUE TITLE
AI: asi vyčerpané kredity?

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#735]
Ale hláška je 
<img width="685" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/811537/070102b9-751e-4d43-b686-07ea1bebceb7">

**Comment by zabak** [comment]
...i když jsem přihlášený

**Comment by honza-rychtar** [comment]
Ano, vyčerpal. V té nové verzi jsem tam dával hlášky pro další možné chyby a tohle mi uteklo. Chyba o přečerpání kreditů se uplatní až po obecné chybě o neautorizovaném přístupu (např. pokud by si to někdo nasadil na svého Krameria, resp. na svůj Keycloak, který nemáme zaregistrovaný) a ta ji přebila.
Opravím.

**Comment by honza-rychtar** [comment]
Pokud se překročí měsíční kvóta, tak se zobrazí oznamující dialog

<img width="682" alt="Snímek obrazovky 2024-09-17 v 7 13 40" src="https://github.com/user-attachments/assets/8a4bf57f-0f73-4246-9bcf-d56c6195c983">

Dostupné ve verzi v2.9.0
