### ISSUE TITLE
Nezobrazují se JPEG IMG_FULL streamy

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#74]
Máme nejaké dokumenty pouze s JPEG obrázky, ve starých klientech se zobrazují v pořádku, například:

http://kramerius.medvik.cz/search/handle/uuid:MED00149115

Ve web-client se nad stejným K5 jádrem (5.3.4) však nezobrazují:

https://dev.medvik.cz/wck/uuid/uuid:MED00149115

Myslím, že se klient snaží získat odpověď přes image server (https://dev.medvik.cz/search/zoomify/uuid:b6c47c86-6b2c-11e3-ad8f-d485646517a0/ImageProperties.xml) a v RELS-EXT samozřejmě žádný tiles-url element není - takže pak nastane NullPointerException a vrátí 500 error.

**Comment by honza-rychtar** [comment]
Klient se vzdy nejdriv pta na zoomify - je to dano tim, ze se nedalo verit API Krameria to, jestli je obrazek v dlazdicich nebo jen jpeg. 
Ted je tam fallback na pouziti jpegu, pokud request na imageProperties.xml vrati 404 (coz by spravne mel!).
Ale pridam stejny fallback i v pripade 500, kterou to vraci u vas.

Jeste bych doporucoval, abyste si zmenili generator uuid, resp. abyste zacali pouzivat uuid a ne nejaky ad hoc retezec. Proste aby identifikatory mely tvar uuid:xxxxxxxx-xxxx-1xxx-axxx-xxxxxxxxxxxx
Nekdy se ten format predpoklada.

**Comment by pavel-stastny** [comment]
>  je to dano tim, ze se nedalo verit API Krameria to, jestli je obrazek v dlazdicich nebo jen jpeg.

Proc nedalo verit?    Ridi se to priznakem `tiles-url` v `RELS-EXT`, pokud je pritomen, jsou k dispozici dlazdice, pokud ne, tak nejsou.

**Comment by filak** [comment]
Stejně se to chová i v případě PDF streamů, např.
https://dev.medvik.cz/wck/view/uuid:c6a38c0e-7d80-41de-92a1-5c2413e64094?page=uuid:4d07cd11-62c5-4afa-980e-ef679f130e3f

**Comment by filak** [comment]
Jinak souhlasim s Pavlem. Delat nejakou logiku podle vyjimek neni IMHO uplne optimalni.

**Comment by filak** [comment]
Kdyby web-client volal pro full page zobrazení nejdřív .../search/api/v5.0/item/uuid:.../ ,
tak by pak měl jasno, zda má použít zoomify nebo zobrazit PDF nebo přímo IMG_FULL stream (v případě holých JPG)

1. image server : https://dev.medvik.cz/search/api/v5.0/item/uuid:b55f1f9f-6ca4-495a-bcfd-68f6c156c07a/
-- zoom.url

2. PDF viewer : https://dev.medvik.cz/search/api/v5.0/item/uuid:cb7b505d-3246-4cbf-a2bb-e6fd8ba8cc2a/
-- pdf.url

3. GET_RAW : https://dev.medvik.cz/search/api/v5.0/item/uuid:b6c47c86-6b2c-11e3-ad8f-d485646517a0/
-- není ani zoom.url ani pdf.url

**Comment by filak** [comment]
Pokus o opravu: 

https://github.com/filak/wck/commit/6a34182cc63a4643ac477267ab51eb4a6cc841a0

**Comment by honza-rychtar** [comment]
Změněno. Klient nejdřív získá item a podle toho se rozhodne, který zdroj použije.

**Comment by honza-rychtar** [comment]
>> je to dano tim, ze se nedalo verit API Krameria to, jestli je obrazek v dlazdicich nebo jen jpeg.

>Proc nedalo verit? Ridi se to priznakem tiles-url v RELS-EXT, pokud je pritomen, jsou k dispozici dlazdice, pokud ne, tak nejsou.

@pavel-stastny U Mendelu Krameria je v *item* - http://kramerius4.mendelu.cz/search/api/v5.0/item/uuid:51d51120-aed5-11e0-b352-001fd02ebcd6 - zoom type=deepzoom.  Zoomify tam nikde neni a presto ho maji 
http://kramerius4.mendelu.cz/search/zoomify/uuid:51d51120-aed5-11e0-b352-001fd02ebcd6/ImageProperties.xml
Maji dost starou verzi 5.3.2
Ridim uz se ted tim, co je v *item*, ale konkretne u Mendelu se to rozbiji. Osetrim to ted tak, ze pokud *item* obsahuje zoom jineho typu nez zoomify, tak budu predpokladat, ze podporuji zoomify na standardnim endpoitnu.

A taky maji ted vsichni v _item_ iiif, i kdyz iiif nemaji. Vypada to, ze pokud je v rels-ext tiles-url, pak je automaticky taky iiif, coz rozhodne neni pravda.

**Comment by pavel-stastny** [comment]
> http://kramerius4.mendelu.cz/search/api/v5.0/item/uuid:51d51120-aed5-11e0-b352-001fd02ebcd6 - zoom type=deepzoom. Zoomify tam nikde neni a presto ho maji
http://kramerius4.mendelu.cz/search/zoomify/uuid:51d51120-aed5-11e0-b352-001fd02ebcd6/ImageProperties.xml

Kdyz se podivas sem` http://kramerius4.mendelu.cz/search/i.jsp?pid=uuid:51d51120-aed5-11e0-b352-001fd02ebcd6`, tak to co vidis, je deepzoom prohlizecka.  Deskriptor  `http://kramerius4.mendelu.cz/search/deepZoom/uuid:51d51120-aed5-11e0-b352-001fd02ebcd6`  je taky pro deepZoom.   Je to nastavitelne uzivatelskou propertou v konfiguracnim souboru.  Ten vyznam API polozky nebyl co vse muze nabidnout ale naopak, jaky typ prohlizeky (protokolu)  se ma pouzit (zoomify nebo seadgragon). Admin rozhrani se tim ridi. U toho modreho klienta nevim.  

>A taky maji ted vsichni v item iiif, i kdyz iiif nemaji. Vypada to, ze pokud je v rels-ext tiles-url, pak je automaticky taky iiif, coz rozhodne neni pravda.

Nevim, tady bych pozadal  o radu @MartinRumanek
