### ISSUE TITLE
Tlačítko pro akce nad stránkou se zobrazuje i u nedostupného dokumentu

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#741]
<img width="852" alt="Snímek obrazovky 2024-04-05 v 9 45 30" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/1178142/146b35e5-11ad-4790-bdc2-bf7a3231a6af">

**Comment by annie-cz** [comment]
Opraveno ve v2.9.0. Tlačítka pro akce nad stránkou se zobrazují aktuálně pouze u volných dokumentů.

U zcela nedostupných dokumentů se nezobrazuje nic.

![image](https://github.com/user-attachments/assets/f3bb2274-c9c0-48f6-9f2d-ccfb89cb1a85)

U DNNT dokumentů lze pouze vybrat oblast a nasdílet jinému uživateli výstřižek, který se zobrazí v souladu s politikou dané licence, tj. v případě DNNT pouze po přihlášení.

![image](https://github.com/user-attachments/assets/0c777f9c-709b-4427-ae76-3fa9d2fe0288)

Viz: http://dk.kramerius.org/mzk/uuid/uuid:60071a0e-1bb9-4a50-8775-782ce644fddc?bb=681,1467,1017,1036
