### ISSUE TITLE
Čtení po částech - stáhnout si vždy jeden fragment textu dopředu

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#742]
Pokud si nechám přečíst celou stranu a ta se rozdělí na fragmenty, u kterých se TTS načítá postupně, tak si vždy natáhnout jeden fragment dopředu, aby bylo čtení plynulé a nečekalo se na načtení mezi dvěmi fragmenty.

**Comment by annie-cz** [comment]
Vyřešeno v rámci v2.9.0. Čtení je v rámci jedné strany nyní plynulejší.

Viz: https://www.dropbox.com/scl/fi/zw8lb8z6e2a57j6aq01ts/Z-znam-obrazovky-2024-09-16-v-17.28.27.mov?rlkey=544qjye1qezeds6ph355vkp3m&st=wxg4kman&dl=0
