### ISSUE TITLE
Umožnit volbu jazyka a hlasu u TTS

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#747]

**Comment by annie-cz** [comment]
Přidáno ve v2.9.0.

Při najetí kurzoru na hlasové předčítání se objeví zároveň i ozubené kolečko s nastavením.

![image](https://github.com/user-attachments/assets/138b55da-1637-4851-9101-0d881c712f0e)

V nastavení lze nastavit preferované jazyky i jednotlivé hlasy dostupné pro každý jazyk zvlášť.

![image](https://github.com/user-attachments/assets/1e146cf0-4bba-431a-a091-a18203f340b7)

![image](https://github.com/user-attachments/assets/1ec193ee-3f8d-4dcb-b484-aefaefcf1143)

**Comment by honza-rychtar** [comment]
Jen poznamenám, že používáme 3 TTS služby (OpenAI, Google, ElevenLabs).
ElevenLabs je dostupné pouze pro uživatelé s rolí TESTER.
Běžný uživatel bude mít dostupné pouze hlasy od Googlu (1 - 4 v závislosti na jazyce) a od OpenAI (vždy 6 hlasů)

<img width="768" alt="Snímek obrazovky 2024-09-17 v 7 28 27" src="https://github.com/user-attachments/assets/5257c088-08ce-484a-8f72-4fbd477f211c">
