### ISSUE TITLE
ČDK: rozbité zobrazení ročníků při nekonzistentních datech

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#748]
V téhle chvíli je kvůli migraci K5->K7 v KUK zvláštním způsobem rozbité zobrazení ročníků

<img width="1430" alt="image" src="https://github.com/ceskaexpedice/kramerius-web-client/assets/811537/bdf2e5ad-9c70-41e6-892b-1906d500277f">

**Comment by zabak** [comment]
https://ceskadigitalniknihovna.cz/periodical/uuid:cb8a7520-fbbf-46a3-bb1e-9f08f70a3af1

**Comment by bezverec** [comment]
To stejné i digitalniknihovna.cz
příklad: https://www.digitalniknihovna.cz/knav/periodical/uuid:f9725147-72a9-4d48-b8a4-9d2d635315f7
![digknihUI](https://github.com/ceskaexpedice/kramerius-web-client/assets/25476976/5e22d493-34c8-4a64-ac74-d5de6f1a9844)
V předchozí verzi klienta je, myslím, jen mřížka. 
Nevím, jestli se jedná o bug, nebo feature kvůli rozšíření přístupnosti.

**Comment by honza-rychtar** [comment]
Je to chyba zanesena při změnách ve struktuře pro podporu webové přístupnosti.
Opravíme co nejrychleji.

**Comment by annie-cz** [comment]
Opraveno ve v2.9.0 @zabak 

![image](https://github.com/user-attachments/assets/dfc6faea-703b-4733-8b55-e5d0044e404d)
