### ISSUE TITLE
Odkaz na titul periodika

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#75]
Název periodika na pravé straně v metadatech by měl být proklikávací na celé periodikum (seznam ročníků). Stejně by to mělo fungovat třeba taky u vícedílných monografií. 

![odkaz](https://user-images.githubusercontent.com/21309201/39613740-ece57b6e-4f69-11e8-990a-9f253c192f30.jpg)

**Comment by filak** [comment]
To bych také uvítali.

**Comment by honza-rychtar** [comment]
Udelal jsem to takto.

**Periodikum**
<img width="300" alt="screenshot 2018-05-15 11 23 06" src="https://user-images.githubusercontent.com/1178142/40048487-aee900f2-5832-11e8-8ff3-424319b4f8c8.png">

**Vicesvazkova monografie**
<img width="300" alt="screenshot 2018-05-15 11 23 17" src="https://user-images.githubusercontent.com/1178142/40048513-bc3ca0c4-5832-11e8-827c-d0f4774ec4e7.png">

**Comment by filak** [comment]
No, "svazek knih" zní trochu divně, nestačilo by jen "Přejít na svazky" ?
