### ISSUE TITLE
Zalamovat filtry u hledání

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-web-client#756]
Znovu vypisovat filtry celé i když přetečou na více řádků.
Checkbox zarovnat nahoru.

**Comment by annie-cz** [comment]
Vyřešeno v rámci v2.9.0

![image](https://github.com/user-attachments/assets/30fb9240-a341-4100-8333-e4f82381a814)

![image](https://github.com/user-attachments/assets/d65dd0a7-11fb-49b0-a194-0219919e7f94)
