### ISSUE TITLE
Hledání uvnitř dokumentu

### ISSUE THREAD

**Issue by BrozekAles** [ceskaexpedice/kramerius-web-client#78]
V časopise Český svět z 19.6.1914, s.1 nenajde slovo "hlavy" (ale slovo "Sezima" ano), na s. 14 nenajde slovo "musea" (ale slovo "třetfod" ano). Proč?

**Comment by honza-rychtar** [comment]
Tohle je problém stavu indexu MZK. Jednak mají verzi, kde je fulltextové pole **text_ocr** lemmatizované (byla to taková meziverze - následující verze maji lemmatizovaný fulltext v jiném poli).
Zároveň mají chyby v indexu v poli text (hodně toho chybí).

Správně by mělo mít na úrovní stránky pole text a text_ocr stejný obsah.

Pro fulltext používá nový kliente pole **text** - chybí slova, výsledku je méně)
http://mzk.kramerius.rychtar.cloud/view/uuid:9be0c5f0-9a83-11e4-a2db-005056825209?fulltext=hlavy
Digitální knihovna používá pole **text_ocr**, které je lemmatizované a vrací zase výsledku více (i při hledání v uvozovkých).
http://www.digitalniknihovna.cz/mzk/view/uuid:9be0c5f0-9a83-11e4-a2db-005056825209?page=uuid:de98f140-9a94-11e4-9a7e-5ef3fc9bb22f&fulltext=%22hlavy%22

Pro starší verzi indexu u NKP oba klienti najdou správně jeden výsledek.
http://nkp.kramerius.rychtar.cloud/view/uuid:9be0c5f0-9a83-11e4-a2db-005056825209?page=uuid:75ec3850-9a94-11e4-b7ae-001018b5eb5c&fulltext=hlavy
http://www.digitalniknihovna.cz/nkp/view/uuid:9be0c5f0-9a83-11e4-a2db-005056825209?page=uuid:75ec3850-9a94-11e4-b7ae-001018b5eb5c&fulltext=hlavy

Do budoucna by to mělo fungovat tak, že se při zadání bez uvozovek bude hledat v lemmatizovaném poli a při použití uvozovek v nelemmatizovaném poli.
