### ISSUE TITLE
Článek nejde stáhnout ani vytisknout

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#79]
U článků v PDF není možnost článek vytisknout ani stáhnout, ptž na pravé straně chybí ta část s vyhledáváním a tlačítky pro stažení a tisk. Šlo by jí tam nechat, samozřejmě jen to stažení a tisk a vyhledávání? Třeba takhle?
![ulozitstahnout](https://user-images.githubusercontent.com/21309201/40043125-d6cba1d8-5823-11e8-867a-cabbbdd2bab0.jpg)

Nejde stáhnout ani monografie v PDF (příklad v http://sluzby.incad.cz/kramerius  "Naše rodina, naše problémy, naše řešení")

**Comment by krizovj** [comment]
Taky není možné PDF přiblížit, na normálním monitoru to je ještě v pohodě, ale na mobilu by to bylo potřeba. Šlo by tam přidat nějaká tlačítka pro přiblížení a oddálení jako je to u skenů?

**Comment by honza-rychtar** [comment]
Pro praci s PDF dokumenty bude nejlepsi pouzit nejakou knihovnu a nevymyslet znova kolo.
Napr. http://www.digitalniknihovna.cz/knav/view/uuid:d8d0911c-f6cc-4deb-b6cb-da0701d5dd10

Tisk, stazeni, hledani, zvyraznovani, pocty stran, navigace, zoomovani zvlada pdf prohlizecka sama.

**Comment by filak** [comment]
Jsem pro, aby to bylo stejně jako ve výše uvedeném příkladu z digiknihovny.

Trochu jsem si s tím ve web klientovi pohrál
https://dev.medvik.cz/wck/uuid/uuid:bmc17017514-b5a04571-ee4e-4b8e-9a8c-59601531beda
ale integrované to bude lepší.

**Comment by krizovj** [comment]
Jsem taky pro

**Comment by filak** [comment]
Jojo, to se musí poladit, mně to už funguje - viz
https://dev.medvik.cz/wck/uuid/uuid:bmc17017514-b5a04571-ee4e-4b8e-9a8c-59601531beda

**Comment by honza-rychtar** [comment]
Použil jsem plnohodnotnou PDF prohlížečku, která obsahuje všechnu požadovanou funkcionalitu.
http://mzk.kramerius.rychtar.cloud/uuid/uuid:4873e8c7-5967-4003-8544-96f64ca55da7
http://knav.kramerius.rychtar.cloud/uuid/uuid:559f8b2d-2ada-406f-86f6-7c61fea59a2a
