### ISSUE TITLE
Problematický parametr facet.field=collection

### ISSUE THREAD

**Issue by kvetjo** [ceskaexpedice/kramerius-web-client#790]
Zdravím,

Snažím se nainstalovat novou instanci Krameria 7 společně i s oběma klienty. U webového klienta se mi ale vyskytl problém, se kterým si nevím moc rady: Když kliknu na "Vstoupit", tak mimo jiné se odešle dotaz na API, který mi vrací 400 (Bad Request).

Toto je onen dotaz:
http://jaguar.is.cuni.cz/search/api/client/v7.0/search?q=*:*&fq=(model:monograph%20OR%20model:periodical%20OR%20model:map%20OR%20model:graphic%20OR%20model:archive%20OR%20model:manuscript%20OR%20model:soundrecording%20OR%20model:sheetmusic%20OR%20model:monographunit)&fl=pid,accessibility,model,authors,titles.search,title.search,root.title,date.str,title.search_*,collection.desc,%20collection.desc_*,licenses,contains_licenses,licenses_of_ancestors&facet=true&facet.mincount=1&facet.field=keywords.facet&facet.field=languages.facet&facet.field=physical_locations.facet&facet.field=geographic_names.facet&facet.field=authors.facet&facet.field=collection&facet.field=own_model_path&facet.field=accessibility&sort=created%20desc&rows=60&start=0

Když jsem to krok po kroku analyzoval, zjistil jsem, že problém dělá jen tento parametr: facet.field=collection
Nalezl jsem jedno issue, které se přesně tímto již zabývalo: [668](https://github.com/ceskaexpedice/kramerius-web-client/issues/668). A podle komentářů by měl být problém vyřešený. Nicméně mě to stále zlobí. Zkoušel jsem i starší verze klinetů (například i 2.5.0, u kterého je v komentáři přímo napsáno, že tento problém byl v této verzi vyřešen) a také mi to nefunguje - stále se na API posílá request s tím problematickým parametrem. 

Začínám mít trochu podezření, že je něco chybného na mé straně i vzhledem k tomu, že všem ostatním to funguje jak má s touto nejnovější verzí (tzn. že mají správně obsažen parametr collection.desc ve verzi 2.8.0). Je možné, že mám něco špatně nastaveného v konfigu? Asi bych potřeboval trochu nasměrovat, co mohu ještě zkontrolovat.

Zde příkládam naše globals.js --> [globals_js.txt](https://github.com/user-attachments/files/16991969/globals_js.txt)

Děkuji moc za každé komentáře,

S pozdravem
Jonáš Květ
UKUK

**Comment by honza-rychtar** [comment]
Vyhoď z filtrů v konfiguraci collections

filters: ['accessibility', 'doctypes', 'authors', 'keywords', 'collections', 'locations', 'languages', 'geonames'],

--->

filters: ['accessibility', 'doctypes', 'authors', 'keywords', 'locations', 'languages', 'geonames'],

**Comment by kvetjo** [comment]
To pomohlo. Už to jede! Díky moc
