### ISSUE TITLE
Sbírky 

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#8]
Řazení sbírek podle výskytů znamená podle počtu dokumentů, které jsou v nich zařazené? 
Celkově ty sbírky nějak nefungují, ať otevřu jakoukoliv, tak má 188 320 výsledků.

**Comment by honza-rychtar** [comment]
> Řazení sbírek podle výskytů znamená podle počtu dokumentů, které jsou v nich zařazené?
Ano, pocet dokumentu se zobrazuje v seznamu vpravu.

> Celkově ty sbírky nějak nefungují, ať otevřu jakoukoliv, tak má 188 320 výsledků.
Chybelo filtrovani podle sbirky (na coz se z toho seznamu sbirek odkazovalo).
Pridal jsem sbirky jako dalsi fasetu u vyhledavani. Ted uz to funguje.

**Comment by honza-rychtar** [comment]
Tohle bylo chybnou aktualizaci na testovacim serveru. Opravovali jsme to uz vcera. Vas prohlizec bude mit jeste nacachovanou starou verzi lokalizacnich souboru. Parkrat reloadnete stranku a melo by to byt ok.
