### ISSUE TITLE
PDF se nenačítají - pouze se zobrazuje náhled první strany

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#81]
Upgradoval jsem na nejnovější dev verzi, data se používají z K5 (http://kramerius.medvik.cz/search/)

PDFka se nenačítají, například:

https://dev.medvik.cz/wck/uuid/uuid:fc61c07d-6a41-11e3-ab2b-d485646517a0

nebo 

https://dev.medvik.cz/wck/view/uuid:c6a38c0e-7d80-41de-92a1-5c2413e64094?article=uuid:bmc07009190-93645991-190b-4969-809c-d9da2c9dbed2

Nejspíš souvisí s https://github.com/ceskaexpedice/kramerius-web-client/issues/74

**Comment by honza-rychtar** [comment]
Opraveno.
Klient zobrazuje PDF i když je navázáno na stránku ...
http://kramerius.rychtar.cloud/nlk/view/uuid:MED00166391?page=uuid:fc61c07d-6a41-11e3-ab2b-d485646517a0
