### ISSUE TITLE
Monografie s volnými částmi (monograph_unit) se jeví jako periodikum

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#83]
Například:
https://dev.medvik.cz/wck/view/uuid:MED00182016-affdf3dd-9c9b-4e1a-b50b-c9e5f08f5ce9

K5-search:
http://kramerius.medvik.cz/search/handle/uuid:MED00182016-affdf3dd-9c9b-4e1a-b50b-c9e5f08f5ce9

**Comment by honza-rychtar** [comment]
@filak Vsak to je dobre ne? Je tam ta uroven nad castmi monografie, ktera umoznuje hledat ve vsech castech (jako v periodiku nebo v rocniku), jednotlive casti jsou oznaceny jako "cast" misto "cislo"/"rocnik", typ doumentu je "kniha". Po rozkliku nektere casti je pak mozne v prohlizecce prechazet na predchozi/nasledujici cast nebo prejit zpet na seznam casti.

Jak jinak byste to chtel zobrazit/prochazet?

**Comment by filak** [comment]
Proti prochazeni pres svazky nic nemam, ale metadata maji prece jen trochu jina nez rocnik nebo cislo periodika. 

https://dev.medvik.cz/search/api/v5.0/item/uuid:d5e4fc47-c333-4b73-b4f0-fcc6d56152f1/streams/BIBLIO_MODS

**Comment by filak** [comment]
OK, zobrazení specifických metadat to částečně vylepšilo - má sice ještě mouchy (https://github.com/ceskaexpedice/kramerius-web-client/issues/90), ale tohle myslím můžeme zavřít.
