### ISSUE TITLE
Tlačítko (šipka) "Zpět na předchozí stránku" nefunguje spolehlivě při filtru autor nebo jazyk

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#84]
Postup:

1. https://dev.medvik.cz/wck/ - pouze verejne => vstupte
2. kliknout na Jazyk - francouzština / nebo Autor - Institut klinické a exp. medicíny
3. kliknout na dokument
4. kliknout na šipku zpět

=> přejde zpátky na úvodní stránku místo na "search" stránku

**Comment by filak** [comment]
Zajimave je, ze se to projevuje zrejme jen u vicedilnych monografii.

- v pripade francouzstiny: "Anatomie de l'homme ou description et figures lithographiées de toutes les parties du corps"

- v pripade nemciny: "Aesculap-Musterbuch"

**Comment by honza-rychtar** [comment]
Opraveno
