### ISSUE TITLE
Zobrazení autora a dalších původců 

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#85]
I přes to, že jsou v metadatech různé role, tedy kódy rolí (např. autor - aut, editor - edt, překladatel - trl), v Krameriovi se všichni původci zobrazují jako autoři. 

<mods:name authorityURI="http://aut.nkp.cz" type="personal" usage="primary" valueURI="http://aut.nkp.cz/jn19981001925">
            <mods:namePart>Ovidius</mods:namePart>
            <mods:namePart type="date">43 př. Kr.-asi 18 po Kr</mods:namePart>
            <mods:role>
                <mods:roleTerm authority="marcrelator" type="code">aut</mods:roleTerm>
            </mods:role>
        </mods:name>
        <mods:name type="personal">
            <mods:namePart>Bureš, Ivan</mods:namePart>
            <mods:role>
                <mods:roleTerm authority="marcrelator" type="code">trl</mods:roleTerm>
            </mods:role>
        </mods:name>

Zde např. autorem (aut) Ovidius a překladatelem (trl) Ivan Bureš. V Krameriovi zobrazeni oba jako autoři: 
 
![obrazek](https://user-images.githubusercontent.com/31240271/40532097-a8361a5a-5ffe-11e8-85e1-5eb0062851ec.png)

Samozřejmě bychom uvítali, kdyby byly i ostatní role (nejen autor) vyjádřeny slovně a ne kódem rolí.

**Comment by krizovj** [comment]
Mně se to zdá dobře udělané v Digitální knihovně:
![autori](https://user-images.githubusercontent.com/21309201/40917398-6705e008-6803-11e8-9778-1f5b9e87dfef.jpg)

**Comment by honza-rychtar** [comment]
Udělal jsem to stejně jako v Digitální knihovně.

![screenshot 2018-10-09 09 47 51](https://user-images.githubusercontent.com/1178142/46654165-67ba3180-cba8-11e8-8301-98106758ecae.png)

Role jsou lokalizované do češtiny a angličtiny.

http://mzk.kramerius.rychtar.cloud/uuid/uuid:36d4cb70-5d12-11e8-87e4-5ef3fc9ae867
