### ISSUE TITLE
Řazení jednotlivých částí

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#86]
U vícedílné monografie jsme nejdřív měli všechny díly za sebou ve správném pořadí (I, II-III, IV, V). 
Pak se to znovu naimportovalo a pořadí už bylo špatně (II-III, IV, V, I). Zkusila jsem ten dokument reindexovat a pořadí se zase změnilo (II-III, I, IV, V). Ale v jádru Krameria se to pořadí pořád zobrazuje správně, jen v klientovi je to přeházené. 
Nevíte čím by to mohlo být?
![image](https://user-images.githubusercontent.com/21309201/40602348-84589f34-6258-11e8-9148-acbea061fcce.png)

![image](https://user-images.githubusercontent.com/21309201/40602357-8e2d7444-6258-11e8-83c6-5c87ba72f374.png)

**Comment by pavel-stastny** [comment]
Jaky je pid toho objektu ?

**Comment by krizovj** [comment]
Uuid nejvyšší úrovně (celé vícedílné monografie): uuid:9af81e41-a99b-44ff-a068-730eec0c5335
Máme to zatím jen v testovacím Krameriovi: 
https://k4test.lib.cas.cz/search/handle/uuid:9af81e41-a99b-44ff-a068-730eec0c5335

**Comment by pavel-stastny** [comment]
Je ten server viditelny z venku ?  (mimo KNAV?) .  Nedari se mi na to dostat.

**Comment by krizovj** [comment]
Není, teď jsem to zkoušela a taky mi to nešlo.

**Comment by pavel-stastny** [comment]
Muzete zkusit nasledujici?  

1. https://k4test.lib.cas.cz/search/api/v5.0/search?q=parent_pid:%22uuid:9af81e41-a99b-44ff-a068-730eec0c5335%22&fl=PID%20rels_ext_index
2. https://k4test.lib.cas.cz/search/api/v5.0/item/uuid:9af81e41-a99b-44ff-a068-730eec0c5335/children
3.  https://k4test.lib.cas.cz/search/api/v5.0/item/uuid:9af81e41-a99b-44ff-a068-730eec0c5335/foxml 

A vysledne json a xml treba poslat mailem ?

**Comment by honza-rychtar** [comment]
Seznam casti monografie se ridi stejnymi pravidly jako seznam rocniku/cisel periodika.
Dotaz na seznam casti/rocniku/cisel se nebere pres /item/UUID/children. 
Bere se pres solr dotaz s omezenim na pid_path a seradi se podle datum, datum_str - razeni pres datum dava smysl u cisel a rocniku periodika. U casti monografie to nemusi byt spravne, protoze pokud byly dve casti vydany ve stejnem roce, tak neni jasne jak je seradit. PartNumber a partName je v solru v multivalued poli details, podle ktereho neni mozne radit.

**Comment by krizovj** [comment]
U těch svazků není jednoduché datum vydání uvedeno, ptž není známé. Takže je tam odhadnuté datum formou rozsahu dat. Tak možná proto ty svazky nevědí, jak se mají seřadit...

**Comment by filak** [comment]
Ja si tedy myslím, že monograph units by si zasloužily vlastní zobrazení, a pro získání dat z K5 API by se měl používat dotaz na children.

Viz například Domácí lékařka: 
https://dev.medvik.cz/wck/uuid/uuid:MED00182016-affdf3dd-9c9b-4e1a-b50b-c9e5f08f5ce9

https://dev.medvik.cz/search/api/v5.0/item/uuid:MED00182016-affdf3dd-9c9b-4e1a-b50b-c9e5f08f5ce9/children

Viz https://github.com/ceskaexpedice/kramerius-web-client/issues/83

**Comment by honza-rychtar** [comment]
@filak Jak by melo to vlastni zobrazeni vypadat? Pouziti dotazu na *children* by v tomto pripda slo (i kdyz by bylo lepsi zaindexovat cisla casti a radit podle nich).

**Comment by filak** [comment]
Myslím, že kromě toho divného zobrazování roků, jako např.

https://dev.medvik.cz/wck/periodical/uuid:MED00182016-affdf3dd-9c9b-4e1a-b50b-c9e5f08f5ce9

 je to použitelné - zobrazení metadat svazku to dost vylepšilo.

**Comment by honza-rychtar** [comment]
Při diskutovaných změnách v solru by se mělo také změnit ukládání strukturálních dat u části monografie (nazev casti, cislo casti), ročníku (cislo rocniku, rok) a číslel (datum, cislo (partNumber a issuNumber)).
Teď se vše ukládá do pole **details**, kde jsou hodnoty oddělěne **##**, takže se podle těchto údajů nedá vyhledávat a ani řadit.

**Comment by honza-rychtar** [comment]
Opraveno. U vícesvazkových monografií se teď berou data z API children místo solru, takže řazení odpovídá editorů částí.
Např. http://kramerius.rychtar.cloud/knav/periodical/uuid:9af81e41-a99b-44ff-a068-730eec0c5335
