### ISSUE TITLE
PDF - zmenšování okna

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#87]
Když má okno prohlížeče určitou velikost, tak zmizí sloupec s navigací a je tam pouze sloupec čtení a informace. Když dál zmenšuji, tak to dojde do takové velikosti, že se to zobrazí jako pro mobil. Ale je tam taková mezera, kdy není vidět navigace. U skenů to není, jsou tam ty šipky, kterými se vyjíždějí ty sloupce.

**Comment by honza-rychtar** [comment]
Přidal jsem tlačítka pro zobrazení/schování bočních panelů u PDF prohlížečky.
