### ISSUE TITLE
Rozsah stran článku

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius-web-client#89]
V metadatech ke článku se v nejnovějším Krameriovi nezobrazuje **rozsah stran** (první a poslední strana článku). V MODSu ale rozsah vnitřní části zaznamenán je, např.: 

<mods:part> 
<mods:extent> 
<mods:start> 1 </mods:start> 
<mods:end> 11 </mods:end> 
</mods:extent> 
</mods:part>
In: Collection of Czechoslovak chemical communications ( http://knav.kramerius.rychtar.cloud/uuid/uuid:4f4a6827-be7a-11e2-9ddd-001e65b2b442 ).

Šel by tento element **přidat** vpravo do zobrazovaných metadat k názvu článku, jeho autorům, klíčovým slovům, jazyku a abstraktu? Děkuji

**Comment by honza-rychtar** [comment]
Pridal jsem
