### ISSUE TITLE
Typ dokumentu - číslo periodika

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius-web-client#9]
Při prohlížení čísla, tedy už jednotlivých naskenovaný stran jsou v pravé sloupci metadata a pod "typem dokumentu" je číslo periodika, které je proklikávací a mělo by tedy fungovat jako filtr (podobně jako jazyk). Ale po kliknutí se objeví výsledky vyhledávání, kdy se vyhodí hláška, že nic nebylo nalezeno. 
Asi by tedy stačilo, aby to nebyl filtr.

**Comment by honza-rychtar** [comment]
Opravil jsem to, aby se v metadatech u rocniku a cisla periodika zobrazoval typ dokumentu jako periodikum.
