### ISSUE TITLE
Navigace-odkazy mezi čísly časopisu nebo svazky monografie (metadata.*.title)

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#90]
Předchozí/Následující číslo zobrazuje **pouze rok**, např:
http://knav.kramerius.rychtar.cloud/uuid/uuid:18c472e0-d56b-11e1-1726-001143e3f55c
nebo 
https://dev.medvik.cz/wck/uuid/uuid:5a04f380-5a65-11e7-921c-d485646517a0

Stejně tak i Předchozí/Následující svazek, např:
https://dev.medvik.cz/wck/uuid/uuid:877dd2d1-6dc8-4155-93a1-5955afbb4f8d

Bylo by lepší zobrazovat údaje z:

```
            <mods:partNumber>
                2
            </mods:partNumber>
```
a
```
            <mods:detail type="issue">
                <mods:number>
                    3
                </mods:number>
            </mods:detail>
```

**Comment by honza-rychtar** [comment]
Upravil jsem to:
U navigace na predchozi/nasledujici cislo periodika se zobrazuje *cislo (datum)*
U navigace na predchozi/nasledujici cast svazku se zobrazuje *cislo casti (nazev casti)*
