### ISSUE TITLE
Ročenky nebo sborníky nemají čísla - přesto je klient virtuálně vytváří

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#91]
...což vypadá poněkud zvláštně.

Např.
https://dev.medvik.cz/wck/uuid/uuid:736c94e7-baaf-46a8-9b45-f6f16b3b1ada

- v K5:
http://kramerius.medvik.cz/search/handle/uuid:MED00020567-45a265d1-af75-4e2f-88d1-b22369bbb1fa

- v k5-client:
http://kramerius.medvik.cz/client/handle/uuid:MED00020567-45a265d1-af75-4e2f-88d1-b22369bbb1fa

**Comment by honza-rychtar** [comment]
V Digitalni knihovne jsem to nedavno upravil tak, ze pokud rocnik obsahuje jen jedno (nebo zadne) cislo, tak se po kliku na rocnik prejde rovnou do prohlizecky.
Taky pokud rocnik obsahuje primo stranky (uroven cisla je vynechana), tak se v prohlizecce v metadatech zobrazuje navigace Predchozi rocnik a Nasledujici rocnik.
Napr.
http://www.digitalniknihovna.cz/nlk/periodical/uuid:MED00020567-45a265d1-af75-4e2f-88d1-b22369bbb1fa
Delal jsem to hlavne kvuli kalendarum.

Muzeme to podebne udelat i tady.

**Comment by filak** [comment]
To by bylo fajn, souhlasim.

**Comment by honza-rychtar** [comment]
Hotovo.
Např. http://kramerius.rychtar.cloud/nlk/periodical/uuid:MED00020567-45a265d1-af75-4e2f-88d1-b22369bbb1fa

Otevření ročníku vede rovnou do prohlížečky a tam se dá přecházet na předchozí/další ročník.
