### ISSUE TITLE
Kalendář - pokud vyšla ve stejný den dvě vydání, proklik vede přímo na jedno z nich

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-web-client#93]
Tj. v kalendáři není nijak vidět, že v daný den bylo více vydání a není možnost si mezi nimi vybrat. Dá se pak přepnout tím, že jdu na další číslo, ale nedalo by se to že je víc čísel naznačit přímo v kalendáři?

Viz např. http://kramerius.rychtar.cloud/periodical/uuid:b23881ea-435d-11dd-b505-00145e5790ea - 11.1.1907

**Comment by zabak** [comment]
Polona to řeší tak, že datum kdy bylo víc vydání podtrhne, zobrazuje tam kontextovou nápovědu a po kliknutí se rozbalí menu s nabídkou vydání. Samozřejmě by bylo hezké, aby byla ta vydání správně seřazena, ale to by muselo být pomocí nějaké heuristiky. Viz. např. https://polona.pl/press/czas,MjQ4NTMwMDc/1905/ nebo přiložený screenshot:
![image](https://user-images.githubusercontent.com/811537/42813480-7250c696-89c1-11e8-855a-123b816bbffc.png)

**Comment by honza-rychtar** [comment]
Přidáno zobrazení indikace (počtem teček), že v den existuje více výtisků a tooltip, který zobrazuje názvy výtisků.
http://www.digitalniknihovna.cz/mzk/periodical/uuid:e84c04a0-67e3-11e3-82ee-005056822549?accessibility=public
<img width="380" alt="Snímek obrazovky 2020-11-12 v 17 06 56" src="https://user-images.githubusercontent.com/1178142/98964841-99312400-2509-11eb-93df-5914d44f778d.png">
Informace o ranním/večerním/odpoledním vydání bude dostupná až s novým indexem.

Na schůzce jsme se dohodli, že v případě více výtisků v daný den se po kliku na tento den ještě zobrazí nabídka s výtisky, tj. nepřejde se automaticky na první jako je tomu teď.

**Comment by zabak** [comment]
vyřešeno, zavírám
