### ISSUE TITLE
Nefunguje vyhledávání v PDF dokumentech

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius-web-client#94]
Příklad:
https://dev.medvik.cz/wck/view/uuid:MED00182721-640dfe5d-7e89-41b0-b962-ffaf7a644d29?fulltext=v%C3%A1lka%20proti%20drog%C3%A1m

Přitom v obou starých klientech to funguje:
K5: 
https://kramerius.medvik.cz/search/i.jsp?pid=uuid:640dfe5d-7e89-41b0-b962-ffaf7a644d29/@13&q=v%C3%A1lka%20proti%20drog%C3%A1m

K5-client:
https://kramerius.medvik.cz/client/index.vm?q=v%C3%A1lka+proti+drog%C3%A1m&page=doc&start=&rows=#pid=uuid:640dfe5d-7e89-41b0-b962-ffaf7a644d29@13

**Comment by honza-rychtar** [comment]
Tady je problém s tím, že je to monografie, která ma jednu stránku a na tu stránku je navázáno PDF a to má zase jednotlivé stránky.
Takže struktura je monograph -> page -> page
No a fulltext je až na té spodní page, které se ale nezobrazují.

Hledání uvnitř dokumentu na stránkách PDF ještě musím doladit.

Ale tady se teda nejdřív zeptám.
Proč to máte zpracované tímto způsobem a ne tak, že je PDF přímo na monografii.
Model page by měl byt listem v té struktuře a neměl by obsahovat nic dalšího.
Tohle _monograph -> page -> page_ nedává smysl.

**Comment by filak** [comment]
K tomu byla diskuze tady https://github.com/ceskaexpedice/kramerius/issues/339

Máme historicky třeba takové dokumenty:
http://kramerius.medvik.cz/search/i.jsp?pid=uuid:MED00111712-143387de-6efd-40e3-8eb5-30e97dcafbf7

Každopádně mi to už "uvnitř" dokumentu hledá, například:
https://dev.medvik.cz/wck/view/uuid:MED00111712-143387de-6efd-40e3-8eb5-30e97dcafbf7?page=uuid:ab1d22fb-30d8-491d-98e1-c607d833b5b0&fulltext=ICSI

Ale to jsou jenom monografie.

V periodikách mi to sice hledá, ale "proklik" už nic nezobrazí:
https://dev.medvik.cz/wck/periodical/uuid:MED00011034-e923bfdd-9d02-4f0d-ba8a-a0151f8cf3ae?fulltext=k%C5%99%C3%AD%C5%BE

**Comment by filak** [comment]
Tak ve verzi 2.0.5 to v periodikách hledá i zobrazuje - viz např.:
- https://www.digitalniknihovna.cz/nlk/periodical/uuid:MED00011034-e923bfdd-9d02-4f0d-ba8a-a0151f8cf3ae?fulltext=filip%20k%C5%99%C3%AD%C5%BE&accessibility=public

Pokud je však ve výsledcích hledání článek:
- https://www.digitalniknihovna.cz/nlk/search?q=filip%20k%C5%99%C3%AD%C5%BE&accessibility=public

tak se ale nic nezobrazí:
- https://www.digitalniknihovna.cz/nlk/view/uuid:9e0876a9-1ad9-4115-8c53-449ae3560672

Což je ale věc, která se mi v nějaké prastaré verzi klienta zobrazuje v pořádku:
https://dev.medvik.cz/wck/view/uuid:9e0876a9-1ad9-4115-8c53-449ae3560672

**Comment by filak** [comment]
Zavírám s tím, že články nalezené v konkrétním periodiku se už zobrazují:

https://www.digitalniknihovna.cz/nlk/periodical/uuid:MED00011034-e923bfdd-9d02-4f0d-ba8a-a0151f8cf3ae?fulltext=maixnerov%C3%A1&accessibility=public
