### ISSUE TITLE
Rozdelené slová na konci strany

### ISSUE THREAD

**Issue by MarosGrm** [ceskaexpedice/kramerius-web-client#95]
Pri výbere textu a zobrazení OCR dochádza k zlému zobrazenie slov, ktoré sú rozdelené na konci riadku a to tak, že rozdelené slovo je v OCR prepolené na dve časti oddelené medzerou (viď obrázok). Toto by šlo vyriešiť pomocou toho, že ALTO obsahuje aj položku SUBS_CONTENT, v ktorej sa rozdelené slovo nachádza celé.
![vyber_081](https://user-images.githubusercontent.com/16135340/43185861-66378728-8fed-11e8-8a03-0c131b007532.png)

**Comment by zabak** [comment]
Zatím jsme vyřešili tak, že jsme při reindexaci odstranili bez náhrady všechny vyskyty -/n z fulltextu, čímž se většina slov spojila

**Comment by zabak** [comment]
Samozřejmě že tento fix neřeší to co je v nadpisu, tj. rozdělené slova na konci strany :-)
Kdyby někoho napadlo, jak to snadno vyřešit, dostane 🥇(medajli)

**Comment by honza-rychtar** [comment]
@zabak No jak se navrhovalo - vzít text z SUBS_CONTENT. Plus zobrazení OCR celé stránky brát taky z ALTA - celá stránka = vvýběr oblasti od rohu k rohu.

**Comment by zabak** [comment]
Problém je, že indexace alta je podstatně pomalejší než indexace textu. Z tohoto hlediska je rychlejší fix spojení rozdělených slov přímo v indexu. 
_Pro úplnost doplňuju, že solr ve stávající podobě při indexaci nezvládá ani normální konce řádků ve fulltextu a považuje slovo na konci řádku a na začátku dalšího za jedno slovo, takže pak ta dvě slova nejdou najít protože solr zná jen jedno slovo: "slovo1/nslovo2", takže správně by se před indexací měly všechny konce řádků nahradit mezerou._
Ale pro klienta (zobrazení textu) platí to co píšeš a to by mělo být předmětem tohoto issue. Akorát, je blbě pojmenované, protože rozdělení slov na konci stránky nevyřeší.

**Comment by zabak** [comment]
V #96 se řeší, jak rozdělené slovo zvýraznit, zde se řeší, jak je zobrazit v rámci textu. Sice to k sobě patří logicky, ale předpokládám, že programátorsky bude lepší to nechat samostatně.

**Comment by honza-rychtar** [comment]
V textovém přepisu teď zachováváme konce řádků (#377), takže naopak to rozdělené pro zobrazení chceme.
Dále tady #96 

Tohle bych teda uzavřel.

**Comment by zabak** [comment]
Indexer K7 už korektně indexuje rozdělená slova - viz např. https://k7-test.mzk.cz/mzkk7/view/uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23?page=uuid:64c16e94-8637-4506-b9f0-db5b24787a2f&fulltext=veden%C3%BDmi

Zde tedy zavírám a počítám, že zvýrazňování rozděleného slova se vyřeší v #96
