### ISSUE TITLE
Tisk/generování PDF u stran orientovaných na šířku

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#97]
Některé dokumenty mají strany naskenované jako dvoustranu nebo strany orientované na šířku (v podstatě v obou případech jde o orientaci strany na šířku). V PDF je strana orientovaná standardně na výšku, což ale v tomto případě není ideální. Předpokládám, že to nemá DK jak poznat, tak navrhujeme, aby si uživatel mohl v dialogu vybrat, zda chce mít stranu/y v PDF orientované na výšku nebo na šířku. Příklad: http://kramerius.rychtar.cloud/view/uuid:801d0e70-685b-11e7-aab4-005056827e52

**Comment by zabak** [comment]
Kramerius tohle poznat může - zná poměr stran jednotlivých obrázků a mohl by je orientovat tak, aby jejich orientace odpovídala papíru. To je možná vhodné pro tisk. U normálního generování pdf ale nevidím důvod, proč to za každou cenu rvát na A4. Vždyť v PDF může mít každá stránka libovolnou velikost, tak toho využijme a generujme velikosti stránky podle velikosti obrázku a dpi. Předpokládám, že by to nemusel být problém ani při tisku, možná naopak.

**Comment by JanHouserek** [comment]
Využiji toto issue k obecnějšímu dotazu. Po zprovoznění nového klienta na digitalniknihovna.cz se mi objevilo několik uživatelských reakcí, kdy údajně u pdf z "Přípravy k tisku" došlo ke změně - podle uživatelů mají větší okraje než před zprovozněním nového klienta. Podle nás tomu tak není, ale zajímalo by mě, jaké rozdíly jsou v generování pdf z "Příprava k tisku" a "Stáhnout PDF". Když nepočítam stránku s podmínkami použití, každá varianta se vygeneruje jinak (viz například dokument z odkazu zde od Lenky). Uživatelé, zdá se, dávají přednost variantě ze "Stáhnout PDF". V našem případě se nejčastěji jedná o noviny A3+, kdy lze u bezokrajových pdf argumentovat lepší čitelností textu, estetikou a snazším tiskem (pokud okraje uživateli vadí a neporadí si s nastavením tisku).

**Comment by honza-rychtar** [comment]
@JanHouserek Nový klient používá pro generování PDF úplně stejný endpoint Krameria jako předchozi klient. Ke změně tedy dojít nemohlo.
Uživatelé skutečně dávají přednost stažení PDF před přípravou k tisku. 
Z analýzy chování klikají na stáhnout PDF 6x častěji.

Generování PDF, ať už ve formě stažení nebo přesměrování na stránku s PDF k tisku, je čistě záležitostí jádra Krameria. Klient to nijak neovlivní.

Odstranění zbytečných okrajů bychom určitě meli vyřešit, ale řešme to tady https://github.com/ceskaexpedice/kramerius

**Comment by zabak** [comment]
Zde zavírám - je to požadavek na jádro a příslušná issues jsou zde nalinkovaná.
