### ISSUE TITLE
Vyhledávání podle signatury

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius-web-client#99]
Navrhujeme, aby klient uměl nějakým způsobem vyhledávat podle signatury. Jde o to, že uživatelé starých tisků jsou běžně zvyklí hledat podle signatury, takže pro ně by to smysl mělo.
Viz https://github.com/honza-rychtar/kramerius-web-client/issues/240

**Comment by honza-rychtar** [comment]
Hotov.
Stačí vepsat do vyhledávacáho pole.
Např. http://kramerius.rychtar.cloud/mzk/search?q=PK-0047.479
